# Generated by Django 6.0.2 on 2026-02-23 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('R2', 'Cloudflare R2'), ('S3', 'AWS S3'), ('MINIO', 'MinIO'), ('LOCAL', 'Local Server')], default='R2', max_length=10)),
                ('endpoint_url', models.URLField(blank=True, default='', help_text='S3-compatible endpoint, e.g. https://<account>.r2.cloudflarestorage.com', max_length=500)),
                ('bucket_name', models.CharField(default='tsf-files', max_length=200)),
                ('access_key', models.CharField(blank=True, default='', max_length=200)),
                ('secret_key', models.CharField(blank=True, default='', max_length=200)),
                ('region', models.CharField(default='auto', help_text='Use "auto" for R2', max_length=50)),
                ('path_prefix', models.CharField(blank=True, default='', help_text='Auto-set to {org_slug}/ if blank', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('max_file_size_mb', models.IntegerField(default=50, help_text='Maximum upload size in MB')),
                ('allowed_extensions', models.JSONField(blank=True, default=list, help_text='Allowed file extensions, e.g. ["pdf","jpg","png"]')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('organization', models.OneToOneField(blank=True, help_text='Null = platform default provider', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_provider', to='erp.organization')),
            ],
            options={
                'db_table': 'storage_provider',
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=200)),
                ('total_size', models.BigIntegerField(help_text='Expected total file size in bytes')),
                ('bytes_received', models.BigIntegerField(default=0)),
                ('chunk_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('complete', 'Complete'), ('failed', 'Failed'), ('expired', 'Expired')], default='uploading', max_length=20)),
                ('checksum_expected', models.CharField(blank=True, default='', help_text='Client-provided SHA-256 for final verification', max_length=64)),
                ('temp_path', models.CharField(blank=True, default='', max_length=1000)),
                ('upload_type', models.CharField(choices=[('file', 'Organization File'), ('package', 'System Package')], default='file', max_length=20)),
                ('category', models.CharField(default='ATTACHMENT', max_length=20)),
                ('linked_model', models.CharField(blank=True, default='', max_length=100)),
                ('linked_id', models.CharField(blank=True, help_text='ID of the linked model (UUID as string or Int)', max_length=100, null=True)),
                ('package_type', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Session expires after this time (default 24h)')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='erp.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=500)),
                ('storage_key', models.CharField(help_text='Full object key in the bucket, e.g. org-slug/invoices/2026/file.pdf', max_length=1000)),
                ('bucket', models.CharField(max_length=200)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=200)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('category', models.CharField(choices=[('ATTACHMENT', 'General Attachment'), ('RECEIPT', 'Receipt'), ('INVOICE', 'Invoice Document'), ('PROFORMA', 'Proforma Invoice'), ('SIGNED_ORDER', 'Signed Order'), ('PURCHASE_ORDER', 'Purchase Order'), ('PURCHASE_RECEIPT', 'Purchase Receipt'), ('PURCHASE_DOC', 'Purchase Document'), ('TRANSFER_ORDER', 'Transfer Order'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT_ORDER', 'Adjustment Order'), ('ADJUSTMENT', 'Adjustment'), ('RECEIPT_VOUCHER', 'Receipt Voucher'), ('PAYMENT_VOUCHER', 'Payment Voucher'), ('EXPENSE', 'Expense'), ('EMPLOYEE_DOC', 'Employee Document'), ('PRODUCT_IMAGE', 'Product Image'), ('PAYMENT_RECEIPT', 'Payment Receipt'), ('LOGO', 'Company Logo'), ('USER_ATTACHMENT', 'User Attachment'), ('MIGRATION', 'Migration Source File'), ('OTHER', 'Other')], default='ATTACHMENT', max_length=20)),
                ('linked_model', models.CharField(blank=True, default='', help_text='Dotted model path, e.g. finance.Invoice', max_length=100)),
                ('linked_id', models.IntegerField(blank=True, help_text='Primary key of the linked record', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('checksum', models.CharField(blank=True, default='', help_text='SHA-256 hash', max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stored_file',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['category'], name='stored_file_categor_07564e_idx'), models.Index(fields=['linked_model', 'linked_id'], name='stored_file_linked__4adb63_idx')],
            },
        ),
    ]
