# Generated by Django 6.0.4 on 2026-04-20 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_remove_approvalrule_organization_and_more'),
        ('storage', '0004_alter_storedfile_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
    ]
