# Generated by Django 6.0.4 on 2026-04-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_city'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='city',
            new_name='ref_cities_country_9237d6_idx',
            old_name='ref_cities_country_active_idx',
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
