# Generated by Django 6.0.4 on 2026-04-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_rename_ref_cities_country_active_idx_ref_cities_country_9237d6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgcurrency',
            name='enabled_in_country_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of Country FK ids this currency is enabled in. Empty = all enabled countries.'),
        ),
    ]
