# Generated by Django 6.0.4 on 2026-04-30 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_remove_approvalrule_organization_and_more'),
        ('reference', '0006_orgcurrency_enabled_in_country_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Machine code (e.g., stripe, wave_ci, orange_money_ci)', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Display name (e.g., "Wave (Côte d\'Ivoire)")', max_length=100)),
                ('provider_family', models.CharField(blank=True, default='', help_text='Groups provider variants (e.g., "wave" for wave_ci, wave_sn)', max_length=50)),
                ('logo_emoji', models.CharField(blank=True, default='💳', help_text='Emoji for quick visual identification', max_length=10)),
                ('color', models.CharField(blank=True, default='#6366f1', help_text='Brand color hex', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Short description of the gateway')),
                ('is_global', models.BooleanField(default=False, help_text='Available worldwide regardless of country selection')),
                ('config_schema', models.JSONField(blank=True, default=list, help_text='JSON array defining credential fields this provider requires')),
                ('website_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('countries', models.ManyToManyField(blank=True, help_text='Countries where this gateway operates. Empty = use is_global.', related_name='payment_gateways', to='reference.country')),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'db_table': 'ref_payment_gateways',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrgPaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('default_config', models.JSONField(blank=True, default=dict, help_text='Org-wide default credentials. Accounts can override per-instance.')),
                ('organization', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization')),
                ('gateway', models.ForeignKey(help_text='Reference to global gateway catalog entry', on_delete=django.db.models.deletion.CASCADE, related_name='org_activations', to='reference.paymentgateway')),
            ],
            options={
                'db_table': 'ref_org_payment_gateways',
                'ordering': ['display_order', 'gateway__name'],
                'indexes': [models.Index(fields=['organization', 'is_enabled'], name='ref_org_pay_tenant__a4dd6e_idx')],
                'unique_together': {('organization', 'gateway')},
            },
        ),
    ]
