# Generated by Django 6.0.3 on 2026-05-02 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_core', '0005_user_tour_completion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usertourcompletion',
            new_name='user_tour_c_user_id_dec172_idx',
            old_name='usr_tour_idx',
        ),
    ]
