# Generated by Django 5.2.11 on 2026-02-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageprovider',
            name='max_file_size_mb',
            field=models.IntegerField(default=500, help_text='Maximum upload size in MB'),
        ),
    ]
