# Generated by Django 5.2.11 on 2026-03-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_storageprovider_max_file_size_mb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='category',
            field=models.CharField(choices=[('ATTACHMENT', 'General Attachment'), ('RECEIPT', 'Receipt'), ('INVOICE', 'Invoice Document'), ('PROFORMA', 'Proforma Invoice'), ('SIGNED_ORDER', 'Signed Order'), ('PURCHASE_ORDER', 'Purchase Order'), ('PURCHASE_RECEIPT', 'Purchase Receipt'), ('PURCHASE_DOC', 'Purchase Document'), ('TRANSFER_ORDER', 'Transfer Order'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT_ORDER', 'Adjustment Order'), ('ADJUSTMENT', 'Adjustment'), ('RECEIPT_VOUCHER', 'Receipt Voucher'), ('PAYMENT_VOUCHER', 'Payment Voucher'), ('EXPENSE', 'Expense'), ('EMPLOYEE_DOC', 'Employee Document'), ('PRODUCT_IMAGE', 'Product Image'), ('PAYMENT_RECEIPT', 'Payment Receipt'), ('LOGO', 'Company Logo'), ('USER_ATTACHMENT', 'User Attachment'), ('MIGRATION', 'Migration Source File'), ('COMPLIANCE_DOC', 'Compliance Document'), ('OTHER', 'Other')], default='ATTACHMENT', max_length=20),
        ),
    ]
