# Generated by Django 6.0.3 on 2026-05-01 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_remove_approvalrule_organization_and_more'),
        ('storage', '0005_alter_storedfile_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='uploadsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', False), ('upload_type', 'file')), models.Q(('organization__isnull', True), ('upload_type', 'package')), _connector='OR'), name='upload_session_type_org_invariant'),
        ),
    ]
