'use client'
/**
 * VAT Rate Change History — Management Page
 */
import { useState, useEffect, useMemo, useRef } from 'react'
import { erpFetch } from '@/lib/erp-api'
import { Plus, Search, Loader2, X, Maximize2, Minimize2, ArrowLeft, Save, History, DollarSign, AlertTriangle, Clock, ArrowUp, Zap } from 'lucide-react'
type Rec = Record<string, any>
const TRANSITIONS = ['INVOICE_DATE','DELIVERY_DATE','PAYMENT_DATE','EARLIER_OF','GOVERNMENT_DECREE']
const TRANSITION_LABELS: Record<string,string> = { INVOICE_DATE:'Invoice Date', DELIVERY_DATE:'Delivery Date', PAYMENT_DATE:'Payment Date', EARLIER_OF:'Earlier of Inv/Del', GOVERNMENT_DECREE:'Per Decree' }
const STATUSES = ['UPCOMING','ACTIVE','HISTORICAL']
const STATUS_COLORS: Record<string,{bg:string;fg:string}> = { UPCOMING:{bg:'color-mix(in srgb, var(--app-warning, #f59e0b) 10%, transparent)',fg:'var(--app-warning, #f59e0b)'}, ACTIVE:{bg:'color-mix(in srgb, var(--app-success, #22c55e) 10%, transparent)',fg:'var(--app-success, #22c55e)'}, HISTORICAL:{bg:'color-mix(in srgb, var(--app-muted-foreground) 10%, transparent)',fg:'var(--app-muted-foreground)'} }
const inputCls = 'w-full text-[12px] font-bold bg-app-surface/60 border border-app-border/50 rounded-xl px-3 py-2 text-app-foreground placeholder:text-app-muted-foreground focus:bg-app-surface focus:border-app-primary/40 focus:ring-2 focus:ring-app-primary/10 outline-none transition-all'
const labelCls = 'text-[9px] font-black text-app-muted-foreground uppercase tracking-widest mb-1 block'

function Editor({ item, onSave, onCancel }: { item: Rec|null; onSave:(d:Rec)=>void; onCancel:()=>void }) {
  const [form, setForm] = useState<Rec>(item || { effective_date: new Date().toISOString().split('T')[0], country_code:'', description:'', old_rate:0, old_rate_label:'', new_rate:0, new_rate_label:'', announcement_date:'', gazette_reference:'', transition_rule:'INVOICE_DATE', transition_notes:'', status:'UPCOMING', notes:'' })
  const [saving, setSaving] = useState(false); const upd = (k:string,v:any) => setForm(p=>({...p,[k]:v}))
  const oldPct = (parseFloat(form.old_rate||0)*100).toFixed(1)
  const newPct = (parseFloat(form.new_rate||0)*100).toFixed(1)
  const diff = parseFloat(form.new_rate||0) - parseFloat(form.old_rate||0)
  return (
    <div className="flex flex-col h-full p-4 md:p-6 animate-in fade-in duration-300">
      <div className="flex items-center gap-3 mb-4 flex-shrink-0"><button onClick={onCancel} className="flex items-center gap-1.5 text-[11px] font-bold text-app-muted-foreground hover:text-app-foreground border border-app-border px-2.5 py-1.5 rounded-xl hover:bg-app-surface transition-all"><ArrowLeft size={13}/> Back</button><div className="flex items-center gap-3 flex-1 min-w-0"><div className="page-header-icon bg-app-primary" style={{boxShadow:'0 4px 14px color-mix(in srgb, var(--app-primary) 30%, transparent)'}}><History size={20} className="text-white"/></div><div className="min-w-0"><h1 className="text-lg font-black text-app-foreground tracking-tight truncate">{item ? 'Edit Rate Change' : 'New Rate Change'}</h1><p className="text-[10px] font-bold text-app-muted-foreground uppercase tracking-widest">VAT Rate History</p></div></div><button onClick={async()=>{setSaving(true);await onSave(form);setSaving(false)}} disabled={saving} className="flex items-center gap-1.5 text-[11px] font-bold bg-app-primary hover:brightness-110 text-white px-3 py-1.5 rounded-xl transition-all" style={{boxShadow:'0 2px 8px color-mix(in srgb, var(--app-primary) 25%, transparent)',opacity:saving?0.7:1}}>{saving?<Loader2 size={14} className="animate-spin"/>:<Save size={14}/>} Save</button></div>
      <div className="flex-1 overflow-y-auto custom-scrollbar space-y-4">
        <div className="rounded-2xl p-4" style={{background:`linear-gradient(135deg, color-mix(in srgb, ${diff>0?'var(--app-error, #ef4444)':'var(--app-success, #22c55e)'} 6%, transparent), color-mix(in srgb, var(--app-surface) 80%, transparent))`,border:`1px solid color-mix(in srgb, ${diff>0?'var(--app-error, #ef4444)':'var(--app-success, #22c55e)'} 15%, transparent)`}}>
          <div className="text-[9px] font-black text-app-muted-foreground uppercase tracking-widest mb-2">RATE CHANGE</div>
          <div className="flex items-center justify-center gap-4">
            <div className="text-center"><div className="text-[9px] font-bold uppercase tracking-wider" style={{color:'var(--app-muted-foreground)'}}>Old Rate</div><div className="text-2xl font-black tabular-nums" style={{color:'var(--app-muted-foreground)'}}>{oldPct}%</div></div>
            <div className="text-2xl font-black" style={{color:diff>0?'var(--app-error, #ef4444)':'var(--app-success, #22c55e)'}}>→</div>
            <div className="text-center"><div className="text-[9px] font-bold uppercase tracking-wider" style={{color:'var(--app-muted-foreground)'}}>New Rate</div><div className="text-2xl font-black tabular-nums" style={{color:diff>0?'var(--app-error, #ef4444)':'var(--app-success, #22c55e)'}}>{newPct}%</div></div>
            <div className="text-center ml-4"><div className="text-[9px] font-bold uppercase tracking-wider" style={{color:'var(--app-muted-foreground)'}}>Change</div><div className="text-lg font-black tabular-nums" style={{color:diff>0?'var(--app-error, #ef4444)':'var(--app-success, #22c55e)'}}>{diff>0?'+':''}{(diff*100).toFixed(1)}pp</div></div>
          </div>
        </div>
        <div className="rounded-2xl p-4" style={{background:'color-mix(in srgb, var(--app-surface) 50%, transparent)',border:'1px solid color-mix(in srgb, var(--app-border) 50%, transparent)'}}>
          <div className="text-[9px] font-black text-app-muted-foreground uppercase tracking-widest mb-3">DETAILS</div>
          <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit, minmax(180px, 1fr))',gap:'12px'}}>
            <div><label className={labelCls}>Country Code</label><input className={inputCls} value={form.country_code} onChange={e=>upd('country_code',e.target.value)} placeholder="LB" maxLength={3}/></div>
            <div><label className={labelCls}>Old Rate</label><input className={inputCls} type="number" min={0} max={1} step={0.0001} value={form.old_rate} onChange={e=>upd('old_rate',e.target.value)}/></div>
            <div><label className={labelCls}>Old Rate Label</label><input className={inputCls} value={form.old_rate_label} onChange={e=>upd('old_rate_label',e.target.value)} placeholder="11% Standard Rate"/></div>
            <div><label className={labelCls}>New Rate</label><input className={inputCls} type="number" min={0} max={1} step={0.0001} value={form.new_rate} onChange={e=>upd('new_rate',e.target.value)}/></div>
            <div><label className={labelCls}>New Rate Label</label><input className={inputCls} value={form.new_rate_label} onChange={e=>upd('new_rate_label',e.target.value)} placeholder="12% Standard Rate"/></div>
            <div><label className={labelCls}>Effective Date</label><input className={inputCls} type="date" value={form.effective_date} onChange={e=>upd('effective_date',e.target.value)}/></div>
            <div><label className={labelCls}>Announcement Date</label><input className={inputCls} type="date" value={form.announcement_date} onChange={e=>upd('announcement_date',e.target.value)}/></div>
            <div><label className={labelCls}>Gazette Reference</label><input className={inputCls} value={form.gazette_reference} onChange={e=>upd('gazette_reference',e.target.value)} placeholder="Official decree ref"/></div>
            <div><label className={labelCls}>Transition Rule</label><select className={inputCls} value={form.transition_rule} onChange={e=>upd('transition_rule',e.target.value)}>{TRANSITIONS.map(t=><option key={t} value={t}>{TRANSITION_LABELS[t]}</option>)}</select></div>
            <div><label className={labelCls}>Status</label><select className={inputCls} value={form.status} onChange={e=>upd('status',e.target.value)}>{STATUSES.map(s=><option key={s} value={s}>{s}</option>)}</select></div>
          </div>
        </div>
        <div className="rounded-2xl p-4" style={{background:'color-mix(in srgb, var(--app-surface) 50%, transparent)',border:'1px solid color-mix(in srgb, var(--app-border) 50%, transparent)'}}><div className="text-[9px] font-black text-app-muted-foreground uppercase tracking-widest mb-3">DESCRIPTION & NOTES</div><div className="space-y-3"><div><label className={labelCls}>Description</label><input className={inputCls} value={form.description} onChange={e=>upd('description',e.target.value)} placeholder="Lebanon VAT increase from 11% to 12%"/></div><div><label className={labelCls}>Transition Notes</label><textarea className={inputCls} rows={2} value={form.transition_notes} onChange={e=>upd('transition_notes',e.target.value)} placeholder="Transitional rules..."/></div><div><label className={labelCls}>Notes</label><textarea className={inputCls} rows={2} value={form.notes} onChange={e=>upd('notes',e.target.value)} placeholder="Additional notes..."/></div></div></div>
      </div>
    </div>
  )
}

export default function VATRateHistoryPage() {
  const [items, setItems] = useState<Rec[]>([]); const [dashboard, setDashboard] = useState<Record<string,any>>({}); const [loading, setLoading] = useState(true); const [searchQuery, setSearchQuery] = useState(''); const [focusMode, setFocusMode] = useState(false); const [editing, setEditing] = useState<Rec|null|'new'>(null); const searchRef = useRef<HTMLInputElement>(null)
  useEffect(()=>{load()},[])
  async function load(){try{setLoading(true);const[d,s]=await Promise.all([erpFetch('finance/vat-rate-history/'),erpFetch('finance/vat-rate-history/dashboard/')]);setItems(Array.isArray(d)?d:d?.results||[]);setDashboard(s||{})}catch(e){console.error(e)}finally{setLoading(false)}}
  async function handleSave(data:Rec){try{if(data.id){await erpFetch(`finance/vat-rate-history/${data.id}/`,{method:'PATCH',body:JSON.stringify(data)})}else{await erpFetch('finance/vat-rate-history/',{method:'POST',body:JSON.stringify(data)})};setEditing(null);load()}catch(e){console.error(e);alert('Save failed')}}
  async function handleApply(id:number){if(!confirm('Apply this rate change to the TaxGroup?'))return;try{await erpFetch(`finance/vat-rate-history/${id}/apply/`,{method:'POST'});load()}catch(e){console.error(e);alert('Apply failed')}}
  const filtered = useMemo(()=>{if(!searchQuery.trim())return items;const q=searchQuery.toLowerCase();return items.filter(i=>i.description?.toLowerCase().includes(q)||i.country_code?.toLowerCase().includes(q)||i.change_display?.toLowerCase().includes(q))},[items,searchQuery])
  const kpis = [{label:'Total Changes',value:dashboard.total_changes??items.length,icon:<History size={11}/>,color:'var(--app-primary)'},{label:'Upcoming',value:dashboard.upcoming??0,icon:<Clock size={11}/>,color:'var(--app-warning, #f59e0b)'},{label:'Active',value:dashboard.active??0,icon:<Zap size={11}/>,color:'var(--app-success, #22c55e)'},{label:'Unapplied',value:dashboard.unapplied??0,icon:<AlertTriangle size={11}/>,color:'var(--app-error, #ef4444)'}]
  if(editing)return<Editor item={editing==='new'?null:editing} onSave={handleSave} onCancel={()=>setEditing(null)}/>
  return (
    <div className="flex flex-col h-full p-4 md:p-6 animate-in fade-in duration-300"><div className={`flex-shrink-0 space-y-4 ${focusMode?'pb-2':'pb-4'}`}>
      {!focusMode&&(<><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div className="flex items-center gap-3"><div className="page-header-icon bg-app-primary" style={{boxShadow:'0 4px 14px color-mix(in srgb, var(--app-primary) 30%, transparent)'}}><History size={20} className="text-white"/></div><div><h1 className="text-lg md:text-xl font-black text-app-foreground tracking-tight">VAT Rate History</h1><p className="text-[10px] md:text-[11px] font-bold text-app-muted-foreground uppercase tracking-widest">Rate Changes · Transition Rules</p></div></div><div className="flex items-center gap-1.5 flex-shrink-0"><button onClick={()=>setEditing('new')} className="flex items-center gap-1.5 text-[11px] font-bold bg-app-primary hover:brightness-110 text-white px-3 py-1.5 rounded-xl transition-all" style={{boxShadow:'0 2px 8px color-mix(in srgb, var(--app-primary) 25%, transparent)'}}><Plus size={14}/> New</button><button onClick={()=>setFocusMode(true)} className="flex items-center gap-1 text-[11px] font-bold text-app-muted-foreground hover:text-app-foreground border border-app-border px-2 py-1.5 rounded-xl hover:bg-app-surface transition-all"><Maximize2 size={13}/></button></div></div>
        <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit, minmax(140px, 1fr))',gap:'8px'}}>{kpis.map(s=>(<div key={s.label} className="flex items-center gap-2 px-3 py-2 rounded-xl" style={{background:'color-mix(in srgb, var(--app-surface) 50%, transparent)',border:'1px solid color-mix(in srgb, var(--app-border) 50%, transparent)'}}><div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{background:`color-mix(in srgb, ${s.color} 10%, transparent)`,color:s.color}}>{s.icon}</div><div className="min-w-0"><div className="text-[10px] font-bold uppercase tracking-wider" style={{color:'var(--app-muted-foreground)'}}>{s.label}</div><div className="text-sm font-black text-app-foreground tabular-nums truncate">{s.value}</div></div></div>))}</div>
      </>)}
      <div className="flex items-center gap-2">{focusMode&&<div className="flex items-center gap-2 flex-shrink-0"><div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{background:'var(--app-primary)'}}><History size={14} style={{color:'#fff'}}/></div></div>}<div className="flex-1 relative"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-app-muted-foreground"/><input ref={searchRef} type="text" value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} placeholder="Search..." className="w-full pl-9 pr-3 py-2 text-[12px] bg-app-surface/50 border border-app-border/50 rounded-xl text-app-foreground placeholder:text-app-muted-foreground focus:bg-app-surface focus:border-app-border focus:ring-2 focus:ring-app-primary/10 outline-none transition-all"/></div>{focusMode&&<><button onClick={()=>setEditing('new')} className="flex items-center gap-1 text-[10px] font-bold bg-app-primary text-white px-2 py-1.5 rounded-lg"><Plus size={12}/></button><button onClick={()=>setFocusMode(false)} className="p-1.5 rounded-lg border border-app-border text-app-muted-foreground hover:text-app-foreground hover:bg-app-surface transition-all"><Minimize2 size={13}/></button></>}{searchQuery&&<button onClick={()=>setSearchQuery('')} className="text-[11px] font-bold px-2 py-2 rounded-xl border" style={{color:'var(--app-error)',borderColor:'color-mix(in srgb, var(--app-error) 20%, transparent)'}}><X size={13}/></button>}</div>
    </div>
    <div className="flex-1 min-h-0 bg-app-surface/30 border border-app-border/50 rounded-2xl overflow-hidden flex flex-col">
      <div className="flex-shrink-0 flex items-center gap-2 md:gap-3 px-3 py-2 bg-app-surface/60 border-b border-app-border/50 text-[10px] font-black text-app-muted-foreground uppercase tracking-wider"><div className="w-7 flex-shrink-0"/><div className="flex-1 min-w-0">Description</div><div className="hidden sm:block w-28 flex-shrink-0 text-center">Change</div><div className="hidden md:block w-28 flex-shrink-0">Effective</div><div className="hidden lg:block w-20 flex-shrink-0">Status</div><div className="w-10 flex-shrink-0"/></div>
      <div className="flex-1 overflow-y-auto custom-scrollbar">
        {loading?<div className="flex items-center justify-center py-20"><Loader2 size={24} className="animate-spin text-app-primary"/></div>:filtered.length>0?filtered.map(item=>{const sc=STATUS_COLORS[item.status]||STATUS_COLORS.UPCOMING;const oldP=(parseFloat(item.old_rate||0)*100).toFixed(1);const newP=(parseFloat(item.new_rate||0)*100).toFixed(1);return<div key={item.id} className="group flex items-center gap-2 md:gap-3 transition-all cursor-pointer border-b border-app-border/30 hover:bg-app-surface/40 py-2.5 px-3" onClick={()=>setEditing(item)}><div className="w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0" style={{background:sc.bg,color:sc.fg}}><History size={13}/></div><div className="flex-1 min-w-0"><span className="truncate text-[13px] font-bold text-app-foreground block">{item.description||item.change_display||`Change #${item.id}`}</span><span className="text-[10px] font-bold text-app-muted-foreground">{item.country_code||'—'} · {TRANSITION_LABELS[item.transition_rule]||item.transition_rule}</span></div><div className="hidden sm:block w-28 flex-shrink-0 text-center"><span className="font-mono text-[12px] font-bold text-app-muted-foreground">{oldP}%</span><span className="mx-1 text-app-muted-foreground">→</span><span className="font-mono text-[12px] font-black" style={{color:parseFloat(item.new_rate)>parseFloat(item.old_rate)?'var(--app-error, #ef4444)':'var(--app-success, #22c55e)'}}>{newP}%</span></div><div className="hidden md:block w-28 flex-shrink-0 text-[12px] font-bold text-app-muted-foreground">{item.effective_date}</div><div className="hidden lg:block w-20 flex-shrink-0"><span className="text-[10px] font-bold px-1.5 py-0.5 rounded-lg" style={{background:sc.bg,color:sc.fg}}>{item.status}</span></div><div className="flex items-center gap-0.5 flex-shrink-0 opacity-0 group-hover:opacity-100 transition-opacity">{!item.applied_to_tax_group&&item.status!=='HISTORICAL'&&<button onClick={e=>{e.stopPropagation();handleApply(item.id)}} className="p-1.5 hover:bg-app-border/50 rounded-lg text-app-info hover:text-app-info transition-colors" title="Apply to TaxGroup"><Zap size={12}/></button>}</div></div>}):<div className="flex flex-col items-center justify-center py-20 px-4 text-center"><History size={36} className="text-app-muted-foreground mb-3 opacity-40"/><p className="text-sm font-bold text-app-muted-foreground">No rate change history</p></div>}
      </div>
    </div></div>
  )
}
