# Generated by Django 5.1.7 on 2026-02-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='linked_account',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('PARTNER', 'Partner'), ('BOTH', 'Partner & Employee')], default='EMPLOYEE', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='linked_account_id',
            field=models.IntegerField(blank=True, db_column='linked_account_id', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
