# Generated by Django 5.1.7 on 2026-02-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_add_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dividends_account_id',
            field=models.IntegerField(blank=True, help_text='GL account for dividends payable (partners only)', null=True),
        ),
    ]
