# Generated by Django 5.2.12 on 2026-03-11 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_employee_home_site_alter_shift_site'),
        ('erp', '0021_alter_approvalrule_organization_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='attendance',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='employee',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='leave',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='shift',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
            ],
            database_operations=[]
        )
    ]
