# Generated by Django 5.1.7 on 2026-02-02 11:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_product_status_contact_product_supplier_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
