# Generated by Django 5.1.7 on 2026-02-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_orderline_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='brands', to='erp.category'),
        ),
        migrations.AddField(
            model_name='brand',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='brands', to='erp.country'),
        ),
    ]
