# Generated by Django 5.1.7 on 2026-02-02 13:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_remove_order_contact_remove_product_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='200', max_length=10)),
                ('next_sequence', models.IntegerField(default=1000)),
                ('length', models.IntegerField(default=13)),
                ('is_enabled', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'BarcodeSettings',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest_type', models.CharField(choices=[('NONE', 'None'), ('SIMPLE', 'Simple'), ('COMPOUND', 'Compound')], default='SIMPLE', max_length=20)),
                ('term_months', models.IntegerField()),
                ('start_date', models.DateField()),
                ('payment_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='erp.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'Loan',
                'unique_together': {('contract_number', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='FinancialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PARTNER_CAPITAL_INJECTION', 'Capital Injection'), ('PARTNER_LOAN', 'Partner Loan'), ('PARTNER_WITHDRAWAL', 'Partner Withdrawal'), ('REFUND_RECEIVED', 'Refund Received')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('date', models.DateTimeField()),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SETTLED', 'Settled'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_events', to='erp.contact')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_events', to='erp.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_events', to='erp.transaction')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_events', to='erp.loan')),
            ],
            options={
                'db_table': 'FinancialEvent',
            },
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='erp.loan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'LoanInstallment',
            },
        ),
        migrations.CreateModel(
            name='TransactionSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('next_number', models.IntegerField(default=1)),
                ('padding', models.IntegerField(default=5)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'TransactionSequence',
                'unique_together': {('type', 'organization')},
            },
        ),
    ]
