# Generated by Django 5.1.7 on 2026-02-02 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_barcodesettings_loan_financialevent_loaninstallment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='home_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='erp.site'),
        ),
        migrations.AddField(
            model_name='unit',
            name='allow_fraction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='balance_code_structure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='base_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='erp.unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='needs_balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='type',
            field=models.CharField(default='COUNT', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
