# Generated by Django 5.1.7 on 2026-02-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_user_cash_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='parfum',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='parfums', to='erp.category'),
        ),
    ]
