# Generated by Django 5.1.7 on 2026-02-03 11:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_fiscalyear_is_hard_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='erp.contact'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_price_type',
            field=models.CharField(default='HT_BASED', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='scope',
            field=models.CharField(default='OFFICIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_recoverable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='unit_cost_ttc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='orderline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
