# Generated by Django 5.1.7 on 2026-02-03 11:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_contact_airsi_tax_rate_contact_is_airsi_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='airsi_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='orderline',
            name='airsi_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
