# Generated by Django 5.1.7 on 2026-02-04 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_systemupdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemmodulelog',
            name='version',
        ),
        migrations.AddField(
            model_name='systemmodulelog',
            name='from_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='systemmodulelog',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemmodulelog',
            name='module_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='systemmodulelog',
            name='status',
            field=models.CharField(default='SUCCESS', max_length=20),
        ),
        migrations.AddField(
            model_name='systemmodulelog',
            name='to_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='systemmodulelog',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='erp.systemmodule'),
        ),
    ]
