# Generated by Django 5.1.7 on 2026-02-04 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_organization_billing_contact_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_module', models.CharField(help_text="Module code (e.g., 'inventory') or '*' for global", max_length=100)),
                ('target_endpoint', models.CharField(default='*', help_text="Specific endpoint or '*' for all endpoints", max_length=255)),
                ('when_missing_read', models.CharField(choices=[('wait', 'Wait (blocking)'), ('empty', 'Empty Safe Response'), ('cached', 'Cached Last Value'), ('mock', 'Mock Response (dev)'), ('error', 'Return Error Object')], default='empty', help_text='Action when module is NOT INSTALLED', max_length=20)),
                ('when_missing_write', models.CharField(choices=[('buffer', 'Buffer for Replay'), ('redirect', 'Redirect to Core'), ('drop', 'Drop Silently'), ('queue_event', 'Queue as Event'), ('error', 'Return Error Object')], default='buffer', help_text='Action for writes when module is NOT INSTALLED', max_length=20)),
                ('when_disabled_read', models.CharField(choices=[('wait', 'Wait (blocking)'), ('empty', 'Empty Safe Response'), ('cached', 'Cached Last Value'), ('mock', 'Mock Response (dev)'), ('error', 'Return Error Object')], default='empty', help_text='Action when module is DISABLED for tenant', max_length=20)),
                ('when_disabled_write', models.CharField(choices=[('buffer', 'Buffer for Replay'), ('redirect', 'Redirect to Core'), ('drop', 'Drop Silently'), ('queue_event', 'Queue as Event'), ('error', 'Return Error Object')], default='drop', help_text='Action for writes when module is DISABLED', max_length=20)),
                ('when_unauthorized_read', models.CharField(choices=[('wait', 'Wait (blocking)'), ('empty', 'Empty Safe Response'), ('cached', 'Cached Last Value'), ('mock', 'Mock Response (dev)'), ('error', 'Return Error Object')], default='empty', help_text='Action when tenant has NO PERMISSION', max_length=20)),
                ('when_unauthorized_write', models.CharField(choices=[('buffer', 'Buffer for Replay'), ('redirect', 'Redirect to Core'), ('drop', 'Drop Silently'), ('queue_event', 'Queue as Event'), ('error', 'Return Error Object')], default='drop', help_text='Action for writes when NO PERMISSION', max_length=20)),
                ('cache_ttl_seconds', models.IntegerField(default=300, help_text="How long to cache responses (for 'cached' fallback)")),
                ('buffer_ttl_seconds', models.IntegerField(default=3600, help_text='How long to retain buffered writes before expiring')),
                ('max_buffer_size', models.IntegerField(default=100, help_text='Maximum buffered requests per org/module')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority policies take precedence')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Connector Policy',
                'verbose_name_plural': 'Connector Policies',
                'db_table': 'ConnectorPolicy',
                'ordering': ['-priority', 'target_module'],
                'unique_together': {('target_module', 'target_endpoint')},
            },
        ),
        migrations.CreateModel(
            name='ModuleContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provides', models.JSONField(default=dict, help_text='\n        {\n            "read_endpoints": ["products/", "categories/"],\n            "write_endpoints": ["products/create/"],\n            "events_emitted": ["product.created", "stock.updated"],\n            "functions_exposed": ["get_product_cost", "validate_sku"]\n        }\n        ')),
                ('needs', models.JSONField(default=dict, help_text='\n        {\n            "data_from": [\n                {"module": "inventory", "endpoint": "products/cost/", "blocking": false}\n            ],\n            "events_from": [\n                {"module": "pos", "event": "sale.completed"}\n            ],\n            "capabilities": ["accounting.post_journal_entry"]\n        }\n        ')),
                ('rules', models.JSONField(default=dict, help_text='\n        {\n            "can_work_without": ["crm", "reporting"],\n            "buffer_writes_to": ["accounting"],\n            "critical_dependencies": ["core"]\n        }\n        ')),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='erp.systemmodule')),
            ],
            options={
                'verbose_name': 'Module Contract',
                'verbose_name_plural': 'Module Contracts',
                'db_table': 'ModuleContract',
            },
        ),
        migrations.CreateModel(
            name='BufferedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_module', models.CharField(max_length=100)),
                ('target_endpoint', models.CharField(max_length=255)),
                ('source_module', models.CharField(blank=True, max_length=100, null=True)),
                ('method', models.CharField(default='POST', max_length=10)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('replayed', 'Replayed'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('replayed_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buffered_requests', to='erp.organization')),
            ],
            options={
                'verbose_name': 'Buffered Request',
                'verbose_name_plural': 'Buffered Requests',
                'db_table': 'BufferedRequest',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_module', 'status'], name='BufferedReq_target__e5698a_idx'), models.Index(fields=['organization', 'status'], name='BufferedReq_organiz_9f3c5c_idx'), models.Index(fields=['expires_at'], name='BufferedReq_expires_24b35d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConnectorCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=500, unique=True)),
                ('target_module', models.CharField(max_length=100)),
                ('target_endpoint', models.CharField(max_length=255)),
                ('response_data', models.JSONField()),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_cache', to='erp.organization')),
            ],
            options={
                'verbose_name': 'Connector Cache',
                'verbose_name_plural': 'Connector Cache Entries',
                'db_table': 'ConnectorCache',
                'indexes': [models.Index(fields=['cache_key'], name='ConnectorCa_cache_k_5010a6_idx'), models.Index(fields=['expires_at'], name='ConnectorCa_expires_6ed7cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConnectorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_module', models.CharField(blank=True, max_length=100, null=True)),
                ('target_module', models.CharField(max_length=100)),
                ('target_endpoint', models.CharField(max_length=255)),
                ('operation', models.CharField(max_length=10)),
                ('module_state', models.CharField(max_length=20)),
                ('decision', models.CharField(choices=[('forward', 'Forwarded'), ('fallback', 'Fallback Applied'), ('buffer', 'Buffered'), ('reject', 'Rejected'), ('replay', 'Replayed')], max_length=20)),
                ('success', models.BooleanField(default=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_logs', to='erp.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('policy_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.connectorpolicy')),
            ],
            options={
                'verbose_name': 'Connector Log',
                'verbose_name_plural': 'Connector Logs',
                'db_table': 'ConnectorLog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_module', 'created_at'], name='ConnectorLo_target__13ab50_idx'), models.Index(fields=['organization', 'created_at'], name='ConnectorLo_organiz_6f6763_idx'), models.Index(fields=['decision', 'created_at'], name='ConnectorLo_decisio_6dd17f_idx')],
            },
        ),
    ]
