"""
OrderLineTaxEntry
=================
One row per tax per order line (transactional taxes only).

Types: VAT, AIRSI, PURCHASE_TAX, VAT_REVERSE_CHARGE, EXCISE, STAMP, OTHER
Periodic taxes (turnover, forfait, profit) are NOT stored here.
They are handled by PeriodicTaxAccrual service at period close.
"""
from django.db import models
from erp.models import TenantModel


class OrderLineTaxEntry(TenantModel):

    TAX_TYPE_CHOICES = (
        ('VAT',               'Value Added Tax (TVA)'),
        ('VAT_REVERSE_CHARGE','VAT Reverse Charge (Autoliquidation)'),
        ('AIRSI',             'AIRSI Withholding Tax'),
        ('PURCHASE_TAX',      'Purchase Tax / Taxe sur Achat'),
        ('SALES_TAX',         'Sales Tax (per transaction)'),
        ('EXCISE',            'Excise Duty'),
        ('STAMP',             'Stamp Duty'),
        ('OTHER',             'Other Tax'),
        ('CUSTOM',            'Custom User-Defined Tax'),
    )

    TRANSACTION_TYPE = (
        ('SALE',     'Sale (POS Order)'),
        ('PURCHASE', 'Purchase Order'),
    )

    AIRSI_TREATMENT = (
        ('CAPITALIZE', 'Added to inventory cost'),
        ('RECOVER',    'Booked as AIRSI Récupérable'),
        ('EXPENSE',    'Expensed to P&L'),
    )

    # ── Link to order line ────────────────────────────────────────────
    # IntegerField to avoid cross-app circular imports
    order_line_id = models.IntegerField(
        db_column='order_line_id',
        help_text='FK to OrderLine or PurchaseOrderLine (by transaction_type)'
    )
    transaction_type = models.CharField(
        max_length=10, choices=TRANSACTION_TYPE, default='SALE'
    )

    # ── Tax definition ────────────────────────────────────────────────
    tax_type = models.CharField(max_length=25, choices=TAX_TYPE_CHOICES)
    rate = models.DecimalField(max_digits=7, decimal_places=4, default=0)
    base_amount = models.DecimalField(
        max_digits=15, decimal_places=2, default=0,
        help_text='The amount this tax was calculated on (usually HT)'
    )
    amount = models.DecimalField(
        max_digits=15, decimal_places=2, default=0,
        help_text='Tax amount (rate × base_amount)'
    )

    # ── Cost impact ────────────────────────────────────────────────────
    cost_impact_ratio = models.DecimalField(
        max_digits=4, decimal_places=3, default=0,
        help_text='0=no cost impact, 1=full cost impact, 0.5=partial'
    )
    cost_impact_amount = models.DecimalField(
        max_digits=15, decimal_places=2, default=0,
        help_text='amount × cost_impact_ratio — added to inventory cost'
    )

    # ── Journal account ────────────────────────────────────────────────
    journal_account_id = models.IntegerField(
        null=True, blank=True,
        help_text='COA account used in the journal entry for this tax line'
    )

    # ── AIRSI specific ─────────────────────────────────────────────────
    airsi_treatment = models.CharField(
        max_length=12, choices=AIRSI_TREATMENT,
        null=True, blank=True,
        help_text='Only set for AIRSI tax type'
    )

    # ── Custom Rule Link ──────────────────────────────────────────────
    custom_tax_rule = models.ForeignKey(
        'finance.CustomTaxRule', on_delete=models.SET_NULL, null=True, blank=True,
        help_text='FK to CustomTaxRule if this line was generated by a dynamic rule'
    )

    # ── Scope ─────────────────────────────────────────────────────────
    scope = models.CharField(
        max_length=10,
        choices=[('OFFICIAL', 'Official'), ('INTERNAL', 'Internal')],
        default='OFFICIAL'
    )

    # ── Audit ─────────────────────────────────────────────────────────
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        db_table = 'order_line_tax_entry'
        ordering = ['order_line_id', 'tax_type']
        indexes = [
            models.Index(fields=['order_line_id', 'transaction_type']),
        ]

    def __str__(self):
        return f"{self.tax_type} {self.rate * 100:.1f}% → {self.amount} (impact={self.cost_impact_amount})"

    @classmethod
    def from_tax_line_dict(cls, tax_line_dict: dict, order_line_id: int,
                           transaction_type: str = 'SALE', scope: str = 'OFFICIAL',
                           organization=None) -> 'OrderLineTaxEntry':
        """
        Build an unsaved OrderLineTaxEntry from a tax_line dict
        as returned by TaxCalculator.resolve_purchase_costs().
        """
        from decimal import Decimal
        amount = Decimal(str(tax_line_dict['amount']))
        ratio  = Decimal(str(tax_line_dict['cost_impact_ratio']))
        base   = Decimal(str(tax_line_dict.get('base_amount', 0)))

        return cls(
            organization=organization,
            order_line_id=order_line_id,
            transaction_type=transaction_type,
            tax_type=tax_line_dict['type'],
            rate=Decimal(str(tax_line_dict['rate'])),
            base_amount=base,
            amount=amount,
            cost_impact_ratio=ratio,
            cost_impact_amount=(amount * ratio).quantize(Decimal('0.01')),
            airsi_treatment=tax_line_dict.get('treatment'),
            custom_tax_rule_id=tax_line_dict.get('custom_tax_rule_id'),
            scope=scope,
        )
