# Generated by Django 5.1.7 on 2026-02-19 11:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField(blank=True, db_column='contact_id', help_text='Specific contact this rule applies to', null=True)),
                ('product_id', models.IntegerField(blank=True, db_column='product_id', help_text='Specific product (null = applies to all products)', null=True)),
                ('category_id', models.IntegerField(blank=True, db_column='category_id', help_text='Product category (null = all categories)', null=True)),
                ('discount_type', models.CharField(choices=[('FIXED_PRICE', 'Fixed Price Override'), ('PERCENTAGE', 'Percentage Discount'), ('AMOUNT_OFF', 'Fixed Amount Off')], default='FIXED_PRICE', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price value: fixed price, percentage, or amount off', max_digits=15)),
                ('min_quantity', models.IntegerField(default=1, help_text='Minimum quantity for this rule to apply')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'client_price_rule',
                'ordering': ['-is_active', 'discount_type'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer'), ('LEAD', 'Lead'), ('PARTNER', 'Partner'), ('CREDITOR', 'Creditor'), ('DEBTOR', 'Debtor')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('vat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('linked_account_id', models.IntegerField(blank=True, db_column='linked_account_id', null=True)),
                ('supplier_category', models.CharField(blank=True, choices=[('REGULAR', 'Regular'), ('DEPOT_VENTE', 'Depot Vente (Consignment)'), ('MIXED', 'Mixed')], default='REGULAR', help_text='Supplier sourcing strategy: Regular, Consignment (Depot Vente), or Mixed', max_length=20, null=True)),
                ('customer_type', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_tier', models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('VIP', 'VIP'), ('WHOLESALE', 'Wholesale'), ('RETAIL', 'Retail')], default='STANDARD', help_text='Client pricing tier: Standard, VIP, Wholesale, Retail', max_length=20, null=True)),
                ('loyalty_points', models.IntegerField(default=0, help_text='Accumulated loyalty points')),
                ('first_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('total_orders', models.IntegerField(default=0, help_text='Total completed orders')),
                ('lifetime_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total revenue from this customer', max_digits=15)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average order value', max_digits=15)),
                ('overall_rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Weighted average rating (1-5)', max_digits=3)),
                ('quality_rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3)),
                ('delivery_rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3)),
                ('pricing_rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3)),
                ('service_rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3)),
                ('total_ratings', models.IntegerField(default=0, help_text='Number of ratings submitted')),
                ('supplier_total_orders', models.IntegerField(default=0)),
                ('on_time_deliveries', models.IntegerField(default=0)),
                ('late_deliveries', models.IntegerField(default=0)),
                ('total_purchase_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total value of POs placed with this supplier', max_digits=15)),
                ('avg_lead_time_days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Average days from PO to delivery', max_digits=6)),
                ('is_eu_supplier', models.BooleanField(default=False)),
                ('vat_number_eu', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=3, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Starting balance when contact was created', max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current running balance (auto-computed)', max_digits=15)),
                ('default_cost_basis', models.CharField(blank=True, choices=[('HT', 'Hors Taxe'), ('TTC', 'Toutes Taxes Comprises')], default='HT', help_text='Default pricing basis for this supplier', max_length=3, null=True)),
                ('payment_terms_days', models.IntegerField(default=0, help_text='Default payment terms in days (0 = immediate)')),
                ('preferred_payment_method', models.CharField(blank=True, help_text='Preferred method: CASH, BANK, CHECK, MOBILE_MONEY, etc.', max_length=50, null=True)),
                ('airsi_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_airsi_subject', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate to hide without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='PriceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority groups override lower ones when a contact belongs to multiple groups')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, help_text='Optional start date for time-limited pricing', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Optional end date for time-limited pricing', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'price_group',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField(db_column='contact_id')),
                ('joined_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'price_group_member',
            },
        ),
    ]
