# Generated by Django 6.0.2 on 2026-02-23 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpricerule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='contact',
            name='home_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.site'),
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='pricegroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='clientpricerule',
            name='price_group',
            field=models.ForeignKey(blank=True, help_text='Price group this rule applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='crm.pricegroup'),
        ),
        migrations.AddField(
            model_name='pricegroupmember',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='pricegroupmember',
            name='price_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='crm.pricegroup'),
        ),
        migrations.AlterUniqueTogether(
            name='pricegroupmember',
            unique_together={('price_group', 'contact_id', 'organization')},
        ),
    ]
