# Generated by Django 6.0.2 on 2026-02-09 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('erp', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='home_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.site'),
        ),
        migrations.AddField(
            model_name='contact',
            name='linked_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
    ]
