# Generated by Django 6.0.3 on 2026-05-02 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_initial'),
        ('erp', '0001_initial'),
        ('inventory', '0001_initial'),
        ('pos', '0001_initial'),
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='home_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='contact',
            name='home_zone',
            field=models.ForeignKey(blank=True, help_text='Default delivery zone for this client (auto-selected in POS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='pos.deliveryzone'),
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='complianceoverride',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_overrides', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='complianceevent',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_events', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='contactauditlog',
            name='contact',
            field=models.ForeignKey(help_text='The contact this audit entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='contactauditlog',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='contactcompliancedocument',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_documents', to='storage.storedfile'),
        ),
        migrations.AddField(
            model_name='contactcompliancedocument',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_documents', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='contactcompliancedocument',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='contactcompliancedocument',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_versions', to='crm.contactcompliancedocument'),
        ),
        migrations.AddField(
            model_name='complianceevent',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='crm.contactcompliancedocument'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='contact',
            field=models.ForeignKey(help_text='Parent business contact', on_delete=django.db.models.deletion.CASCADE, related_name='people', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='contacttag',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='contacttag',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category for hierarchical grouping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='crm.contacttag'),
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='User-defined categories: Wholesale, Retail, Family, VIP, etc.', related_name='contacts', to='crm.contacttag'),
        ),
        migrations.AddField(
            model_name='contacttask',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='contacttask',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='followuppolicy',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followuppolicy',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Scope to a specific branch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='followuppolicy',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_policies', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='followuppolicy',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='interactionlog',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='interactionlog',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='interactionlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricegroup',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='clientpricerule',
            name='price_group',
            field=models.ForeignKey(blank=True, help_text='Price group this rule applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='crm.pricegroup'),
        ),
        migrations.AddField(
            model_name='pricegroupmember',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='pricegroupmember',
            name='price_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='crm.pricegroup'),
        ),
        migrations.AddField(
            model_name='relationshipassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_relationship_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationshipassignment',
            name='assigned_to',
            field=models.ForeignKey(help_text='The user responsible for this relationship', on_delete=django.db.models.deletion.CASCADE, related_name='owned_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationshipassignment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='relationshipassignment',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='relationshipassignment',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='scheduledactivity',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledactivity',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledactivity',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='scheduledactivity',
            name='followup_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.followuppolicy'),
        ),
        migrations.AddField(
            model_name='scheduledactivity',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='activityreminder',
            name='scheduled_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='crm.scheduledactivity'),
        ),
        migrations.AddField(
            model_name='supplierproductpolicy',
            name='assigned_buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierproductpolicy',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='supplierproductpolicy',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='supplierproductpolicy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='supplierproductpolicy',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_product_policies', to='crm.contact'),
        ),
        migrations.AddIndex(
            model_name='contactauditlog',
            index=models.Index(fields=['contact', '-created_at'], name='idx_audit_contact_time'),
        ),
        migrations.AddIndex(
            model_name='contactauditlog',
            index=models.Index(fields=['organization', 'action'], name='idx_audit_tenant_action'),
        ),
        migrations.AlterUniqueTogether(
            name='contacttag',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'type'], name='idx_contact_tenant_type'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'status'], name='idx_contact_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'email'], name='idx_contact_tenant_email'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'phone'], name='idx_contact_tenant_phone'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'vat_id'], name='idx_contact_tenant_vat'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'entity_type'], name='idx_contact_tenant_entity'),
        ),
        migrations.AlterUniqueTogether(
            name='pricegroupmember',
            unique_together={('price_group', 'contact_id', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='supplierproductpolicy',
            unique_together={('organization', 'supplier', 'product', 'branch')},
        ),
    ]
