# Generated by Django 5.1.7 on 2026-02-19 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricegroup',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='pricegroupmember',
            name='price_group',
        ),
        migrations.AlterUniqueTogether(
            name='pricegroupmember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pricegroupmember',
            name='organization',
        ),
        migrations.DeleteModel(
            name='ClientPriceRule',
        ),
        migrations.DeleteModel(
            name='PriceGroup',
        ),
        migrations.DeleteModel(
            name='PriceGroupMember',
        ),
    ]
