# Generated by Django 5.2.11 on 2026-02-27 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_contact_home_site'),
        ('pos', '0017_alter_possettings_require_client_delivery_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='home_zone',
            field=models.ForeignKey(blank=True, help_text='Default delivery zone for this client (auto-selected in POS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='pos.deliveryzone'),
        ),
    ]
