# Generated by Django 5.1.7 on 2026-02-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_contact_created_at_alter_contact_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='linked_account',
        ),
        migrations.AddField(
            model_name='contact',
            name='linked_account_id',
            field=models.IntegerField(blank=True, db_column='linked_account_id', null=True),
        ),
    ]
