# Generated by Django 6.0.2 on 2026-03-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_contact_home_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='whatsapp_group_id',
            field=models.CharField(blank=True, help_text='WhatsApp Group ID (if you want notifications sent to a shared group instead of direct message)', max_length=100, null=True),
        ),
    ]
