# Generated by Django 5.1.7 on 2026-02-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_contact_linked_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='customer_tier',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('VIP', 'VIP'), ('WHOLESALE', 'Wholesale'), ('RETAIL', 'Retail')], default='STANDARD', help_text='Client pricing tier: Standard, VIP, Wholesale, Retail', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Deactivate to hide without deleting'),
        ),
        migrations.AddField(
            model_name='contact',
            name='loyalty_points',
            field=models.IntegerField(default=0, help_text='Accumulated loyalty points'),
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='payment_terms_days',
            field=models.IntegerField(default=0, help_text='Default payment terms in days (0 = immediate)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='preferred_payment_method',
            field=models.CharField(blank=True, help_text='Preferred method: CASH, BANK, CHECK, MOBILE_MONEY, etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='supplier_category',
            field=models.CharField(blank=True, choices=[('REGULAR', 'Regular'), ('DEPOT_VENTE', 'Depot Vente (Consignment)'), ('MIXED', 'Mixed')], default='REGULAR', help_text='Supplier sourcing strategy: Regular, Consignment (Depot Vente), or Mixed', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer'), ('LEAD', 'Lead'), ('PARTNER', 'Partner'), ('CREDITOR', 'Creditor'), ('DEBTOR', 'Debtor')], max_length=20),
        ),
    ]
