# Generated by Django 5.1.7 on 2026-02-16 14:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_add_supplier_categories_and_contact_enrichment'),
        ('erp', '0043_transaction_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority groups override lower ones when a contact belongs to multiple groups')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, help_text='Optional start date for time-limited pricing', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Optional end date for time-limited pricing', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'price_group',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientPriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField(blank=True, db_column='contact_id', help_text='Specific contact this rule applies to', null=True)),
                ('product_id', models.IntegerField(blank=True, db_column='product_id', help_text='Specific product (null = applies to all products)', null=True)),
                ('category_id', models.IntegerField(blank=True, db_column='category_id', help_text='Product category (null = all categories)', null=True)),
                ('discount_type', models.CharField(choices=[('FIXED_PRICE', 'Fixed Price Override'), ('PERCENTAGE', 'Percentage Discount'), ('AMOUNT_OFF', 'Fixed Amount Off')], default='FIXED_PRICE', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price value: fixed price, percentage, or amount off', max_digits=15)),
                ('min_quantity', models.IntegerField(default=1, help_text='Minimum quantity for this rule to apply')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('price_group', models.ForeignKey(blank=True, help_text='Price group this rule applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='crm.pricegroup')),
            ],
            options={
                'db_table': 'client_price_rule',
                'ordering': ['-is_active', 'discount_type'],
            },
        ),
        migrations.CreateModel(
            name='PriceGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField(db_column='contact_id')),
                ('joined_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('price_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='crm.pricegroup')),
            ],
            options={
                'db_table': 'price_group_member',
                'unique_together': {('price_group', 'contact_id', 'organization')},
            },
        ),
    ]
