# Generated by Django 5.2.11 on 2026-03-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_contact_tax_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='supplier_vat_regime',
            field=models.CharField(blank=True, choices=[('ASSUJETTI', 'Assujetti TVA — issues official TVA invoices (HT + TVA)'), ('NON_ASSUJETTI', 'Non-assujetti — issues simple receipts (no TVA breakdown)'), ('FOREIGN', 'Foreign supplier — reverse charge may apply')], default='ASSUJETTI', help_text='Tax regime of this supplier — determines whether VAT appears on their invoices', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='client_type',
            field=models.CharField(blank=True, choices=[('B2B', 'Business (B2B) — Can receive TVA invoices'), ('B2C', 'Individual (B2C) — Receives simple receipts only'), ('UNKNOWN', 'Unknown — Not yet classified')], default='UNKNOWN', help_text='Legacy. Use tax_profile_id.vat_registered for new engine logic.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='commercial_category',
            field=models.CharField(blank=True, choices=[('RETAIL', 'Retail Supplier'), ('WHOLESALE', 'Wholesale Supplier'), ('NORMAL', 'Normal / Standard'), ('FOREIGN', 'Foreign Supplier'), ('MICRO', 'Micro / Non-assujetti'), ('B2B_ASSUJETTI', 'B2B — VAT Registered Client'), ('B2B_NON_ASSUJETTI', 'B2B — Not VAT Registered Client'), ('B2C', 'B2C — Individual Client'), ('INSTITUTIONAL', 'Institutional / Government'), ('EXPORT', 'Export Client')], default='NORMAL', help_text='Commercial label only — NO fiscal effect. Tax behavior comes from tax_profile_id.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tax_profile_id',
            field=models.IntegerField(blank=True, db_column='tax_profile_id', help_text='FK to CounterpartyTaxProfile (IntegerField avoids circular import)', null=True),
        ),
    ]
