# Generated by Django 5.2.11 on 2026-03-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_contact_supplier_vat_regime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpricerule',
            name='packaging_level_id',
            field=models.IntegerField(blank=True, db_column='packaging_level_id', help_text='Packaging level (null = base unit price)', null=True),
        ),
        migrations.AddField(
            model_name='clientpricerule',
            name='product_group_id',
            field=models.IntegerField(blank=True, db_column='product_group_id', help_text='Product group (null = not group-scoped)', null=True),
        ),
    ]
