# Generated by Django 5.2.11 on 2026-03-10 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_contacttag_contact_type'),
        ('erp', '0019_paymentterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='entity_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('BUSINESS', 'Business / Company')], default='INDIVIDUAL', help_text='Individual person or Business/Company entity', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer'), ('BOTH', 'Customer & Supplier'), ('LEAD', 'Lead'), ('CREDITOR', 'Creditor'), ('DEBTOR', 'Debtor'), ('CONTACT', 'Contact'), ('SERVICE', 'Service Provider')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contacttag',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('BOTH', 'Customer & Supplier'), ('LEAD', 'Lead'), ('CREDITOR', 'Creditor'), ('DEBTOR', 'Debtor'), ('CONTACT', 'Contact'), ('SERVICE', 'Service Provider')], help_text='Scope this category to a specific contact type. Null = applies to all types.', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person', max_length=255)),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary Contact'), ('CEO', 'CEO / Director'), ('MANAGER', 'Manager'), ('ACCOUNTANT', 'Accountant / Finance'), ('SALES', 'Sales Representative'), ('PURCHASING', 'Purchasing / Procurement'), ('LOGISTICS', 'Logistics / Delivery'), ('TECHNICAL', 'Technical / IT'), ('LEGAL', 'Legal / Compliance'), ('OTHER', 'Other')], default='OTHER', help_text='Role within the organization', max_length=20)),
                ('department', models.CharField(blank=True, help_text='Department: Finance, IT, Operations, etc.', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp number (for direct notifications)', max_length=50, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the main point of contact for this business?')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('contact', models.ForeignKey(help_text='Parent business contact', on_delete=django.db.models.deletion.CASCADE, related_name='people', to='crm.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'contact_person',
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
