# Generated by Django 6.0.2 on 2026-03-10 20:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_contact_entity_type_alter_contact_type_and_more'),
        ('erp', '0019_paymentterm'),
        ('inventory', '0019_goodsreceipt_branch_inventory_branch_and_more'),
        ('pos', '0059_procurementrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('FIELD_CHANGE', 'Field Value Changed'), ('STATUS_CHANGE', 'Lifecycle Status Changed'), ('LOYALTY_ADJUST', 'Manual Loyalty Adjustment'), ('PRICE_RULE_CHANGE', 'Price Rule Modified'), ('GROUP_MEMBERSHIP', 'Price Group Membership Changed'), ('MERGE', 'Contact Merged'), ('BLOCK', 'Contact Blocked'), ('ARCHIVE', 'Contact Archived'), ('UNBLOCK', 'Contact Unblocked'), ('RESTORE', 'Contact Restored from Archive')], max_length=30)),
                ('field_name', models.CharField(blank=True, help_text='Name of the field that changed (for FIELD_CHANGE actions)', max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (JSON-safe string)', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value (JSON-safe string)', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason or comment for this change', null=True)),
                ('source', models.CharField(choices=[('UI', 'User Interface'), ('API', 'API Call'), ('IMPORT', 'Bulk Import'), ('EVENT', 'System Event'), ('SYSTEM', 'Internal System')], default='UI', max_length=10)),
                ('actor_user_id', models.IntegerField(blank=True, help_text='User who made the change', null=True)),
                ('actor_name', models.CharField(blank=True, help_text='Display name of actor', max_length=255, null=True)),
                ('correlation_id', models.CharField(blank=True, help_text='Request/event correlation ID for tracing', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contact_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='archived_by',
            field=models.IntegerField(blank=True, help_text='User ID who archived', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='blocked_by',
            field=models.IntegerField(blank=True, help_text='User ID who blocked', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='blocked_reason',
            field=models.TextField(blank=True, help_text='Reason for blocking', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='commercial_status',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('CREDIT_HOLD', 'Credit Hold — no new credit sales'), ('NO_NEW_SALES', 'No New Sales — blocked from sales transactions'), ('NO_NEW_PURCHASES', 'No New Purchases — blocked from purchase transactions'), ('MANUAL_REVIEW', 'Manual Review — requires admin approval for transactions')], default='NORMAL', help_text='Operational status affecting commercial transactions', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='finance_link_status',
            field=models.CharField(choices=[('LINKED', 'Successfully linked to COA'), ('PENDING', 'Pending — finance service was unavailable'), ('FAILED', 'Failed — posting rules misconfigured'), ('N_A', 'Not applicable (LEAD/CONTACT)')], default='N_A', help_text='Status of COA account linkage', max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='linked_payable_account_id',
            field=models.IntegerField(blank=True, help_text='Secondary AP sub-account for BOTH contacts. Only populated when type=BOTH.', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='merge_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='merged_into_contact_id',
            field=models.IntegerField(blank=True, help_text='If MERGED, the surviving master contact ID', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft — incomplete, not commercially usable'), ('ACTIVE', 'Active — fully operational'), ('ON_HOLD', 'On Hold — temporarily paused, pending review'), ('BLOCKED', 'Blocked — risk/compliance block, no new transactions'), ('ARCHIVED', 'Archived — historically preserved, read-only'), ('MERGED', 'Merged — absorbed into another master contact')], default='ACTIVE', help_text='Lifecycle status governing what operations are allowed', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='DEPRECATED: use current_balance (finance-derived). Kept for backward compat only.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linked_account_id',
            field=models.IntegerField(blank=True, db_column='linked_account_id', help_text='Primary COA sub-account (AR for customers, AP for suppliers, AR for BOTH)', null=True),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'type'], name='idx_contact_org_type'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'status'], name='idx_contact_org_status'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'email'], name='idx_contact_org_email'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'phone'], name='idx_contact_org_phone'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'vat_id'], name='idx_contact_org_vat'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'entity_type'], name='idx_contact_org_entity'),
        ),
        migrations.AddField(
            model_name='contactauditlog',
            name='contact',
            field=models.ForeignKey(help_text='The contact this audit entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='contactauditlog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddIndex(
            model_name='contactauditlog',
            index=models.Index(fields=['contact', '-created_at'], name='idx_audit_contact_time'),
        ),
        migrations.AddIndex(
            model_name='contactauditlog',
            index=models.Index(fields=['organization', 'action'], name='idx_audit_org_action'),
        ),
    ]
