# Generated by Django 5.2.11 on 2026-03-10 21:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_deprecations_and_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='avg_lead_time_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='[OBJECTIVE] Average days from PO to delivery', max_digits=6),
        ),
        migrations.AlterField(
            model_name='contact',
            name='delivery_rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='[SUBJECTIVE] Manual delivery reliability impression (1-5)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='contact',
            name='late_deliveries',
            field=models.IntegerField(default=0, help_text='[OBJECTIVE] Deliveries received after expected date'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='on_time_deliveries',
            field=models.IntegerField(default=0, help_text='[OBJECTIVE] Deliveries received on or before expected date'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='overall_rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='[COMPOSITE] Weighted average of subjective ratings (1-5)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='contact',
            name='pricing_rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='[SUBJECTIVE] Manual pricing competitiveness rating (1-5)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='contact',
            name='quality_rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='[SUBJECTIVE] Manual quality assessment (1-5)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='contact',
            name='service_rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='[SUBJECTIVE] Manual communication/service quality (1-5)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='contact',
            name='supplier_total_orders',
            field=models.IntegerField(default=0, help_text='[OBJECTIVE] Total POs placed with this supplier'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='total_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='[OBJECTIVE] Total value of POs placed with this supplier', max_digits=15),
        ),
        migrations.AlterField(
            model_name='contact',
            name='total_ratings',
            field=models.IntegerField(default=0, help_text='[SUBJECTIVE] Number of manual ratings submitted'),
        ),
    ]
