# Generated by Django 6.0.2 on 2026-03-10 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_alter_contact_avg_lead_time_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttag',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category for hierarchical grouping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='crm.contacttag'),
        ),
    ]
