# Generated by Django 5.2.11 on 2026-03-11 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_merge_20260311_0135'),
        ('erp', '0020_organization_finance_hard_locked_at_and_more'),
        ('inventory', '0021_goodsreceipt_approved_by_goodsreceipt_assigned_to_and_more'),
        ('pos', '0062_purchaseorder_invoiced_at_supplierclaim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contact',
            name='idx_contact_org_type',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='idx_contact_org_status',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='idx_contact_org_email',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='idx_contact_org_phone',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='idx_contact_org_vat',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='idx_contact_org_entity',
        ),
        migrations.RemoveIndex(
            model_name='contactauditlog',
            name='idx_audit_org_action',
        ),
        migrations.RemoveField(
            model_name='activityreminder',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='clientpricerule',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='complianceevent',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='complianceoverride',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='compliancerule',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='contactauditlog',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='contactcompliancedocument',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='contacttag',
            unique_together={('organization', 'name')},
        ),
        migrations.RemoveField(
            model_name='contacttask',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='followuppolicy',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='interactionlog',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='pricegroup',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='pricegroupmember',
            unique_together={('price_group', 'contact_id', 'organization')},
        ),
        migrations.RemoveField(
            model_name='relationshipassignment',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='scheduledactivity',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='supplierproductpolicy',
            unique_together={('organization', 'supplier', 'product', 'branch')},
        ),
        migrations.AddField(
            model_name='activityreminder',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='clientpricerule',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='complianceevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='complianceoverride',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='compliancerule',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='contactauditlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='contactcompliancedocument',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='contacttag',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='contacttask',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='followuppolicy',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='interactionlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='pricegroup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='pricegroupmember',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='relationshipassignment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='scheduledactivity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='supplierproductpolicy',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='followup_status',
            field=models.CharField(choices=[('ON_TRACK', 'On Track'), ('DUE_SOON', 'Follow-up Due Soon'), ('OVERDUE', 'Follow-up Overdue'), ('DORMANT', 'Dormant (No interaction > 30d)'), ('NO_OWNER', 'No Owner Assigned')], default='ON_TRACK', max_length=20),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'type'], name='idx_contact_organization_type'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'status'], name='idx_contact_organization_status'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'email'], name='idx_contact_organization_email'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'phone'], name='idx_contact_organization_phone'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'vat_id'], name='idx_contact_organization_vat'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'entity_type'], name='idx_contact_organization_entity'),
        ),
        migrations.AddIndex(
            model_name='contactauditlog',
            index=models.Index(fields=['organization', 'action'], name='idx_audit_organization_action'),
        ),
        migrations.RemoveField(
            model_name='contacttag',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='pricegroupmember',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='supplierproductpolicy',
            name='organization',
        ),
    ]
