# Generated by Django 6.0.3 on 2026-04-02 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_remove_contact_idx_contact_org_type_and_more'),
        ('erp', '0025_rename_erp_auditlo_organization__3bae30_idx_erp_auditlo_tenant__3bae30_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contact',
            new_name='idx_contact_tenant_type',
            old_name='idx_contact_organization_type',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='idx_contact_tenant_status',
            old_name='idx_contact_organization_status',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='idx_contact_tenant_email',
            old_name='idx_contact_organization_email',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='idx_contact_tenant_phone',
            old_name='idx_contact_organization_phone',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='idx_contact_tenant_vat',
            old_name='idx_contact_organization_vat',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='idx_contact_tenant_entity',
            old_name='idx_contact_organization_entity',
        ),
        migrations.RenameIndex(
            model_name='contactauditlog',
            new_name='idx_audit_tenant_action',
            old_name='idx_audit_organization_action',
        ),
        migrations.AddField(
            model_name='contacttag',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='pricegroupmember',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='supplierproductpolicy',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='activityreminder',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='clientpricerule',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='complianceevent',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='complianceoverride',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='compliancerule',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='contactauditlog',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='contactcompliancedocument',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='contacttask',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='followuppolicy',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='pricegroup',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='relationshipassignment',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='scheduledactivity',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
    ]
