# Generated by Django 6.0.4 on 2026-04-20 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_remove_approvalrule_organization_and_more'),
        ('workforce', '0008_fix_organization_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebadge',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeescoreadjustment',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeescoreevent',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeescoreperiod',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeescoresummary',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scorerule',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
    ]
