import re
import sys

def process_file(filepath):
    with open(filepath, 'r') as f:
        content = f.read()

    # Generic white/black fading mapping
    content = content.replace("bg-white/[0.04]", "bg-[var(--app-surface-2)]")
    content = content.replace("bg-white/4", "bg-[var(--app-surface-2)]/50")
    content = content.replace("bg-white/5", "bg-[var(--app-surface-2)]")
    content = content.replace("bg-white/8", "bg-[var(--app-surface-hover)]")
    content = content.replace("bg-white/10", "bg-[var(--app-surface-hover)]")
    content = content.replace("bg-white/12", "bg-[var(--app-surface-hover)]")
    content = content.replace("bg-white/15", "bg-[var(--app-surface-hover)]")
    content = content.replace("bg-white/20", "bg-[var(--app-surface-hover)]")
    content = content.replace("bg-[#0a0f1c]", "bg-[var(--app-surface-2)]")
    content = content.replace("bg-black/30", "bg-black/10")

    content = content.replace("border-white/5", "border-[var(--app-border)]/50")
    content = content.replace("border-white/6", "border-[var(--app-border)]/50")
    content = content.replace("border-white/10", "border-[var(--app-border)]")
    content = content.replace("border-white/12", "border-[var(--app-border)]")
    content = content.replace("border-white/15", "border-[var(--app-border)]")
    content = content.replace("border-white/20", "border-[var(--app-border-strong)]/30")

    content = content.replace("text-white/20", "text-[var(--app-text-faint)]")
    content = content.replace("text-white/25", "text-[var(--app-text-faint)]")
    content = content.replace("text-white/30", "text-[var(--app-text-muted)]")
    content = content.replace("text-white/35", "text-[var(--app-text-muted)]")
    content = content.replace("text-white/40", "text-[var(--app-text-muted)]")
    content = content.replace("text-white/60", "text-[var(--app-text)]/80")
    content = content.replace("text-white/70", "text-[var(--app-text)]")
    content = content.replace("text-white/80", "text-[var(--app-text)]")
    content = content.replace("text-white ", "text-[var(--app-text)] ")
    content = content.replace("text-white'", "text-[var(--app-text)]'")
    content = content.replace('text-white"', 'text-[var(--app-text)]"')

    # POS Settings specifics
    content = content.replace("#080c18", "var(--app-bg)")
    content = content.replace("rgba(0,212,255,.05)", "var(--app-primary-light)")
    content = content.replace("rgba(0,212,255,.12)", "var(--app-primary-light)")
    content = content.replace("rgba(0,212,255,.25)", "var(--app-primary-glow)")
    content = content.replace("#00D4FF", "var(--app-primary)")
    content = content.replace("rgba(8,12,24,.85)", "var(--app-surface)")

    content = content.replace("bg-gradient-to-r from-cyan-500 to-teal-500", "bg-[var(--app-primary)] hover:bg-[var(--app-primary-dark)]")
    content = content.replace("shadow-cyan-500/20", "shadow-[var(--app-primary-glow)]")
    content = content.replace("text-slate-900", "text-white") # Since primary might be any color, better to assume white text on primary btn

    content = content.replace("text-cyan-400", "text-[var(--app-primary)]")
    content = content.replace("text-cyan-300", "text-[var(--app-primary)]")
    content = content.replace("text-cyan-500", "text-[var(--app-primary)]")
    content = content.replace("bg-cyan-500", "bg-[var(--app-primary)]")
    content = content.replace("bg-cyan-400/10", "bg-[var(--app-primary-light)]")
    content = content.replace("bg-cyan-400/12", "bg-[var(--app-primary-light)]")
    content = content.replace("border-cyan-400/20", "border-[var(--app-primary)]/20")
    content = content.replace("border-cyan-400/25", "border-[var(--app-primary)]/25")
    content = content.replace("border-cyan-400/30", "border-[var(--app-primary)]/30")
    content = content.replace("border-cyan-400/50", "border-[var(--app-primary-strong)]/50")

    content = content.replace("text-amber-400", "text-[var(--app-warning)]")
    content = content.replace("text-amber-300", "text-[var(--app-warning)]")
    content = content.replace("bg-amber-400/10", "bg-[var(--app-warning-bg)]")
    content = content.replace("bg-amber-400/12", "bg-[var(--app-warning-bg)]")
    content = content.replace("bg-amber-400/15", "bg-[var(--app-warning-bg)]")
    content = content.replace("bg-amber-400/25", "bg-[var(--app-warning-bg)]")
    content = content.replace("bg-amber-500/10", "bg-[var(--app-warning-bg)]")
    content = content.replace("border-amber-400/15", "border-[var(--app-warning)]/15")
    content = content.replace("border-amber-400/20", "border-[var(--app-warning)]/20")
    content = content.replace("border-amber-400/30", "border-[var(--app-warning)]/30")
    content = content.replace("border-amber-400/40", "border-[var(--app-warning)]/40")
    content = content.replace("hover:text-amber-400", "hover:text-[var(--app-warning)]")

    content = content.replace("text-emerald-400", "text-[var(--app-success)]")
    content = content.replace("text-emerald-300", "text-[var(--app-success)]")
    content = content.replace("bg-emerald-400/10", "bg-[var(--app-success-bg)]")
    content = content.replace("bg-emerald-400/12", "bg-[var(--app-success-bg)]")
    content = content.replace("border-emerald-400/15", "border-[var(--app-success)]/15")
    content = content.replace("border-emerald-400/20", "border-[var(--app-success)]/20")
    content = content.replace("border-emerald-400/25", "border-[var(--app-success)]/25")

    content = content.replace("text-rose-400", "text-[var(--app-error)]")
    content = content.replace("text-rose-500", "text-[var(--app-error)]")
    content = content.replace("bg-rose-500/8", "bg-[var(--app-error-bg)]")
    content = content.replace("bg-rose-500/12", "bg-[var(--app-error-bg)]")
    content = content.replace("bg-rose-500/15", "bg-[var(--app-error-bg)]")
    content = content.replace("border-rose-500/20", "border-[var(--app-error)]/20")
    content = content.replace("border-rose-500/40", "border-[var(--app-error)]/40")
    content = content.replace("border-rose-500/50", "border-[var(--app-error)]/50")

    content = content.replace("text-violet-400", "text-[var(--app-info)]")
    content = content.replace("text-violet-300", "text-[var(--app-info)]")
    content = content.replace("bg-violet-500/10", "bg-[var(--app-info-bg)]")
    content = content.replace("bg-violet-500/12", "bg-[var(--app-info-bg)]")
    content = content.replace("bg-violet-400/12", "bg-[var(--app-info-bg)]")
    content = content.replace("border-violet-500/20", "border-[var(--app-info)]/20")
    content = content.replace("border-violet-400/15", "border-[var(--app-info)]/15")
    content = content.replace("border-violet-400/30", "border-[var(--app-info)]/30")
    content = content.replace("border-violet-500/25", "border-[var(--app-info)]/25")

    # Lobby specifics
    content = content.replace("bg-gradient-to-br from-slate-950 via-indigo-950 to-slate-900", "")
    content = content.replace("text-indigo-400", "text-[var(--app-primary)]")
    content = content.replace("bg-indigo-500", "bg-[var(--app-primary)]")
    content = content.replace("text-indigo-500", "text-[var(--app-primary)]")
    content = content.replace("bg-indigo-500/10", "bg-[var(--app-primary-light)]")
    content = content.replace("bg-indigo-500/20", "bg-[var(--app-primary-light)]")
    content = content.replace("ring-indigo-500/10", "ring-[var(--app-primary-light)]")
    content = content.replace("from-indigo-500/0", "from-[var(--app-primary)]/0")
    content = content.replace("from-indigo-500/10", "from-[var(--app-primary)]/10")
    content = content.replace("to-purple-500/0", "to-[var(--app-primary-glow)]/0")
    content = content.replace("to-purple-500/10", "to-[var(--app-primary-glow)]/10")
    content = content.replace("shadow-indigo-500/30", "shadow-[var(--app-primary-glow)]")
    content = content.replace("border-indigo-500/50", "border-[var(--app-primary-strong)]")
    content = content.replace("border-indigo-500", "border-[var(--app-primary-strong)]")
    content = content.replace("hover:border-indigo-500/50", "hover:border-[var(--app-primary)]/50")
    content = content.replace("hover:border-indigo-400", "hover:border-[var(--app-primary)]/50")

    content = content.replace("bg-app-text/5", "bg-[var(--app-surface-2)]")
    content = content.replace("bg-app-text/10", "bg-[var(--app-surface-hover)]")
    content = content.replace("bg-app-text/15", "bg-[var(--app-surface-hover)]")
    content = content.replace("bg-app-text/20", "bg-[var(--app-surface-hover)]")
    content = content.replace("bg-app-text/25", "bg-[var(--app-surface-hover)]")

    content = content.replace("border-app-text/5", "border-[var(--app-border)]/50")
    content = content.replace("border-app-text/10", "border-[var(--app-border)]")
    content = content.replace("border-app-text/20", "border-[var(--app-border-strong)]/30")

    content = content.replace("text-app-text/15", "text-[var(--app-text-faint)]")
    content = content.replace("text-app-text/20", "text-[var(--app-text-faint)]")
    content = content.replace("text-app-text/30", "text-[var(--app-text-faint)]")
    content = content.replace("text-app-text/40", "text-[var(--app-text-muted)]")
    content = content.replace("text-app-text/50", "text-[var(--app-text-muted)]")
    content = content.replace("text-app-text/60", "text-[var(--app-text)]/80")
    content = content.replace("text-app-text/80", "text-[var(--app-text)]/90")

    with open(filepath, 'w') as f:
        f.write(content)

process_file('/root/.gemini/antigravity/scratch/TSFSYSTEM/src/app/(privileged)/sales/pos-settings/page.tsx')
process_file('/root/.gemini/antigravity/scratch/TSFSYSTEM/src/components/pos/POSLobby.tsx')

print("Replacement complete.")
