# Generated by Django 6.0.2 on 2026-02-23 01:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTaskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trigger_event', models.CharField(choices=[('PRICE_CHANGE', 'Product Price Changed'), ('LOW_STOCK', 'Low Stock Alert'), ('NEW_INVOICE', 'New Invoice Received'), ('EXPIRY_APPROACHING', 'Product Expiry Approaching'), ('PO_APPROVED', 'Purchase Order Approved'), ('CLIENT_COMPLAINT', 'Client Complaint Filed'), ('NEW_SUPPLIER', 'New Supplier Onboarded'), ('DELIVERY_COMPLETED', 'Delivery Completed'), ('ORDER_COMPLETED', 'Order Completed'), ('INVENTORY_COUNT', 'Inventory Count Needed'), ('CUSTOM', 'Custom Event')], max_length=30)),
                ('custom_event_code', models.CharField(blank=True, help_text='Event code for CUSTOM trigger type', max_length=100, null=True)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='JSON filter conditions, e.g. {"category_id": 5, "min_value": 1000}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'workspace_auto_task_rule',
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trigger', models.CharField(default='CUSTOM', help_text='Internal trigger code', max_length=30)),
                ('points', models.IntegerField(default=5, help_text='Points for completing the full checklist')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('assign_to_role', models.ForeignKey(blank=True, help_text='Auto-assign to users with this role', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.role')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'workspace_checklist_template',
            },
        ),
        migrations.CreateModel(
            name='ChecklistInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(default='PENDING', help_text='Internal status code', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workspace.checklisttemplate')),
            ],
            options={
                'db_table': 'workspace_checklist_instance',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workspace.checklisttemplate')),
            ],
            options={
                'db_table': 'workspace_checklist_template_item',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('assign_to_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.role')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'workspace_questionnaire',
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('RATING', 'Rating (1-5)'), ('TEXT', 'Free Text'), ('YESNO', 'Yes / No'), ('CHOICE', 'Multiple Choice')], default='RATING', max_length=10)),
                ('choices', models.JSONField(blank=True, default=list, help_text='Options for CHOICE type, e.g. ["Good", "Fair", "Poor"]')),
                ('max_score', models.IntegerField(default=5)),
                ('order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='workspace.questionnaire')),
            ],
            options={
                'db_table': 'workspace_questionnaire_question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(blank=True, help_text='e.g. "2026-Q1", "Jan 2026"', max_length=50, null=True)),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('max_possible_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('score_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_evaluations', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_given', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.questionnaire')),
            ],
            options={
                'db_table': 'workspace_questionnaire_response',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', help_text='Internal status code', max_length=20)),
                ('priority', models.CharField(default='MEDIUM', help_text='Internal priority code', max_length=20)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('SYSTEM', 'System Generated'), ('RECURRING', 'Recurring Instance'), ('REPLY', 'Task Response')], default='MANUAL', max_length=15)),
                ('points', models.IntegerField(default=1, help_text='Points earned on completion')),
                ('estimated_minutes', models.IntegerField(default=30)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_object_label', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_received', to=settings.AUTH_USER_MODEL)),
                ('assigned_to_group', models.ForeignKey(blank=True, help_text='Assign to all users with this role', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.role')),
                ('auto_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='workspace.autotaskrule')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='workspace.task')),
            ],
            options={
                'db_table': 'workspace_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('request_type', models.CharField(default='SUGGESTION', help_text='Internal request type code', max_length=30)),
                ('status', models.CharField(default='PENDING', help_text='Internal status code', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('resulting_task', models.ForeignKey(blank=True, help_text='Task created if request is approved', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.task')),
            ],
            options={
                'db_table': 'workspace_employee_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='workspace/attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workspace.task')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspace_task_attachment',
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'verbose_name_plural': 'Task Categories',
                'db_table': 'workspace_task_category',
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='workspace.taskcategory'),
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_response', models.BooleanField(default=False, help_text='True if this is a response flowing back UP the hierarchy')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workspace.task')),
            ],
            options={
                'db_table': 'workspace_task_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('default_priority', models.CharField(default='MEDIUM', help_text='Internal priority code', max_length=20)),
                ('default_points', models.IntegerField(default=1, help_text='Points earned on completion')),
                ('estimated_minutes', models.IntegerField(default=30, help_text='Estimated time in minutes')),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, help_text='DAILY, WEEKLY, MONTHLY, or cron-like expression', max_length=20, null=True)),
                ('recurrence_time', models.TimeField(blank=True, help_text='Time of day to create task', null=True)),
                ('assign_to_department', models.IntegerField(blank=True, help_text='Department ID — decoupled from HR module', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('assign_to_role', models.ForeignKey(blank=True, help_text='Auto-assign to users with this role', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.role')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'workspace_task_template',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='workspace.tasktemplate'),
        ),
        migrations.AddField(
            model_name='autotaskrule',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_rules', to='workspace.tasktemplate'),
        ),
        migrations.CreateModel(
            name='WorkspaceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_statuses', models.JSONField(blank=True, default=dict, help_text='JSON: {"PENDING": {"label": "Pending", "color": "#94a3b8"}, ...}')),
                ('task_priorities', models.JSONField(blank=True, default=dict, help_text='JSON: {"URGENT": {"label": "Urgent", "color": "#ef4444", "multiplier": 2.0}, ...}')),
                ('task_completion_weight', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5)),
                ('on_time_weight', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5)),
                ('checklist_weight', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('evaluation_weight', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5)),
                ('bronze_threshold', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5)),
                ('silver_threshold', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5)),
                ('gold_threshold', models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=5)),
                ('platinum_threshold', models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=5)),
                ('checklist_triggers', models.JSONField(blank=True, default=dict, help_text='JSON: {"SHIFT_START": "Start of Shift", ...}')),
                ('request_types', models.JSONField(blank=True, default=dict, help_text='JSON: {"EXPENSE": "Expense Claim", ...}')),
                ('enable_auto_tasks', models.BooleanField(default=True)),
                ('enable_checklists', models.BooleanField(default=True)),
                ('enable_performance_scoring', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'verbose_name': 'Workspace Configuration',
                'verbose_name_plural': 'Workspace Configurations',
                'db_table': 'workspace_config',
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_responses', to='workspace.checklistinstance')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('template_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.checklisttemplateitem')),
            ],
            options={
                'db_table': 'workspace_checklist_item_response',
                'unique_together': {('instance', 'template_item')},
            },
        ),
        migrations.CreateModel(
            name='EmployeePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=50)),
                ('overall_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tier', models.CharField(blank=True, max_length=20, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'workspace_employee_performance',
                'unique_together': {('organization', 'employee', 'period_label')},
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('choice_answer', models.CharField(blank=True, max_length=200, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.questionnairequestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='workspace.questionnaireresponse')),
            ],
            options={
                'db_table': 'workspace_questionnaire_answer',
                'unique_together': {('response', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'assigned_to'], name='workspace_t_status_a8d57c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='workspace_t_due_dat_c3b9e9_idx'),
        ),
    ]
