# Generated by Django 5.2.11 on 2026-02-28 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autotaskrule',
            name='assign_to_user',
            field=models.ForeignKey(blank=True, help_text='Assign generated task to this specific user (overrides role)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_task_rules_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Conditions: min_amount, max_amount, site_id, client_id, cashier_id, payment_method'),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='trigger_event',
            field=models.CharField(choices=[('PRICE_CHANGE', 'Product Price Changed'), ('LOW_STOCK', 'Low Stock Alert'), ('NEW_INVOICE', 'New Invoice Received'), ('EXPIRY_APPROACHING', 'Product Expiry Approaching'), ('PO_APPROVED', 'Purchase Order Approved'), ('CLIENT_COMPLAINT', 'Client Complaint Filed'), ('NEW_SUPPLIER', 'New Supplier Onboarded'), ('DELIVERY_COMPLETED', 'Delivery Completed'), ('ORDER_COMPLETED', 'Order Completed'), ('INVENTORY_COUNT', 'Inventory Count Needed'), ('CREDIT_SALE', 'Credit Sale — No Cash Collected'), ('HIGH_VALUE_SALE', 'High-Value Sale Threshold Crossed'), ('POS_RETURN', 'POS Return / Refund Processed'), ('OVERDUE_INVOICE', 'Invoice Overdue'), ('LATE_PAYMENT', 'Late Payment Detected'), ('CASHIER_DISCOUNT', 'Cashier Applied Discount'), ('NEGATIVE_STOCK', 'Negative Stock Sale'), ('DAILY_SUMMARY', 'End-of-Day Financial Summary'), ('CUSTOM', 'Custom Event')], max_length=30),
        ),
    ]
