# Generated by Django 6.0.2 on 2026-03-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_rename_wk_atr_module_active_idx_workspace_a_module_0a58d8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotaskrule',
            name='trigger_event',
            field=models.CharField(choices=[('PRICE_CHANGE', 'Product Price Changed'), ('LOW_STOCK', 'Low Stock Alert'), ('EXPIRY_APPROACHING', 'Product Expiry Approaching'), ('PRODUCT_EXPIRED', 'Product Has Expired'), ('PRODUCT_CREATED', 'New Product Created'), ('BARCODE_MISSING_PURCHASE', 'Product Purchased Without Barcode'), ('BARCODE_MISSING_TRANSFER', 'Product Transferred Without Barcode'), ('BARCODE_DAILY_CHECK', 'Daily: Products Without Barcodes'), ('STOCK_ADJUSTMENT', 'Stock Adjustment Made'), ('INVENTORY_COUNT', 'Inventory Count Needed'), ('NEGATIVE_STOCK', 'Negative Stock Sale'), ('PURCHASE_ENTERED', 'Purchase Order Entered'), ('PURCHASE_NO_ATTACHMENT', 'Purchase Without Invoice Attachment'), ('PO_APPROVED', 'Purchase Order Approved'), ('RECEIPT_VOUCHER', 'Receipt Voucher Arrived'), ('PROFORMA_RECEIVED', 'Proforma Received'), ('TRANSFER_CREATED', 'Transfer Order Created'), ('DELIVERY_COMPLETED', 'Delivery Completed'), ('NEW_SUPPLIER', 'New Supplier Onboarded'), ('CREDIT_SALE', 'Credit Sale — No Cash Collected'), ('HIGH_VALUE_SALE', 'High-Value Sale Threshold Crossed'), ('ORDER_COMPLETED', 'Order Completed'), ('POS_RETURN', 'POS Return / Refund Processed'), ('CASHIER_DISCOUNT', 'Cashier Applied Discount'), ('OVERDUE_INVOICE', 'Invoice Overdue'), ('LATE_PAYMENT', 'Late Payment Detected'), ('PAYMENT_DUE_SUPPLIER', 'Supplier Payment Due'), ('NEW_INVOICE', 'New Invoice Received'), ('BANK_STATEMENT', 'Bank Statement Received'), ('DAILY_SUMMARY', 'End-of-Day Financial Summary'), ('MONTH_END', 'Month-End Close'), ('PROMOTION_TRIGGERED', 'Targeted Client Promotion'), ('EXTERNAL_DOCUMENT_SEND', 'Send Document to Client/Supplier'), ('CLIENT_FOLLOWUP_DUE', 'Client Follow-Up Strategy Due'), ('SUPPLIER_FOLLOWUP_DUE', 'Supplier Follow-Up Due'), ('NEW_CLIENT', 'New Client Registered'), ('CLIENT_INACTIVE', 'Client Inactive > X Days'), ('CLIENT_COMPLAINT', 'Client Complaint Filed'), ('ADDRESS_BOOK_VERIFY', 'Address Book Verification'), ('EMPLOYEE_ONBOARD', 'New Employee Onboarded'), ('LEAVE_REQUEST', 'Leave Request Submitted'), ('ATTENDANCE_ANOMALY', 'Attendance Anomaly Detected'), ('USER_REGISTRATION', 'New User Registration'), ('REPORT_NEEDS_REVIEW', 'Report Needs Review'), ('ORDER_STALE', 'Order Not Treated After X Days'), ('APPROVAL_PENDING', 'Approval Pending > X Days'), ('CUSTOM', 'Custom Event')], max_length=30),
        ),
    ]
