# Generated by Django 6.0.2 on 2026-03-05 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_transactionstatuslog_meta_transactiontype_and_more'),
        ('workspace', '0005_alter_autotaskrule_trigger_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Add 'tenant' field to all models first
        migrations.AddField(
            model_name='autotaskrule',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='checklistitemresponse',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='employeerequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='questionnaireanswer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='questionnairequestion',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='task',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='workspaceconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),

        # 2. Now constraints can use 'tenant'
        migrations.AlterUniqueTogether(
            name='employeeperformance',
            unique_together={('tenant', 'employee', 'period_label')},
        ),
        migrations.AlterUniqueTogether(
            name='taskcategory',
            unique_together={('tenant', 'name')},
        ),

        # 3. Remove old fields
        migrations.RemoveField(
            model_name='autotaskrule',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='checklistinstance',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='checklistitemresponse',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='checklisttemplate',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='checklisttemplateitem',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='employeeperformance',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='employeerequest',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='questionnaireanswer',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='questionnairequestion',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='questionnaireresponse',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='task',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='taskattachment',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='taskcategory',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='tasktemplate',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='workspaceconfig',
            name='organization',
        ),
    ]
