# Generated by Django 6.0.4 on 2026-04-20 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_remove_approvalrule_organization_and_more'),
        ('workspace', '0009_autotaskrule_sync_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistinstance',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistitemresponse',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeerequest',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaireanswer',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnairequestion',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspaceconfig',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='chain_delay_minutes',
            field=models.IntegerField(default=0, help_text='Wait X minutes after parent task completes before creating this task'),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='chain_parent',
            field=models.ForeignKey(blank=True, help_text='Parent rule in a chain — this rule runs after parent completes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chain_children', to='workspace.autotaskrule'),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, help_text='JSON filter conditions, e.g. {"category_id": 5, "min_value": 1000}'),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='is_system_default',
            field=models.BooleanField(default=False, help_text='True for platform-seeded rules (not user-created)'),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='last_fired_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last firing — used by recurring scheduler', null=True),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Default priority for generated tasks', max_length=10),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='recurrence_day_of_month',
            field=models.IntegerField(blank=True, help_text='1-28 (for MONTHLY rules). Use 28 for end-of-month.', null=True),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='recurrence_day_of_week',
            field=models.IntegerField(blank=True, help_text='0=Monday, 6=Sunday (for WEEKLY rules)', null=True),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='recurrence_interval',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], help_text='Recurrence schedule for RECURRING rules', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='recurrence_time',
            field=models.TimeField(blank=True, help_text='What time of day to fire (e.g. 08:00)', null=True),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='rule_type',
            field=models.CharField(choices=[('EVENT', 'Event-triggered (one-shot)'), ('RECURRING', 'Recurring (scheduled)')], default='EVENT', help_text='EVENT = one-shot on trigger, RECURRING = scheduled', max_length=15),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='stale_threshold_days',
            field=models.IntegerField(default=3, help_text='Days before an item is considered stale (for stale-order rules)'),
        ),
    ]
