# Generated by Django 5.2.11 on 2026-02-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration', '0008_migrationjob_current_step_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationmapping',
            name='entity_type',
            field=models.CharField(choices=[('UNIT', 'Unit'), ('CATEGORY', 'Category'), ('BRAND', 'Brand'), ('PRODUCT', 'Product'), ('CONTACT', 'Contact'), ('TRANSACTION', 'Transaction'), ('ORDER_LINE', 'Order Line'), ('ACCOUNT', 'Account'), ('INVENTORY', 'Inventory'), ('SITE', 'Site'), ('TAX_GROUP', 'Tax Group'), ('PAYMENT', 'Payment'), ('EXPENSE', 'Expense'), ('COMBO_LINK', 'Combo Component Link'), ('USER', 'User'), ('JOURNAL_ENTRY', 'Journal Entry')], max_length=20),
        ),
    ]
