# Generated by Django 5.2.11 on 2026-02-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration', '0009_alter_migrationmapping_entity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migrationjob',
            name='db_password',
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='db_password_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted direct DB password', null=True),
        ),
    ]
