# Generated by Django 6.0.2 on 2026-03-01 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration', '0010_remove_migrationjob_db_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationmapping',
            name='audit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='migrationmapping',
            name='audit_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='migrationmapping',
            name='audit_status',
            field=models.CharField(choices=[('PENDING', 'Pending Audit'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged for Review'), ('AUTO_VERIFIED', 'Auto-Verified')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='migrationmapping',
            name='audited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_mappings', to=settings.AUTH_USER_MODEL),
        ),
    ]
