# Generated by Django 5.2.11 on 2026-03-01 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration', '0013_remove_migrationjob_total_flagged_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='total_flagged',
            field=models.IntegerField(default=0, help_text='Total entities flagged for review'),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='total_verified',
            field=models.IntegerField(default=0, help_text='Total entities verified by auditing'),
        ),
        migrations.AddField(
            model_name='migrationmapping',
            name='audit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='migrationmapping',
            name='audit_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='migrationmapping',
            name='audit_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified / Approved'), ('FLAGGED', 'Flagged / Needs Fix')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='migrationmapping',
            name='audited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_mappings', to=settings.AUTH_USER_MODEL),
        ),
    ]
