# Generated by Django 6.0.3 on 2026-03-31 10:33

import django.db.models.deletion
import erp.mixins
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0024_listview_policy'),
        ('inventory', '0048_attribute_requires_barcode'),
        ('reference', '0002_country_isolation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name', max_length=200)),
                ('code', models.CharField(db_index=True, help_text='Regulation code (e.g., REG-CI-2026-042)', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('regulation_type', models.CharField(choices=[('FIXED', 'Fixed Price — cannot sell above or below'), ('MAX', 'Maximum Price — ceiling, cannot exceed'), ('MIN', 'Minimum Price — floor, cannot go below'), ('RANGE', 'Price Range — must stay within band')], help_text='How the price is controlled', max_length=5)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, help_text='Government-set fixed price (for FIXED type)', max_digits=15, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed selling price (for MAX or RANGE type)', max_digits=15, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum allowed selling price (for MIN or RANGE type)', max_digits=15, null=True)),
                ('tolerance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Allowed deviation before flagging violation (e.g., MAX 800 + tolerance 5 = allow up to 805)', max_digits=10)),
                ('scope', models.CharField(choices=[('OFFICIAL', 'Official scope only'), ('INTERNAL', 'Internal scope only'), ('BOTH', 'Both official and internal')], default='BOTH', help_text='Which pricing scope this regulation applies to', max_length=8)),
                ('severity', models.CharField(choices=[('BLOCKING', 'Blocking — cannot sell if violated'), ('WARNING', 'Warning — allow but log violation')], default='BLOCKING', help_text='BLOCKING = hard block at POS/save, WARNING = allow + log', max_length=8)),
                ('allow_override', models.BooleanField(default=False, help_text='Whether a manager can override this regulation at POS')),
                ('override_requires_approval', models.BooleanField(default=True, help_text='If override allowed, whether it requires compliance approval')),
                ('auto_correct', models.BooleanField(default=False, help_text='If True: FIXED → force price, MAX → clamp, MIN → clamp')),
                ('reference', models.CharField(blank=True, default='', help_text='Official decree/law reference (e.g., Decree #2026-042)', max_length=200)),
                ('authority', models.CharField(blank=True, default='', help_text='Issuing body (e.g., Ministry of Commerce)', max_length=200)),
                ('effective_date', models.DateField(help_text='When the regulation takes effect')),
                ('expiry_date', models.DateField(blank=True, help_text='When the regulation expires (null = indefinite)', null=True)),
                ('jurisdiction_region', models.CharField(blank=True, default='', help_text='Sub-country region (e.g., Abidjan, Zone CEMAC). Empty = whole country', max_length=100)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number — increments when regulation price changes')),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text='Only the current version is enforced')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft — not yet active'), ('ACTIVE', 'Active — currently enforced'), ('EXPIRED', 'Expired — past expiry date'), ('SUSPENDED', 'Suspended — temporarily not enforced')], db_index=True, default='DRAFT', help_text='Lifecycle status of this regulation', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(help_text='Currency for regulated prices (must match at comparison time)', on_delete=django.db.models.deletion.PROTECT, related_name='price_regulations', to='reference.currency')),
                ('jurisdiction_country', models.ForeignKey(blank=True, help_text='Country where this regulation applies (null = all countries)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_regulations', to='reference.country')),
                ('organization', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization')),
                ('previous_version', models.ForeignKey(blank=True, help_text='Link to the version this replaces', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='compliance.priceregulation')),
            ],
            options={
                'db_table': 'compliance_price_regulation',
                'ordering': ['-is_current', '-version', 'name'],
            },
            bases=(erp.mixins.AuditLogMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RegulationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIOLATION_DETECTED', 'Violation detected'), ('AUTO_FIX', 'Auto-corrected to regulated price'), ('MANUAL_FIX', 'Manually fixed by user'), ('MANUAL_OVERRIDE', 'Manager override (with PIN)'), ('REGULATION_APPLIED', 'Regulation first applied to product'), ('REGULATION_REMOVED', 'Regulation removed from product'), ('REGULATION_UPDATED', 'Regulation price changed (new version)'), ('COMPLIANCE_ACHIEVED', 'Product now compliant'), ('POS_BLOCKED', 'POS sale blocked due to violation'), ('POS_CLAMPED', 'POS sale price auto-clamped'), ('SAVE_BLOCKED', 'Product save blocked due to violation'), ('SAVE_WARNING', 'Product saved with warning'), ('EXEMPTION_GRANTED', 'Product exempted from regulation'), ('BULK_FIX', 'Bulk fix — price corrected by batch operation')], db_index=True, max_length=30)),
                ('product_sku', models.CharField(blank=True, default='', max_length=100)),
                ('product_name', models.CharField(blank=True, default='', max_length=300)),
                ('regulation_code', models.CharField(blank=True, default='', max_length=50)),
                ('regulation_version', models.PositiveIntegerField(default=1)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price before action', max_digits=15, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price after action', max_digits=15, null=True)),
                ('regulated_price', models.DecimalField(blank=True, decimal_places=2, help_text='What the regulation dictates the price should be', max_digits=15, null=True)),
                ('violation_amount', models.DecimalField(blank=True, decimal_places=2, help_text='How much over/under the regulation (+50 = 50 over max)', max_digits=15, null=True)),
                ('source', models.CharField(choices=[('pos', 'POS Terminal'), ('product_save', 'Product Editor'), ('bulk_import', 'Bulk Import'), ('group_sync', 'Group Price Sync'), ('compliance_check', 'Scheduled Compliance Check'), ('manual', 'Manual Action')], default='manual', help_text='Where the action originated', max_length=20)),
                ('scope', models.CharField(blank=True, default='', help_text='OFFICIAL, INTERNAL, or BOTH', max_length=10)),
                ('override_reason', models.TextField(blank=True, default='', help_text='Justification if manager overrode regulation')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional structured metadata for the audit entry')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reference.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_audit_logs', to='erp.organization')),
                ('product', models.ForeignKey(blank=True, help_text='FK may be null if product was deleted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.product')),
                ('regulation', models.ForeignKey(blank=True, help_text='FK may be null if regulation was deleted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='compliance.priceregulation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_regulation_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RegulationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_exact', models.DecimalField(blank=True, decimal_places=2, help_text='Exact size to match (e.g., 1.00 for 1L)', max_digits=10, null=True)),
                ('size_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum size for range match', max_digits=10, null=True)),
                ('size_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum size for range match', max_digits=10, null=True)),
                ('auto_create_group', models.BooleanField(default=False, help_text='Automatically create/link a ProductGroup for matched products')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are checked first when specificity ties')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brands', models.ManyToManyField(blank=True, help_text='Brands to match. Empty = any brand', related_name='+', to='inventory.brand')),
                ('category', models.ForeignKey(blank=True, help_text='Product category to match (e.g., "Huile")', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.category')),
                ('organization', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization')),
                ('parfum', models.ForeignKey(blank=True, help_text='Product parfum/variant to match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.parfum')),
                ('price_group', models.ForeignKey(blank=True, help_text='ProductGroup to auto-enroll matched products into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulation_rules', to='inventory.productgroup')),
                ('product_country', models.ForeignKey(blank=True, help_text='Product country of origin to match (not regulation jurisdiction)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reference.country')),
                ('regulation', models.ForeignKey(help_text='The regulation this rule enrolls products into', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='compliance.priceregulation')),
                ('unit', models.ForeignKey(blank=True, help_text='Product unit to match (e.g., Liter, Kg)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.unit')),
            ],
            options={
                'db_table': 'compliance_regulation_rule',
                'ordering': ['-priority', '-id'],
            },
            bases=(erp.mixins.AuditLogMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='priceregulation',
            index=models.Index(fields=['organization', 'status', 'is_current'], name='reg_active_current_idx'),
        ),
        migrations.AddIndex(
            model_name='priceregulation',
            index=models.Index(fields=['organization', 'jurisdiction_country'], name='reg_country_idx'),
        ),
        migrations.AddConstraint(
            model_name='priceregulation',
            constraint=models.UniqueConstraint(fields=('organization', 'code', 'version'), name='unique_regulation_code_version_tenant'),
        ),
        migrations.AddIndex(
            model_name='regulationauditlog',
            index=models.Index(fields=['organization', 'product', '-timestamp'], name='audit_product_time_idx'),
        ),
        migrations.AddIndex(
            model_name='regulationauditlog',
            index=models.Index(fields=['organization', 'action', '-timestamp'], name='audit_action_time_idx'),
        ),
        migrations.AddIndex(
            model_name='regulationauditlog',
            index=models.Index(fields=['organization', 'regulation', '-timestamp'], name='audit_regulation_time_idx'),
        ),
        migrations.AddIndex(
            model_name='regulationrule',
            index=models.Index(fields=['organization', 'is_active'], name='rule_active_idx'),
        ),
    ]
