# Generated by Django 6.0.3 on 2026-05-02 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='ISO 4217 alpha code (e.g., USD, EUR, XOF)', max_length=3, unique=True)),
                ('numeric_code', models.CharField(blank=True, default='', help_text='ISO 4217 numeric code (e.g., 840, 978, 952)', max_length=3)),
                ('name', models.CharField(help_text='Currency name (e.g., US Dollar, Euro)', max_length=255)),
                ('symbol', models.CharField(blank=True, default='', help_text='Currency symbol (e.g., $, €, £)', max_length=10)),
                ('minor_unit', models.PositiveSmallIntegerField(default=2, help_text='Number of decimal places (e.g., 2 for USD, 0 for JPY, 3 for BHD)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'ref_currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso2', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-2 code (e.g., US, FR, LB)', max_length=2, unique=True)),
                ('iso3', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-3 code (e.g., USA, FRA, LBN)', max_length=3, unique=True)),
                ('numeric_code', models.CharField(blank=True, default='', help_text='ISO 3166-1 numeric code (e.g., 840, 250, 422)', max_length=3)),
                ('name', models.CharField(help_text='Common English name', max_length=255)),
                ('official_name', models.CharField(blank=True, default='', help_text='Official state name (e.g., Republic of Lebanon)', max_length=255)),
                ('phone_code', models.CharField(blank=True, default='', help_text='International dialing code (e.g., +1, +33, +961)', max_length=20)),
                ('region', models.CharField(blank=True, default='', help_text='Geographic region (e.g., Americas, Europe, Asia)', max_length=100)),
                ('subregion', models.CharField(blank=True, default='', help_text='Geographic subregion (e.g., Northern America, Western Europe)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('default_currency', models.ForeignKey(blank=True, help_text='Primary/default currency for this country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_countries', to='reference.currency')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'ref_countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Machine code (e.g., stripe, wave_ci, orange_money_ci)', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Display name (e.g., "Wave (Côte d\'Ivoire)")', max_length=100)),
                ('provider_family', models.CharField(blank=True, default='', help_text='Groups provider variants (e.g., "wave" for wave_ci, wave_sn)', max_length=50)),
                ('logo_emoji', models.CharField(blank=True, default='💳', help_text='Emoji for quick visual identification', max_length=10)),
                ('color', models.CharField(blank=True, default='#6366f1', help_text='Brand color hex', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Short description of the gateway')),
                ('is_global', models.BooleanField(default=False, help_text='Available worldwide regardless of country selection')),
                ('config_schema', models.JSONField(blank=True, default=list, help_text='JSON array defining credential fields this provider requires')),
                ('website_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('countries', models.ManyToManyField(blank=True, help_text='Countries where this gateway operates. Empty = use is_global.', related_name='payment_gateways', to='reference.country')),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'db_table': 'ref_payment_gateways',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='City name (e.g., Beirut, Abidjan, Paris)', max_length=255)),
                ('state_province', models.CharField(blank=True, default='', help_text='State/Province/Region (e.g., Mount Lebanon, Île-de-France)', max_length=255)),
                ('is_capital', models.BooleanField(default=False, help_text='Whether this is the country capital')),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(help_text='The country this city belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='reference.country')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'ref_cities',
                'ordering': ['-is_capital', 'name'],
                'indexes': [models.Index(fields=['country', 'is_active'], name='ref_cities_country_9237d6_idx')],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CountryCurrencyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary currency for this country')),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_mappings', to='reference.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_mappings', to='reference.currency')),
            ],
            options={
                'db_table': 'ref_country_currency_map',
                'ordering': ['country__name', '-is_primary'],
                'unique_together': {('country', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='OrgCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default/base country for this organization')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_activations', to='reference.country')),
                ('organization', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization')),
            ],
            options={
                'db_table': 'ref_org_countries',
                'ordering': ['-is_default', 'display_order', 'country__name'],
                'indexes': [models.Index(fields=['organization', 'is_enabled'], name='ref_org_cou_tenant__e48134_idx')],
                'unique_together': {('organization', 'country')},
            },
        ),
        migrations.CreateModel(
            name='OrgCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Base/functional currency for this organization')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('exchange_rate_source', models.CharField(blank=True, choices=[('MANUAL', 'Manual Entry'), ('ECB', 'European Central Bank'), ('BCEAO', 'BCEAO (West Africa)'), ('IMPORT', 'Imported'), ('API', 'External API')], default='MANUAL', help_text='Default exchange rate source for this currency', max_length=50)),
                ('is_reporting_currency', models.BooleanField(default=False, help_text='Used for consolidated reporting')),
                ('is_transaction_currency', models.BooleanField(default=True, help_text='Allowed in transactional documents (invoices, POs, payments)')),
                ('enabled_in_country_ids', models.JSONField(blank=True, default=list, help_text='List of Country FK ids this currency is enabled in. Empty = all enabled countries.')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_activations', to='reference.currency')),
                ('organization', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization')),
            ],
            options={
                'db_table': 'ref_org_currencies',
                'ordering': ['-is_default', 'display_order', 'currency__code'],
                'indexes': [models.Index(fields=['organization', 'is_enabled'], name='ref_org_cur_tenant__bbb040_idx')],
                'unique_together': {('organization', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='OrgPaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('default_config', models.JSONField(blank=True, default=dict, help_text='Org-wide default credentials. Accounts can override per-instance.')),
                ('organization', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization')),
                ('gateway', models.ForeignKey(help_text='Reference to global gateway catalog entry', on_delete=django.db.models.deletion.CASCADE, related_name='org_activations', to='reference.paymentgateway')),
            ],
            options={
                'db_table': 'ref_org_payment_gateways',
                'ordering': ['display_order', 'gateway__name'],
                'indexes': [models.Index(fields=['organization', 'is_enabled'], name='ref_org_pay_tenant__a4dd6e_idx')],
                'unique_together': {('organization', 'gateway')},
            },
        ),
        migrations.CreateModel(
            name='SourcingCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', help_text='Optional notes (e.g., "Main food import hub")', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing_activations', to='reference.country')),
                ('organization', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization')),
            ],
            options={
                'db_table': 'ref_sourcing_countries',
                'ordering': ['display_order', 'country__name'],
                'indexes': [models.Index(fields=['organization', 'is_enabled'], name='ref_sourcin_tenant__b253cf_idx')],
                'unique_together': {('organization', 'country')},
            },
        ),
    ]
