# Generated by Django 6.0.4 on 2026-05-06 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryLanguageMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, help_text='ISO 639-1 language code, e.g. "en", "fr", "ar"', max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text='Default/primary language for this country')),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_mappings', to='reference.country')),
            ],
            options={
                'db_table': 'ref_country_language_map',
                'ordering': ['country__name', '-is_default', 'language_code'],
                'indexes': [models.Index(fields=['country', 'is_default'], name='ref_country_country_35285e_idx')],
                'unique_together': {('country', 'language_code')},
            },
        ),
    ]
