# Generated by Django 6.0.3 on 2026-03-31 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_rename_erp_auditlo_organization__3bae30_idx_erp_auditlo_tenant__3bae30_idx_and_more'),
        ('reference', '0002_country_isolation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sourcingcountry',
            name='unique_sourcing_country_per_org',
        ),
        migrations.RenameIndex(
            model_name='orgcountry',
            new_name='ref_org_cou_tenant__e48134_idx',
            old_name='ref_org_cou_tenant__6f4b2e_idx',
        ),
        migrations.RenameIndex(
            model_name='orgcurrency',
            new_name='ref_org_cur_tenant__bbb040_idx',
            old_name='ref_org_cur_tenant__a3c1de_idx',
        ),
        migrations.RenameIndex(
            model_name='sourcingcountry',
            new_name='ref_sourcin_tenant__b253cf_idx',
            old_name='ref_sourci_org_idx',
        ),
        migrations.AlterUniqueTogether(
            name='sourcingcountry',
            unique_together={('organization', 'country')},
        ),
        migrations.AlterField(
            model_name='orgcountry',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='orgcurrency',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='sourcingcountry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sourcingcountry',
            name='notes',
            field=models.CharField(blank=True, default='', help_text='Optional notes (e.g., "Main food import hub")', max_length=255),
        ),
        migrations.AlterField(
            model_name='sourcingcountry',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.RemoveField(
            model_name='sourcingcountry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sourcingcountry',
            name='updated_at',
        ),
    ]
