# Generated by Django 5.2.11 on 2026-03-08 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_v2', '0002_migrationjob_source_business_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_jobs_v2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
