# Generated by Django 6.0.4 on 2026-04-20 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_remove_approvalrule_organization_and_more'),
        ('migration_v2', '0005_migrationjob_created_at_updated_at_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationjob',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='migration_v2_jobs', to='erp.organization'),
            preserve_default=False,
        ),
    ]
