# Generated by Django 6.0.3 on 2026-05-02 01:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
            ],
            options={
                'verbose_name': 'eCommerce Order',
                'verbose_name_plural': 'eCommerce Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('client_portal.clientorder',),
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
            ],
            options={
                'verbose_name': 'Order Line',
                'verbose_name_plural': 'Order Lines',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('client_portal.clientorderline',),
        ),
        migrations.CreateModel(
            name='StorefrontConfig',
            fields=[
            ],
            options={
                'verbose_name': 'Storefront Configuration',
                'verbose_name_plural': 'Storefront Configurations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('client_portal.clientportalconfig',),
        ),
    ]
