"""
ISO 3166-1 Country Seed Data
==============================
Complete list of ISO 3166-1 countries with iso2, iso3, numeric_code,
name, official_name, phone_code, region, subregion, and default_currency_code.

Source: ISO 3166-1 standard + UN Statistics Division M49 regions
Notes:
  - phone_code includes the + prefix
  - default_currency_code maps to the ISO 4217 code in the currencies table
  - Some territories share phone codes with parent countries
"""

# (iso2, iso3, numeric, name, official_name, phone_code, region, subregion, default_currency_code)
COUNTRIES = [
    ('AF', 'AFG', '004', 'Afghanistan', 'Islamic Republic of Afghanistan', '+93', 'Asia', 'Southern Asia', 'AFN'),
    ('AL', 'ALB', '008', 'Albania', 'Republic of Albania', '+355', 'Europe', 'Southern Europe', 'ALL'),
    ('DZ', 'DZA', '012', 'Algeria', "People's Democratic Republic of Algeria", '+213', 'Africa', 'Northern Africa', 'DZD'),
    ('AS', 'ASM', '016', 'American Samoa', 'American Samoa', '+1-684', 'Oceania', 'Polynesia', 'USD'),
    ('AD', 'AND', '020', 'Andorra', 'Principality of Andorra', '+376', 'Europe', 'Southern Europe', 'EUR'),
    ('AO', 'AGO', '024', 'Angola', 'Republic of Angola', '+244', 'Africa', 'Middle Africa', 'AOA'),
    ('AG', 'ATG', '028', 'Antigua and Barbuda', 'Antigua and Barbuda', '+1-268', 'Americas', 'Caribbean', 'XCD'),
    ('AR', 'ARG', '032', 'Argentina', 'Argentine Republic', '+54', 'Americas', 'South America', 'ARS'),
    ('AM', 'ARM', '051', 'Armenia', 'Republic of Armenia', '+374', 'Asia', 'Western Asia', 'AMD'),
    ('AU', 'AUS', '036', 'Australia', 'Commonwealth of Australia', '+61', 'Oceania', 'Australia and New Zealand', 'AUD'),
    ('AT', 'AUT', '040', 'Austria', 'Republic of Austria', '+43', 'Europe', 'Western Europe', 'EUR'),
    ('AZ', 'AZE', '031', 'Azerbaijan', 'Republic of Azerbaijan', '+994', 'Asia', 'Western Asia', 'AZN'),
    ('BS', 'BHS', '044', 'Bahamas', 'Commonwealth of The Bahamas', '+1-242', 'Americas', 'Caribbean', 'BSD'),
    ('BH', 'BHR', '048', 'Bahrain', 'Kingdom of Bahrain', '+973', 'Asia', 'Western Asia', 'BHD'),
    ('BD', 'BGD', '050', 'Bangladesh', "People's Republic of Bangladesh", '+880', 'Asia', 'Southern Asia', 'BDT'),
    ('BB', 'BRB', '052', 'Barbados', 'Barbados', '+1-246', 'Americas', 'Caribbean', 'BBD'),
    ('BY', 'BLR', '112', 'Belarus', 'Republic of Belarus', '+375', 'Europe', 'Eastern Europe', 'BYN'),
    ('BE', 'BEL', '056', 'Belgium', 'Kingdom of Belgium', '+32', 'Europe', 'Western Europe', 'EUR'),
    ('BZ', 'BLZ', '084', 'Belize', 'Belize', '+501', 'Americas', 'Central America', 'BZD'),
    ('BJ', 'BEN', '204', 'Benin', 'Republic of Benin', '+229', 'Africa', 'Western Africa', 'XOF'),
    ('BT', 'BTN', '064', 'Bhutan', 'Kingdom of Bhutan', '+975', 'Asia', 'Southern Asia', 'BTN'),
    ('BO', 'BOL', '068', 'Bolivia', 'Plurinational State of Bolivia', '+591', 'Americas', 'South America', 'BOB'),
    ('BA', 'BIH', '070', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', '+387', 'Europe', 'Southern Europe', 'BAM'),
    ('BW', 'BWA', '072', 'Botswana', 'Republic of Botswana', '+267', 'Africa', 'Southern Africa', 'BWP'),
    ('BR', 'BRA', '076', 'Brazil', 'Federative Republic of Brazil', '+55', 'Americas', 'South America', 'BRL'),
    ('BN', 'BRN', '096', 'Brunei', 'Brunei Darussalam', '+673', 'Asia', 'South-Eastern Asia', 'BND'),
    ('BG', 'BGR', '100', 'Bulgaria', 'Republic of Bulgaria', '+359', 'Europe', 'Eastern Europe', 'BGN'),
    ('BF', 'BFA', '854', 'Burkina Faso', 'Burkina Faso', '+226', 'Africa', 'Western Africa', 'XOF'),
    ('BI', 'BDI', '108', 'Burundi', 'Republic of Burundi', '+257', 'Africa', 'Eastern Africa', 'BIF'),
    ('CV', 'CPV', '132', 'Cabo Verde', 'Republic of Cabo Verde', '+238', 'Africa', 'Western Africa', 'CVE'),
    ('KH', 'KHM', '116', 'Cambodia', 'Kingdom of Cambodia', '+855', 'Asia', 'South-Eastern Asia', 'KHR'),
    ('CM', 'CMR', '120', 'Cameroon', 'Republic of Cameroon', '+237', 'Africa', 'Middle Africa', 'XAF'),
    ('CA', 'CAN', '124', 'Canada', 'Canada', '+1', 'Americas', 'Northern America', 'CAD'),
    ('CF', 'CAF', '140', 'Central African Republic', 'Central African Republic', '+236', 'Africa', 'Middle Africa', 'XAF'),
    ('TD', 'TCD', '148', 'Chad', 'Republic of Chad', '+235', 'Africa', 'Middle Africa', 'XAF'),
    ('CL', 'CHL', '152', 'Chile', 'Republic of Chile', '+56', 'Americas', 'South America', 'CLP'),
    ('CN', 'CHN', '156', 'China', "People's Republic of China", '+86', 'Asia', 'Eastern Asia', 'CNY'),
    ('CO', 'COL', '170', 'Colombia', 'Republic of Colombia', '+57', 'Americas', 'South America', 'COP'),
    ('KM', 'COM', '174', 'Comoros', 'Union of the Comoros', '+269', 'Africa', 'Eastern Africa', 'KMF'),
    ('CG', 'COG', '178', 'Congo', 'Republic of the Congo', '+242', 'Africa', 'Middle Africa', 'XAF'),
    ('CD', 'COD', '180', 'DR Congo', 'Democratic Republic of the Congo', '+243', 'Africa', 'Middle Africa', 'CDF'),
    ('CR', 'CRI', '188', 'Costa Rica', 'Republic of Costa Rica', '+506', 'Americas', 'Central America', 'CRC'),
    ('CI', 'CIV', '384', "Côte d'Ivoire", "Republic of Côte d'Ivoire", '+225', 'Africa', 'Western Africa', 'XOF'),
    ('HR', 'HRV', '191', 'Croatia', 'Republic of Croatia', '+385', 'Europe', 'Southern Europe', 'EUR'),
    ('CU', 'CUB', '192', 'Cuba', 'Republic of Cuba', '+53', 'Americas', 'Caribbean', 'CUP'),
    ('CY', 'CYP', '196', 'Cyprus', 'Republic of Cyprus', '+357', 'Europe', 'Southern Europe', 'EUR'),
    ('CZ', 'CZE', '203', 'Czechia', 'Czech Republic', '+420', 'Europe', 'Eastern Europe', 'CZK'),
    ('DK', 'DNK', '208', 'Denmark', 'Kingdom of Denmark', '+45', 'Europe', 'Northern Europe', 'DKK'),
    ('DJ', 'DJI', '262', 'Djibouti', 'Republic of Djibouti', '+253', 'Africa', 'Eastern Africa', 'DJF'),
    ('DM', 'DMA', '212', 'Dominica', 'Commonwealth of Dominica', '+1-767', 'Americas', 'Caribbean', 'XCD'),
    ('DO', 'DOM', '214', 'Dominican Republic', 'Dominican Republic', '+1-809', 'Americas', 'Caribbean', 'DOP'),
    ('EC', 'ECU', '218', 'Ecuador', 'Republic of Ecuador', '+593', 'Americas', 'South America', 'USD'),
    ('EG', 'EGY', '818', 'Egypt', 'Arab Republic of Egypt', '+20', 'Africa', 'Northern Africa', 'EGP'),
    ('SV', 'SLV', '222', 'El Salvador', 'Republic of El Salvador', '+503', 'Americas', 'Central America', 'USD'),
    ('GQ', 'GNQ', '226', 'Equatorial Guinea', 'Republic of Equatorial Guinea', '+240', 'Africa', 'Middle Africa', 'XAF'),
    ('ER', 'ERI', '232', 'Eritrea', 'State of Eritrea', '+291', 'Africa', 'Eastern Africa', 'ERN'),
    ('EE', 'EST', '233', 'Estonia', 'Republic of Estonia', '+372', 'Europe', 'Northern Europe', 'EUR'),
    ('SZ', 'SWZ', '748', 'Eswatini', 'Kingdom of Eswatini', '+268', 'Africa', 'Southern Africa', 'SZL'),
    ('ET', 'ETH', '231', 'Ethiopia', 'Federal Democratic Republic of Ethiopia', '+251', 'Africa', 'Eastern Africa', 'ETB'),
    ('FJ', 'FJI', '242', 'Fiji', 'Republic of Fiji', '+679', 'Oceania', 'Melanesia', 'FJD'),
    ('FI', 'FIN', '246', 'Finland', 'Republic of Finland', '+358', 'Europe', 'Northern Europe', 'EUR'),
    ('FR', 'FRA', '250', 'France', 'French Republic', '+33', 'Europe', 'Western Europe', 'EUR'),
    ('GA', 'GAB', '266', 'Gabon', 'Gabonese Republic', '+241', 'Africa', 'Middle Africa', 'XAF'),
    ('GM', 'GMB', '270', 'Gambia', 'Republic of The Gambia', '+220', 'Africa', 'Western Africa', 'GMD'),
    ('GE', 'GEO', '268', 'Georgia', 'Georgia', '+995', 'Asia', 'Western Asia', 'GEL'),
    ('DE', 'DEU', '276', 'Germany', 'Federal Republic of Germany', '+49', 'Europe', 'Western Europe', 'EUR'),
    ('GH', 'GHA', '288', 'Ghana', 'Republic of Ghana', '+233', 'Africa', 'Western Africa', 'GHS'),
    ('GR', 'GRC', '300', 'Greece', 'Hellenic Republic', '+30', 'Europe', 'Southern Europe', 'EUR'),
    ('GD', 'GRD', '308', 'Grenada', 'Grenada', '+1-473', 'Americas', 'Caribbean', 'XCD'),
    ('GT', 'GTM', '320', 'Guatemala', 'Republic of Guatemala', '+502', 'Americas', 'Central America', 'GTQ'),
    ('GN', 'GIN', '324', 'Guinea', 'Republic of Guinea', '+224', 'Africa', 'Western Africa', 'GNF'),
    ('GW', 'GNB', '624', 'Guinea-Bissau', 'Republic of Guinea-Bissau', '+245', 'Africa', 'Western Africa', 'XOF'),
    ('GY', 'GUY', '328', 'Guyana', 'Co-operative Republic of Guyana', '+592', 'Americas', 'South America', 'GYD'),
    ('HT', 'HTI', '332', 'Haiti', 'Republic of Haiti', '+509', 'Americas', 'Caribbean', 'HTG'),
    ('HN', 'HND', '340', 'Honduras', 'Republic of Honduras', '+504', 'Americas', 'Central America', 'HNL'),
    ('HU', 'HUN', '348', 'Hungary', 'Hungary', '+36', 'Europe', 'Eastern Europe', 'HUF'),
    ('IS', 'ISL', '352', 'Iceland', 'Iceland', '+354', 'Europe', 'Northern Europe', 'ISK'),
    ('IN', 'IND', '356', 'India', 'Republic of India', '+91', 'Asia', 'Southern Asia', 'INR'),
    ('ID', 'IDN', '360', 'Indonesia', 'Republic of Indonesia', '+62', 'Asia', 'South-Eastern Asia', 'IDR'),
    ('IR', 'IRN', '364', 'Iran', 'Islamic Republic of Iran', '+98', 'Asia', 'Southern Asia', 'IRR'),
    ('IQ', 'IRQ', '368', 'Iraq', 'Republic of Iraq', '+964', 'Asia', 'Western Asia', 'IQD'),
    ('IE', 'IRL', '372', 'Ireland', 'Ireland', '+353', 'Europe', 'Northern Europe', 'EUR'),
    ('IL', 'ISR', '376', 'Israel', 'State of Israel', '+972', 'Asia', 'Western Asia', 'ILS'),
    ('IT', 'ITA', '380', 'Italy', 'Italian Republic', '+39', 'Europe', 'Southern Europe', 'EUR'),
    ('JM', 'JAM', '388', 'Jamaica', 'Jamaica', '+1-876', 'Americas', 'Caribbean', 'JMD'),
    ('JP', 'JPN', '392', 'Japan', 'Japan', '+81', 'Asia', 'Eastern Asia', 'JPY'),
    ('JO', 'JOR', '400', 'Jordan', 'Hashemite Kingdom of Jordan', '+962', 'Asia', 'Western Asia', 'JOD'),
    ('KZ', 'KAZ', '398', 'Kazakhstan', 'Republic of Kazakhstan', '+7', 'Asia', 'Central Asia', 'KZT'),
    ('KE', 'KEN', '404', 'Kenya', 'Republic of Kenya', '+254', 'Africa', 'Eastern Africa', 'KES'),
    ('KI', 'KIR', '296', 'Kiribati', 'Republic of Kiribati', '+686', 'Oceania', 'Micronesia', 'AUD'),
    ('KP', 'PRK', '408', 'North Korea', "Democratic People's Republic of Korea", '+850', 'Asia', 'Eastern Asia', 'KPW'),
    ('KR', 'KOR', '410', 'South Korea', 'Republic of Korea', '+82', 'Asia', 'Eastern Asia', 'KRW'),
    ('KW', 'KWT', '414', 'Kuwait', 'State of Kuwait', '+965', 'Asia', 'Western Asia', 'KWD'),
    ('KG', 'KGZ', '417', 'Kyrgyzstan', 'Kyrgyz Republic', '+996', 'Asia', 'Central Asia', 'KGS'),
    ('LA', 'LAO', '418', 'Laos', "Lao People's Democratic Republic", '+856', 'Asia', 'South-Eastern Asia', 'LAK'),
    ('LV', 'LVA', '428', 'Latvia', 'Republic of Latvia', '+371', 'Europe', 'Northern Europe', 'EUR'),
    ('LB', 'LBN', '422', 'Lebanon', 'Lebanese Republic', '+961', 'Asia', 'Western Asia', 'LBP'),
    ('LS', 'LSO', '426', 'Lesotho', 'Kingdom of Lesotho', '+266', 'Africa', 'Southern Africa', 'LSL'),
    ('LR', 'LBR', '430', 'Liberia', 'Republic of Liberia', '+231', 'Africa', 'Western Africa', 'LRD'),
    ('LY', 'LBY', '434', 'Libya', 'State of Libya', '+218', 'Africa', 'Northern Africa', 'LYD'),
    ('LI', 'LIE', '438', 'Liechtenstein', 'Principality of Liechtenstein', '+423', 'Europe', 'Western Europe', 'CHF'),
    ('LT', 'LTU', '440', 'Lithuania', 'Republic of Lithuania', '+370', 'Europe', 'Northern Europe', 'EUR'),
    ('LU', 'LUX', '442', 'Luxembourg', 'Grand Duchy of Luxembourg', '+352', 'Europe', 'Western Europe', 'EUR'),
    ('MG', 'MDG', '450', 'Madagascar', 'Republic of Madagascar', '+261', 'Africa', 'Eastern Africa', 'MGA'),
    ('MW', 'MWI', '454', 'Malawi', 'Republic of Malawi', '+265', 'Africa', 'Eastern Africa', 'MWK'),
    ('MY', 'MYS', '458', 'Malaysia', 'Malaysia', '+60', 'Asia', 'South-Eastern Asia', 'MYR'),
    ('MV', 'MDV', '462', 'Maldives', 'Republic of Maldives', '+960', 'Asia', 'Southern Asia', 'MVR'),
    ('ML', 'MLI', '466', 'Mali', 'Republic of Mali', '+223', 'Africa', 'Western Africa', 'XOF'),
    ('MT', 'MLT', '470', 'Malta', 'Republic of Malta', '+356', 'Europe', 'Southern Europe', 'EUR'),
    ('MH', 'MHL', '584', 'Marshall Islands', 'Republic of the Marshall Islands', '+692', 'Oceania', 'Micronesia', 'USD'),
    ('MR', 'MRT', '478', 'Mauritania', 'Islamic Republic of Mauritania', '+222', 'Africa', 'Western Africa', 'MRU'),
    ('MU', 'MUS', '480', 'Mauritius', 'Republic of Mauritius', '+230', 'Africa', 'Eastern Africa', 'MUR'),
    ('MX', 'MEX', '484', 'Mexico', 'United Mexican States', '+52', 'Americas', 'Central America', 'MXN'),
    ('FM', 'FSM', '583', 'Micronesia', 'Federated States of Micronesia', '+691', 'Oceania', 'Micronesia', 'USD'),
    ('MD', 'MDA', '498', 'Moldova', 'Republic of Moldova', '+373', 'Europe', 'Eastern Europe', 'MDL'),
    ('MC', 'MCO', '492', 'Monaco', 'Principality of Monaco', '+377', 'Europe', 'Western Europe', 'EUR'),
    ('MN', 'MNG', '496', 'Mongolia', 'Mongolia', '+976', 'Asia', 'Eastern Asia', 'MNT'),
    ('ME', 'MNE', '499', 'Montenegro', 'Montenegro', '+382', 'Europe', 'Southern Europe', 'EUR'),
    ('MA', 'MAR', '504', 'Morocco', 'Kingdom of Morocco', '+212', 'Africa', 'Northern Africa', 'MAD'),
    ('MZ', 'MOZ', '508', 'Mozambique', 'Republic of Mozambique', '+258', 'Africa', 'Eastern Africa', 'MZN'),
    ('MM', 'MMR', '104', 'Myanmar', 'Republic of the Union of Myanmar', '+95', 'Asia', 'South-Eastern Asia', 'MMK'),
    ('NA', 'NAM', '516', 'Namibia', 'Republic of Namibia', '+264', 'Africa', 'Southern Africa', 'NAD'),
    ('NR', 'NRU', '520', 'Nauru', 'Republic of Nauru', '+674', 'Oceania', 'Micronesia', 'AUD'),
    ('NP', 'NPL', '524', 'Nepal', 'Federal Democratic Republic of Nepal', '+977', 'Asia', 'Southern Asia', 'NPR'),
    ('NL', 'NLD', '528', 'Netherlands', 'Kingdom of the Netherlands', '+31', 'Europe', 'Western Europe', 'EUR'),
    ('NZ', 'NZL', '554', 'New Zealand', 'New Zealand', '+64', 'Oceania', 'Australia and New Zealand', 'NZD'),
    ('NI', 'NIC', '558', 'Nicaragua', 'Republic of Nicaragua', '+505', 'Americas', 'Central America', 'NIO'),
    ('NE', 'NER', '562', 'Niger', 'Republic of the Niger', '+227', 'Africa', 'Western Africa', 'XOF'),
    ('NG', 'NGA', '566', 'Nigeria', 'Federal Republic of Nigeria', '+234', 'Africa', 'Western Africa', 'NGN'),
    ('MK', 'MKD', '807', 'North Macedonia', 'Republic of North Macedonia', '+389', 'Europe', 'Southern Europe', 'MKD'),
    ('NO', 'NOR', '578', 'Norway', 'Kingdom of Norway', '+47', 'Europe', 'Northern Europe', 'NOK'),
    ('OM', 'OMN', '512', 'Oman', 'Sultanate of Oman', '+968', 'Asia', 'Western Asia', 'OMR'),
    ('PK', 'PAK', '586', 'Pakistan', 'Islamic Republic of Pakistan', '+92', 'Asia', 'Southern Asia', 'PKR'),
    ('PW', 'PLW', '585', 'Palau', 'Republic of Palau', '+680', 'Oceania', 'Micronesia', 'USD'),
    ('PA', 'PAN', '591', 'Panama', 'Republic of Panama', '+507', 'Americas', 'Central America', 'PAB'),
    ('PG', 'PNG', '598', 'Papua New Guinea', 'Independent State of Papua New Guinea', '+675', 'Oceania', 'Melanesia', 'PGK'),
    ('PY', 'PRY', '600', 'Paraguay', 'Republic of Paraguay', '+595', 'Americas', 'South America', 'PYG'),
    ('PE', 'PER', '604', 'Peru', 'Republic of Peru', '+51', 'Americas', 'South America', 'PEN'),
    ('PH', 'PHL', '608', 'Philippines', 'Republic of the Philippines', '+63', 'Asia', 'South-Eastern Asia', 'PHP'),
    ('PL', 'POL', '616', 'Poland', 'Republic of Poland', '+48', 'Europe', 'Eastern Europe', 'PLN'),
    ('PT', 'PRT', '620', 'Portugal', 'Portuguese Republic', '+351', 'Europe', 'Southern Europe', 'EUR'),
    ('QA', 'QAT', '634', 'Qatar', 'State of Qatar', '+974', 'Asia', 'Western Asia', 'QAR'),
    ('RO', 'ROU', '642', 'Romania', 'Romania', '+40', 'Europe', 'Eastern Europe', 'RON'),
    ('RU', 'RUS', '643', 'Russia', 'Russian Federation', '+7', 'Europe', 'Eastern Europe', 'RUB'),
    ('RW', 'RWA', '646', 'Rwanda', 'Republic of Rwanda', '+250', 'Africa', 'Eastern Africa', 'RWF'),
    ('KN', 'KNA', '659', 'Saint Kitts and Nevis', 'Federation of Saint Christopher and Nevis', '+1-869', 'Americas', 'Caribbean', 'XCD'),
    ('LC', 'LCA', '662', 'Saint Lucia', 'Saint Lucia', '+1-758', 'Americas', 'Caribbean', 'XCD'),
    ('VC', 'VCT', '670', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', '+1-784', 'Americas', 'Caribbean', 'XCD'),
    ('WS', 'WSM', '882', 'Samoa', 'Independent State of Samoa', '+685', 'Oceania', 'Polynesia', 'WST'),
    ('SM', 'SMR', '674', 'San Marino', 'Republic of San Marino', '+378', 'Europe', 'Southern Europe', 'EUR'),
    ('ST', 'STP', '678', 'São Tomé and Príncipe', 'Democratic Republic of São Tomé and Príncipe', '+239', 'Africa', 'Middle Africa', 'STN'),
    ('SA', 'SAU', '682', 'Saudi Arabia', 'Kingdom of Saudi Arabia', '+966', 'Asia', 'Western Asia', 'SAR'),
    ('SN', 'SEN', '686', 'Senegal', 'Republic of Senegal', '+221', 'Africa', 'Western Africa', 'XOF'),
    ('RS', 'SRB', '688', 'Serbia', 'Republic of Serbia', '+381', 'Europe', 'Southern Europe', 'RSD'),
    ('SC', 'SYC', '690', 'Seychelles', 'Republic of Seychelles', '+248', 'Africa', 'Eastern Africa', 'SCR'),
    ('SL', 'SLE', '694', 'Sierra Leone', 'Republic of Sierra Leone', '+232', 'Africa', 'Western Africa', 'SLE'),
    ('SG', 'SGP', '702', 'Singapore', 'Republic of Singapore', '+65', 'Asia', 'South-Eastern Asia', 'SGD'),
    ('SK', 'SVK', '703', 'Slovakia', 'Slovak Republic', '+421', 'Europe', 'Eastern Europe', 'EUR'),
    ('SI', 'SVN', '705', 'Slovenia', 'Republic of Slovenia', '+386', 'Europe', 'Southern Europe', 'EUR'),
    ('SB', 'SLB', '090', 'Solomon Islands', 'Solomon Islands', '+677', 'Oceania', 'Melanesia', 'SBD'),
    ('SO', 'SOM', '706', 'Somalia', 'Federal Republic of Somalia', '+252', 'Africa', 'Eastern Africa', 'SOS'),
    ('ZA', 'ZAF', '710', 'South Africa', 'Republic of South Africa', '+27', 'Africa', 'Southern Africa', 'ZAR'),
    ('SS', 'SSD', '728', 'South Sudan', 'Republic of South Sudan', '+211', 'Africa', 'Eastern Africa', 'SSP'),
    ('ES', 'ESP', '724', 'Spain', 'Kingdom of Spain', '+34', 'Europe', 'Southern Europe', 'EUR'),
    ('LK', 'LKA', '144', 'Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', '+94', 'Asia', 'Southern Asia', 'LKR'),
    ('SD', 'SDN', '729', 'Sudan', 'Republic of the Sudan', '+249', 'Africa', 'Northern Africa', 'SDG'),
    ('SR', 'SUR', '740', 'Suriname', 'Republic of Suriname', '+597', 'Americas', 'South America', 'SRD'),
    ('SE', 'SWE', '752', 'Sweden', 'Kingdom of Sweden', '+46', 'Europe', 'Northern Europe', 'SEK'),
    ('CH', 'CHE', '756', 'Switzerland', 'Swiss Confederation', '+41', 'Europe', 'Western Europe', 'CHF'),
    ('SY', 'SYR', '760', 'Syria', 'Syrian Arab Republic', '+963', 'Asia', 'Western Asia', 'SYP'),
    ('TW', 'TWN', '158', 'Taiwan', 'Republic of China (Taiwan)', '+886', 'Asia', 'Eastern Asia', 'TWD'),
    ('TJ', 'TJK', '762', 'Tajikistan', 'Republic of Tajikistan', '+992', 'Asia', 'Central Asia', 'TJS'),
    ('TZ', 'TZA', '834', 'Tanzania', 'United Republic of Tanzania', '+255', 'Africa', 'Eastern Africa', 'TZS'),
    ('TH', 'THA', '764', 'Thailand', 'Kingdom of Thailand', '+66', 'Asia', 'South-Eastern Asia', 'THB'),
    ('TL', 'TLS', '626', 'Timor-Leste', 'Democratic Republic of Timor-Leste', '+670', 'Asia', 'South-Eastern Asia', 'USD'),
    ('TG', 'TGO', '768', 'Togo', 'Togolese Republic', '+228', 'Africa', 'Western Africa', 'XOF'),
    ('TO', 'TON', '776', 'Tonga', 'Kingdom of Tonga', '+676', 'Oceania', 'Polynesia', 'TOP'),
    ('TT', 'TTO', '780', 'Trinidad and Tobago', 'Republic of Trinidad and Tobago', '+1-868', 'Americas', 'Caribbean', 'TTD'),
    ('TN', 'TUN', '788', 'Tunisia', 'Republic of Tunisia', '+216', 'Africa', 'Northern Africa', 'TND'),
    ('TR', 'TUR', '792', 'Turkey', 'Republic of Turkey', '+90', 'Asia', 'Western Asia', 'TRY'),
    ('TM', 'TKM', '795', 'Turkmenistan', 'Turkmenistan', '+993', 'Asia', 'Central Asia', 'TMT'),
    ('TV', 'TUV', '798', 'Tuvalu', 'Tuvalu', '+688', 'Oceania', 'Polynesia', 'AUD'),
    ('UG', 'UGA', '800', 'Uganda', 'Republic of Uganda', '+256', 'Africa', 'Eastern Africa', 'UGX'),
    ('UA', 'UKR', '804', 'Ukraine', 'Ukraine', '+380', 'Europe', 'Eastern Europe', 'UAH'),
    ('AE', 'ARE', '784', 'United Arab Emirates', 'United Arab Emirates', '+971', 'Asia', 'Western Asia', 'AED'),
    ('GB', 'GBR', '826', 'United Kingdom', 'United Kingdom of Great Britain and Northern Ireland', '+44', 'Europe', 'Northern Europe', 'GBP'),
    ('US', 'USA', '840', 'United States', 'United States of America', '+1', 'Americas', 'Northern America', 'USD'),
    ('UY', 'URY', '858', 'Uruguay', 'Oriental Republic of Uruguay', '+598', 'Americas', 'South America', 'UYU'),
    ('UZ', 'UZB', '860', 'Uzbekistan', 'Republic of Uzbekistan', '+998', 'Asia', 'Central Asia', 'UZS'),
    ('VU', 'VUT', '548', 'Vanuatu', 'Republic of Vanuatu', '+678', 'Oceania', 'Melanesia', 'VUV'),
    ('VA', 'VAT', '336', 'Vatican City', 'Vatican City State', '+379', 'Europe', 'Southern Europe', 'EUR'),
    ('VE', 'VEN', '862', 'Venezuela', 'Bolivarian Republic of Venezuela', '+58', 'Americas', 'South America', 'VES'),
    ('VN', 'VNM', '704', 'Vietnam', 'Socialist Republic of Viet Nam', '+84', 'Asia', 'South-Eastern Asia', 'VND'),
    ('YE', 'YEM', '886', 'Yemen', 'Republic of Yemen', '+967', 'Asia', 'Western Asia', 'YER'),
    ('ZM', 'ZMB', '894', 'Zambia', 'Republic of Zambia', '+260', 'Africa', 'Eastern Africa', 'ZMW'),
    ('ZW', 'ZWE', '716', 'Zimbabwe', 'Republic of Zimbabwe', '+263', 'Africa', 'Eastern Africa', 'ZWL'),
    # --- Territories & Dependencies ---
    ('HK', 'HKG', '344', 'Hong Kong', 'Hong Kong Special Administrative Region', '+852', 'Asia', 'Eastern Asia', 'HKD'),
    ('MO', 'MAC', '446', 'Macao', 'Macao Special Administrative Region', '+853', 'Asia', 'Eastern Asia', 'MOP'),
    ('PS', 'PSE', '275', 'Palestine', 'State of Palestine', '+970', 'Asia', 'Western Asia', 'ILS'),
    ('PR', 'PRI', '630', 'Puerto Rico', 'Commonwealth of Puerto Rico', '+1-787', 'Americas', 'Caribbean', 'USD'),
    ('XK', 'XKX', '', 'Kosovo', 'Republic of Kosovo', '+383', 'Europe', 'Southern Europe', 'EUR'),
]
