# Generated by Django 6.0.2 on 2026-02-09 15:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_active_account', models.BooleanField(default=True)),
                ('registration_status', models.CharField(default='APPROVED', max_length=50)),
                ('correction_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BufferedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_module', models.CharField(blank=True, max_length=100, null=True)),
                ('target_endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('source_module', models.CharField(blank=True, max_length=100, null=True)),
                ('method', models.CharField(blank=True, default='POST', max_length=10, null=True)),
                ('payload', models.JSONField(blank=True, default=dict, null=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('replayed', 'Replayed'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('replayed_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Buffered Request',
                'verbose_name_plural': 'Buffered Requests',
                'db_table': 'bufferedrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'businesstype',
            },
        ),
        migrations.CreateModel(
            name='ConnectorCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=500, unique=True)),
                ('target_module', models.CharField(blank=True, max_length=100, null=True)),
                ('target_endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('cached_at', models.DateTimeField(auto_now=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Connector Cache',
                'verbose_name_plural': 'Connector Cache Entries',
                'db_table': 'connectorcache',
            },
        ),
        migrations.CreateModel(
            name='ConnectorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_module', models.CharField(blank=True, max_length=100, null=True)),
                ('target_module', models.CharField(blank=True, max_length=100, null=True)),
                ('target_endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('operation', models.CharField(blank=True, max_length=10, null=True)),
                ('module_state', models.CharField(blank=True, max_length=20, null=True)),
                ('decision', models.CharField(blank=True, choices=[('forward', 'Forwarded'), ('fallback', 'Fallback Applied'), ('buffer', 'Buffered'), ('reject', 'Rejected'), ('replay', 'Replayed')], max_length=20, null=True)),
                ('success', models.BooleanField(default=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Connector Log',
                'verbose_name_plural': 'Connector Logs',
                'db_table': 'connectorlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_module', models.CharField(blank=True, help_text="Module code (e.g., 'inventory') or '*' for global", max_length=100, null=True)),
                ('target_endpoint', models.CharField(blank=True, default='*', help_text="Specific endpoint or '*' for all endpoints", max_length=255, null=True)),
                ('source_module', models.CharField(default='*', help_text="Requesting module (e.g., 'pos') or '*' for any module", max_length=100)),
                ('when_missing_read', models.CharField(choices=[('wait', 'Wait (blocking)'), ('empty', 'Empty Safe Response'), ('cached', 'Cached Last Value'), ('mock', 'Mock Response (dev)'), ('error', 'Return Error Object')], default='empty', help_text='Action when module is NOT INSTALLED', max_length=20)),
                ('when_missing_write', models.CharField(choices=[('buffer', 'Buffer for Replay'), ('redirect', 'Redirect to Core'), ('drop', 'Drop Silently'), ('queue_event', 'Queue as Event'), ('error', 'Return Error Object')], default='buffer', help_text='Action for writes when module is NOT INSTALLED', max_length=20)),
                ('when_disabled_read', models.CharField(choices=[('wait', 'Wait (blocking)'), ('empty', 'Empty Safe Response'), ('cached', 'Cached Last Value'), ('mock', 'Mock Response (dev)'), ('error', 'Return Error Object')], default='empty', help_text='Action when module is DISABLED for tenant', max_length=20)),
                ('when_disabled_write', models.CharField(choices=[('buffer', 'Buffer for Replay'), ('redirect', 'Redirect to Core'), ('drop', 'Drop Silently'), ('queue_event', 'Queue as Event'), ('error', 'Return Error Object')], default='drop', help_text='Action for writes when module is DISABLED', max_length=20)),
                ('when_unauthorized_read', models.CharField(choices=[('wait', 'Wait (blocking)'), ('empty', 'Empty Safe Response'), ('cached', 'Cached Last Value'), ('mock', 'Mock Response (dev)'), ('error', 'Return Error Object')], default='empty', help_text='Action when tenant has NO PERMISSION', max_length=20)),
                ('when_unauthorized_write', models.CharField(choices=[('buffer', 'Buffer for Replay'), ('redirect', 'Redirect to Core'), ('drop', 'Drop Silently'), ('queue_event', 'Queue as Event'), ('error', 'Return Error Object')], default='drop', help_text='Action for writes when NO PERMISSION', max_length=20)),
                ('cache_ttl_seconds', models.IntegerField(default=300, help_text="How long to cache responses (for 'cached' fallback)")),
                ('buffer_ttl_seconds', models.IntegerField(default=3600, help_text='How long to retain buffered writes before expiring')),
                ('max_buffer_size', models.IntegerField(default=100, help_text='Maximum buffered requests per org/module')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority policies take precedence')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Connector Policy',
                'verbose_name_plural': 'Connector Policies',
                'db_table': 'connectorpolicy',
                'ordering': ['-priority', 'target_module'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='GlobalCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('symbol', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'globalcurrency',
            },
        ),
        migrations.CreateModel(
            name='ModuleContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provides', models.JSONField(default=dict, help_text='\n        {\n            "read_endpoints": ["products/", "categories/"],\n            "write_endpoints": ["products/create/"],\n            "events_emitted": ["product.created", "stock.updated"],\n            "functions_exposed": ["get_product_cost", "validate_sku"]\n        }\n        ')),
                ('needs', models.JSONField(default=dict, help_text='\n        {\n            "data_from": [\n                {"module": "inventory", "endpoint": "products/cost/", "blocking": false}\n            ],\n            "events_from": [\n                {"module": "pos", "event": "sale.completed"}\n            ],\n            "capabilities": ["accounting.post_journal_entry"]\n        }\n        ')),
                ('rules', models.JSONField(default=dict, help_text='\n        {\n            "can_work_without": ["crm", "reporting"],\n            "buffer_writes_to": ["accounting"],\n            "critical_dependencies": ["core"]\n        }\n        ')),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Module Contract',
                'verbose_name_plural': 'Module Contracts',
                'db_table': 'modulecontract',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_read_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('data_usage_bytes', models.BigIntegerField(default=0)),
                ('plan_expiry_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_config', models.JSONField(blank=True, default=dict, help_text="e.g. {'days_before': 5}")),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='OrganizationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(default='legacy', max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('active_features', models.JSONField(blank=True, default=list)),
                ('granted_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'organizationmodule',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='PlanAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('addon_type', models.CharField(choices=[('users', 'Extra Users'), ('sites', 'Extra Sites'), ('storage', 'Extra Storage (GB)'), ('products', 'Extra Products'), ('invoices', 'Extra Invoices/Month'), ('customers', 'Extra Customers')], max_length=20)),
                ('quantity', models.IntegerField(help_text='How much this add-on provides (e.g. 10 users, 50 GB)')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('annual_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'planaddon',
                'ordering': ['addon_type', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='PlanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'plancategory',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public_requestable', models.BooleanField(default=False, help_text='Can users self-request this role during registration')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='SaaSClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('company_name', models.CharField(blank=True, default='', help_text='Legal company name if different from person name', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'saasclient',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'site',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('billing_cycle', models.CharField(blank=True, default='MONTHLY', help_text='MONTHLY, ANNUAL, ONE_TIME', max_length=20)),
                ('type', models.CharField(choices=[('PURCHASE', 'Purchase Invoice'), ('CREDIT_NOTE', 'Credit Note'), ('RENEWAL', 'Renewal')], default='PURCHASE', max_length=20)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was confirmed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'subscriptionpayment',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('annual_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('modules', models.JSONField(default=list)),
                ('features', models.JSONField(default=dict)),
                ('limits', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True, help_text='Public plans show on landing/pricing page. Private plans are org-specific.')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order on pricing pages (lower = first)')),
                ('trial_days', models.IntegerField(default=0, help_text='Free trial duration in days. 0 = no trial.')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'subscriptionplan',
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('INSTALLED', 'Installed'), ('UPGRADING', 'Upgrading'), ('FAILED', 'Failed'), ('DISABLED', 'Disabled')], default='INSTALLED', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public – shown on landing page'), ('organization', 'Organization – only visible to assigned orgs'), ('private', 'Private – hidden/internal only')], default='public', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Short description shown on landing page and plan pages')),
                ('icon', models.CharField(blank=True, default='', help_text="Lucide icon name (e.g. 'shopping-cart', 'bar-chart')", max_length=50)),
                ('manifest', models.JSONField(default=dict)),
                ('checksum', models.CharField(max_length=64)),
                ('installed_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'systemmodule',
            },
        ),
        migrations.CreateModel(
            name='SystemModuleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('from_version', models.CharField(default='N/A', max_length=50)),
                ('to_version', models.CharField(default='N/A', max_length=50)),
                ('action', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('logs', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'systemmodulelog',
            },
        ),
        migrations.CreateModel(
            name='SystemUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('changelog', models.TextField(blank=True, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('package_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'systemupdate',
                'ordering': ['-created_at'],
            },
        ),
    ]
