# Generated by Django 6.0.3 on 2026-05-02 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageroverridelog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.order'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.globalcurrency'),
        ),
        migrations.AddField(
            model_name='organization',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.businesstype'),
        ),
        migrations.AddField(
            model_name='organization',
            name='finance_hard_locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='manageroverridelog',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='domainevent',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='decisionrule',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='connectorlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connector_logs', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='connectorcache',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connector_cache', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='confighistory',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='bufferedrequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buffered_requests', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='approvalpolicystep',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='approvalpolicy',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='organizationaddon',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_addons', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='organizationmodule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_modules', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='orglistdefault',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='list_defaults', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='organizationaddon',
            name='addon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='erp.planaddon'),
        ),
        migrations.AddField(
            model_name='plancategory',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.country'),
        ),
        migrations.AddField(
            model_name='plancategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='erp.plancategory'),
        ),
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', to='erp.permission'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='erp.role'),
        ),
        migrations.AddField(
            model_name='organization',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Account owner / billing contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='erp.saasclient'),
        ),
        migrations.AddField(
            model_name='site',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='home_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_users', to='erp.site'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='business_types',
            field=models.ManyToManyField(blank=True, help_text='Business types this plan is available for. Empty = available to all.', related_name='plans', to='erp.businesstype'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='erp.plancategory'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='erp.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='previous_plan',
            field=models.ForeignKey(blank=True, help_text='Plan before the switch (for audit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrade_payments', to='erp.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='planaddon',
            name='plans',
            field=models.ManyToManyField(blank=True, help_text='Plans that can use this add-on. Empty = available to all.', related_name='addons', to='erp.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='organization',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='erp.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='modulecontract',
            name='module',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='erp.systemmodule'),
        ),
        migrations.AddField(
            model_name='systemmodulelog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='confighistory',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='erp.tenantconfig'),
        ),
        migrations.AddField(
            model_name='transactionstatuslog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionverificationconfig',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='txnapproval',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='txnapproval',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='udlesavedview',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='udlesavedview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='udle_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlistpreference',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_list_preferences', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='userlistpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['organization', 'model_type', 'is_active'], name='ml_model_org_type_idx'),
        ),
        migrations.AddIndex(
            model_name='featureflag',
            index=models.Index(fields=['organization', 'key'], name='erp_feature_tenant__6b9fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='featureflag',
            index=models.Index(fields=['is_enabled'], name='erp_feature_is_enab_712223_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featureflag',
            unique_together={('organization', 'key')},
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='erp_domaine_tenant__ff3bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['organization', 'event_type', 'created_at'], name='erp_domaine_tenant__c286e5_idx'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['aggregate_type', 'aggregate_id', 'created_at'], name='erp_domaine_aggrega_cfb094_idx'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['status', 'next_retry_at'], name='erp_domaine_status_235b54_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionrule',
            index=models.Index(fields=['organization', 'context', 'is_active'], name='dec_rule_org_ctx_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionlog',
            index=models.Index(fields=['organization', 'context', '-created_at'], name='dec_log_org_ctx_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionlog',
            index=models.Index(fields=['decision_type'], name='dec_log_type_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionlog',
            index=models.Index(fields=['subject_id'], name='dec_log_subj_idx'),
        ),
        migrations.AddIndex(
            model_name='connectorlog',
            index=models.Index(fields=['target_module', 'created_at'], name='connectorlo_target__71d8af_idx'),
        ),
        migrations.AddIndex(
            model_name='connectorlog',
            index=models.Index(fields=['organization', 'created_at'], name='connectorlo_organiz_1035ee_idx'),
        ),
        migrations.AddIndex(
            model_name='connectorlog',
            index=models.Index(fields=['decision', 'created_at'], name='connectorlo_decisio_2743f7_idx'),
        ),
        migrations.AddIndex(
            model_name='connectorcache',
            index=models.Index(fields=['cache_key'], name='connectorca_cache_k_f68e11_idx'),
        ),
        migrations.AddIndex(
            model_name='connectorcache',
            index=models.Index(fields=['expires_at'], name='connectorca_expires_35a7ab_idx'),
        ),
        migrations.AddIndex(
            model_name='bufferedrequest',
            index=models.Index(fields=['target_module', 'status'], name='bufferedreq_target__3634dc_idx'),
        ),
        migrations.AddIndex(
            model_name='bufferedrequest',
            index=models.Index(fields=['organization', 'status'], name='bufferedreq_organiz_3f8ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='bufferedrequest',
            index=models.Index(fields=['expires_at'], name='bufferedreq_expires_f9101d_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['organization', 'model_name', 'object_id'], name='erp_audittr_tenant__cab6d8_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['audit_log'], name='erp_audittr_audit_l_89a6cc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'timestamp'], name='erp_auditlo_tenant__3bae30_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'user', 'timestamp'], name='erp_auditlo_tenant__7aa361_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'action', 'timestamp'], name='erp_auditlo_tenant__5422cf_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'resource_type', 'resource_id'], name='erp_auditlo_tenant__2245f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalpolicystep',
            unique_together={('policy', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='approvalpolicy',
            unique_together={('organization', 'txn_type')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationmodule',
            unique_together={('organization', 'module_name')},
        ),
        migrations.AlterUniqueTogether(
            name='orglistdefault',
            unique_together={('organization', 'list_key')},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('code', 'organization')},
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username', 'organization'), name='unique_username_per_org'),
        ),
        migrations.AddIndex(
            model_name='tenantconfig',
            index=models.Index(fields=['organization', 'key'], name='erp_tenantc_tenant__a104e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantconfig',
            unique_together={('organization', 'key')},
        ),
        migrations.AddIndex(
            model_name='transactionstatuslog',
            index=models.Index(fields=['transaction_type', 'transaction_id'], name='transaction_transac_49eed7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionverificationconfig',
            unique_together={('organization', 'transaction_type')},
        ),
        migrations.AddIndex(
            model_name='txnapproval',
            index=models.Index(fields=['txn_type', 'txn_id'], name='kernel_txn__txn_typ_253222_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='udlesavedview',
            unique_together={('user', 'model_name', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='userlistpreference',
            unique_together={('user', 'organization', 'list_key')},
        ),
    ]
