# Generated by Django 6.0.2 on 2026-05-04 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bufferedrequest',
            new_name='bufferedreq_tenant__076e1c_idx',
            old_name='bufferedreq_organiz_3f8ed5_idx',
        ),
        migrations.RenameIndex(
            model_name='connectorlog',
            new_name='connectorlo_tenant__d9927a_idx',
            old_name='connectorlo_organiz_1035ee_idx',
        ),
        migrations.AlterField(
            model_name='bufferedrequest',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buffered_requests', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='connectorcache',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connector_cache', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='connectorlog',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connector_logs', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='udlesavedview',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
    ]
