# Generated by Django 6.0.2 on 2026-02-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancategory',
            name='linked_inventory_category',
            field=models.IntegerField(blank=True, help_text='FK to inventory Category.id for catalog integration', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='business_types',
            field=models.ManyToManyField(blank=True, help_text='Business types this plan is available for. Empty = available to all.', related_name='plans', to='erp.businesstype'),
        ),
    ]
