# Generated by Django 6.0.2 on 2026-02-21 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_organization_is_read_only_user_declared_password_and_more'),
        ('erp', '0003_plancategory_linked_inventory_category_and_more'),
    ]

    operations = [
    ]
