# Generated by Django 5.2.11 on 2026-02-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_customdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pos_pin',
            field=models.CharField(blank=True, help_text='Hashed 4-6 digit PIN for POS cashier login and user switching', max_length=128, null=True),
        ),
    ]
