# Generated by Django 6.0.2 on 2026-02-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_list_preferences'),
        ('erp', '0003_plancategory_linked_inventory_category_and_more'),
    ]

    operations = [
    ]
