# Generated by Django 5.2.11 on 2026-02-26 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_user_pos_pin'),
        ('inventory', '0004_alter_category_barcode_sequence_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='UPDATE "user" SET home_site_id = NULL WHERE home_site_id IS NOT NULL AND home_site_id NOT IN (SELECT id FROM warehouse);',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='user',
            name='home_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_users', to='inventory.warehouse'),
        ),
    ]
