# Generated by Django 5.1.7 on 2026-02-02 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_brand_categories_brand_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='erp.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
