# Generated by Django 5.2.11 on 2026-02-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_user_home_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_driver',
            field=models.BooleanField(default=False, help_text='Tag: this user is a delivery driver. Used to filter the driver list in POS delivery.'),
        ),
    ]
