# Generated by Django 6.0.2 on 2026-03-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_user_is_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Used for system alerts and task assignments', max_length=50, null=True),
        ),
    ]
