# Generated by Django 5.1.7 on 2026-02-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_brand_short_name_category_code_category_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
    ]
