# Generated by Django 6.0.2 on 2026-03-05 00:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_alter_planaddon_addon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('resource_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('resource_repr', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('http_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('field_type', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Audit Trail',
                'verbose_name_plural': 'Audit Trails',
                'ordering': ['field_name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.JSONField()),
                ('new_value', models.JSONField()),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Config History',
                'verbose_name_plural': 'Config Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('category', models.CharField(choices=[('EVENT', 'Event Payload'), ('API', 'API Contract'), ('TYPE', 'Shared Type'), ('MODEL', 'Model Interface')], max_length=50)),
                ('owner_module', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_version', models.CharField(default='1.0.0', max_length=20)),
                ('is_deprecated', models.BooleanField(default=False)),
                ('deprecated_reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContractUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('usage_type', models.CharField(choices=[('PRODUCER', 'Produces (emits events, sends API responses)'), ('CONSUMER', 'Consumes (handles events, calls APIs)'), ('BOTH', 'Both producer and consumer')], max_length=50)),
                ('required_version', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contract Usage',
                'verbose_name_plural': 'Contract Usages',
                'ordering': ['module_name'],
            },
        ),
        migrations.CreateModel(
            name='ContractVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('schema', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('changelog', models.TextField(blank=True)),
                ('is_breaking_change', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contract Version',
                'verbose_name_plural': 'Contract Versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('event_version', models.IntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('aggregate_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('aggregate_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Domain Event',
                'verbose_name_plural': 'Domain Events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_pattern', models.CharField(db_index=True, max_length=100)),
                ('handler_name', models.CharField(max_length=200)),
                ('handler_module', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Event Subscription',
                'verbose_name_plural': 'Event Subscriptions',
                'ordering': ['-priority', 'handler_name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('rollout_percentage', models.IntegerField(default=100, help_text='0-100')),
                ('start_date', models.DateTimeField(blank=True, help_text='Auto-enable on this date', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Auto-disable on this date', null=True)),
                ('target_user_ids', models.JSONField(blank=True, default=list, help_text='List of user IDs who should see this feature')),
                ('target_user_roles', models.JSONField(blank=True, default=list, help_text='List of role names who should see this feature')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='KernelModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('author', models.CharField(blank=True, max_length=200)),
                ('license', models.CharField(blank=True, max_length=100)),
                ('manifest', models.JSONField()),
                ('is_system_module', models.BooleanField(default=False)),
                ('is_marketplace_module', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('depends_on', models.JSONField(default=list)),
                ('signature', models.TextField(blank=True)),
                ('signature_verified', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_path', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Kernel Module',
                'verbose_name_plural': 'Kernel Modules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_version', models.CharField(blank=True, max_length=20)),
                ('max_version', models.CharField(blank=True, max_length=20)),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Module Dependency',
                'verbose_name_plural': 'Module Dependencies',
            },
        ),
        migrations.CreateModel(
            name='ModuleMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration_name', models.CharField(max_length=255)),
                ('migration_version', models.CharField(blank=True, max_length=20)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Module Migration',
                'verbose_name_plural': 'Module Migrations',
                'ordering': ['applied_at'],
            },
        ),
        migrations.CreateModel(
            name='OrgModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('INSTALLED', 'Installed'), ('ENABLED', 'Enabled'), ('DISABLED', 'Disabled'), ('UPGRADING', 'Upgrading'), ('FAILED', 'Failed')], default='REGISTERED', max_length=20)),
                ('installed_version', models.CharField(max_length=20)),
                ('target_version', models.CharField(blank=True, max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('last_upgrade_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Organization Module',
                'verbose_name_plural': 'Organization Modules',
                'ordering': ['module__name'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.IntegerField()),
                ('granted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kernel_resource_permission',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.CharField(default='free', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'core_tenant',
            },
        ),
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('value', models.JSONField()),
                ('value_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant Config',
                'verbose_name_plural': 'Tenant Configs',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kernel_user_role',
            },
        ),
        migrations.RemoveField(
            model_name='permission',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='permission',
            name='is_dangerous',
            field=models.BooleanField(default=False, help_text='Mark as dangerous (delete, modify critical data)'),
        ),
        migrations.AddField(
            model_name='permission',
            name='module',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='is_system_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='parent_role',
            field=models.ForeignKey(blank=True, help_text='Inherit permissions from parent role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roles', to='erp.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(help_text='Format: module.action_resource (e.g., finance.create_invoice)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='erp.permission'),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['code'], name='kernel_perm_code_b750f5_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['module'], name='kernel_perm_module_e995ba_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization', 'name'], name='kernel_role_organization__7d80c1_idx'),
        ),
        migrations.AlterModelTable(
            name='permission',
            table='kernel_permission',
        ),
        migrations.AlterModelTable(
            name='role',
            table='kernel_role',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='audit_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_changes', to='erp.auditlog'),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='confighistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='confighistory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='contract',
            name='replacement_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='erp.contract'),
        ),
        migrations.AddField(
            model_name='contractusage',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='erp.contract'),
        ),
        migrations.AddField(
            model_name='contractversion',
            name='compatible_with',
            field=models.ManyToManyField(blank=True, related_name='compatible_versions', to='erp.contractversion'),
        ),
        migrations.AddField(
            model_name='contractversion',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='erp.contract'),
        ),
        migrations.AddField(
            model_name='domainevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='domainevent',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='eventsubscription',
            unique_together={('event_pattern', 'handler_name')},
        ),
        migrations.AddField(
            model_name='featureflag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='moduledependency',
            name='depends_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='erp.kernelmodule'),
        ),
        migrations.AddField(
            model_name='moduledependency',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='erp.kernelmodule'),
        ),
        migrations.AddField(
            model_name='modulemigration',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='orgmodule',
            name='enabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enabled_modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgmodule',
            name='installed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_modules', to='erp.kernelmodule'),
        ),
        migrations.AddField(
            model_name='orgmodule',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='modulemigration',
            name='org_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrations', to='erp.orgmodule'),
        ),
        migrations.AddField(
            model_name='resourcepermission',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.permission'),
        ),
        migrations.AddField(
            model_name='resourcepermission',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='resourcepermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='core_organization_slug_bb8545_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active'], name='core_organization_is_acti_99418a_idx'),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='confighistory',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='erp.tenantconfig'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='erp.role'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_public_requestable',
        ),
        migrations.RemoveField(
            model_name='role',
            name='organization',
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'timestamp'], name='erp_auditlo_organization__3bae30_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'user', 'timestamp'], name='erp_auditlo_organization__7aa361_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'action', 'timestamp'], name='erp_auditlo_organization__5422cf_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'resource_type', 'resource_id'], name='erp_auditlo_organization__2245f0_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['organization', 'model_name', 'object_id'], name='erp_audittr_organization__cab6d8_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['audit_log'], name='erp_audittr_audit_l_89a6cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractusage',
            unique_together={('contract', 'module_name')},
        ),
        migrations.AlterUniqueTogether(
            name='contractversion',
            unique_together={('contract', 'version')},
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='erp_domaine_organization__ff3bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['organization', 'event_type', 'created_at'], name='erp_domaine_organization__c286e5_idx'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['aggregate_type', 'aggregate_id', 'created_at'], name='erp_domaine_aggrega_cfb094_idx'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['status', 'next_retry_at'], name='erp_domaine_status_235b54_idx'),
        ),
        migrations.AddIndex(
            model_name='featureflag',
            index=models.Index(fields=['organization', 'key'], name='erp_feature_organization__6b9fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='featureflag',
            index=models.Index(fields=['is_enabled'], name='erp_feature_is_enab_712223_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featureflag',
            unique_together={('organization', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='moduledependency',
            unique_together={('module', 'depends_on')},
        ),
        migrations.AddIndex(
            model_name='orgmodule',
            index=models.Index(fields=['organization', 'status'], name='erp_orgmodu_organization__e71a63_idx'),
        ),
        migrations.AddIndex(
            model_name='orgmodule',
            index=models.Index(fields=['module', 'status'], name='erp_orgmodu_module__a20886_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orgmodule',
            unique_together={('organization', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='modulemigration',
            unique_together={('org_module', 'migration_name')},
        ),
        migrations.AddIndex(
            model_name='resourcepermission',
            index=models.Index(fields=['organization', 'user', 'resource_type', 'resource_id'], name='kernel_reso_organization__63236d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcepermission',
            unique_together={('organization', 'user', 'permission', 'resource_type', 'resource_id')},
        ),
        migrations.AddIndex(
            model_name='tenantconfig',
            index=models.Index(fields=['organization', 'key'], name='erp_tenantc_organization__a104e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantconfig',
            unique_together={('organization', 'key')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['organization', 'user'], name='kernel_user_organization__e61c89_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role'], name='kernel_user_role_id_386945_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('organization', 'user', 'role', 'resource_type', 'resource_id')},
        ),
    ]
