# Generated by Django 5.1.7 on 2026-02-02 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_businesstype_globalcurrency_employee_address_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='erp.financialaccount'),
        ),
    ]
