# Generated by Django 6.0.2 on 2026-03-05 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_auditlog_audittrail_confighistory_contract_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organization',
            name='core_organization_slug_bb8545_idx',
        ),
        migrations.RemoveIndex(
            model_name='organization',
            name='core_organization_is_acti_99418a_idx',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
