# Generated by Django 6.0.2 on 2026-03-05 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_remove_organization_core_organization_slug_bb8545_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionstatuslog',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='JSON metadata: which rule matched, bypass reason, etc.'),
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for this transaction type', max_length=50)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'transaction_type',
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TransactionVerificationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_controlled', models.BooleanField(default=True, help_text='Whether this transaction type requires approval')),
                ('mode', models.CharField(choices=[('SIMPLE', 'Simple - Fixed levels for all transactions'), ('RULED', 'Rule-Based - Dynamic levels based on conditions')], default='SIMPLE', help_text='SIMPLE: fixed levels, RULED: dynamic based on rules', max_length=10)),
                ('default_levels', models.IntegerField(default=1, help_text='Default verification levels (used in SIMPLE mode)')),
                ('allow_override', models.BooleanField(default=False, help_text='Allow managers to use "Verify & Complete" to skip levels')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='erp.transactiontype')),
            ],
            options={
                'db_table': 'transaction_verification_policy',
                'ordering': ['transaction_type__name'],
                'unique_together': {('organization', 'transaction_type')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Rule description', max_length=100)),
                ('priority', models.IntegerField(default=100, help_text='Higher priority rules are evaluated first')),
                ('conditions', models.JSONField(help_text='JSON conditions e.g., {"amount__gt": 10000, "type": "REFUND"}')),
                ('required_levels', models.IntegerField(help_text='Number of verification levels required if this rule matches')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='erp.transactionverificationpolicy')),
            ],
            options={
                'db_table': 'approval_rule',
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LevelRoleMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='Verification level (1, 2, 3, ...)')),
                ('role_name', models.CharField(blank=True, help_text='Role name required to verify at this level', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_role_maps', to='erp.transactionverificationpolicy')),
            ],
            options={
                'db_table': 'level_role_map',
                'ordering': ['level'],
                'unique_together': {('policy', 'level')},
            },
        ),
    ]
