# Generated by Django 6.0.2 on 2026-03-06 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_transactionstatuslog_meta_transactiontype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(db_index=True, max_length=100)),
                ('min_level_required', models.PositiveIntegerField(default=1)),
                ('allow_bypass', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization')),
            ],
            options={
                'db_table': 'kernel_approval_policies',
                'unique_together': {('tenant', 'txn_type')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalPolicyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('role_id', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='erp.approvalpolicy')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization')),
            ],
            options={
                'db_table': 'kernel_approval_policy_steps',
                'ordering': ['level'],
                'unique_together': {('policy', 'level')},
            },
        ),
        migrations.CreateModel(
            name='TxnApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(db_index=True, max_length=100)),
                ('txn_id', models.PositiveIntegerField(db_index=True)),
                ('level', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit'), ('VERIFY', 'Verify'), ('APPROVE', 'Approve'), ('POST', 'Post'), ('LOCK', 'Lock'), ('REVERSE', 'Reverse'), ('REJECT', 'Reject')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization')),
            ],
            options={
                'db_table': 'kernel_txn_approvals',
                'indexes': [models.Index(fields=['txn_type', 'txn_id'], name='kernel_txn__txn_typ_253222_idx')],
            },
        ),
    ]
