# Generated by Django 5.1.7 on 2026-02-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_alter_user_username_user_unique_username_per_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='is_hard_locked',
            field=models.BooleanField(default=False),
        ),
    ]
