# Generated by Django 6.0.2 on 2026-03-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_approvalpolicy_approvalpolicystep_txnapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txnapproval',
            name='action',
            field=models.CharField(choices=[('SUBMIT', 'Submit'), ('VERIFY', 'Verify'), ('APPROVE', 'Approve'), ('POST', 'Post'), ('LOCK', 'Lock'), ('REVERSE', 'Reverse'), ('REJECT', 'Reject'), ('CANCEL', 'Cancel'), ('REOPEN', 'Re-open')], max_length=20),
        ),
    ]
