# Generated by Django 5.2.11 on 2026-03-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_alter_txnapproval_action'),
        ('inventory', '0018_merge_20260307_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_branches',
            field=models.ManyToManyField(blank=True, help_text='Branches this user can access. Empty = all branches.', limit_choices_to={'location_type': 'BRANCH'}, related_name='branch_users', to='inventory.warehouse'),
        ),
    ]
