# Generated by Django 5.2.11 on 2026-03-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_user_assigned_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driver_scope',
            field=models.CharField(blank=True, choices=[('SALES', 'Sales Delivery'), ('PURCHASE', 'Purchase Pickup'), ('BOTH', 'Both')], default='BOTH', help_text='Whether this driver handles sales deliveries, purchase pickups, or both.', max_length=10),
        ),
    ]
