# Generated by Django 5.1.7 on 2026-02-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_order_contact_order_invoice_price_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='customer_type',
            field=models.CharField(choices=[('B2B', 'Business to Business'), ('B2C', 'Business to Consumer'), ('B2F', 'Business to Foreign'), ('B2G', 'Business to Government')], default='B2C', max_length=10),
        ),
    ]
