# Generated by Django 5.2.11 on 2026-03-08 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_user_driver_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, default=1.0, help_text='1 from_currency = X to_currency', max_digits=18)),
                ('rate_mode', models.CharField(choices=[('FIXED', 'Fixed (Manual)'), ('DAILY', 'Daily Update')], default='FIXED', max_length=10)),
                ('effective_date', models.DateField(auto_now=True, help_text='Date this rate was last updated')),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='erp.globalcurrency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='erp.organization')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='erp.globalcurrency')),
            ],
            options={
                'db_table': 'exchange_rate',
                'ordering': ['from_currency__code', 'to_currency__code'],
                'unique_together': {('organization', 'from_currency', 'to_currency')},
            },
        ),
    ]
