# Generated by Django 5.1.7 on 2026-02-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_contact_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='airsi_tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override specific rate. If null, uses global.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_airsi_subject',
            field=models.BooleanField(default=False, help_text='If true, AIRSI tax logic applies to this contact.'),
        ),
    ]
