# Generated by Django 5.2.11 on 2026-03-09 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_exchangerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='driver_scope',
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
    ]
