# Generated by Django 5.1.7 on 2026-02-03 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_module_names(apps, schema_editor):
    OrganizationModule = apps.get_model('erp', 'OrganizationModule')
    for om in OrganizationModule.objects.all():
        if om.module:
            om.module_name = om.module.code
            om.save()

class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_module_organizationmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('INSTALLED', 'Installed'), ('UPGRADING', 'Upgrading'), ('FAILED', 'Failed'), ('DISABLED', 'Disabled')], default='INSTALLED', max_length=20)),
                ('manifest', models.JSONField(default=dict)),
                ('checksum', models.CharField(max_length=64)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'systemmodule',
            },
        ),
        migrations.RenameField(
            model_name='organizationmodule',
            old_name='installed_at',
            new_name='granted_at',
        ),
        migrations.AddField(
            model_name='organizationmodule',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizationmodule',
            name='module_name',
            field=models.CharField(default='legacy', max_length=100),
        ),
        migrations.RunPython(populate_module_names),
        migrations.AlterUniqueTogether(
            name='organizationmodule',
            unique_together={('organization', 'module_name')},
        ),
        migrations.AlterField(
            model_name='organizationmodule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_modules', to='erp.organization'),
        ),
        migrations.CreateModel(
            name='SystemModuleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('from_version', models.CharField(max_length=50)),
                ('to_version', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('logs', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'systemmodulelog',
            },
        ),
        migrations.RemoveField(
            model_name='organizationmodule',
            name='module',
        ),
        migrations.RemoveField(
            model_name='organizationmodule',
            name='status',
        ),
        migrations.RemoveField(
            model_name='organizationmodule',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
