# Generated by Django 6.0.2 on 2026-03-10 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_paymentterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='finance_hard_locked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the first journal entry was posted', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='finance_hard_locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='finance_setup_completed',
            field=models.BooleanField(default=False, help_text='Set to True when the COA Setup Wizard is finalized'),
        ),
    ]
