# Generated by Django 5.1.7 on 2026-02-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_systemmodule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmodule',
            name='active_features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
