# Generated by Django 5.1.7 on 2026-02-04 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_organizationmodule_active_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('changelog', models.TextField(blank=True, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('package_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'systemupdate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameField(
            model_name='systemmodulelog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='systemmodulelog',
            old_name='from_version',
            new_name='version',
        ),
        migrations.RemoveField(
            model_name='systemmodulelog',
            name='logs',
        ),
        migrations.RemoveField(
            model_name='systemmodulelog',
            name='module_name',
        ),
        migrations.RemoveField(
            model_name='systemmodulelog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='systemmodulelog',
            name='to_version',
        ),
        migrations.AddField(
            model_name='systemmodulelog',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemmodulelog',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='erp.systemmodule'),
        ),
        migrations.AlterField(
            model_name='systemmodulelog',
            name='action',
            field=models.CharField(max_length=50),
        ),
    ]
