# Generated by Django 5.1.7 on 2026-02-04 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_remove_systemmodulelog_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='billing_contact_id',
            field=models.IntegerField(blank=True, help_text="ID of the Contact record in the SaaS Provider's ledger.", null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='data_usage_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_read_only',
            field=models.BooleanField(default=False, help_text='If true, organization has read-only access due to plan expiry.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='plan_expiry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='reminder_config',
            field=models.JSONField(blank=True, default=dict, help_text="e.g. {'days_before': 5}"),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_role', models.CharField(blank=True, help_text='Role of the actor at time of event', max_length=100)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View')], max_length=10)),
                ('table_name', models.CharField(db_index=True, max_length=100)),
                ('record_id', models.CharField(max_length=100)),
                ('old_value', models.JSONField(blank=True, help_text='Previous state (for UPDATE/DELETE)', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New state (for CREATE/UPDATE)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='erp.organization')),
            ],
            options={
                'db_table': 'AuditLog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(help_text='The data change to be applied')),
                ('target_table', models.CharField(max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('review_notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='erp.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_approvals', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_approvals', to=settings.AUTH_USER_MODEL)),
                ('audit_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='erp.auditlog')),
            ],
            options={
                'db_table': 'ApprovalRequest',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('PUBLIC', 'Public (Landing Page)'), ('ORGANIZATION', 'Organization Specific'), ('INTERNAL', 'Internal / Legacy')], max_length=20)),
                ('allowed_organizations', models.ManyToManyField(blank=True, related_name='available_plan_categories', to='erp.organization')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.country')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='erp.plancategory')),
            ],
            options={
                'verbose_name_plural': 'Plan Categories',
                'db_table': 'PlanCategory',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('annual_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('modules', models.JSONField(default=list, help_text='List of module codes enabled for this plan')),
                ('features', models.JSONField(default=dict, help_text='Dictionary of feature flags and settings')),
                ('limits', models.JSONField(default=dict, help_text="Usage limits, e.g. {'max_users': 10, 'storage_gb': 5}")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='erp.plancategory')),
                ('upgrade_path', models.ManyToManyField(blank=True, related_name='downgrade_options', to='erp.subscriptionplan')),
            ],
            options={
                'db_table': 'SubscriptionPlan',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('journal_entry_id', models.IntegerField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='erp.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.subscriptionplan')),
            ],
            options={
                'db_table': 'SubscriptionPayment',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='erp.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'Print Etiquette'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=5, help_text='1=Low, 5=Normal, 10=Urgent')),
                ('due_hours', models.IntegerField(default=24, help_text='Default hours until due')),
                ('title_template', models.CharField(default='{action} for {record}', help_text='Placeholders: {action}, {record}, {user}', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_assignee_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_task_templates', to='erp.role')),
            ],
            options={
                'db_table': 'TaskTemplate',
            },
        ),
        migrations.CreateModel(
            name='TaskQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('priority', models.IntegerField(default=5)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Additional task context/data')),
                ('assigned_to_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='erp.role')),
                ('assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_queue', to='erp.organization')),
                ('source_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='erp.approvalrequest')),
                ('source_audit_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='erp.auditlog')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='erp.tasktemplate')),
            ],
            options={
                'db_table': 'TaskQueue',
                'ordering': ['-priority', 'due_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, help_text="e.g., 'product.price_change', 'invoice.delete'", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable name', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approval_mode', models.CharField(choices=[('PRE', 'Pre-Approval (Hold until approved)'), ('POST', 'Post-Approval (Apply, then review)')], default='POST', max_length=4)),
                ('priority_threshold', models.IntegerField(default=0, help_text='Events with priority >= this value require this workflow')),
                ('generates_task', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver_role', models.ForeignKey(blank=True, help_text='Role required to approve this workflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_definitions', to='erp.role')),
                ('bypass_roles', models.ManyToManyField(blank=True, help_text='Roles that can bypass this approval requirement', related_name='bypassed_workflows', to='erp.role')),
                ('task_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_definitions', to='erp.tasktemplate')),
            ],
            options={
                'db_table': 'WorkflowDefinition',
                'ordering': ['event_type'],
            },
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='erp.workflowdefinition'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'timestamp'], name='AuditLog_organiz_75b165_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['table_name', 'record_id'], name='AuditLog_table_n_5ecbe4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', 'timestamp'], name='AuditLog_actor_i_85630c_idx'),
        ),
        migrations.AddIndex(
            model_name='taskqueue',
            index=models.Index(fields=['organization', 'status'], name='TaskQueue_organiz_6ee4f6_idx'),
        ),
        migrations.AddIndex(
            model_name='taskqueue',
            index=models.Index(fields=['assigned_to_user', 'status'], name='TaskQueue_assigne_41db0a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskqueue',
            index=models.Index(fields=['assigned_to_role', 'status'], name='TaskQueue_assigne_6d785f_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['organization', 'status'], name='ApprovalReq_organiz_610ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['requested_by', 'status'], name='ApprovalReq_request_577027_idx'),
        ),
    ]
