# Generated by Django 6.0.4 on 2026-04-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_einvoice_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlistpreference',
            name='active_profile_id',
            field=models.CharField(blank=True, default='default', help_text='ID of the currently active profile', max_length=100),
        ),
        migrations.AddField(
            model_name='userlistpreference',
            name='view_profiles',
            field=models.JSONField(blank=True, default=list, help_text='Array of DajingoViewProfile objects [{id, name, columns, filters, columnOrder}]'),
        ),
    ]
