# Generated by Django 5.1.7 on 2026-02-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_connector_module'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connectorpolicy',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='connectorpolicy',
            name='source_module',
            field=models.CharField(default='*', help_text="Requesting module (e.g., 'pos') or '*' for any module", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='connectorpolicy',
            unique_together={('source_module', 'target_module', 'target_endpoint')},
        ),
    ]
