# Generated by Django 6.0.3 on 2026-05-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_remove_approvalrule_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orglistdefault',
            name='active_profile_id',
            field=models.CharField(blank=True, default='default', help_text='Recommended default profile for the organization', max_length=100),
        ),
        migrations.AddField(
            model_name='orglistdefault',
            name='view_profiles',
            field=models.JSONField(blank=True, default=list, help_text='Array of shared DajingoViewProfile objects'),
        ),
    ]
