# Generated by Django 6.0.2 on 2026-02-09 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0038_remove_approvalrequest_approvalreq_organiz_610ec8_idx_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskqueue',
            name='source_approval',
        ),
        migrations.RemoveField(
            model_name='taskqueue',
            name='source_audit_log',
        ),
        migrations.DeleteModel(
            name='BarcodeSettings',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ChartOfAccount',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='FinancialAccount',
        ),
        migrations.DeleteModel(
            name='FinancialEvent',
        ),
        migrations.DeleteModel(
            name='FiscalPeriod',
        ),
        migrations.DeleteModel(
            name='FiscalYear',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='InventoryLevel',
        ),
        migrations.DeleteModel(
            name='InventoryMovement',
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.DeleteModel(
            name='JournalEntryLine',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='LoanInstallment',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderLine',
        ),
        migrations.RemoveField(
            model_name='packageupload',
            name='applied_by',
        ),
        migrations.RemoveField(
            model_name='packageupload',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='Parfum',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductGroup',
        ),
        migrations.DeleteModel(
            name='StockBatch',
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
        migrations.RemoveField(
            model_name='taskqueue',
            name='assigned_to_role',
        ),
        migrations.RemoveField(
            model_name='taskqueue',
            name='assigned_to_user',
        ),
        migrations.RemoveField(
            model_name='taskqueue',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='taskqueue',
            name='template',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransactionSequence',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
        migrations.DeleteModel(
            name='WorkflowDefinition',
        ),
        migrations.AddField(
            model_name='modulecontract',
            name='module',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='erp.systemmodule'),
        ),
        migrations.AddField(
            model_name='permission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='plancategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='erp.plancategory'),
        ),
        migrations.AddField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='is_public_requestable',
            field=models.BooleanField(default=False, help_text='Can users self-request this role during registration'),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='Linked accounting journal entry', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When payment was confirmed', null=True),
        ),
        migrations.AlterField(
            model_name='bufferedrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bufferedrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bufferedrequest',
            name='method',
            field=models.CharField(blank=True, default='POST', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bufferedrequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buffered_requests', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='bufferedrequest',
            name='payload',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='bufferedrequest',
            name='target_endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bufferedrequest',
            name='target_module',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='connectorcache',
            name='cached_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectorcache',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectorcache',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connector_cache', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='connectorcache',
            name='response_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectorcache',
            name='target_endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='connectorcache',
            name='target_module',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='connectorlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectorlog',
            name='decision',
            field=models.CharField(blank=True, choices=[('forward', 'Forwarded'), ('fallback', 'Fallback Applied'), ('buffer', 'Buffered'), ('reject', 'Rejected'), ('replay', 'Replayed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='connectorlog',
            name='module_state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='connectorlog',
            name='operation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='connectorlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connector_logs', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='connectorlog',
            name='target_endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='connectorlog',
            name='target_module',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='connectorpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectorpolicy',
            name='target_endpoint',
            field=models.CharField(blank=True, default='*', help_text="Specific endpoint or '*' for all endpoints", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='connectorpolicy',
            name='target_module',
            field=models.CharField(blank=True, help_text="Module code (e.g., 'inventory') or '*' for global", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='connectorpolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulecontract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulecontract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationmodule',
            name='granted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='planaddon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='planaddon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='saasclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='saasclient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemmodule',
            name='installed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemmodule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemmodulelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='connectorpolicy',
            unique_together={('source_module', 'target_module', 'target_endpoint')},
        ),
        migrations.AddIndex(
            model_name='bufferedrequest',
            index=models.Index(fields=['target_module', 'status'], name='bufferedreq_target__3634dc_idx'),
        ),
        migrations.AddIndex(
            model_name='bufferedrequest',
            index=models.Index(fields=['organization', 'status'], name='bufferedreq_organiz_3f8ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='bufferedrequest',
            index=models.Index(fields=['expires_at'], name='bufferedreq_expires_f9101d_idx'),
        ),
        migrations.AddIndex(
            model_name='connectorcache',
            index=models.Index(fields=['cache_key'], name='connectorca_cache_k_f68e11_idx'),
        ),
        migrations.AddIndex(
            model_name='connectorcache',
            index=models.Index(fields=['expires_at'], name='connectorca_expires_35a7ab_idx'),
        ),
        migrations.AddIndex(
            model_name='connectorlog',
            index=models.Index(fields=['target_module', 'created_at'], name='connectorlo_target__71d8af_idx'),
        ),
        migrations.AddIndex(
            model_name='connectorlog',
            index=models.Index(fields=['organization', 'created_at'], name='connectorlo_organiz_1035ee_idx'),
        ),
        migrations.AddIndex(
            model_name='connectorlog',
            index=models.Index(fields=['decision', 'created_at'], name='connectorlo_decisio_2743f7_idx'),
        ),
        migrations.AlterModelTable(
            name='bufferedrequest',
            table='bufferedrequest',
        ),
        migrations.AlterModelTable(
            name='businesstype',
            table='businesstype',
        ),
        migrations.AlterModelTable(
            name='connectorcache',
            table='connectorcache',
        ),
        migrations.AlterModelTable(
            name='connectorlog',
            table='connectorlog',
        ),
        migrations.AlterModelTable(
            name='connectorpolicy',
            table='connectorpolicy',
        ),
        migrations.AlterModelTable(
            name='globalcurrency',
            table='globalcurrency',
        ),
        migrations.AlterModelTable(
            name='modulecontract',
            table='modulecontract',
        ),
        migrations.AlterModelTable(
            name='organizationmodule',
            table='organizationmodule',
        ),
        migrations.AlterModelTable(
            name='planaddon',
            table='planaddon',
        ),
        migrations.AlterModelTable(
            name='plancategory',
            table='plancategory',
        ),
        migrations.AlterModelTable(
            name='subscriptionpayment',
            table='subscriptionpayment',
        ),
        migrations.AlterModelTable(
            name='subscriptionplan',
            table='subscriptionplan',
        ),
        migrations.DeleteModel(
            name='ApprovalRequest',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='PackageUpload',
        ),
        migrations.DeleteModel(
            name='TaskQueue',
        ),
        migrations.DeleteModel(
            name='TaskTemplate',
        ),
    ]
