# Generated by Django 5.1.7 on 2026-02-13 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0039_remove_taskqueue_source_approval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cash_register',
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='journal_entry_id',
            field=models.IntegerField(blank=True, db_column='journal_entry_id', help_text='Linked accounting journal entry', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cash_register_id',
            field=models.IntegerField(blank=True, db_column='cash_register_id', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='scope_pin_internal',
            field=models.CharField(blank=True, help_text='Hashed PIN required to access Internal scope. Null = free access.', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='scope_pin_official',
            field=models.CharField(blank=True, help_text='Hashed PIN required to access Official scope. Null = free access.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='erp.organization'),
        ),
    ]
