# Generated by Django 5.1.7 on 2026-02-16 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0041_organization_encryption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planaddon',
            name='addon_type',
            field=models.CharField(choices=[('users', 'Extra Users'), ('sites', 'Extra Sites'), ('storage', 'Extra Storage (GB)'), ('products', 'Extra Products'), ('invoices', 'Extra Invoices/Month'), ('customers', 'Extra Customers'), ('encryption', 'AES-256 Encryption')], max_length=20),
        ),
        migrations.CreateModel(
            name='OrganizationAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Number of units purchased')),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='erp.planaddon')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_addons', to='erp.organization')),
            ],
            options={
                'db_table': 'organizationaddon',
                'ordering': ['-purchased_at'],
            },
        ),
    ]
