# Generated by Django 5.1.7 on 2026-02-16 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0042_add_organizationaddon'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('JOURNAL_ENTRY', 'Journal Entry'), ('VOUCHER', 'Voucher'), ('SALES_INVOICE', 'Sales Invoice'), ('PURCHASE_INVOICE', 'Purchase Invoice'), ('PAYMENT_IN', 'Payment Incoming'), ('PAYMENT_OUT', 'Payment Outgoing'), ('REFUND', 'Refund'), ('STOCK_ADJUSTMENT', 'Stock Adjustment'), ('STOCK_TRANSFER', 'Stock Transfer'), ('REGISTER_SESSION', 'Register Session')], db_index=True, max_length=30)),
                ('transaction_id', models.IntegerField(db_index=True)),
                ('action', models.CharField(choices=[('LOCK', 'Lock'), ('UNLOCK', 'Unlock'), ('VERIFY', 'Verify'), ('UNVERIFY', 'Unverify'), ('CONFIRM', 'Confirm')], max_length=20)),
                ('level', models.IntegerField(default=0, help_text='Verification level (1, 2, 3...)')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, help_text='Mandatory for UNLOCK and UNVERIFY', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaction_status_log',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['transaction_type', 'transaction_id'], name='transaction_transac_49eed7_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionVerificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('JOURNAL_ENTRY', 'Journal Entry'), ('VOUCHER', 'Voucher'), ('SALES_INVOICE', 'Sales Invoice'), ('PURCHASE_INVOICE', 'Purchase Invoice'), ('PAYMENT_IN', 'Payment Incoming'), ('PAYMENT_OUT', 'Payment Outgoing'), ('REFUND', 'Refund'), ('STOCK_ADJUSTMENT', 'Stock Adjustment'), ('STOCK_TRANSFER', 'Stock Transfer'), ('REGISTER_SESSION', 'Register Session')], max_length=30)),
                ('required_levels', models.IntegerField(default=1, help_text='Default verification levels required')),
                ('amount_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='If transaction amount exceeds this, use threshold_levels instead', max_digits=15, null=True)),
                ('threshold_levels', models.IntegerField(blank=True, help_text='Verification levels for high-value transactions', null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'transaction_verification_config',
                'unique_together': {('organization', 'transaction_type')},
            },
        ),
    ]
