# Generated by Django 5.1.7 on 2026-02-16 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0043_transaction_lifecycle'),
        ('pos', '0008_orderline_qty_invoiced_orderline_qty_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='override_pin',
            field=models.CharField(blank=True, help_text='Hashed PIN for manager-level overrides (void, refund, discount override)', max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='ManagerOverrideLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VOID_ORDER', 'Void Order'), ('APPLY_DISCOUNT', 'Apply Manual Discount'), ('PRICE_OVERRIDE', 'Price Override'), ('REFUND', 'Process Refund'), ('DELETE_LINE', 'Delete Order Line'), ('REOPEN_ORDER', 'Reopen Closed Order'), ('OTHER', 'Other Override')], max_length=30)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='override_logs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'manager_override_log',
                'ordering': ['-performed_at'],
            },
        ),
    ]
