# Generated by Django 6.0.3 on 2026-05-02 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('erp', '0001_initial'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceregulation',
            name='currency',
            field=models.ForeignKey(help_text='Currency for regulated prices (must match at comparison time)', on_delete=django.db.models.deletion.PROTECT, related_name='price_regulations', to='reference.currency'),
        ),
        migrations.AddField(
            model_name='priceregulation',
            name='jurisdiction_country',
            field=models.ForeignKey(blank=True, help_text='Country where this regulation applies (null = all countries)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_regulations', to='reference.country'),
        ),
        migrations.AddField(
            model_name='priceregulation',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='priceregulation',
            name='previous_version',
            field=models.ForeignKey(blank=True, help_text='Link to the version this replaces', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='compliance.priceregulation'),
        ),
        migrations.AddField(
            model_name='regulationauditlog',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reference.currency'),
        ),
        migrations.AddField(
            model_name='regulationauditlog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_audit_logs', to='erp.organization'),
        ),
    ]
