# Generated by Django 6.0.3 on 2026-05-02 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0002_initial'),
        ('erp', '0001_initial'),
        ('inventory', '0001_initial'),
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='regulationauditlog',
            name='product',
            field=models.ForeignKey(blank=True, help_text='FK may be null if product was deleted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='regulationauditlog',
            name='regulation',
            field=models.ForeignKey(blank=True, help_text='FK may be null if regulation was deleted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='compliance.priceregulation'),
        ),
        migrations.AddField(
            model_name='regulationauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regulationrule',
            name='brands',
            field=models.ManyToManyField(blank=True, help_text='Brands to match. Empty = any brand', related_name='+', to='inventory.brand'),
        ),
        migrations.AddField(
            model_name='regulationrule',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Product category to match (e.g., "Huile")', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.category'),
        ),
        migrations.AddField(
            model_name='regulationrule',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='regulationrule',
            name='parfum',
            field=models.ForeignKey(blank=True, help_text='Product parfum/variant to match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.parfum'),
        ),
        migrations.AddField(
            model_name='regulationrule',
            name='price_group',
            field=models.ForeignKey(blank=True, help_text='ProductGroup to auto-enroll matched products into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulation_rules', to='inventory.productgroup'),
        ),
        migrations.AddField(
            model_name='regulationrule',
            name='product_country',
            field=models.ForeignKey(blank=True, help_text='Product country of origin to match (not regulation jurisdiction)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reference.country'),
        ),
        migrations.AddField(
            model_name='regulationrule',
            name='regulation',
            field=models.ForeignKey(help_text='The regulation this rule enrolls products into', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='compliance.priceregulation'),
        ),
        migrations.AddField(
            model_name='regulationrule',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Product unit to match (e.g., Liter, Kg)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.unit'),
        ),
        migrations.AddIndex(
            model_name='priceregulation',
            index=models.Index(fields=['organization', 'status', 'is_current'], name='reg_active_current_idx'),
        ),
        migrations.AddIndex(
            model_name='priceregulation',
            index=models.Index(fields=['organization', 'jurisdiction_country'], name='reg_country_idx'),
        ),
        migrations.AddConstraint(
            model_name='priceregulation',
            constraint=models.UniqueConstraint(fields=('organization', 'code', 'version'), name='unique_regulation_code_version_tenant'),
        ),
        migrations.AddIndex(
            model_name='regulationauditlog',
            index=models.Index(fields=['organization', 'product', '-timestamp'], name='audit_product_time_idx'),
        ),
        migrations.AddIndex(
            model_name='regulationauditlog',
            index=models.Index(fields=['organization', 'action', '-timestamp'], name='audit_action_time_idx'),
        ),
        migrations.AddIndex(
            model_name='regulationauditlog',
            index=models.Index(fields=['organization', 'regulation', '-timestamp'], name='audit_regulation_time_idx'),
        ),
        migrations.AddIndex(
            model_name='regulationrule',
            index=models.Index(fields=['organization', 'is_active'], name='rule_active_idx'),
        ),
    ]
