# Generated by Django 5.1.7 on 2026-02-04 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0001_initial'),  # Use base migration for compatibility
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('context', models.JSONField(default=dict, help_text='Conversation context/memory')),
                ('message_count', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_conversations', to='erp.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MCPConversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MCPMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=20)),
                ('content', models.TextField()),
                ('tool_calls', models.JSONField(default=list, help_text='Tool calls made by AI')),
                ('tool_call_id', models.CharField(blank=True, help_text='ID if this is a tool response', max_length=100)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mcp.mcpconversation')),
            ],
            options={
                'db_table': 'MCPMessage',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MCPProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('google', 'Google (Gemini)'), ('azure', 'Azure OpenAI'), ('ollama', 'Ollama (Local)'), ('custom', 'Custom API')], max_length=20)),
                ('api_key', models.TextField(blank=True, help_text='Encrypted API key')),
                ('api_base_url', models.URLField(blank=True, help_text='Custom API endpoint')),
                ('model_name', models.CharField(default='gpt-4', max_length=100)),
                ('max_tokens', models.IntegerField(default=4096)),
                ('temperature', models.FloatField(default=0.7)),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_providers', to='erp.organization')),
            ],
            options={
                'db_table': 'MCPProvider',
                'ordering': ['-is_default', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='mcpconversation',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcp.mcpprovider'),
        ),
        migrations.CreateModel(
            name='MCPConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('starting', 'Starting'), ('running', 'Running'), ('error', 'Error'), ('stopped', 'Stopped')], default='inactive', max_length=20)),
                ('server_url', models.URLField(blank=True)),
                ('server_port', models.IntegerField(blank=True, null=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('last_request_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('error_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_connection', to='erp.organization')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcp.mcpprovider')),
            ],
            options={
                'db_table': 'MCPConnection',
            },
        ),
        migrations.CreateModel(
            name='MCPTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('inventory', 'Inventory'), ('finance', 'Finance'), ('pos', 'Point of Sale'), ('crm', 'CRM'), ('hr', 'Human Resources'), ('system', 'System'), ('custom', 'Custom')], max_length=20)),
                ('internal_endpoint', models.CharField(max_length=255)),
                ('http_method', models.CharField(default='GET', max_length=10)),
                ('parameters_schema', models.JSONField(default=dict)),
                ('required_permissions', models.JSONField(default=list, help_text='List of permission codes required to use this tool')),
                ('is_active', models.BooleanField(default=True)),
                ('requires_confirmation', models.BooleanField(default=False, help_text='Require user confirmation before execution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tools', to='erp.organization')),
            ],
            options={
                'db_table': 'MCPTool',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MCPRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_type', models.CharField(choices=[('requests_per_minute', 'Requests per Minute'), ('requests_per_hour', 'Requests per Hour'), ('requests_per_day', 'Requests per Day'), ('tokens_per_day', 'Tokens per Day'), ('cost_per_day', 'Cost per Day')], max_length=30)),
                ('limit_value', models.IntegerField()),
                ('current_usage', models.IntegerField(default=0)),
                ('reset_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_rate_limits', to='erp.organization')),
                ('user', models.ForeignKey(blank=True, help_text='If null, applies to entire organization', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MCPRateLimit',
                'unique_together': {('organization', 'user', 'limit_type')},
            },
        ),
        migrations.CreateModel(
            name='MCPUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('endpoint', models.CharField(max_length=255)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost_per_input_token', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('cost_per_output_token', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('response_time_ms', models.IntegerField(null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcp.mcpconversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_usage_logs', to='erp.organization')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcp.mcpprovider')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MCPUsageLog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='MCPUsageLog_organiz_7fe40c_idx'), models.Index(fields=['provider', 'created_at'], name='MCPUsageLog_provide_686e85_idx')],
            },
        ),
    ]
