# Generated by Django 6.0.2 on 2026-02-27 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_user_home_site'),
        ('mcp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('inventory_manager', 'Inventory Manager'), ('finance_specialist', 'Finance Specialist'), ('sales_analyst', 'Sales Analyst'), ('customer_support', 'Customer Support'), ('system_admin', 'System Administrator')], max_length=50)),
                ('persona', models.TextField(help_text='The system prompt/personality of this virtual employee')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('error', 'Error')], default='idle', max_length=20)),
                ('auto_execute', models.BooleanField(default=False, help_text='If true, agent can execute tools without human approval')),
                ('frequency_minutes', models.IntegerField(default=60)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_agents', to='erp.organization')),
                ('provider', models.ForeignKey(blank=True, help_text='Specific AI provider for this agent (uses default if null)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcp.mcpprovider')),
            ],
            options={
                'verbose_name': 'MCP Agent',
                'verbose_name_plural': 'MCP Agents',
                'db_table': 'mcpagent',
            },
        ),
        migrations.CreateModel(
            name='MCPAgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Information'), ('thought', 'Internal Thought'), ('action', 'Action Taken'), ('error', 'Error'), ('decision', 'Decision Made')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Structured data about the action/decision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mcp.mcpagent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'mcpagentlog',
                'ordering': ['-created_at'],
            },
        ),
    ]
