# Generated by Django 5.1.7 on 2026-02-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mcpusagelog',
            new_name='mcpusagelog_organiz_3329df_idx',
            old_name='MCPUsageLog_organiz_7fe40c_idx',
        ),
        migrations.RenameIndex(
            model_name='mcpusagelog',
            new_name='mcpusagelog_provide_5ec7e4_idx',
            old_name='MCPUsageLog_provide_686e85_idx',
        ),
        migrations.AlterField(
            model_name='mcpconnection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcpconnection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcpconversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcpconversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcpmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcpprovider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcpprovider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcpratelimit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcpratelimit',
            name='reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcpratelimit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcptool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcptool',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcpusagelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterModelTable(
            name='mcpconnection',
            table='mcpconnection',
        ),
        migrations.AlterModelTable(
            name='mcpconversation',
            table='mcpconversation',
        ),
        migrations.AlterModelTable(
            name='mcpmessage',
            table='mcpmessage',
        ),
        migrations.AlterModelTable(
            name='mcpprovider',
            table='mcpprovider',
        ),
        migrations.AlterModelTable(
            name='mcpratelimit',
            table='mcpratelimit',
        ),
        migrations.AlterModelTable(
            name='mcptool',
            table='mcptool',
        ),
        migrations.AlterModelTable(
            name='mcpusagelog',
            table='mcpusagelog',
        ),
    ]
