# Generated by Django 6.0.4 on 2026-04-20 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0002_mcpagent_mcpagentlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcpagentlog',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='mcpagentlog',
            name='organization',
        ),
        migrations.DeleteModel(
            name='MCPAgent',
        ),
        migrations.DeleteModel(
            name='MCPAgentLog',
        ),
    ]
