# Generated by Django 6.0.2 on 2026-03-05 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_link_to_po_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='current_verification_level',
            field=models.IntegerField(default=0, help_text='How many verification levels have been completed'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lifecycle_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked'), ('VERIFIED', 'Verified'), ('CONFIRMED', 'Confirmed')], default='OPEN', help_text='Current lifecycle stage', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='policy_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='JSON snapshot of policy/rules at LOCK time for audit trail'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='required_levels_frozen',
            field=models.IntegerField(default=0, help_text='Required levels frozen at LOCK time (immutable)'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='current_verification_level',
            field=models.IntegerField(default=0, help_text='How many verification levels have been completed'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='lifecycle_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked'), ('VERIFIED', 'Verified'), ('CONFIRMED', 'Confirmed')], default='OPEN', help_text='Current lifecycle stage', max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='policy_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='JSON snapshot of policy/rules at LOCK time for audit trail'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='required_levels_frozen',
            field=models.IntegerField(default=0, help_text='Required levels frozen at LOCK time (immutable)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='current_verification_level',
            field=models.IntegerField(default=0, help_text='How many verification levels have been completed'),
        ),
        migrations.AddField(
            model_name='payment',
            name='lifecycle_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked'), ('VERIFIED', 'Verified'), ('CONFIRMED', 'Confirmed')], default='OPEN', help_text='Current lifecycle stage', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='policy_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='JSON snapshot of policy/rules at LOCK time for audit trail'),
        ),
        migrations.AddField(
            model_name='payment',
            name='required_levels_frozen',
            field=models.IntegerField(default=0, help_text='Required levels frozen at LOCK time (immutable)'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='policy_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='JSON snapshot of policy/rules at LOCK time for audit trail'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='required_levels_frozen',
            field=models.IntegerField(default=0, help_text='Required levels frozen at LOCK time (immutable)'),
        ),
    ]
