# Generated by Django 6.0.2 on 2026-03-10 20:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_paymentterm'),
        ('finance', '0017_alter_transactionsequence_unique_together_and_more'),
        ('inventory', '0019_goodsreceipt_branch_inventory_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='OFFICIAL', max_length=20)),
                ('opening_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('opening_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('movement_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('movement_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('closing_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('closing_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('transaction_count', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('is_stale', models.BooleanField(default=False, help_text='Set to True when new JEs are posted — triggers re-computation')),
            ],
            options={
                'db_table': 'account_balance_snapshot',
            },
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('scope', models.CharField(choices=[('OFFICIAL', 'Official'), ('INTERNAL', 'Internal')], default='OFFICIAL', max_length=20)),
                ('source', models.CharField(choices=[('TRANSFER', 'Year-End Transfer'), ('MANUAL', 'Manual Entry'), ('MIGRATION', 'Data Migration')], default='MANUAL', max_length=20)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('amount_currency', models.DecimalField(blank=True, decimal_places=2, help_text='Balance in foreign currency (if multi-currency account)', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'opening_balance',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount allocated from this JE line to this match', max_digits=15)),
                ('is_debit_side', models.BooleanField(default=True, help_text='True if this line is on the debit side of the match')),
            ],
            options={
                'db_table': 'reconciliation_line',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('AUTO', 'Automatic Match'), ('MANUAL', 'Manual Match'), ('PAYMENT', 'Payment Allocation'), ('WRITE_OFF', 'Write-Off'), ('REVERSAL', 'Reversal / Credit Note')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('MATCHED', 'Fully Matched'), ('PARTIAL', 'Partially Matched'), ('BROKEN', 'Broken (requires re-match)')], default='MATCHED', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('partner_type', models.CharField(blank=True, max_length=20, null=True)),
                ('partner_id', models.IntegerField(blank=True, null=True)),
                ('matched_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('write_off_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('unmatched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reconciliation_match',
            },
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='allow_multi_currency',
            field=models.BooleanField(default=False, help_text='If True, multiple currencies can post to this account'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='allow_posting',
            field=models.BooleanField(default=True, help_text='If False, this is a header/parent account — no direct journal entries'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='allow_reconciliation',
            field=models.BooleanField(default=False, help_text='If True, this account supports line-level reconciliation (AR/AP/Bank)'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='class_code',
            field=models.CharField(blank=True, db_index=True, help_text='Universal account class: 1=Asset, 2=Liability, 3=Equity, 4=Revenue, 5=Expense, 6-9=Extended', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coa_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='currency',
            field=models.CharField(blank=True, help_text='Restrict this account to a specific currency (null = org default)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='is_control_account',
            field=models.BooleanField(default=False, help_text='AR/AP control accounts — posting only via subledger'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_coa_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='normal_balance',
            field=models.CharField(blank=True, choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], help_text='Debit or Credit — auto-resolved from type if blank', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='path',
            field=models.CharField(blank=True, db_index=True, help_text='Materialized path (e.g., "1000.1100.1110") — for fast tree queries', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='revaluation_required',
            field=models.BooleanField(default=False, help_text='If True, this account needs FX revaluation at period end'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='subledger_type',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('EMPLOYEE', 'Employee'), ('BANK', 'Bank')], help_text='Links to CRM contacts, employees, or bank accounts', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_coa_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_fiscal_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='is_adjustment_period',
            field=models.BooleanField(default=False, help_text='13th period for year-end audit adjustments'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_fiscal_years', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='closing_journal_entry',
            field=models.ForeignKey(blank=True, help_text='The year-end closing JE that transfers P&L into retained earnings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_fiscal_year', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('FINALIZED', 'Finalized')], default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='currency',
            field=models.CharField(blank=True, help_text='Transaction currency (null = org default)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Rate to convert from transaction currency to org base currency', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='journal_type',
            field=models.CharField(choices=[('GENERAL', 'General Journal'), ('SALES', 'Sales Journal'), ('PURCHASE', 'Purchase Journal'), ('CASH', 'Cash Journal'), ('BANK', 'Bank Journal'), ('INVENTORY', 'Inventory Journal'), ('PAYROLL', 'Payroll Journal'), ('TAX', 'Tax Journal'), ('CLOSING', 'Closing Journal'), ('OPENING', 'Opening Balance Journal'), ('ADJUSTMENT', 'Adjustment Journal')], default='GENERAL', help_text='Classifies the journal for filtering and reporting', max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_id',
            field=models.IntegerField(blank=True, help_text='PK of the source document — prevents duplicate posting', null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_model',
            field=models.CharField(blank=True, help_text='Model class that generated this JE (e.g., Invoice, Order, StockMove)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_module',
            field=models.CharField(blank=True, help_text='Module that generated this JE (e.g., sales, purchases, inventory, pos)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all line credits — updated on post', max_digits=15),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='total_debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all line debits — updated on post', max_digits=15),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='amount_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in foreign currency (debit-credit in that currency)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='cost_center',
            field=models.CharField(blank=True, help_text='Cost center / department code for management accounting', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='currency',
            field=models.CharField(blank=True, help_text='Line-level currency (if different from JE header)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='financial_account',
            field=models.ForeignKey(blank=True, help_text='Physical bank/cash account (for cash flow tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='is_reconciled',
            field=models.BooleanField(default=False, help_text='Set to True when this line is fully matched in reconciliation'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='partner_id',
            field=models.IntegerField(blank=True, help_text='FK to the partner entity (Contact.id or User.id)', null=True),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='partner_type',
            field=models.CharField(blank=True, help_text='CUSTOMER, SUPPLIER, EMPLOYEE, PARTNER — for subledger reporting', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product linked to this line (for COGS/inventory analysis)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='reconciled_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='How much of this line has been reconciled so far', max_digits=15),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='tax_line',
            field=models.ForeignKey(blank=True, help_text='Tax code applied to this line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='finance.taxgroup'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='type',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fiscalperiod',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('SOFT_LOCKED', 'Soft Locked'), ('HARD_LOCKED', 'Hard Locked'), ('CLOSED', 'Closed'), ('FUTURE', 'Future')], default='OPEN', max_length=20),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['organization', 'class_code'], name='chartofacco_organiz_8a6b47_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['organization', 'type'], name='chartofacco_organiz_b882b3_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['organization', 'is_active'], name='chartofacco_organiz_8b07f0_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['path'], name='chartofacco_path_7a6f32_idx'),
        ),
        migrations.AddField(
            model_name='accountbalancesnapshot',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='accountbalancesnapshot',
            name='fiscal_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='finance.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='accountbalancesnapshot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opening_balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='finance.fiscalyear'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='reconciliationline',
            name='journal_entry_line',
            field=models.ForeignKey(help_text='The matched journal entry line', on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_lines', to='finance.journalentryline'),
        ),
        migrations.AddField(
            model_name='reconciliationline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='reconciliationmatch',
            name='account',
            field=models.ForeignKey(help_text='The control/reconcilable account (AR, AP, Bank)', on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_matches', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='reconciliationmatch',
            name='matched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationmatch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='reconciliationmatch',
            name='unmatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmatched_reconciliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationline',
            name='reconciliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.reconciliationmatch'),
        ),
        migrations.AddIndex(
            model_name='accountbalancesnapshot',
            index=models.Index(fields=['organization', 'fiscal_period', 'scope'], name='account_bal_organiz_54abac_idx'),
        ),
        migrations.AddIndex(
            model_name='accountbalancesnapshot',
            index=models.Index(fields=['organization', 'account'], name='account_bal_organiz_1d029d_idx'),
        ),
        migrations.AddIndex(
            model_name='accountbalancesnapshot',
            index=models.Index(fields=['is_stale'], name='account_bal_is_stal_0f7a35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountbalancesnapshot',
            unique_together={('account', 'fiscal_period', 'scope', 'organization')},
        ),
        migrations.AddIndex(
            model_name='openingbalance',
            index=models.Index(fields=['organization', 'fiscal_year'], name='opening_bal_organiz_f2c4ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='openingbalance',
            unique_together={('account', 'fiscal_year', 'scope', 'organization')},
        ),
        migrations.AddIndex(
            model_name='reconciliationmatch',
            index=models.Index(fields=['organization', 'account'], name='reconciliat_organiz_2f6525_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationmatch',
            index=models.Index(fields=['organization', 'status'], name='reconciliat_organiz_dee980_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationmatch',
            index=models.Index(fields=['partner_type', 'partner_id'], name='reconciliat_partner_5a0bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationline',
            index=models.Index(fields=['reconciliation'], name='reconciliat_reconci_8d7017_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationline',
            index=models.Index(fields=['journal_entry_line'], name='reconciliat_journal_2d060b_idx'),
        ),
    ]
