# Generated by Django 6.0.2 on 2026-03-10 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_v2_financial_engine_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='directexpense',
            name='posted_journal_entry',
            field=models.ForeignKey(blank=True, help_text='The JournalEntry generated when this document was posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_source_docs', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='posted_journal_entry',
            field=models.ForeignKey(blank=True, help_text='The JournalEntry generated when this document was posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_source_docs', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='payment',
            name='posted_journal_entry',
            field=models.ForeignKey(blank=True, help_text='The JournalEntry generated when this document was posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_source_docs', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='posted_journal_entry',
            field=models.ForeignKey(blank=True, help_text='The JournalEntry generated when this document was posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_source_docs', to='finance.journalentry'),
        ),
    ]
