# Generated by Django 6.0.2 on 2026-03-10 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_organization_finance_hard_locked_at_and_more'),
        ('finance', '0020_v3_enterprise_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='financial_section',
            field=models.CharField(blank=True, choices=[('BS_ASSET', 'Balance Sheet: Assets'), ('BS_LIABILITY', 'Balance Sheet: Liabilities'), ('BS_EQUITY', 'Balance Sheet: Equity'), ('IS_REVENUE', 'Income Statement: Revenue'), ('IS_EXPENSE', 'Income Statement: Expense')], help_text='Auto-mapping for financial statements', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='is_structure_locked',
            field=models.BooleanField(default=False, help_text='Once locked, this account cannot be deleted or moved in the hierarchy'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='system_role',
            field=models.CharField(blank=True, choices=[('AR_CONTROL', 'Accounts Receivable Control'), ('AP_CONTROL', 'Accounts Payable Control'), ('CASH_ACCOUNT', 'Cash Account'), ('BANK_ACCOUNT', 'Bank Account'), ('REVENUE_CONTROL', 'Revenue Account'), ('COGS_CONTROL', 'Cost of Goods Sold Account'), ('INVENTORY_ASSET', 'Inventory Asset'), ('TAX_PAYABLE', 'Tax Payable'), ('TAX_RECEIVABLE', 'Tax Receivable'), ('RETAINED_EARNINGS', 'Retained Earnings'), ('P_L_SUMMARY', 'Current Year Profit/Loss'), ('OPENING_BALANCE_OFFSET', 'Opening Balance Offset'), ('ROUNDING_DIFF', 'Rounding Difference'), ('EXCHANGE_DIFF', 'Exchange Difference'), ('SUSPENSE', 'Suspense/Clearing Account')], help_text='Enterprise role for programmatic engine lookups', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='template_origin',
            field=models.CharField(blank=True, help_text='Original template key (e.g., IFRS_COA)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='template_version',
            field=models.CharField(blank=True, help_text='Template version string', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['organization', 'system_role'], name='chartofacco_organiz_af93d7_idx'),
        ),
    ]
