# Generated by Django 6.0.3 on 2026-04-01 11:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_rename_erp_auditlo_organization__3bae30_idx_erp_auditlo_tenant__3bae30_idx_and_more'),
        ('finance', '0045_financialaccount_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryTaxTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2 or alpha-3 code (e.g. CI, FR, US)', max_length=3, unique=True)),
                ('country_name', models.CharField(help_text='Human-readable country name', max_length=100)),
                ('currency_code', models.CharField(default='USD', help_text='Default currency ISO code', max_length=3)),
                ('org_policy_defaults', models.JSONField(blank=True, default=dict, help_text='Default values for OrgTaxPolicy fields when creating a new policy for this country. Keys must match OrgTaxPolicy field names.')),
                ('document_requirements', models.JSONField(blank=True, default=list, help_text='Default document requirements for counterparty profiles. Each entry: {"type": "TAX_ID", "label": "...", "required": true, "renewable": false, "renewal_months": null}')),
                ('counterparty_presets', models.JSONField(blank=True, default=list, help_text='Default counterparty tax profiles to seed for this country. Each entry: {"name": "...", "vat_registered": true, ...}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Country Tax Template',
                'verbose_name_plural': 'Country Tax Templates',
                'db_table': 'country_tax_template',
                'ordering': ['country_code'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name: Cash, Orange Money, Wave...', max_length=100)),
                ('code', models.CharField(help_text='Unique code per org: CASH, OM, WAVE...', max_length=30)),
                ('icon', models.CharField(blank=True, default='', help_text='Lucide icon name: banknote, smartphone, credit-card...', max_length=50)),
                ('color', models.CharField(blank=True, default='', help_text='Hex color for UI badge', max_length=20)),
                ('is_system', models.BooleanField(default=False, help_text='System-seeded method (cannot be deleted)')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'finance_payment_method',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='chartofaccount',
            name='coa_org_type_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='chartofaccount',
            name='coa_org_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='chartofaccount',
            name='coa_org_parent_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_org_date_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_org_contact_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_org_due_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_org_type_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoiceline',
            name='invoice_line_org_inv_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='journal_org_date_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='journal_org_fiscal_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='journal_org_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='loaninstallment',
            name='loan_inst_org_loan_paid_idx',
        ),
        migrations.RemoveIndex(
            model_name='loaninstallment',
            name='loan_inst_org_date_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_org_date_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_org_contact_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_org_type_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentallocation',
            name='payment_alloc_org_inv_pay_idx',
        ),
        migrations.RenameIndex(
            model_name='accountbalancesnapshot',
            new_name='account_bal_organiz_54abac_idx',
            old_name='account_bal_organization__c281f2_idx',
        ),
        migrations.RenameIndex(
            model_name='accountbalancesnapshot',
            new_name='account_bal_organiz_1d029d_idx',
            old_name='account_bal_organization__a38ba6_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatement',
            new_name='bank_statem_tenant__6a76fc_idx',
            old_name='bank_stmt_org_acct_date_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatement',
            new_name='bank_statem_tenant__48f269_idx',
            old_name='bank_stmt_org_status_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatementline',
            new_name='bank_statem_tenant__4074b1_idx',
            old_name='bank_line_org_stmt_match_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatementline',
            new_name='bank_statem_tenant__d01167_idx',
            old_name='bank_line_org_date_idx',
        ),
        migrations.RenameIndex(
            model_name='budget',
            new_name='finance_bud_organiz_3e6611_idx',
            old_name='finance_bud_organization__cc5c16_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='chartofacco_organiz_8a6b47_idx',
            old_name='chartofacco_organization__9dbbcd_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='chartofacco_organiz_b882b3_idx',
            old_name='chartofacco_organization__f942bd_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='chartofacco_organiz_8b07f0_idx',
            old_name='chartofacco_organization__425576_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='chartofacco_organiz_af93d7_idx',
            old_name='chartofacco_organization__0ff896_idx',
        ),
        migrations.RenameIndex(
            model_name='currencyrevaluation',
            new_name='finance_cur_organiz_ab65da_idx',
            old_name='finance_cur_organization__f78f72_idx',
        ),
        migrations.RenameIndex(
            model_name='exchangerate',
            new_name='finance_exc_organiz_2b0a91_idx',
            old_name='finance_exc_organization__509586_idx',
        ),
        migrations.RenameIndex(
            model_name='forensicauditlog',
            new_name='forensicaud_organiz_15cd02_idx',
            old_name='forensicaud_organization__e91fcc_idx',
        ),
        migrations.RenameIndex(
            model_name='forensicauditlog',
            new_name='forensicaud_organiz_f6ab40_idx',
            old_name='forensicaud_organization__a96361_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoice_tenant__622a8f_idx',
            old_name='invoice_organization__622a8f_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoice_tenant__5ad5ff_idx',
            old_name='invoice_organization__5ad5ff_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoice_tenant__54699b_idx',
            old_name='invoice_organization__54699b_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoice_tenant__e6fe4b_idx',
            old_name='invoice_organization__e6fe4b_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='journalentr_organiz_5c542f_idx',
            old_name='journalentr_organization__8a56b4_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='journalentr_organiz_339014_idx',
            old_name='journalentr_organization__2aaed0_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='journalentr_organiz_cdf611_idx',
            old_name='journalentr_organization__1f43db_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentryline',
            new_name='journalentr_organiz_d847f4_idx',
            old_name='journalentr_organization__655ba8_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentryline',
            new_name='journalentr_organiz_ebb715_idx',
            old_name='journalentr_organization__d96f42_idx',
        ),
        migrations.RenameIndex(
            model_name='openingbalance',
            new_name='opening_bal_organiz_f2c4ba_idx',
            old_name='opening_bal_organization__e1cf48_idx',
        ),
        migrations.RenameIndex(
            model_name='postingrulehistory',
            new_name='finance_pos_organiz_0710a1_idx',
            old_name='prh_org_event_idx',
        ),
        migrations.RenameIndex(
            model_name='postingrulehistory',
            new_name='finance_pos_organiz_6be4cc_idx',
            old_name='prh_org_time_idx',
        ),
        migrations.RenameIndex(
            model_name='reconciliationmatch',
            new_name='reconciliat_organiz_2f6525_idx',
            old_name='reconciliat_organization__d70831_idx',
        ),
        migrations.RenameIndex(
            model_name='reconciliationmatch',
            new_name='reconciliat_organiz_dee980_idx',
            old_name='reconciliat_organization__0a19cf_idx',
        ),
        migrations.RenameIndex(
            model_name='reconciliationsession',
            new_name='reconciliat_tenant__9afff2_idx',
            old_name='recon_sess_org_stmt_idx',
        ),
        migrations.RenameIndex(
            model_name='reconciliationsession',
            new_name='reconciliat_tenant__41c198_idx',
            old_name='recon_sess_org_status_idx',
        ),
        migrations.RenameIndex(
            model_name='recurringjournaltemplate',
            new_name='finance_rec_organiz_c86bac_idx',
            old_name='finance_rec_organization__d7d68e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='coatemplatemigrationmap',
            unique_together={('source_template', 'target_template', 'source_account_code', 'target_account_code')},
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='bankstatementline',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bankstatementline',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='reconciliationsession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reconciliationsession',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='amortizationschedule',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='asset',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='customerbalance',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='deferredexpense',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='supplierbalance',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='accountbalancesnapshot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='calculated_closing',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='total_credits',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='total_debits',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='debit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='barcodesettings',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='coamigrationaccountplan',
            name='allocation_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% of source balance allocated to this target (1:N splits)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='coamigrationaccountplan',
            name='balance_at_migration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net balance as of session.migration_date', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='coamigrationaccountplan',
            name='children_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of direct child accounts'),
        ),
        migrations.AlterField(
            model_name='coamigrationaccountplan',
            name='execution_notes',
            field=models.TextField(blank=True, default='', help_text='Engine notes: rename details, merge target, split JE ref, etc.'),
        ),
        migrations.AlterField(
            model_name='coamigrationaccountplan',
            name='financial_account_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of FinancialAccounts linked to this account'),
        ),
        migrations.AlterField(
            model_name='coamigrationaccountplan',
            name='group_key',
            field=models.CharField(blank=True, default='', help_text='Groups related split rows together', max_length=50),
        ),
        migrations.AlterField(
            model_name='coamigrationaccountplan',
            name='has_financial_accounts',
            field=models.BooleanField(default=False, help_text='True if FinancialAccount references exist — must remap first'),
        ),
        migrations.AlterField(
            model_name='coamigrationaccountplan',
            name='has_posting_rules',
            field=models.BooleanField(default=False, help_text='True if PostingRule references exist — must remap first'),
        ),
        migrations.AlterField(
            model_name='coamigrationaccountplan',
            name='historically_locked',
            field=models.BooleanField(default=False, help_text='True if ANY journal line exists — cannot hard-delete'),
        ),
        migrations.AlterField(
            model_name='coamigrationaccountplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coamigrationaccountplan',
            name='is_executed',
            field=models.BooleanField(default=False, help_text='True after this account has been migrated'),
        ),
        migrations.AlterField(
            model_name='coamigrationaccountplan',
            name='is_mode_overridden',
            field=models.BooleanField(default=False, help_text='True if user manually changed the auto-assigned mode'),
        ),
        migrations.AlterField(
            model_name='coamigrationaccountplan',
            name='journal_line_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of JournalEntryLines referencing this account'),
        ),
        migrations.AlterField(
            model_name='coamigrationaccountplan',
            name='migration_mode',
            field=models.CharField(choices=[('RENAME_IN_PLACE', 'Rename In Place — same row, code+name change'), ('REPOINT_AND_ARCHIVE', 'Repoint & Archive — remap refs, archive old'), ('MERGE_FORWARD', 'Merge Forward — N:1, archive sources'), ('SPLIT_BY_OPENING_ENTRY', 'Split by Opening Entry — 1:N, opening JE'), ('DELETE_UNUSED', 'Delete Unused — zero journals, safe to remove'), ('MANUAL_REVIEW', 'Manual Review — needs human decision')], default='MANUAL_REVIEW', help_text='Engine-assigned or user-overridden migration action', max_length=30),
        ),
        migrations.AlterField(
            model_name='coamigrationaccountplan',
            name='posting_rule_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of PostingRules mapping to this account'),
        ),
        migrations.AlterField(
            model_name='coamigrationaccountplan',
            name='session',
            field=models.ForeignKey(help_text='Parent migration session', on_delete=django.db.models.deletion.CASCADE, related_name='account_plans', to='finance.coamigrationsession'),
        ),
        migrations.AlterField(
            model_name='coamigrationaccountplan',
            name='source_account',
            field=models.ForeignKey(blank=True, help_text='Source COA account being migrated (null for target-only accounts)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_plans_as_source', to='finance.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='coamigrationaccountplan',
            name='target_account_code',
            field=models.CharField(blank=True, default='', help_text='Target account code from template mapping', max_length=20),
        ),
        migrations.AlterField(
            model_name='coamigrationaccountplan',
            name='target_account_name',
            field=models.CharField(blank=True, default='', help_text='Target account name from template mapping', max_length=200),
        ),
        migrations.AlterField(
            model_name='coamigrationsession',
            name='dry_run_report',
            field=models.JSONField(blank=True, help_text='Full impact analysis: per-account balance, journal count, refs, planned action', null=True),
        ),
        migrations.AlterField(
            model_name='coamigrationsession',
            name='error_report',
            field=models.JSONField(blank=True, help_text='Blocker details if execution failed or was rolled back', null=True),
        ),
        migrations.AlterField(
            model_name='coamigrationsession',
            name='execution_report',
            field=models.JSONField(blank=True, help_text='Post-execution summary: accounts renamed, merged, split, deleted', null=True),
        ),
        migrations.AlterField(
            model_name='coamigrationsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coamigrationsession',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='True during EXECUTING — org finance freeze active'),
        ),
        migrations.AlterField(
            model_name='coamigrationsession',
            name='migration_date',
            field=models.DateTimeField(blank=True, help_text='Cutover datetime — balances computed as of this date', null=True),
        ),
        migrations.AlterField(
            model_name='coamigrationsession',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='coamigrationsession',
            name='phase_a_completed_at',
            field=models.DateTimeField(blank=True, help_text='Structural remap completion timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='coamigrationsession',
            name='phase_b_completed_at',
            field=models.DateTimeField(blank=True, help_text='Split journal creation completion timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='coamigrationsession',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft — plan under construction'), ('DRY_RUN', 'Dry-Run — impact report generated'), ('APPROVED', 'Approved — awaiting execution'), ('EXECUTING', 'Executing — migration in progress'), ('COMPLETED', 'Completed — migration successful'), ('FAILED', 'Failed — migration aborted with errors'), ('ROLLED_BACK', 'Rolled Back — reverted to pre-migration state'), ('PARTIAL', 'Partial — Phase A done, Phase B pending/failed')], default='DRAFT', help_text='Current lifecycle stage', max_length=20),
        ),
        migrations.AlterField(
            model_name='coamigrationsession',
            name='validation_report',
            field=models.JSONField(blank=True, help_text='Post-execution: referential, accounting, functional, governance checks', null=True),
        ),
        migrations.AlterField(
            model_name='coamigrationsession',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Monotonic version — prevents duplicate runs'),
        ),
        migrations.AlterField(
            model_name='coatemplate',
            name='accounts',
            field=models.JSONField(default=list, help_text='Full nested account tree as JSON array (legacy, use template_accounts for queries)'),
        ),
        migrations.AlterField(
            model_name='coatemplateaccount',
            name='semantic_group',
            field=models.CharField(blank=True, choices=[('CASH_ON_HAND', 'Cash on Hand'), ('BANK_CURRENT', 'Bank Current Account'), ('BANK_SAVINGS', 'Bank Savings Account'), ('BANK_FOREIGN', 'Foreign Currency Bank Account'), ('VAT_STANDARD', 'VAT Standard Rate'), ('VAT_REDUCED', 'VAT Reduced Rate'), ('VAT_ZERO', 'VAT Zero Rate / Exempt'), ('VAT_IMPORT', 'VAT on Imports'), ('WHT_SERVICES', 'WHT on Services'), ('WHT_SALARY', 'WHT on Salary'), ('RECEIVABLE_TRADE', 'Trade Receivables'), ('RECEIVABLE_OTHER', 'Other Receivables'), ('RECEIVABLE_RELATED', 'Related Party Receivables'), ('PAYABLE_TRADE', 'Trade Payables'), ('PAYABLE_OTHER', 'Other Payables'), ('PAYABLE_RELATED', 'Related Party Payables'), ('REVENUE_GOODS', 'Revenue from Goods'), ('REVENUE_SERVICES', 'Revenue from Services'), ('REVENUE_OTHER', 'Other Operating Revenue'), ('COGS_MATERIALS', 'Cost of Materials'), ('COGS_DIRECT_LABOR', 'Direct Labor Costs'), ('COGS_OVERHEAD', 'Manufacturing Overhead'), ('EXPENSE_OPERATING', 'Operating Expenses'), ('EXPENSE_ADMIN', 'Administrative Expenses'), ('EXPENSE_SELLING', 'Selling & Distribution'), ('EXPENSE_FINANCIAL', 'Financial Expenses'), ('INVENTORY_RAW', 'Raw Materials'), ('INVENTORY_WIP', 'Work in Progress'), ('INVENTORY_FINISHED', 'Finished Goods'), ('INVENTORY_MERCHANDISE', 'Merchandise')], help_text='Fine-grained semantic sub-classification for Level 4+ matching', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='coatemplatemigrationmap',
            name='notes',
            field=models.CharField(blank=True, default='', help_text='Optional notes', max_length=200),
        ),
        migrations.AlterField(
            model_name='consolidationentity',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='consolidationgroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='consolidationline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='consolidationrun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='contextualpostingrule',
            name='account',
            field=models.ForeignKey(help_text='Override GL account for this context', on_delete=django.db.models.deletion.PROTECT, related_name='contextual_posting_rules', to='finance.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='contextualpostingrule',
            name='base_rule',
            field=models.ForeignKey(help_text='The base posting rule this overrides', on_delete=django.db.models.deletion.CASCADE, related_name='contextual_overrides', to='finance.postingrule'),
        ),
        migrations.AlterField(
            model_name='contextualpostingrule',
            name='context_value',
            field=models.CharField(help_text='Value to match: warehouse code, branch ID, category slug, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='contextualpostingrule',
            name='priority',
            field=models.SmallIntegerField(default=0, help_text='Higher priority wins when multiple contexts match'),
        ),
        migrations.AlterField(
            model_name='counterpartytaxprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='counterpartytaxprofile',
            name='required_documents',
            field=models.JSONField(blank=True, default=list, help_text='Structured list of document requirements. Each entry: {"type": "NCC", "label": "Tax ID Certificate", "required": true, "renewable": false, "renewal_months": null}'),
        ),
        migrations.AlterField(
            model_name='counterpartytaxprofile',
            name='state_code',
            field=models.CharField(blank=True, help_text='State/province/region code for sub-national taxes (e.g. CA, ON, BW)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='currencyrevaluation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='currencyrevaluationline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='customtaxrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='financialaccountcategory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='financialevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='fiscalperiod',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='forensicauditlog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='gatewayconfig',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='intercompanyrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amortization_method',
            field=models.CharField(choices=[('REDUCING_BALANCE', 'Reducing Balance'), ('FLAT_RATE', 'Flat Rate'), ('BALLOON', 'Balloon Payment'), ('INTEREST_ONLY', 'Interest Only')], default='REDUCING_BALANCE', max_length=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='disbursement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='loaninstallment',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='loaninstallment',
            name='installment_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='loaninstallment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='openingbalance',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='orgtaxpolicy',
            name='airsi_account',
            field=models.ForeignKey(blank=True, help_text='AIRSI withholding: LIABILITY if non-refundable, ASSET if RECOVER', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_policy_airsi', to='finance.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='orgtaxpolicy',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='orgtaxpolicy',
            name='vat_collected_account',
            field=models.ForeignKey(blank=True, help_text='Output VAT liability on sales invoices (TVA Collectée)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_policy_vat_collected', to='finance.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='orgtaxpolicy',
            name='vat_recoverable_account',
            field=models.ForeignKey(blank=True, help_text='Input VAT asset on purchases (TVA Récupérable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_policy_vat_recoverable', to='finance.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='periodictaxaccrual',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='postingrule',
            name='module',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchases', 'Purchases'), ('inventory', 'Inventory'), ('payments', 'Payments'), ('tax', 'Tax Engine'), ('treasury', 'Finance / Treasury'), ('assets', 'Fixed Assets'), ('equity', 'Equity & Capital'), ('adjustment', 'Adjustments'), ('automation', 'Automation'), ('suspense', 'Suspense'), ('partners', 'Partners'), ('fixedAssets', 'Fixed Assets (legacy)'), ('fx', 'FX / Revaluation (legacy)'), ('payroll', 'Payroll')], default='sales', help_text='Module this rule belongs to (derived from event_code prefix)', max_length=20),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='reconciliationline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='reconciliationmatch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='reconciliationsession',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='recurringjournalexecution',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='recurringjournalline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='recurringjournaltemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='reportdefinition',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='reportexecution',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='taxjurisdictionrule',
            name='country_code',
            field=models.CharField(db_index=True, help_text='ISO 3166-1 alpha-2/3 country code this rule applies to', max_length=3),
        ),
        migrations.AlterField(
            model_name='taxjurisdictionrule',
            name='effective_from',
            field=models.DateField(blank=True, help_text='Date this rule becomes effective', null=True),
        ),
        migrations.AlterField(
            model_name='taxjurisdictionrule',
            name='effective_to',
            field=models.DateField(blank=True, help_text='Date this rule expires (null = no expiry)', null=True),
        ),
        migrations.AlterField(
            model_name='taxjurisdictionrule',
            name='is_system_preset',
            field=models.BooleanField(default=False, help_text='True = seeded by system, not org-specific'),
        ),
        migrations.AlterField(
            model_name='taxjurisdictionrule',
            name='name',
            field=models.CharField(help_text='Descriptive name (e.g. "Côte d\'Ivoire Domestic VAT", "US-CA Sales Tax")', max_length=200),
        ),
        migrations.AlterField(
            model_name='taxjurisdictionrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='taxjurisdictionrule',
            name='place_of_supply_mode',
            field=models.CharField(choices=[('ORIGIN', 'Tax based on seller location'), ('DESTINATION', 'Tax based on buyer/delivery location'), ('REVERSE_CHARGE', 'Buyer self-assesses (B2B cross-border)')], default='ORIGIN', help_text="How to determine which jurisdiction's rate applies", max_length=20),
        ),
        migrations.AlterField(
            model_name='taxjurisdictionrule',
            name='priority',
            field=models.IntegerField(default=100, help_text='Higher priority rules override lower ones for same jurisdiction'),
        ),
        migrations.AlterField(
            model_name='taxjurisdictionrule',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Standard tax rate for this jurisdiction (e.g. 0.18 for 18%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='taxjurisdictionrule',
            name='region_code',
            field=models.CharField(blank=True, help_text='State/province/region code for sub-national taxes (e.g. CA, ON, BW)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taxjurisdictionrule',
            name='registration_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Revenue threshold requiring tax registration (marketplace nexus)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='taxjurisdictionrule',
            name='reverse_charge_allowed',
            field=models.BooleanField(default=False, help_text='True if B2B cross-border reverse charge is available'),
        ),
        migrations.AlterField(
            model_name='taxjurisdictionrule',
            name='zero_rate_export',
            field=models.BooleanField(default=True, help_text='True if exports to this jurisdiction are zero-rated'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='transactionsequence',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='zatcaconfig',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='document_url',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='verified_by',
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('code', 'organization')},
        ),
    ]
