# Generated by Django 6.0.3 on 2026-04-02 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_tax_engine_phase1'),
        ('erp', '0025_rename_erp_auditlo_organization__3bae30_idx_erp_auditlo_tenant__3bae30_idx_and_more'),
        ('finance', '0046_country_tax_template'),
        ('pos', '0074_snapshot_governance_expansion'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrytaxtemplate',
            name='bad_debt_recovery_months',
            field=models.PositiveIntegerField(default=12, help_text='Months after invoice due date before bad debt VAT claim is eligible'),
        ),
        migrations.AddField(
            model_name='countrytaxtemplate',
            name='gift_vat_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Value above which gifts/samples trigger output VAT', max_digits=15),
        ),
        migrations.AddField(
            model_name='countrytaxtemplate',
            name='self_supply_vat_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum value for self-supply VAT to apply (auto-livraison)', max_digits=15),
        ),
        migrations.AddField(
            model_name='countrytaxtemplate',
            name='vat_on_advance_payment',
            field=models.BooleanField(default=False, help_text='Whether VAT is due when advance payment/deposit is received'),
        ),
        migrations.AlterField(
            model_name='countrytaxtemplate',
            name='org_policy_defaults',
            field=models.JSONField(blank=True, default=list, help_text='Array of org tax policy presets for this country. Each entry: {"name": "Standard VAT", "vat_output_enabled": true, ...}. Keys must match OrgTaxPolicy field names.'),
        ),
        migrations.CreateModel(
            name='BadDebtVATClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_vat_amount', models.DecimalField(decimal_places=2, help_text='The output VAT amount originally declared on this invoice', max_digits=15)),
                ('original_invoice_amount', models.DecimalField(decimal_places=2, help_text='The total invoice amount (TTC)', max_digits=15)),
                ('vat_rate', models.DecimalField(decimal_places=4, help_text='VAT rate at time of original invoice', max_digits=7)),
                ('currency_code', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('ELIGIBLE', 'Eligible — awaiting claim'), ('CLAIMED', 'Claimed — submitted to tax authority'), ('RECOVERED', 'Recovered — VAT refunded/credited'), ('REJECTED', 'Rejected — claim denied'), ('REVERSED', 'Reversed — customer paid after claim')], default='ELIGIBLE', max_length=12)),
                ('eligible_date', models.DateField(blank=True, help_text='Date when claim becomes eligible (invoice_due_date + recovery_months)', null=True)),
                ('claim_date', models.DateField(blank=True, help_text='Date when claim was actually submitted', null=True)),
                ('recovery_date', models.DateField(blank=True, help_text='Date when VAT was recovered/refunded', null=True)),
                ('recovered_amount', models.DecimalField(decimal_places=2, default=0, help_text='Actual amount recovered (may differ from original)', max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('claim_journal_entry', models.ForeignKey(blank=True, help_text='Journal entry created when claim is filed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bad_debt_claims', to='finance.journalentry')),
                ('contact', models.ForeignKey(blank=True, help_text='The defaulting customer/client', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bad_debt_claims', to='crm.contact')),
                ('invoice', models.ForeignKey(help_text='The unpaid invoice for which VAT recovery is claimed', on_delete=django.db.models.deletion.PROTECT, related_name='bad_debt_claims', to='finance.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('reversal_journal_entry', models.ForeignKey(blank=True, help_text='Journal entry if customer pays after claim (reversal)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bad_debt_reversals', to='finance.journalentry')),
            ],
            options={
                'verbose_name': 'Bad Debt VAT Claim',
                'db_table': 'bad_debt_vat_claim',
                'ordering': ['-eligible_date'],
            },
        ),
        migrations.CreateModel(
            name='ImportDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_number', models.CharField(blank=True, default='', help_text='Customs declaration number / reference', max_length=100)),
                ('origin_country', models.CharField(default='', help_text='Country of origin (ISO 3166-1)', max_length=3)),
                ('destination_country', models.CharField(default='', help_text='Import destination country', max_length=3)),
                ('declaration_date', models.DateField(blank=True, help_text='Date of customs assessment', null=True)),
                ('clearance_date', models.DateField(blank=True, help_text='Date goods were released from customs', null=True)),
                ('fob_value', models.DecimalField(decimal_places=2, default=0, help_text='Free On Board value (goods cost at origin)', max_digits=15)),
                ('freight_cost', models.DecimalField(decimal_places=2, default=0, help_text='Shipping/freight cost', max_digits=15)),
                ('insurance_cost', models.DecimalField(decimal_places=2, default=0, help_text='Insurance cost', max_digits=15)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('customs_duty_rate', models.DecimalField(decimal_places=4, default=0, help_text='Customs duty rate (e.g., 0.2000 for 20%)', max_digits=7)),
                ('customs_duty_amount', models.DecimalField(decimal_places=2, default=0, help_text='Customs duty amount (calculated or overridden)', max_digits=15)),
                ('customs_duty_treatment', models.CharField(choices=[('CAPITALIZE', 'Capitalize into inventory cost'), ('EXPENSE', 'Expense to P&L')], default='CAPITALIZE', help_text='How customs duties affect cost', max_length=20)),
                ('import_vat_rate', models.DecimalField(decimal_places=4, default=0, help_text='Import VAT rate (e.g., 0.1800 for 18%)', max_digits=7)),
                ('import_vat_amount', models.DecimalField(decimal_places=2, default=0, help_text='Import VAT amount', max_digits=15)),
                ('import_vat_base', models.CharField(choices=[('CIF', 'VAT on CIF value only'), ('CIF_PLUS_DUTY', 'VAT on CIF + customs duty')], default='CIF_PLUS_DUTY', help_text='What the import VAT is calculated on', max_length=20)),
                ('import_vat_recoverable', models.BooleanField(default=True, help_text='Can this import VAT be recovered in VAT declaration?')),
                ('other_charges', models.JSONField(blank=True, default=list, help_text='Additional charges: [{name, amount, capitalize}]. Examples: inspection, port, handling')),
                ('other_charges_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ASSESSED', 'Assessed by customs'), ('PAID', 'Duties & VAT paid'), ('CLEARED', 'Goods cleared'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Journal entry recording customs duties and import VAT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_declarations', to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('purchase_order', models.ForeignKey(blank=True, help_text='The purchase order for the imported goods', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_declarations', to='pos.purchaseorder')),
            ],
            options={
                'verbose_name': 'Import Declaration',
                'db_table': 'import_declaration',
                'ordering': ['-declaration_date'],
            },
        ),
        migrations.CreateModel(
            name='WithholdingTaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(default='', help_text='Country where this withholding rule applies (ISO 3166-1)', max_length=3)),
                ('name', models.CharField(help_text='e.g. "Lebanon Services WHT 7.5%", "AIRSI 20%"', max_length=200)),
                ('tax_type', models.CharField(choices=[('INCOME', 'Income Tax Withholding'), ('VAT', 'VAT Withholding'), ('PROFESSIONAL', 'Professional Tax'), ('SERVICES', 'Services Withholding'), ('GOODS', 'Goods Withholding'), ('FOREIGN', 'Foreign Payment Withholding'), ('CUSTOM', 'Custom')], default='INCOME', max_length=20)),
                ('applies_to', models.CharField(choices=[('PURCHASES', 'On purchases from this counterparty'), ('SALES', 'On sales to this counterparty'), ('BOTH', 'Both purchases and sales')], default='PURCHASES', max_length=12)),
                ('rate', models.DecimalField(decimal_places=4, default=0, help_text='Withholding rate as decimal (e.g., 0.0750 for 7.5%)', max_digits=7)),
                ('threshold_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum transaction amount before withholding applies (0 = always)', max_digits=15)),
                ('certificate_required', models.BooleanField(default=True, help_text='Counterparty must provide withholding tax certificate for reconciliation')),
                ('auto_generate_certificate', models.BooleanField(default=False, help_text='System auto-generates withholding certificate for the counterparty')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=12)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('counterparty_profile', models.ForeignKey(blank=True, help_text='If set, applies only to contacts with this profile. If null, applies to all.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withholding_rules', to='finance.counterpartytaxprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'verbose_name': 'Withholding Tax Rule',
                'db_table': 'withholding_tax_rule',
                'ordering': ['-created_at'],
            },
        ),
    ]
