# Generated by Django 6.0.4 on 2026-04-24 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_remove_approvalrule_organization_and_more'),
        ('finance', '0067_alter_coatemplate_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalPeriodCloseSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('OFFICIAL', 'Official'), ('INTERNAL', 'Internal')], max_length=10)),
                ('movement_debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('movement_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('je_count', models.PositiveIntegerField(default=0)),
                ('je_lines_count', models.PositiveIntegerField(default=0)),
                ('unique_accounts_touched', models.PositiveIntegerField(default=0)),
                ('trial_balance', models.JSONField(default=list)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 over canonical payload', max_length=64, null=True)),
                ('prev_hash', models.CharField(blank=True, help_text='content_hash of the prior snapshot (any period or year) per org', max_length=64, null=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fp_close_snapshots_captured', to=settings.AUTH_USER_MODEL)),
                ('fiscal_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_snapshots', to='finance.fiscalperiod')),
                ('organization', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'finance_fp_close_snapshot',
                'indexes': [models.Index(fields=['organization', 'fiscal_period'], name='finance_fp__tenant__9052b7_idx'), models.Index(fields=['fiscal_period', 'scope'], name='finance_fp__fiscal__550dde_idx')],
                'constraints': [models.UniqueConstraint(fields=('fiscal_period', 'scope'), name='fp_close_snapshot_uniq_period_scope')],
            },
        ),
    ]
