# Generated by Django 6.0.4 on 2026-04-24 22:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_remove_approvalrule_organization_and_more'),
        ('finance', '0068_fiscalperiodclosesnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DunningReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField(db_index=True, help_text='FK to CRM Contact — decoupled to avoid app import cycle')),
                ('contact_name', models.CharField(help_text='Denormalized at send time — survives contact rename', max_length=255)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1 — Friendly reminder'), (2, 'Level 2 — Formal notice'), (3, 'Level 3 — Final demand'), (4, 'Legal escalation')], default=1)),
                ('method', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('POST', 'Postal mail'), ('CALL', 'Phone call'), ('PORTAL', 'Client portal notification')], default='EMAIL', max_length=10)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered (confirmed)'), ('FAILED', 'Failed to deliver'), ('CANCELLED', 'Cancelled'), ('ACKNOWLEDGED', 'Customer acknowledged')], default='QUEUED', max_length=20)),
                ('amount_overdue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('oldest_invoice_days', models.PositiveIntegerField(default=0, help_text='Age (days past due) of the oldest overdue invoice at send time')),
                ('invoices_referenced', models.JSONField(default=list, help_text='Snapshot of invoice IDs + amounts at send time')),
                ('subject', models.CharField(blank=True, default='', max_length=300)),
                ('body', models.TextField(blank=True, default='', help_text='Rendered body at send time — preserved for audit')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal ops notes (not sent to customer)')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_ref', models.CharField(blank=True, default='', help_text='Provider message ID (e.g. SES message-id) for correlation', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dunning_reminders_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_dunning_reminder',
                'ordering': ['-sent_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'contact_id'], name='finance_dun_tenant__f13cbc_idx'), models.Index(fields=['organization', 'level'], name='finance_dun_tenant__0428cb_idx'), models.Index(fields=['organization', 'status'], name='finance_dun_tenant__77d062_idx'), models.Index(fields=['organization', 'sent_at'], name='finance_dun_tenant__bfc882_idx')],
            },
        ),
    ]
