# Generated by Django 6.0.4 on 2026-04-26 15:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_remove_approvalrule_organization_and_more'),
        ('finance', '0070_chartofaccount_is_internal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRatePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('SPOT', 'Spot Rate'), ('AVERAGE', 'Monthly Average'), ('CLOSING', 'Period Closing Rate')], default='SPOT', max_length=20)),
                ('provider', models.CharField(choices=[('MANUAL', 'Manual entry only'), ('ECB', 'European Central Bank (free, daily, EUR-base)'), ('FIXER', 'Fixer.io (API key required)'), ('OPENEXCHANGERATES', 'OpenExchangeRates.org (API key required)')], default='MANUAL', max_length=30)),
                ('provider_config', models.JSONField(blank=True, default=dict, help_text='Provider-specific config (e.g. api_key, endpoint override).')),
                ('auto_sync', models.BooleanField(default=False, help_text='If True, the daily cron sync command writes a fresh rate each run. False = manual / on-demand only.')),
                ('multiplier', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Multiply the fetched provider rate by this factor before saving. Example: 1.03 for a 3% spread above official.', max_digits=10)),
                ('markup_pct', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Additional percentage adjustment applied after multiplier (0.5 = +0.5%). Useful when bank charges a fixed % spread.', max_digits=6)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, help_text='OK / FAIL / SKIPPED — see last_sync_error for detail.', max_length=20, null=True)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_policies_from', to='finance.currency')),
                ('organization', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_policies_to', to='finance.currency')),
            ],
            options={
                'db_table': 'finance_currency_rate_policy',
                'indexes': [models.Index(fields=['organization', 'auto_sync'], name='finance_cur_tenant__d81c58_idx')],
                'unique_together': {('organization', 'from_currency', 'to_currency', 'rate_type')},
            },
        ),
    ]
