# Generated by Django 6.0.4 on 2026-04-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0075_revaluation_overhaul'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='digital_config',
            field=models.JSONField(blank=True, default=dict, help_text='Provider-specific config: api_key, webhook_url, merchant_id, etc.'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='digital_provider',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('mtn_momo', 'MTN MoMo'), ('custom', 'Custom API')], default='', help_text='Payment gateway provider (inherited from category or overridden)', max_length=30),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='has_account_book',
            field=models.BooleanField(default=False, help_text='Whether this account has a dedicated ledger book'),
        ),
        migrations.AddField(
            model_name='financialaccountcategory',
            name='default_has_account_book',
            field=models.BooleanField(default=False, help_text='New child accounts inherit this account book setting'),
        ),
        migrations.AddField(
            model_name='financialaccountcategory',
            name='default_pos_enabled',
            field=models.BooleanField(default=False, help_text='New child accounts inherit this POS visibility setting'),
        ),
        migrations.AddField(
            model_name='financialaccountcategory',
            name='digital_provider',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('mtn_momo', 'MTN MoMo'), ('custom', 'Custom API')], default='', help_text='Default digital provider for child accounts (Stripe, PayPal, etc.)', max_length=30),
        ),
        migrations.AddField(
            model_name='financialaccountcategory',
            name='is_digital',
            field=models.BooleanField(default=False, help_text='If true, child accounts can define payment gateway integrations'),
        ),
    ]
