# Generated by Django 6.0.4 on 2026-04-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0076_category_defaults_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialaccount',
            name='digital_provider',
        ),
        migrations.RemoveField(
            model_name='financialaccountcategory',
            name='digital_provider',
        ),
    ]
