# Generated by Django 6.0.4 on 2026-04-30 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0077_payment_gateway_catalog'),
        ('reference', '0007_payment_gateway_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='digital_gateway',
            field=models.ForeignKey(blank=True, help_text='Payment gateway (inherited from category or overridden)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_accounts', to='reference.orgpaymentgateway'),
        ),
        migrations.AddField(
            model_name='financialaccountcategory',
            name='digital_gateway',
            field=models.ForeignKey(blank=True, help_text="Default payment gateway for child accounts (from org's activated gateways)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_categories', to='reference.orgpaymentgateway'),
        ),
    ]
