# Generated by Django 5.2.11 on 2026-03-03 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_alter_planaddon_addon_type'),
        ('integrations', '0002_webhook_subscription_delivery_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhookdeliverylog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='event_type',
            field=models.CharField(choices=[('order.placed', 'Order Placed'), ('order.confirmed', 'Order Confirmed'), ('order.shipped', 'Order Shipped'), ('order.delivered', 'Order Delivered'), ('order.cancelled', 'Order Cancelled'), ('order.returned', 'Order Returned'), ('payment.confirmed', 'Payment Confirmed')], help_text="Event type to subscribe to (e.g. 'order.placed')", max_length=50),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='secret',
            field=models.CharField(blank=True, default='', help_text='HMAC-SHA256 secret for payload signing. Set and share with the receiver.', max_length=255),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='target_url',
            field=models.URLField(help_text='URL that will receive POST requests with the event payload'),
        ),
    ]
