# Generated by Django 5.1.7 on 2026-02-19 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_initial'),
        ('erp', '0002_initial'),
        ('inventory', '0001_initial'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalert',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_alerts', to='pos.purchaseorder'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktransferorder'),
        ),
        migrations.AddField(
            model_name='stockadjustmentline',
            name='reflect_transfer',
            field=models.ForeignKey(blank=True, help_text='Linked transfer order if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocktransferorder'),
        ),
        migrations.AddField(
            model_name='stockvaluationentry',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productbatch'),
        ),
        migrations.AddField(
            model_name='stockvaluationentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='stockvaluationentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valuation_entries', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='unit',
            name='base_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_units', to='inventory.unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sized_products', to='inventory.unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unit'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.site'),
        ),
        migrations.AddField(
            model_name='stockvaluationentry',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_lines_out', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_lines_in', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Specific warehouse, or null for org-wide alert', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockadjustmentorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_orders', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockadjustmentline',
            name='warehouse',
            field=models.ForeignKey(help_text='Specific location for this adjustment', on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='seriallog',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='productserial',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='operationalrequestline',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counting_sessions', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='warehouseaisle',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='warehousebin',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='productlocation',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_locations', to='inventory.warehousebin'),
        ),
        migrations.AddField(
            model_name='warehouserack',
            name='aisle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='inventory.warehouseaisle'),
        ),
        migrations.AddField(
            model_name='warehouserack',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='warehouseshelf',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='warehouseshelf',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='inventory.warehouserack'),
        ),
        migrations.AddField(
            model_name='warehousebin',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='inventory.warehouseshelf'),
        ),
        migrations.AddField(
            model_name='warehousezone',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='warehousezone',
            name='warehouse',
            field=models.ForeignKey(help_text='Warehouse site this zone belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='erp.site'),
        ),
        migrations.AddField(
            model_name='warehouseaisle',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisles', to='inventory.warehousezone'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_category_name_org'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_brand_name_org'),
        ),
        migrations.AddConstraint(
            model_name='parfum',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_parfum_name_org'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorysessionline',
            unique_together={('session', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='combocomponent',
            unique_together={('combo_product', 'component_product', 'organization')},
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('code', 'organization'), name='unique_unit_code_org'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('sku', 'organization'), name='unique_product_sku_per_org'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('barcode', 'organization'), name='unique_product_barcode_per_org'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('code', 'site', 'organization')},
        ),
        migrations.AddIndex(
            model_name='stockvaluationentry',
            index=models.Index(fields=['organization', 'product', 'warehouse', 'movement_date'], name='stock_valua_organiz_bf9e30_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['organization', 'status'], name='stock_alert_organiz_e38e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['organization', 'alert_type'], name='stock_alert_organiz_a6fc0e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['organization', 'product'], name='stock_alert_organiz_e63ba0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productserial',
            unique_together={('serial_number', 'product', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='productbatch',
            unique_together={('batch_number', 'product', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('warehouse', 'product', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='productlocation',
            unique_together={('product', 'bin')},
        ),
        migrations.AlterUniqueTogether(
            name='warehouserack',
            unique_together={('aisle', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='warehouseshelf',
            unique_together={('rack', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='warehousebin',
            unique_together={('shelf', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='warehousezone',
            unique_together={('warehouse', 'code', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='warehouseaisle',
            unique_together={('zone', 'code')},
        ),
    ]
