# Generated by Django 5.1.7 on 2026-02-19 01:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_stock_level',
            field=models.IntegerField(blank=True, help_text='Maximum stock level before overstock alert', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_point',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Stock level at which to trigger reorder alert', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suggested quantity to reorder', max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock'), ('OVERSTOCK', 'Overstock'), ('REORDER', 'Reorder Point Reached'), ('EXPIRY_WARNING', 'Expiry Warning')], max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('SNOOZED', 'Snoozed')], default='ACTIVE', max_length=15)),
                ('current_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stock level when alert was created', max_digits=15)),
                ('threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Threshold that was breached', max_digits=15)),
                ('reorder_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suggested reorder quantity', max_digits=15)),
                ('message', models.TextField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='inventory.product')),
            ],
            options={
                'db_table': 'stock_alert',
                'ordering': ['-created_at'],
            },
        ),
    ]
