# Generated by Django 5.1.7 on 2026-02-19 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_max_stock_level_product_reorder_point_and_more'),
        ('pos', '0002_purchaseorder_purchaseorderline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalert',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_alerts', to='pos.purchaseorder'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Specific warehouse, or null for org-wide alert', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='inventory.warehouse'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['organization', 'status'], name='stock_alert_organiz_e38e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['organization', 'alert_type'], name='stock_alert_organiz_a6fc0e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['organization', 'product'], name='stock_alert_organiz_e63ba0_idx'),
        ),
    ]
