# Generated by Django 6.0.2 on 2026-02-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='legacy_id',
            field=models.IntegerField(blank=True, help_text='ID from legacy tsfci.com system', null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='legacy_id',
            field=models.IntegerField(blank=True, help_text='ID from legacy tsfci.com system', null=True),
        ),
    ]
