# Generated by Django 6.0.2 on 2026-02-21 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_plancategory_linked_inventory_category_and_more'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='inventorysessionline',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventory',
            name='bin',
            field=models.ForeignKey(blank=True, help_text='Optional micro-location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock', to='inventory.warehousebin'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehousebin'),
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='bin',
            field=models.ForeignKey(blank=True, help_text='Optional specific bin to count', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehousebin'),
        ),
        migrations.AddField(
            model_name='inventorysessionline',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehousebin'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehousebin'),
        ),
        migrations.AddField(
            model_name='productserial',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehousebin'),
        ),
        migrations.AddField(
            model_name='seriallog',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehousebin'),
        ),
        migrations.AddField(
            model_name='stockvaluationentry',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehousebin'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('warehouse', 'bin', 'product', 'batch_number', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='inventorysessionline',
            unique_together={('session', 'product', 'bin')},
        ),
    ]
