# Generated by Django 5.1.7 on 2026-02-13 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0040_add_scope_pins_to_user'),
        ('inventory', '0002_category_code_category_short_name_inventory_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='brands', to='erp.country'),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sized_products', to='inventory.unit'),
        ),
    ]
