# Generated by Django 6.0.2 on 2026-02-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0040_add_scope_pins_to_user'),
        ('inventory', '0003_brand_countries_brand_logo_product_size_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='scope',
            field=models.CharField(default='OFFICIAL', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('code', 'site', 'organization')},
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('sku', 'organization'), name='unique_product_sku_per_org'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('barcode', 'organization'), name='unique_product_barcode_per_org'),
        ),
    ]
