# Generated by Django 5.2.11 on 2026-02-25 01:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productattribute_productattributevalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='barcode_sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='full_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='products_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='combocomponent',
            name='combo_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_components', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='combocomponent',
            name='component_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_of_combos', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='combocomponent',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='consignment_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='operationalrequest',
            name='converted_to_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationalrequest',
            name='converted_to_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_stock_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_point',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tracks_serials',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stockadjustmentline',
            name='qty_adjustment',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockadjustmentline',
            name='recovered_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockadjustmentline',
            name='reflect_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocktransferorder'),
        ),
        migrations.AlterField(
            model_name='stockadjustmentline',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='stockadjustmentorder',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stocktransferline',
            name='recovered_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stocktransferorder',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
