# Generated by Django 6.0.2 on 2026-02-21 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_plancategory_linked_inventory_category_and_more'),
        ('inventory', '0003_alter_inventory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('warehouse', 'product', 'organization')},
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='inventorysession',
            name='bin',
        ),
        migrations.AlterUniqueTogether(
            name='inventorysessionline',
            unique_together={('session', 'product')},
        ),
        migrations.RemoveField(
            model_name='productbatch',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='productserial',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='seriallog',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='stockvaluationentry',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='inventorysessionline',
            name='bin',
        ),
    ]
