# Generated by Django 5.1.7 on 2026-02-16 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_contact_linked_account_and_more'),
        ('erp', '0043_transaction_lifecycle'),
        ('inventory', '0004_alter_product_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('request_type', models.CharField(choices=[('PURCHASE_ORDER', 'Purchase Order'), ('STOCK_ADJUSTMENT', 'Stock Adjustment'), ('STOCK_TRANSFER', 'Stock Transfer')], max_length=30)),
                ('date', models.DateField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CONVERTED', 'Converted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('converted_to_type', models.CharField(blank=True, help_text='Type of order created: stock_adjustment, stock_transfer, purchase_order', max_length=30, null=True)),
                ('converted_to_id', models.IntegerField(blank=True, help_text='ID of the created order', null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operational_request',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationalRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.operationalrequest')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'operational_request_line',
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifecycle_status', models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked'), ('VERIFIED', 'Verified'), ('CONFIRMED', 'Confirmed')], default='OPEN', help_text='Current lifecycle stage', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('current_verification_level', models.IntegerField(default=0, help_text='How many verification levels have been completed')),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('total_qty_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_posted', models.BooleanField(default=False, help_text='Whether adjustments have been executed')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_orders', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_orders', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'stock_adjustment_order',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifecycle_status', models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked'), ('VERIFIED', 'Verified'), ('CONFIRMED', 'Confirmed')], default='OPEN', help_text='Current lifecycle stage', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('current_verification_level', models.IntegerField(default=0, help_text='How many verification levels have been completed')),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('driver', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('total_qty_transferred', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_posted', models.BooleanField(default=False, help_text='Whether transfers have been executed')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_orders', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='inventory.warehouse')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'stock_transfer_order',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_transferred', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.TextField(blank=True, null=True)),
                ('recovered_amount', models.DecimalField(decimal_places=2, default=0, help_text='Damage recovery amount', max_digits=15)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_lines_out', to='inventory.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_lines_in', to='inventory.warehouse')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktransferorder')),
            ],
            options={
                'db_table': 'stock_transfer_line',
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_adjustment', models.DecimalField(decimal_places=2, help_text='Positive = gain, Negative = loss', max_digits=15)),
                ('amount_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reason', models.TextField(blank=True, null=True)),
                ('recovered_amount', models.DecimalField(decimal_places=2, default=0, help_text='Insurance/recovery amount', max_digits=15)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('warehouse', models.ForeignKey(help_text='Specific location for this adjustment', on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockadjustmentorder')),
                ('reflect_transfer', models.ForeignKey(blank=True, help_text='Linked transfer order if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocktransferorder')),
            ],
            options={
                'db_table': 'stock_adjustment_line',
            },
        ),
    ]
