# Generated by Django 5.2.11 on 2026-02-26 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_user_home_site'),
        ('inventory', '0004_alter_category_barcode_sequence_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('code', 'organization')},
        ),
        migrations.AddField(
            model_name='warehouse',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='location_type',
            field=models.CharField(choices=[('BRANCH', 'Branch / Site'), ('STORE', 'Store'), ('WAREHOUSE', 'Warehouse'), ('VIRTUAL', 'Virtual')], default='WAREHOUSE', max_length=20),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent location (e.g., a branch contains warehouses)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='vat_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='can_sell',
            field=models.BooleanField(default=True, help_text='Can products be sold directly from this location?'),
        ),
        migrations.AlterField(
            model_name='warehousezone',
            name='warehouse',
            field=models.ForeignKey(help_text='Warehouse this zone belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='inventory.warehouse'),
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='site',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='type',
        ),
    ]
