# Generated by Django 5.2.11 on 2026-02-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_warehouse_unique_together_warehouse_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustmentline',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockadjustmentline',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
