# Generated by Django 5.1.7 on 2026-02-16 11:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_contact_linked_account_and_more'),
        ('erp', '0043_transaction_lifecycle'),
        ('inventory', '0005_stock_orders_and_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('QUARANTINE', 'In Quarantine'), ('EXPIRED', 'Expired'), ('CONSUMED', 'Consumed')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'product_batch',
                'ordering': ['expiry_date', 'received_date'],
                'unique_together': {('batch_number', 'product', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='ExpiryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('WARNING', 'Warning (30-60 days)'), ('CRITICAL', 'Critical (0-30 days)'), ('EXPIRED', 'Expired')], max_length=20)),
                ('days_until_expiry', models.IntegerField(help_text='Negative = already expired')),
                ('quantity_at_risk', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('value_at_risk', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_alerts', to='inventory.productbatch')),
            ],
            options={
                'db_table': 'expiry_alert',
                'ordering': ['days_until_expiry', '-quantity_at_risk'],
            },
        ),
        migrations.CreateModel(
            name='ProductSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('RETURNED', 'Returned'), ('DAMAGED', 'Damaged'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=20)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sold_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serials', to='inventory.productbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='inventory.product')),
                ('sold_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'product_serial',
                'ordering': ['-created_at'],
                'unique_together': {('serial_number', 'product', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='StockValuationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out')], max_length=20)),
                ('movement_date', models.DateTimeField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valuation_method', models.CharField(choices=[('FIFO', 'First In First Out'), ('LIFO', 'Last In First Out'), ('WEIGHTED_AVG', 'Weighted Average')], default='WEIGHTED_AVG', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='E.g., PUR-123, SALE-456', max_length=100, null=True)),
                ('running_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('running_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('running_avg_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valuation_entries', to='inventory.product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'stock_valuation_entry',
                'ordering': ['-movement_date', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'product', 'warehouse', 'movement_date'], name='stock_valua_organiz_bf9e30_idx')],
            },
        ),
    ]
