# Generated by Django 6.0.2 on 2026-02-28 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_user_is_driver'),
        ('inventory', '0006_stockadjustmentline_batch_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1, help_text='Hierarchy level (1=first above base, 2=second, etc.)')),
                ('ratio', models.DecimalField(decimal_places=4, default=1, help_text='How many BASE units this level contains', max_digits=15)),
                ('barcode', models.CharField(blank=True, help_text='Unique barcode for this packaging level', max_length=100, null=True)),
                ('custom_selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Override selling price for this level', max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_levels', to='inventory.product')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_levels', to='inventory.unit')),
            ],
            options={
                'db_table': 'product_packaging',
                'ordering': ['level'],
                'constraints': [models.UniqueConstraint(fields=('product', 'unit', 'organization'), name='unique_packaging_per_unit'), models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('barcode', 'organization'), name='unique_packaging_barcode')],
            },
        ),
    ]
