# Generated by Django 5.1.7 on 2026-02-16 12:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_contact_linked_account_and_more'),
        ('erp', '0043_transaction_lifecycle'),
        ('inventory', '0006_productbatch_expiryalert_productserial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(help_text='Warehouse/location name', max_length=255)),
                ('section', models.CharField(default='All Categories', help_text='Category section label', max_length=255)),
                ('session_date', models.DateField()),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('WAITING_VERIFICATION', 'Waiting Verification'), ('VERIFIED', 'Verified'), ('ADJUSTED', 'Adjusted'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=30)),
                ('person1_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category_filter', models.CharField(blank=True, max_length=255, null=True)),
                ('qty_filter', models.CharField(blank=True, help_text='zero, non_zero, custom', max_length=20, null=True)),
                ('qty_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('qty_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('assigned_users', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('adjustment_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counting_session', to='inventory.stockadjustmentorder')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counting_sessions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('supplier_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counting_sessions', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_session',
                'ordering': ['-session_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventorySessionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('physical_qty_person1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('physical_qty_person2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('difference_person1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('difference_person2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_same_difference', models.BooleanField(default=False, help_text='Both persons agree on count')),
                ('needs_adjustment', models.BooleanField(default=False, help_text='Difference found, needs stock adjustment')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_adjusted', models.BooleanField(default=False, help_text='Adjustment order has been created for this line')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counting_lines', to='inventory.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventorysession')),
            ],
            options={
                'db_table': 'inventory_session_line',
                'unique_together': {('session', 'product')},
            },
        ),
    ]
