# Generated by Django 6.0.2 on 2026-05-04 11:32

import django.db.models.deletion
from django.db import migrations, models


def backfill_template_fk(apps, schema_editor):
    """Link existing ProductPackaging rows to their UnitPackage template
    when (unit, ratio, organization) match. Same heuristic as
    ProductPackaging.save() — prefer same-name match, fall back to
    most-recent. Idempotent: skips rows that already have a template.
    """
    ProductPackaging = apps.get_model('inventory', 'ProductPackaging')
    UnitPackage = apps.get_model('inventory', 'UnitPackage')

    rows = ProductPackaging.objects.filter(
        template__isnull=True,
        unit__isnull=False,
        ratio__isnull=False,
    )
    updated = 0
    for pp in rows.iterator():
        candidates = UnitPackage.objects.filter(
            unit_id=pp.unit_id,
            organization_id=pp.organization_id,
            ratio=pp.ratio,
            is_archived=False,
        )
        # Same-name first, otherwise most-recent.
        chosen = (
            candidates.filter(name=pp.name).order_by('-updated_at').first()
            if pp.name else None
        ) or candidates.order_by('-updated_at').first()
        if chosen is not None:
            pp.template_id = chosen.id
            pp.save(update_fields=['template'])
            updated += 1
    print(f'[migration] linked {updated} ProductPackaging rows to a UnitPackage template.')


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_rename_bufferedreq_organiz_3f8ed5_idx_bufferedreq_tenant__076e1c_idx_and_more'),
        ('inventory', '0007_ai_category_rule_review'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aicategoryrulereview',
            new_name='inventory_a_tenant__fc55bd_idx',
            old_name='inv_ai_cr_org_cat_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='aicategoryrulereview',
            new_name='inventory_a_created_42d63a_idx',
            old_name='inv_ai_cr_created_idx',
        ),
        migrations.RenameIndex(
            model_name='aiscopereview',
            new_name='inventory_a_tenant__754ae5_idx',
            old_name='inv_ai_rev_org_val_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='aiscopereview',
            new_name='inventory_a_created_84b17c_idx',
            old_name='inv_ai_rev_created_idx',
        ),
        migrations.AddField(
            model_name='productpackaging',
            name='template',
            field=models.ForeignKey(blank=True, help_text='UnitPackage template this row adopted (auto-linked when unit+ratio match).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_packagings', to='inventory.unitpackage'),
        ),
        # Backfill template FK on rows created before this column existed.
        # `RunPython.noop` reverse — we just drop the FK on rollback (the
        # AddField above handles the schema rollback), nothing to undo.
        migrations.RunPython(backfill_template_fk, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='aicategoryrulereview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aiscopereview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aiscopesuggesterconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='printerconfig',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='printsession',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='printsessionitem',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
    ]
