# Generated by Django 5.1.7 on 2026-02-16 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0043_transaction_lifecycle'),
        ('inventory', '0007_counting_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('COMBO', 'Combo / Bundle'), ('SERVICE', 'Service')], default='STANDARD', max_length=20),
        ),
        migrations.CreateModel(
            name='ComboComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Optional price override for this component within the combo', max_digits=15, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('combo_product', models.ForeignKey(help_text='The parent combo/bundle product', on_delete=django.db.models.deletion.CASCADE, related_name='combo_components', to='inventory.product')),
                ('component_product', models.ForeignKey(help_text='The child product included in this combo', on_delete=django.db.models.deletion.CASCADE, related_name='part_of_combos', to='inventory.product')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'combo_component',
                'ordering': ['sort_order'],
                'unique_together': {('combo_product', 'component_product', 'organization')},
            },
        ),
    ]
