# Generated by Django 5.1.7 on 2026-02-16 16:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_add_pricing_models'),
        ('inventory', '0008_add_product_type_and_combo_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='consignment_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Agreed payout amount to supplier per unit', max_digits=15),
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_consignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'SUPPLIER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignment_stock', to='crm.contact'),
        ),
    ]
