# Generated by Django 5.2.11 on 2026-03-02 20:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_seed_app_change_theme_permission'),
        ('inventory', '0008_stock_ledger'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockledger',
            new_name='stock_ledge_organiz_0e48ba_idx',
            old_name='sl_org_prod_wh_idx',
        ),
        migrations.RenameIndex(
            model_name='stockledger',
            new_name='stock_ledge_order_i_57d8a5_idx',
            old_name='sl_order_type_idx',
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='on_hand_delta',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Change to physical on-hand qty (-deduction / +return)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
    ]
