# Generated by Django 5.1.7 on 2026-02-16 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0045_user_is_2fa_enabled_user_two_factor_secret_and_more'),
        ('inventory', '0009_add_consignment_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tracks_serials',
            field=models.BooleanField(default=False, help_text='Requires Serial/IMEI per unit'),
        ),
        migrations.CreateModel(
            name='SerialLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.productserial')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'product_serial_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
