# Generated by Django 6.0.2 on 2026-03-05 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_transactionstatuslog_meta_transactiontype_and_more'),
        ('inventory', '0011_gap10_performance_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='brand',
            name='unique_brand_name_org',
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_org',
        ),
        migrations.RemoveConstraint(
            model_name='parfum',
            name='unique_parfum_name_org',
        ),
        migrations.RemoveConstraint(
            model_name='unit',
            name='unique_unit_code_org',
        ),
        migrations.RemoveField(
            model_name='productgroup',
            name='organization',
        ),
        # v3.5.0 cleanup: were AddField — Brand/Category/Parfum.organization already
        # added by 0001_initial. Switched to AlterField to apply the new
        # blank/null/related_name without crashing on duplicate column.
        migrations.AlterField(
            model_name='brand',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='parfum',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='stockadjustmentorder',
            name='policy_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='JSON snapshot of policy/rules at LOCK time for audit trail'),
        ),
        migrations.AddField(
            model_name='stockadjustmentorder',
            name='required_levels_frozen',
            field=models.IntegerField(default=0, help_text='Required levels frozen at LOCK time (immutable)'),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='policy_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='JSON snapshot of policy/rules at LOCK time for audit trail'),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='required_levels_frozen',
            field=models.IntegerField(default=0, help_text='Required levels frozen at LOCK time (immutable)'),
        ),
        # v3.5.0 cleanup: was AddField — Unit.organization already added by 0002_initial.
        # Switched to AlterField to apply the new shape without crashing on duplicate column.
        migrations.AlterField(
            model_name='unit',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_brand_name_tenant'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_category_name_tenant'),
        ),
        migrations.AddConstraint(
            model_name='parfum',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_parfum_name_tenant'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('code', 'organization'), name='unique_unit_code_tenant'),
        ),
        migrations.RemoveField(
            model_name='brand',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='category',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='parfum',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='organization',
        ),
    ]
