# Generated by Django 6.0.2 on 2026-03-06 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_contact_supplier_vat_regime_and_more'),
        ('erp', '0013_approvalpolicy_approvalpolicystep_txnapproval'),
        ('inventory', '0012_remove_brand_unique_brand_name_org_and_more'),
        ('pos', '0049_landedcost_landedcostline_purchaseattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockmove',
            name='stock_move_organiz_a5badb_idx',
        ),
        migrations.RenameField(
            model_name='stockadjustmentorder',
            old_name='is_posted',
            new_name='is_locked',
        ),
        migrations.RenameField(
            model_name='stocktransferorder',
            old_name='is_posted',
            new_name='is_locked',
        ),
        migrations.RemoveField(
            model_name='operationalrequest',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='stockadjustmentorder',
            name='current_verification_level',
        ),
        migrations.RemoveField(
            model_name='stockadjustmentorder',
            name='lifecycle_status',
        ),
        migrations.RemoveField(
            model_name='stockadjustmentorder',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='stockadjustmentorder',
            name='policy_snapshot',
        ),
        migrations.RemoveField(
            model_name='stockadjustmentorder',
            name='required_levels_frozen',
        ),
        migrations.RemoveField(
            model_name='stockmoveline',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='stocktransferorder',
            name='current_verification_level',
        ),
        migrations.RemoveField(
            model_name='stocktransferorder',
            name='lifecycle_status',
        ),
        migrations.RemoveField(
            model_name='stocktransferorder',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='stocktransferorder',
            name='policy_snapshot',
        ),
        migrations.RemoveField(
            model_name='stocktransferorder',
            name='required_levels_frozen',
        ),
        migrations.AddField(
            model_name='operationalrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='operationalrequestline',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='stockadjustmentline',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='stockadjustmentorder',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockadjustmentorder',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustmentorder',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='inventory.stockadjustmentorder'),
        ),
        migrations.AddField(
            model_name='stockadjustmentorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('LOCKED', 'Locked'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='stockadjustmentorder',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockadjustmentorder',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustmentorder',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_locked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='inventory.stockmove'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='stockmoveline',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='inventory.stocktransferorder'),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('LOCKED', 'Locked'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='stockadjustmentorder',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_locked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('LOCKED', 'Locked'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktransferorder',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_locked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='stockadjustmentorder',
            index=models.Index(fields=['tenant', 'status'], name='stock_adjus_tenant__32c7e3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustmentorder',
            index=models.Index(fields=['tenant', 'date'], name='stock_adjus_tenant__6379d2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['tenant', 'status'], name='stock_move_tenant__d85b58_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransferorder',
            index=models.Index(fields=['tenant', 'status'], name='stock_trans_tenant__abd0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransferorder',
            index=models.Index(fields=['tenant', 'date'], name='stock_trans_tenant__4e3b8c_idx'),
        ),
        migrations.RemoveField(
            model_name='stockmove',
            name='organization',
        ),
    ]
