# Generated by Django 6.0.2 on 2026-03-06 01:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_contact_supplier_vat_regime_and_more'),
        ('erp', '0014_alter_txnapproval_action'),
        ('inventory', '0013_remove_stockmove_stock_move_organiz_a5badb_idx_and_more'),
        ('pos', '0049_landedcost_landedcostline_purchaseattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('DAMAGE', 'Damage'), ('LOSS', 'Loss'), ('THEFT', 'Theft'), ('CORRECTION', 'Count Correction'), ('EXPIRED', 'Expired'), ('RETURN', 'Return'), ('WRITE_OFF', 'Write Off'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('requires_approval', models.BooleanField(default=False, help_text='If true, adjustments with this reason require manager approval')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'adjustment_reason',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CostLayerConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_consumed', models.DecimalField(decimal_places=3, max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('consumption_type', models.CharField(choices=[('SALE', 'Sale'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER_OUT', 'Transfer Out'), ('WRITE_OFF', 'Write Off'), ('PRODUCTION', 'Production Input')], max_length=30)),
                ('consumption_id', models.IntegerField(blank=True, help_text='PK of the consuming document', null=True)),
                ('consumed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_cost_layer_consumption',
                'ordering': ['-consumed_at'],
            },
        ),
        migrations.CreateModel(
            name='CycleCountPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classification', models.CharField(choices=[('A', 'A — High Value / Fast Moving'), ('B', 'B — Medium Value'), ('C', 'C — Low Value / Slow Moving')], max_length=1)),
                ('count_frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=15)),
                ('min_value_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Products with total value >= this threshold qualify for this class', max_digits=15, null=True)),
                ('max_value_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'cycle_count_policy',
                'ordering': ['classification', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15)),
                ('reserved', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=15)),
                ('available', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Computed: on_hand - reserved', max_digits=15)),
                ('avg_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Weighted average cost from cost layers', max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='on_hand × avg_cost', max_digits=15)),
                ('last_movement_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_balance',
            },
        ),
        migrations.CreateModel(
            name='InventoryBalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('on_hand', models.DecimalField(decimal_places=3, max_digits=15)),
                ('reserved', models.DecimalField(decimal_places=3, max_digits=15)),
                ('available', models.DecimalField(decimal_places=3, max_digits=15)),
                ('avg_cost', models.DecimalField(decimal_places=4, max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'inventory_balance_history',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryFreezePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. "March 2026 Close"', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_freeze_period',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PackingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('LOCKED', 'Locked'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('total_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('total_packages', models.IntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'packing_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('LOCKED', 'Locked'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'pick_list',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickListLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_requested', models.DecimalField(decimal_places=3, max_digits=15)),
                ('qty_picked', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Actual quantity picked (may differ from requested)', max_digits=15)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pick_list_line',
            },
        ),
        migrations.CreateModel(
            name='PurchaseSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.DecimalField(decimal_places=3, max_digits=15)),
                ('suggested_qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='suggested_qty × product.cost_price', max_digits=15)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent — stockout imminent')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('CONVERTED', 'Converted to PO'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=15)),
                ('converted_po_id', models.IntegerField(blank=True, help_text='PK of the PurchaseOrder created from this suggestion', null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'purchase_suggestion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.DecimalField(decimal_places=3, help_text='Trigger replenishment when available falls below this', max_digits=15)),
                ('max_qty', models.DecimalField(decimal_places=3, help_text='Fill up to this level', max_digits=15)),
                ('reorder_qty', models.DecimalField(decimal_places=3, help_text='Default order quantity (max_qty - current_stock)', max_digits=15)),
                ('lead_time_days', models.IntegerField(default=7, help_text='Expected delivery time from supplier')),
                ('method', models.CharField(choices=[('FIXED', 'Fixed Reorder Quantity'), ('TOP_UP', 'Top Up to Max'), ('EOQ', 'Economic Order Quantity')], default='TOP_UP', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'replenishment_rule',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('LOCKED', 'Locked'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('carrier', models.CharField(blank=True, choices=[('DHL', 'DHL'), ('FEDEX', 'FedEx'), ('UPS', 'UPS'), ('ARAMEX', 'Aramex'), ('LOCAL', 'Local Courier'), ('SELF', 'Self Delivery'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('carrier_name', models.CharField(blank=True, help_text='Custom carrier name when carrier=OTHER', max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=200, null=True)),
                ('tracking_url', models.URLField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_proof', models.CharField(blank=True, help_text='URL to delivery proof (photo/signature)', max_length=500, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'shipment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCostLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_initial', models.DecimalField(decimal_places=3, help_text='Original receipt quantity', max_digits=15)),
                ('quantity_remaining', models.DecimalField(decimal_places=3, help_text='Unconsumed quantity (decrements on sale/adjustment)', max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Per-unit cost at time of receipt', max_digits=15)),
                ('source_type', models.CharField(choices=[('PURCHASE', 'Purchase Receipt'), ('ADJUSTMENT', 'Stock Adjustment'), ('RETURN', 'Customer Return'), ('TRANSFER_IN', 'Transfer In'), ('OPENING', 'Opening Balance'), ('PRODUCTION', 'Production Output')], max_length=20)),
                ('source_id', models.IntegerField(blank=True, help_text='PK of the source document (PO line, adjustment, etc.)', null=True)),
                ('receipt_date', models.DateField(db_index=True)),
                ('is_exhausted', models.BooleanField(db_index=True, default=False, help_text='True when quantity_remaining reaches 0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_cost_layer',
                'ordering': ['receipt_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(decimal_places=6, help_text='1 from_unit = ratio × to_unit', max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'unit_conversion',
                'ordering': ['from_unit__name', 'to_unit__name'],
            },
        ),
        migrations.AddField(
            model_name='stockledger',
            name='reservation_source_id',
            field=models.IntegerField(blank=True, help_text='PK of the source document', null=True),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='reservation_source_type',
            field=models.CharField(blank=True, choices=[('SALES_ORDER', 'Sales Order'), ('TRANSFER_ORDER', 'Transfer Order'), ('PRODUCTION_ORDER', 'Production Order'), ('PICK_LIST', 'Pick List'), ('MANUAL', 'Manual Reservation')], help_text='What document reserved this stock', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stockvaluationentry',
            name='valuation_scope',
            field=models.CharField(choices=[('GLOBAL', 'Global — single cost across all warehouses'), ('PER_WAREHOUSE', 'Per Warehouse — cost differs by location'), ('PER_BATCH', 'Per Batch — cost tracked at batch level')], default='GLOBAL', help_text='Determines costing granularity', max_length=15),
        ),
        migrations.AddIndex(
            model_name='productserial',
            index=models.Index(fields=['organization', 'serial_number'], name='product_ser_organiz_e3e474_idx'),
        ),
        migrations.AddIndex(
            model_name='productserial',
            index=models.Index(fields=['organization', 'product', 'status'], name='product_ser_organiz_028cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='productserial',
            index=models.Index(fields=['organization', 'warehouse', 'status'], name='product_ser_organiz_150f3c_idx'),
        ),
        migrations.AddField(
            model_name='adjustmentreason',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='stockadjustmentorder',
            name='reason_code',
            field=models.ForeignKey(blank=True, help_text='Structured reason code (auditor-required)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_orders', to='inventory.adjustmentreason'),
        ),
        migrations.AddField(
            model_name='costlayerconsumption',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='cyclecountpolicy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_count_policies', to='inventory.category'),
        ),
        migrations.AddField(
            model_name='cyclecountpolicy',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='cyclecountpolicy',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Null = applies to all warehouses', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_count_policies', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='inventorybalancehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_history', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='inventorybalancehistory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='inventorybalancehistory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_history', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='inventoryfreezeperiod',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryfreezeperiod',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='packingorder',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_locked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packingorder',
            name='packed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packingorder',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packingorder',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='inventory.packingorder'),
        ),
        migrations.AddField(
            model_name='packingorder',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packingorder',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='picklist',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pick_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='picklist',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_locked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='picklist',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_lists', to='pos.order'),
        ),
        migrations.AddField(
            model_name='picklist',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='picklist',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='inventory.picklist'),
        ),
        migrations.AddField(
            model_name='picklist',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='picklist',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='picklist',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_lists', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='packingorder',
            name='pick_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_orders', to='inventory.picklist'),
        ),
        migrations.AddField(
            model_name='picklistline',
            name='bin_location',
            field=models.ForeignKey(blank=True, help_text='Suggested bin to pick from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehousebin'),
        ),
        migrations.AddField(
            model_name='picklistline',
            name='pick_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.picklist'),
        ),
        migrations.AddField(
            model_name='picklistline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='picklistline',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='purchasesuggestion',
            name='converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasesuggestion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_suggestions', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='purchasesuggestion',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_suggestions', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='purchasesuggestion',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='purchasesuggestion',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_suggestions', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='replenishmentrule',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_rules', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='replenishmentrule',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Preferred supplier for this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishment_rules', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='replenishmentrule',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='replenishmentrule',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Null = applies to all warehouses', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_rules', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='purchasesuggestion',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='inventory.replenishmentrule'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_locked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='pos.order'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='packing_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='inventory.packingorder'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='inventory.shipment'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='stockcostlayer',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_layers', to='inventory.productbatch'),
        ),
        migrations.AddField(
            model_name='stockcostlayer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stockcostlayer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='stockcostlayer',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Null = global (non-warehouse-specific) layer', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='costlayerconsumption',
            name='cost_layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='inventory.stockcostlayer'),
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='from_unit',
            field=models.ForeignKey(help_text='Source unit (e.g., carton)', on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='inventory.unit'),
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product-specific conversion (null = universal for this organization)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='to_unit',
            field=models.ForeignKey(help_text='Target unit (e.g., bottle)', on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='inventory.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='adjustmentreason',
            unique_together={('code', 'organization')},
        ),
        migrations.AddIndex(
            model_name='cyclecountpolicy',
            index=models.Index(fields=['organization', 'classification', 'is_active'], name='cycle_count_organiz_5e960e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['organization', 'warehouse'], name='inventory_b_organization__0e72b4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['organization', 'product'], name='inventory_b_organization__fc159a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['organization', 'available'], name='inventory_b_organization__9a458f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorybalance',
            unique_together={('product', 'warehouse', 'organization')},
        ),
        migrations.AddIndex(
            model_name='inventorybalancehistory',
            index=models.Index(fields=['organization', 'snapshot_date'], name='inventory_b_organization__cb554c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalancehistory',
            index=models.Index(fields=['organization', 'product', 'snapshot_date'], name='inventory_b_organization__5fb521_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorybalancehistory',
            unique_together={('product', 'warehouse', 'snapshot_date', 'organization')},
        ),
        migrations.AddIndex(
            model_name='inventoryfreezeperiod',
            index=models.Index(fields=['organization', 'start_date', 'end_date'], name='inventory_f_organization__7cd43f_idx'),
        ),
        migrations.AddIndex(
            model_name='picklist',
            index=models.Index(fields=['organization', 'status'], name='pick_list_organization__bfa097_idx'),
        ),
        migrations.AddIndex(
            model_name='picklist',
            index=models.Index(fields=['organization', 'assigned_to', 'status'], name='pick_list_organization__25cffa_idx'),
        ),
        migrations.AddIndex(
            model_name='packingorder',
            index=models.Index(fields=['organization', 'status'], name='packing_ord_organization__1cf36a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='picklistline',
            unique_together={('pick_list', 'product', 'bin_location')},
        ),
        migrations.AddIndex(
            model_name='replenishmentrule',
            index=models.Index(fields=['organization', 'is_active'], name='replenishme_organization__216cbb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='replenishmentrule',
            unique_together={('product', 'warehouse', 'organization')},
        ),
        migrations.AddIndex(
            model_name='purchasesuggestion',
            index=models.Index(fields=['organization', 'status'], name='purchase_su_organization__4718e7_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasesuggestion',
            index=models.Index(fields=['organization', 'product', 'status'], name='purchase_su_organization__4e31ba_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['organization', 'status'], name='shipment_organization__904ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='shipment_trackin_b82c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcostlayer',
            index=models.Index(fields=['organization', 'product', 'warehouse', 'is_exhausted'], name='stock_cost__organization__eb8e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcostlayer',
            index=models.Index(fields=['organization', 'product', 'receipt_date'], name='stock_cost__organization__1082d2_idx'),
        ),
        migrations.AddIndex(
            model_name='costlayerconsumption',
            index=models.Index(fields=['cost_layer', 'consumed_at'], name='stock_cost__cost_la_1d8927_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unitconversion',
            unique_together={('from_unit', 'to_unit', 'product', 'organization')},
        ),
    ]
