# Generated by Django 5.2.11 on 2026-03-06 03:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_adjustmentreason_costlayerconsumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='base_selling_price_ht',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reference selling price (HT) for all products in this group', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='base_selling_price_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reference selling price (TTC) for all products in this group', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='packaging_formula',
            field=models.JSONField(blank=True, default=dict, help_text='Per-packaging-level discount formula, e.g. {"CARTON": {"discount_pct": 2.0}, "PAQUET": {"discount_pct": 5.0}}'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='price_sync_enabled',
            field=models.BooleanField(default=True, help_text='When enabled, changing any member product price updates all members'),
        ),
        migrations.AddField(
            model_name='productpackaging',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage vs unit price (e.g. 2.00 = 2% cheaper per unit in this packaging)', max_digits=5),
        ),
        migrations.AddField(
            model_name='productpackaging',
            name='price_mode',
            field=models.CharField(choices=[('FORMULA', 'Formula — auto-calculated from base price × ratio × discount'), ('FIXED', 'Fixed — manually set custom_selling_price')], default='FORMULA', help_text='FORMULA: auto = base × ratio × (1 - discount%). FIXED: use custom_selling_price.', max_length=10),
        ),
    ]
