# Generated by Django 5.2.11 on 2026-03-06 18:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_clientpricerule_packaging_level_id_and_more'),
        ('erp', '0014_alter_txnapproval_action'),
        ('inventory', '0016_product_avg_available_expiry_days_and_more'),
        ('pos', '0049_landedcost_landedcostline_purchaseattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, db_index=True, help_text='Auto-generated reference (e.g., GR-000001)', max_length=50, null=True)),
                ('mode', models.CharField(choices=[('DIRECT', 'Direct Receiving (No PO)'), ('PO_BASED', 'Receiving Against Purchase Order')], default='DIRECT', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft — session created'), ('IN_PROGRESS', 'In Progress — actively receiving'), ('COMPLETED', 'Completed — all items processed'), ('PARTIALLY_COMPLETED', 'Partially Completed — some items pending'), ('CLOSED', 'Closed — finalized and locked'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=25)),
                ('supplier_ref', models.CharField(blank=True, help_text='Delivery note / BL reference from supplier', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Linked PO (Mode B only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='pos.purchaseorder')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts_received', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, limit_choices_to={'type': 'SUPPLIER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='crm.contact')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization')),
                ('warehouse', models.ForeignKey(help_text='Receiving location', on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'goods_receipt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_ordered', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected qty from PO (0 in Mode A)', max_digits=15)),
                ('qty_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('qty_rejected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('line_status', models.CharField(choices=[('PENDING', 'Pending — awaiting processing'), ('SCANNED', 'Scanned — identified but not yet decided'), ('UNDER_REVIEW', 'Under Review — needs manager input'), ('RECEIVED', 'Received — accepted into stock'), ('PARTIALLY_RECEIVED', 'Partially Received — partial acceptance'), ('REJECTED', 'Rejected — refused'), ('APPROVAL_REQUIRED', 'Approval Required — unexpected item'), ('APPROVED_EXTRA', 'Approved Extra Item'), ('REFUSED_EXTRA', 'Refused Extra Item'), ('RETURN_PENDING', 'Return Pending'), ('TRANSFER_REQUIRED', 'Transfer Required'), ('VERIFIED', 'Verified — quality check passed'), ('CLOSED', 'Closed')], default='PENDING', max_length=25)),
                ('rejection_reason', models.CharField(choices=[('NOT_REJECTED', 'Not Rejected'), ('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('SHORT_SHELF_LIFE', 'Short Shelf Life'), ('QUALITY_ISSUE', 'Quality Issue'), ('NOT_ORDERED', 'Not Ordered'), ('WRONG_PRODUCT', 'Wrong Product'), ('OTHER', 'Other')], default='NOT_REJECTED', max_length=25)),
                ('rejection_notes', models.TextField(blank=True, null=True)),
                ('is_unexpected', models.BooleanField(default=False, help_text='Item not on the PO (Mode B only)')),
                ('approval_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REFUSED', 'Refused'), ('ESCALATED', 'Escalated')], default='NOT_REQUIRED', max_length=20)),
                ('transfer_requirement', models.CharField(choices=[('NO_TRANSFER', 'No Transfer Needed'), ('TO_STORE', 'Transfer to Store Required'), ('TO_WAREHOUSE', 'Transfer to Warehouse Required'), ('REQUEST_CREATED', 'Transfer Request Created'), ('IN_PROGRESS', 'Transfer In Progress'), ('COMPLETED', 'Transfer Completed')], default='NO_TRANSFER', max_length=20)),
                ('stock_on_location', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current stock at receiving warehouse', max_digits=15)),
                ('total_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total stock across all locations', max_digits=15)),
                ('avg_daily_sales', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Average daily sales velocity', max_digits=15)),
                ('remaining_shelf_life_days', models.IntegerField(blank=True, help_text='Days until expiry (null if non-expiry item)', null=True)),
                ('safe_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='(avg_daily_sales × shelf_life_days) - current_stock', max_digits=15)),
                ('safe_qty_after_receipt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='safe_qty - qty_received', max_digits=15)),
                ('receipt_coverage_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='(qty_received / max(safe_qty, 1)) × 100', max_digits=8)),
                ('sales_performance_score', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Sales rotation efficiency score', max_digits=10)),
                ('adjustment_risk_score', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Negative adjustment ratio (shrinkage/damage risk)', max_digits=10)),
                ('recommended_action', models.CharField(blank=True, help_text='System-generated recommended action text', max_length=255, null=True)),
                ('decision_warnings', models.JSONField(blank=True, default=list, help_text='List of warning badge codes from decision engine')),
                ('evidence_attachment', models.URLField(blank=True, help_text='Photo/document evidence URL (for rejections)', max_length=500, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po_line', models.ForeignKey(blank=True, help_text='Linked PO line (Mode B only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipt_lines', to='pos.purchaseorderline')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_receipt_lines', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='inventory.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.goodsreceipt')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization')),
            ],
            options={
                'db_table': 'goods_receipt_line',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['tenant', 'status'], name='goods_recei_tenant__5001d4_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['receipt_number'], name='goods_recei_receipt_d38ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceiptline',
            index=models.Index(fields=['receipt', 'line_status'], name='goods_recei_receipt_43bc4e_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceiptline',
            index=models.Index(fields=['product'], name='goods_recei_product_64a18b_idx'),
        ),
    ]
