# Generated by Django 6.0.2 on 2026-03-07 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_fix_null_organization_data'),
        ('inventory', '0017_goodsreceipt_goodsreceiptline_and_more'),
    ]

    operations = [
    ]
