# Generated by Django 6.0.2 on 2026-03-11 00:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_postable_journal_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User assigned to follow up on this receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='batch_priority_index',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Expiry Date / Sales Velocity (priority for exposure)', max_digits=10),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='coverage_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Network stock coverage days after this receipt', max_digits=10),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_receipt_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='predicted_expiry_loss',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Predicted financial loss due to remaining stock at expiry', max_digits=15),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='putaway_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='putaway_receipt_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='qc_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_checked_receipt_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='qty_returned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='rts_minutes',
            field=models.IntegerField(blank=True, help_text='Receive-To-Shelf (RTS): Time from physical receipt to putaway (minutes)', null=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='shelf_pressure',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Incoming Qty / Display Capacity (if >100% suggests overstock)', max_digits=10),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='supplier_reliability_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot of supplier score at time of receipt', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_receipt_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_display_capacity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Physical capacity of the display shelf for this product', max_digits=15),
        ),
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='line_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED_SAFE', 'Received Safe'), ('RECEIVED_CAUTION', 'Received With Caution'), ('RECEIVED_RISKY', 'Received Risky'), ('REJECTED', 'Rejected'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('NEEDS_APPROVAL', 'Needs Approval'), ('NEEDS_RETURN', 'Needs Return'), ('NEEDS_TRANSFER', 'Needs Transfer'), ('NEEDS_ROTATION', 'Needs Shelf Rotation'), ('NEEDS_EXPIRY_VERIF', 'Needs Expiry Verification'), ('DISCREPANCY', 'Discrepancy Detected')], default='PENDING', max_length=25),
        ),
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='receipt_coverage_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Receipt Safety Ratio %: (qty_received / max(safe_qty, 1)) × 100', max_digits=8),
        ),
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='rejection_reason',
            field=models.CharField(choices=[('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('NEAR_EXPIRY', 'Near Expiry'), ('WRONG_PRODUCT', 'Wrong Product'), ('WRONG_QUANTITY', 'Wrong Quantity'), ('WRONG_PACKAGING', 'Wrong Packaging'), ('WRONG_BATCH', 'Wrong Batch'), ('PRICE_DISCREPANCY', 'Price Discrepancy'), ('QUALITY_ISSUE', 'Quality Issue'), ('NO_APPROVAL', 'No Approval'), ('NOT_IN_PO', 'Not in PO'), ('SUPPLIER_ERROR', 'Supplier Error'), ('INTERNAL_REFUSAL', 'Internal Refusal'), ('OTHER', 'Other')], default='NOT_REJECTED', max_length=25),
        ),
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='safe_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sell-Through Safe Qty: (avg_daily_sales × shelf_life_days) - current_stock', max_digits=15),
        ),
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='safe_qty_after_receipt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining Safe Capacity: Sell-Through Safe Qty - Qty Received', max_digits=15),
        ),
    ]
