# Generated by Django 5.2.11 on 2026-03-11 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_remove_contact_idx_contact_org_type_and_more'),
        ('erp', '0020_organization_finance_hard_locked_at_and_more'),
        ('inventory', '0021_goodsreceipt_approved_by_goodsreceipt_assigned_to_and_more'),
        ('pos', '0062_purchaseorder_invoiced_at_supplierclaim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_sku_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_barcode_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='productattribute',
            name='unique_attribute_name_org',
        ),
        migrations.RemoveConstraint(
            model_name='productpackaging',
            name='unique_packaging_per_unit',
        ),
        migrations.RemoveConstraint(
            model_name='productpackaging',
            name='unique_packaging_barcode',
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_variant_sku_org',
        ),
        migrations.RemoveIndex(
            model_name='cyclecountpolicy',
            name='cycle_count_organiz_5e960e_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventory',
            name='inv_org_branch_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorymovement',
            name='invmov_org_branch_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_org_cat_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_org_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_org_minstk_idx',
        ),
        migrations.RemoveIndex(
            model_name='productserial',
            name='product_ser_organiz_e3e474_idx',
        ),
        migrations.RemoveIndex(
            model_name='productserial',
            name='product_ser_organiz_028cd9_idx',
        ),
        migrations.RemoveIndex(
            model_name='productserial',
            name='product_ser_organiz_150f3c_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockalert',
            name='stock_alert_organiz_e38e2c_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockalert',
            name='stock_alert_organiz_a6fc0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockalert',
            name='stock_alert_organiz_e63ba0_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockledger',
            name='stock_ledge_organiz_0e48ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockvaluationentry',
            name='stock_valua_organiz_bf9e30_idx',
        ),
        migrations.AlterUniqueTogether(
            name='combocomponent',
            unique_together={('combo_product', 'component_product', 'tenant')},
        ),
        migrations.RemoveField(
            model_name='cyclecountpolicy',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='expiryalert',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('warehouse', 'product', 'variant', 'tenant')},
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='inventorysession',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='product',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='productattributevalue',
            unique_together={('attribute', 'value', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='productbatch',
            unique_together={('batch_number', 'product', 'tenant')},
        ),
        migrations.RemoveField(
            model_name='productlocation',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='productpackaging',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='productserial',
            unique_together={('serial_number', 'product', 'tenant')},
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='seriallog',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='stockalert',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='stockledger',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='stockvaluationentry',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('code', 'tenant')},
        ),
        migrations.RemoveField(
            model_name='warehouseaisle',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='warehousebin',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='warehouserack',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='warehouseshelf',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='warehousezone',
            unique_together={('warehouse', 'code', 'tenant')},
        ),
        migrations.AddField(
            model_name='combocomponent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='cyclecountpolicy',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='expiryalert',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='inventorysessionline',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='productlocation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='productpackaging',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='productserial',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='seriallog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='stockvaluationentry',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='warehouseaisle',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='warehousebin',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='warehouserack',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='warehouseshelf',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='warehousezone',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddIndex(
            model_name='cyclecountpolicy',
            index=models.Index(fields=['tenant', 'classification', 'is_active'], name='cycle_count_tenant__9d8842_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['tenant', 'branch'], name='inv_tenant_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['tenant', 'branch'], name='invmov_tenant_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'category', 'is_active'], name='product_tenant_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'status'], name='product_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'min_stock_level'], name='product_tenant_minstk_idx'),
        ),
        migrations.AddIndex(
            model_name='productserial',
            index=models.Index(fields=['tenant', 'serial_number'], name='product_ser_tenant__94fbb8_idx'),
        ),
        migrations.AddIndex(
            model_name='productserial',
            index=models.Index(fields=['tenant', 'product', 'status'], name='product_ser_tenant__af6f16_idx'),
        ),
        migrations.AddIndex(
            model_name='productserial',
            index=models.Index(fields=['tenant', 'warehouse', 'status'], name='product_ser_tenant__e199ef_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['tenant', 'status'], name='stock_alert_tenant__0e1ee9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['tenant', 'alert_type'], name='stock_alert_tenant__d0b067_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['tenant', 'product'], name='stock_alert_tenant__6e5562_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['tenant', 'product', 'warehouse', 'created_at'], name='stock_ledge_tenant__a4d0a5_idx'),
        ),
        migrations.AddIndex(
            model_name='stockvaluationentry',
            index=models.Index(fields=['tenant', 'product', 'warehouse', 'movement_date'], name='stock_valua_tenant__9b19ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('sku', 'tenant'), name='unique_product_sku_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('barcode', 'tenant'), name='unique_product_barcode_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(fields=('name', 'tenant'), name='unique_attribute_name_tenant'),
        ),
        migrations.AddConstraint(
            model_name='productpackaging',
            constraint=models.UniqueConstraint(fields=('product', 'unit', 'tenant'), name='unique_packaging_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='productpackaging',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('barcode', 'tenant'), name='unique_packaging_barcode'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('sku', 'tenant'), name='unique_variant_sku_tenant'),
        ),
        migrations.RemoveField(
            model_name='combocomponent',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='productbatch',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='productserial',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='warehousezone',
            name='organization',
        ),
    ]
