# Generated by Django 6.0.3 on 2026-03-17 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_merge_20260317_1638'),
        ('inventory', '0043_merge_grouping_and_timestamps'),
    ]

    operations = [
    ]
