# Generated by Django 6.0.3 on 2026-03-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0044_merge_20260317_2351'),
        ('erp', '0001_initial'),
    ]

    operations = [
        # ── GroupingRule table ──
        migrations.CreateModel(
            name='GroupingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Rule display name', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('match_brand', models.BooleanField(default=True, help_text='Group by same brand')),
                ('match_category', models.BooleanField(default=False, help_text='Group by same product category')),
                ('match_parfum', models.BooleanField(default=False, help_text='Group by same parfum/fragrance (Parfum model)')),
                ('match_packaging_family', models.BooleanField(default=False, help_text='Group products with same/similar packaging structure')),
                ('match_packaging_name_pattern', models.CharField(blank=True, default='', help_text='Packaging name pattern to match, e.g. "Carton", "Pack%"', max_length=200)),
                ('match_size_range', models.BooleanField(default=False, help_text='Group products within similar size ranges')),
                ('size_tolerance_pct', models.DecimalField(decimal_places=2, default=10.00, help_text='Size tolerance percentage for SIMILAR grouping (e.g. 10 = ±10%)', max_digits=5)),
                ('default_group_type', models.CharField(choices=[('EXACT', 'Exact Twins'), ('SIMILAR', 'Similar Substitute'), ('FAMILY', 'Product Family')], default='EXACT', help_text='Type assigned to auto-generated groups', max_length=10)),
                ('auto_approve', models.BooleanField(default=False, help_text='Auto-approve generated groups (vs queue for manual approval)')),
                ('auto_name_template', models.CharField(blank=True, default='{brand} {attribute} {size}', help_text='Template for auto-generated group names', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('groups_created_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('match_attribute', models.ForeignKey(blank=True, help_text='Specific attribute to match on (e.g. "Size", "Color")', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grouping_rules', to='inventory.productattribute')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization')),
            ],
            options={
                'db_table': 'product_grouping_rule',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='groupingrule',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_grouping_rule_name_tenant'),
        ),

        # ── InventoryGroup enhancements ──
        migrations.AddField(
            model_name='inventorygroup',
            name='grouping_rule',
            field=models.ForeignKey(blank=True, help_text='Rule that auto-generated this group (null = manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_groups', to='inventory.groupingrule'),
        ),
        migrations.AddField(
            model_name='inventorygroup',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='Whether this group was created by a GroupingRule'),
        ),
        migrations.AddField(
            model_name='inventorygroup',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', help_text='Approval workflow for auto-generated groups', max_length=10),
        ),
        migrations.AddField(
            model_name='inventorygroup',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Who approved this auto-generated group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_inventory_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorygroup',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
