# Generated by Django 6.0.3 on 2026-03-31 10:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('erp', '0025_rename_erp_auditlo_organization__3bae30_idx_erp_auditlo_tenant__3bae30_idx_and_more'),
        ('inventory', '0048_attribute_requires_barcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='productattribute',
            name='unique_attribute_name_tenant',
        ),
        migrations.RenameIndex(
            model_name='cyclecountpolicy',
            new_name='cycle_count_tenant__9d8842_idx',
            old_name='cycle_count_organization__9d8842_idx',
        ),
        migrations.RenameIndex(
            model_name='goodsreceipt',
            new_name='goods_recei_tenant__5001d4_idx',
            old_name='goods_recei_organization__5001d4_idx',
        ),
        migrations.RenameIndex(
            model_name='inventory',
            new_name='inv_tenant_branch_idx',
            old_name='inv_organization_branch_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorybalance',
            new_name='inventory_b_tenant__0e72b4_idx',
            old_name='inventory_b_organization__0e72b4_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorybalance',
            new_name='inventory_b_tenant__fc159a_idx',
            old_name='inventory_b_organization__fc159a_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorybalance',
            new_name='inventory_b_tenant__9a458f_idx',
            old_name='inventory_b_organization__9a458f_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorybalancehistory',
            new_name='inventory_b_tenant__cb554c_idx',
            old_name='inventory_b_organization__cb554c_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorybalancehistory',
            new_name='inventory_b_tenant__5fb521_idx',
            old_name='inventory_b_organization__5fb521_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryfreezeperiod',
            new_name='inventory_f_tenant__7cd43f_idx',
            old_name='inventory_f_organization__7cd43f_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorymovement',
            new_name='invmov_tenant_branch_idx',
            old_name='invmov_organization_branch_idx',
        ),
        migrations.RenameIndex(
            model_name='packingorder',
            new_name='packing_ord_tenant__1cf36a_idx',
            old_name='packing_ord_organization__1cf36a_idx',
        ),
        migrations.RenameIndex(
            model_name='picklist',
            new_name='pick_list_tenant__bfa097_idx',
            old_name='pick_list_organization__bfa097_idx',
        ),
        migrations.RenameIndex(
            model_name='picklist',
            new_name='pick_list_tenant__25cffa_idx',
            old_name='pick_list_organization__25cffa_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_tenant_cat_active_idx',
            old_name='product_organization_cat_active_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_tenant_status_idx',
            old_name='product_organization_status_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_tenant_minstk_idx',
            old_name='product_organization_minstk_idx',
        ),
        migrations.RenameIndex(
            model_name='productserial',
            new_name='product_ser_tenant__94fbb8_idx',
            old_name='product_ser_organization__94fbb8_idx',
        ),
        migrations.RenameIndex(
            model_name='productserial',
            new_name='product_ser_tenant__af6f16_idx',
            old_name='product_ser_organization__af6f16_idx',
        ),
        migrations.RenameIndex(
            model_name='productserial',
            new_name='product_ser_tenant__e199ef_idx',
            old_name='product_ser_organization__e199ef_idx',
        ),
        migrations.RenameIndex(
            model_name='purchasesuggestion',
            new_name='purchase_su_tenant__4718e7_idx',
            old_name='purchase_su_organization__4718e7_idx',
        ),
        migrations.RenameIndex(
            model_name='purchasesuggestion',
            new_name='purchase_su_tenant__4e31ba_idx',
            old_name='purchase_su_organization__4e31ba_idx',
        ),
        migrations.RenameIndex(
            model_name='replenishmentrule',
            new_name='replenishme_tenant__216cbb_idx',
            old_name='replenishme_organization__216cbb_idx',
        ),
        migrations.RenameIndex(
            model_name='shipment',
            new_name='shipment_tenant__904ae2_idx',
            old_name='shipment_organization__904ae2_idx',
        ),
        migrations.RenameIndex(
            model_name='stockadjustmentorder',
            new_name='stock_adjus_tenant__32c7e3_idx',
            old_name='stock_adjus_organization__32c7e3_idx',
        ),
        migrations.RenameIndex(
            model_name='stockadjustmentorder',
            new_name='stock_adjus_tenant__6379d2_idx',
            old_name='stock_adjus_organization__6379d2_idx',
        ),
        migrations.RenameIndex(
            model_name='stockalert',
            new_name='stock_alert_tenant__0e1ee9_idx',
            old_name='stock_alert_organization__0e1ee9_idx',
        ),
        migrations.RenameIndex(
            model_name='stockalert',
            new_name='stock_alert_tenant__d0b067_idx',
            old_name='stock_alert_organization__d0b067_idx',
        ),
        migrations.RenameIndex(
            model_name='stockalert',
            new_name='stock_alert_tenant__6e5562_idx',
            old_name='stock_alert_organization__6e5562_idx',
        ),
        migrations.RenameIndex(
            model_name='stockcostlayer',
            new_name='stock_cost__tenant__eb8e7d_idx',
            old_name='stock_cost__organization__eb8e7d_idx',
        ),
        migrations.RenameIndex(
            model_name='stockcostlayer',
            new_name='stock_cost__tenant__1082d2_idx',
            old_name='stock_cost__organization__1082d2_idx',
        ),
        migrations.RenameIndex(
            model_name='stockledger',
            new_name='stock_ledge_tenant__a4d0a5_idx',
            old_name='stock_ledge_organization__a4d0a5_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmove',
            new_name='stock_move_tenant__d85b58_idx',
            old_name='stock_move_organization__d85b58_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransferorder',
            new_name='stock_trans_tenant__abd0bb_idx',
            old_name='stock_trans_organization__abd0bb_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransferorder',
            new_name='stock_trans_tenant__4e3b8c_idx',
            old_name='stock_trans_organization__4e3b8c_idx',
        ),
        migrations.RenameIndex(
            model_name='stockvaluationentry',
            new_name='stock_valua_tenant__9b19ac_idx',
            old_name='stock_valua_organization__9b19ac_idx',
        ),
        migrations.RemoveField(
            model_name='barcodechangerequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='barcodechangerequest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='barcodepolicy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='barcodepolicy',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='categorycreationrule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='categorycreationrule',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='labelpolicy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='labelpolicy',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='labelrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='labelrecord',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='labeltemplate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='labeltemplate',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pricechangerequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pricechangerequest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='printerconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='printerconfig',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='printsessionitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='printsessionitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productaudittrail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productaudittrail',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productbarcode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productbarcode',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productfreshprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productfreshprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='producttask',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='producttask',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='weightedproductpolicy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='weightedproductpolicy',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='brand',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='combocomponent',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='labelpolicy',
            name='auto_approve_for_roles',
            field=models.JSONField(blank=True, default=list, help_text='List of role names that auto-approve print sessions'),
        ),
        migrations.AddField(
            model_name='labelpolicy',
            name='require_approval_before_print',
            field=models.BooleanField(default=False, help_text='Require manager approval before sessions can be printed'),
        ),
        migrations.AddField(
            model_name='parfum',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_regulation',
            field=models.ForeignKey(blank=True, help_text='Active government price regulation for this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='compliance.priceregulation'),
        ),
        migrations.AddField(
            model_name='product',
            name='regulation_checked_at',
            field=models.DateTimeField(blank=True, help_text='Last time compliance was checked for this product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='regulation_status',
            field=models.CharField(choices=[('NOT_REGULATED', 'Not regulated'), ('COMPLIANT', 'Compliant'), ('VIOLATION', 'Price violates regulation'), ('EXEMPT', 'Exempt from regulation')], db_index=True, default='NOT_REGULATED', help_text='Current compliance status with price regulation', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='regulation_violation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='How much over/under the regulated price (null if compliant)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='productserial',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='unit',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='warehousezone',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='adjustmentreason',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='barcodechangerequest',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='barcodechangerequest',
            name='packaging',
            field=models.ForeignKey(blank=True, help_text='If set, this change is for a packaging-level barcode', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barcode_change_requests', to='inventory.productpackaging'),
        ),
        migrations.AlterField(
            model_name='barcodechangerequest',
            name='review_notes',
            field=models.TextField(blank=True, default='', help_text='Notes from the reviewer (approve/reject rationale)'),
        ),
        migrations.AlterField(
            model_name='barcodepolicy',
            name='auto_generate_on_create',
            field=models.BooleanField(default=True, help_text='Auto-generate barcode when product is created without one'),
        ),
        migrations.AlterField(
            model_name='barcodepolicy',
            name='category_prefix_enabled',
            field=models.BooleanField(default=True, help_text='Include category.code in generated barcodes'),
        ),
        migrations.AlterField(
            model_name='barcodepolicy',
            name='change_requires_approval',
            field=models.BooleanField(default=False, help_text='Barcode changes require BarcodeChangeRequest approval'),
        ),
        migrations.AlterField(
            model_name='barcodepolicy',
            name='checksum_enabled',
            field=models.BooleanField(default=True, help_text='Validate check digit on barcode entry'),
        ),
        migrations.AlterField(
            model_name='barcodepolicy',
            name='format',
            field=models.CharField(choices=[('EAN13', 'EAN-13 (13 digits, European standard)'), ('EAN8', 'EAN-8 (8 digits, small items)'), ('CODE128', 'Code 128 (alphanumeric, variable length)'), ('UPC_A', 'UPC-A (12 digits, North America)'), ('FREE', 'Free format (no validation)')], default='EAN13', help_text='Expected barcode format for validation', max_length=10),
        ),
        migrations.AlterField(
            model_name='barcodepolicy',
            name='mode',
            field=models.CharField(choices=[('SUPPLIER', 'Use supplier barcodes only'), ('INTERNAL_AUTO', 'Auto-generate internal barcodes'), ('MANUAL', 'Manual entry only'), ('HYBRID', 'Supplier preferred, auto-generate if missing')], default='HYBRID', help_text='How barcodes are sourced for new products', max_length=15),
        ),
        migrations.AlterField(
            model_name='barcodepolicy',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='barcodepolicy',
            name='prefix',
            field=models.CharField(default='2', help_text='Org-level prefix for internally generated barcodes', max_length=20),
        ),
        migrations.AlterField(
            model_name='barcodepolicy',
            name='uniqueness_scope',
            field=models.CharField(choices=[('ORGANIZATION', 'Unique within organization'), ('GLOBAL', 'Globally unique across all orgs')], default='ORGANIZATION', help_text='Scope of barcode uniqueness enforcement', max_length=15),
        ),
        migrations.AlterField(
            model_name='brand',
            name='attributes',
            field=models.ManyToManyField(blank=True, help_text='Attribute groups relevant for this brand (e.g. Parfum, Concentration)', related_name='brands', to='inventory.productattribute'),
        ),
        migrations.AlterField(
            model_name='category',
            name='attributes',
            field=models.ManyToManyField(blank=True, help_text='Attribute groups relevant for products in this category (e.g. Size, Color, Parfum)', related_name='categories', to='inventory.productattribute'),
        ),
        migrations.AlterField(
            model_name='categorycreationrule',
            name='auto_create_packaging',
            field=models.BooleanField(default=False, help_text='Auto-create packaging levels on product creation'),
        ),
        migrations.AlterField(
            model_name='categorycreationrule',
            name='auto_print_label',
            field=models.BooleanField(default=True, help_text='Auto-create print label task on product creation'),
        ),
        migrations.AlterField(
            model_name='categorycreationrule',
            name='barcode_mode_override',
            field=models.CharField(blank=True, choices=[('', 'Use org default'), ('INTERNAL_AUTO', 'Always auto-generate'), ('SUPPLIER', 'Supplier barcode required'), ('MANUAL', 'Manual entry only')], default='', help_text='Override org barcode mode for this category', max_length=15),
        ),
        migrations.AlterField(
            model_name='categorycreationrule',
            name='barcode_prefix',
            field=models.CharField(blank=True, default='', help_text='Category-specific barcode prefix (overrides org policy)', max_length=10),
        ),
        migrations.AlterField(
            model_name='categorycreationrule',
            name='completeness_profile_override',
            field=models.CharField(blank=True, choices=[('', 'Use product_type default'), ('STANDARD', 'Full L0-L7'), ('COMBO', 'L0-L4'), ('SERVICE', 'L0-L2')], default='', help_text='Override completeness profile for this category', max_length=20),
        ),
        migrations.AlterField(
            model_name='categorycreationrule',
            name='default_product_type',
            field=models.CharField(blank=True, choices=[('', 'Use form selection'), ('STANDARD', 'Standard Product'), ('COMBO', 'Combo / Bundle'), ('SERVICE', 'Service'), ('BLANK', 'Blank / Internal'), ('FRESH', 'Fresh / Variable Weight')], default='', help_text='Auto-set product_type when category is selected', max_length=20),
        ),
        migrations.AlterField(
            model_name='categorycreationrule',
            name='default_tva_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default TVA rate for products in this category', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='categorycreationrule',
            name='default_unit_id',
            field=models.ForeignKey(blank=True, help_text='Default unit of measure for products in this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_categories', to='inventory.unit'),
        ),
        migrations.AlterField(
            model_name='categorycreationrule',
            name='label_template',
            field=models.CharField(blank=True, default='', help_text='Label template to use (e.g. shelf_label, packaging_label)', max_length=50),
        ),
        migrations.AlterField(
            model_name='categorycreationrule',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='categorycreationrule',
            name='packaging_template',
            field=models.JSONField(blank=True, default=list, help_text='Template for auto-created packaging. Format: [{name, ratio, unit_id}]'),
        ),
        migrations.AlterField(
            model_name='categorycreationrule',
            name='requires_barcode',
            field=models.BooleanField(default=False, help_text='Product must have a barcode before saving'),
        ),
        migrations.AlterField(
            model_name='categorycreationrule',
            name='requires_brand',
            field=models.BooleanField(default=False, help_text='Brand is mandatory for this category'),
        ),
        migrations.AlterField(
            model_name='categorycreationrule',
            name='requires_packaging',
            field=models.BooleanField(default=False, help_text='At least one packaging level required'),
        ),
        migrations.AlterField(
            model_name='categorycreationrule',
            name='requires_photo',
            field=models.BooleanField(default=False, help_text='Product image is mandatory'),
        ),
        migrations.AlterField(
            model_name='categorycreationrule',
            name='requires_supplier',
            field=models.BooleanField(default=False, help_text='At least one supplier must be linked'),
        ),
        migrations.AlterField(
            model_name='categorycreationrule',
            name='requires_unit',
            field=models.BooleanField(default=True, help_text='Unit of measure is mandatory'),
        ),
        migrations.AlterField(
            model_name='categorycreationrule',
            name='shelf_placement_required',
            field=models.BooleanField(default=True, help_text='Auto-create shelf placement task'),
        ),
        migrations.AlterField(
            model_name='costlayerconsumption',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='cyclecountpolicy',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='expiryalert',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='groupingrule',
            name='auto_name_template',
            field=models.CharField(blank=True, default='{brand} {attribute} {size}', help_text='Template for auto-generated group names. Vars: {brand}, {attribute}, {category}, {parfum}, {size}', max_length=300),
        ),
        migrations.AlterField(
            model_name='groupingrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groupingrule',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='inventorybalance',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='inventorybalancehistory',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='inventoryfreezeperiod',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='inventorygroup',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Optional brand filter for this group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_groups', to='inventory.brand'),
        ),
        migrations.AlterField(
            model_name='inventorygroup',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='inventorygroupmember',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='inventorysessionline',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='labelpolicy',
            name='auto_invalidate_on',
            field=models.CharField(choices=[('BARCODE_CHANGE', 'Invalidate on barcode change'), ('PRICE_CHANGE', 'Invalidate on price change'), ('BOTH', 'Invalidate on barcode or price change'), ('MANUAL', 'Manual invalidation only')], default='BOTH', help_text='When existing labels should be marked as invalid', max_length=15),
        ),
        migrations.AlterField(
            model_name='labelpolicy',
            name='default_fresh_template',
            field=models.CharField(blank=True, default='fresh_weight', help_text='Default template for fresh/variable-weight labels', max_length=50),
        ),
        migrations.AlterField(
            model_name='labelpolicy',
            name='default_packaging_template',
            field=models.CharField(blank=True, default='packaging_standard', help_text='Default template for packaging/barcode labels', max_length=50),
        ),
        migrations.AlterField(
            model_name='labelpolicy',
            name='default_shelf_template',
            field=models.CharField(blank=True, default='shelf_standard', help_text='Default template for shelf labels', max_length=50),
        ),
        migrations.AlterField(
            model_name='labelpolicy',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='labelpolicy',
            name='require_reprint_after_barcode_change',
            field=models.BooleanField(default=True, help_text='Auto-create PRINT_LABEL task after barcode change'),
        ),
        migrations.AlterField(
            model_name='labelpolicy',
            name='require_reprint_after_price_change',
            field=models.BooleanField(default=True, help_text='Auto-create PRINT_LABEL task after price change'),
        ),
        migrations.AlterField(
            model_name='labelpolicy',
            name='retention_days',
            field=models.IntegerField(default=365, help_text='How many days to keep label print history'),
        ),
        migrations.AlterField(
            model_name='labelrecord',
            name='label_type',
            field=models.CharField(choices=[('SHELF', 'Shelf label'), ('BARCODE', 'Barcode label'), ('PACKAGING', 'Packaging label'), ('FRESH', 'Fresh/weight label'), ('CUSTOM', 'Custom label')], default='SHELF', max_length=10),
        ),
        migrations.AlterField(
            model_name='labelrecord',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='labelrecord',
            name='packaging',
            field=models.ForeignKey(blank=True, help_text='If set, label for a specific packaging level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_records', to='inventory.productpackaging'),
        ),
        migrations.AlterField(
            model_name='labelrecord',
            name='printed_barcode',
            field=models.CharField(blank=True, help_text='Barcode as printed', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labelrecord',
            name='printed_name',
            field=models.CharField(help_text='Product/package name as printed', max_length=255),
        ),
        migrations.AlterField(
            model_name='labelrecord',
            name='printed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price as printed (TTC)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='labelrecord',
            name='printed_unit',
            field=models.CharField(blank=True, help_text='Unit of measure as printed', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labelrecord',
            name='reason',
            field=models.CharField(choices=[('INITIAL', 'Initial print (product creation)'), ('PRICE_CHANGE', 'Price changed'), ('BARCODE_CHANGE', 'Barcode changed'), ('RESTOCK', 'Restocking / shelf refresh'), ('DAMAGED', 'Previous label damaged'), ('CORRECTION', 'Data correction'), ('MANUAL', 'Manual reprint request')], default='INITIAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='labelrecord',
            name='status',
            field=models.CharField(choices=[('VALID', 'Currently valid'), ('INVALIDATED', 'Invalidated by data change'), ('REPRINTED', 'Superseded by reprint')], default='VALID', max_length=15),
        ),
        migrations.AlterField(
            model_name='labelrecord',
            name='template_name',
            field=models.CharField(default='shelf_standard', help_text='Label template used for printing', max_length=50),
        ),
        migrations.AlterField(
            model_name='labelrecord',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Label version number (increments on reprint)'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='columns',
            field=models.PositiveIntegerField(default=3, help_text='Number of labels per row'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='dpi',
            field=models.PositiveIntegerField(default=203, help_text='Target print resolution'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='gap_horizontal_mm',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Horizontal gap between labels', max_digits=6),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='gap_vertical_mm',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Vertical gap between labels', max_digits=6),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default template for its label type'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System template — cannot be deleted, only cloned'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='label_height_mm',
            field=models.DecimalField(decimal_places=2, default=30, help_text='Label height in millimeters', max_digits=8),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='label_width_mm',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Label width in millimeters', max_digits=8),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='preview_image',
            field=models.CharField(blank=True, default='', help_text='Path to preview thumbnail image', max_length=500),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='rows',
            field=models.PositiveIntegerField(default=10, help_text='Number of label rows per page'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='template_schema_version',
            field=models.CharField(default='1.0', help_text='Schema version for template format compatibility', max_length=10),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='variables_schema',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed variable names for this template'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Template version (increments on edit)'),
        ),
        migrations.AlterField(
            model_name='operationalrequest',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='operationalrequestline',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='packingorder',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='picklist',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='picklistline',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='priceapprovalpolicy',
            name='action',
            field=models.CharField(choices=[('AUTO_APPROVE', 'Auto-approve and apply'), ('AUTO_APPROVE_PENDING_VERIFY', 'Auto-approve, apply, but require verification'), ('BLOCK', 'Block — must have manual approval')], default='BLOCK', max_length=30),
        ),
        migrations.AlterField(
            model_name='priceapprovalpolicy',
            name='allow_group_changes',
            field=models.BooleanField(default=False, help_text='Can this policy auto-approve group-level price changes?'),
        ),
        migrations.AlterField(
            model_name='priceapprovalpolicy',
            name='applies_to_role',
            field=models.CharField(blank=True, help_text='User role this applies to (e.g. "manager", "owner", "cashier")', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='priceapprovalpolicy',
            name='applies_to_user',
            field=models.ForeignKey(blank=True, help_text='Specific user this applies to (overrides role)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_approval_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='priceapprovalpolicy',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max absolute price change amount for auto-approval', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='priceapprovalpolicy',
            name='max_delta_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max allowed price change % for auto-approval (null=unlimited)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='priceapprovalpolicy',
            name='min_margin_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum margin % that must be maintained after change', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='priceapprovalpolicy',
            name='name',
            field=models.CharField(help_text='Policy name, e.g. "Manager Auto-Approve"', max_length=100),
        ),
        migrations.AlterField(
            model_name='priceapprovalpolicy',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='priceapprovalpolicy',
            name='priority',
            field=models.PositiveIntegerField(default=10, help_text='Lower = evaluated first. First matching policy wins.'),
        ),
        migrations.AlterField(
            model_name='pricechangerequest',
            name='affected_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of products affected by this change (for GROUP scope)'),
        ),
        migrations.AlterField(
            model_name='pricechangerequest',
            name='auto_approval_reason',
            field=models.CharField(blank=True, help_text='Why auto-approval was granted (e.g. "trusted role", "delta < 2%")', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pricechangerequest',
            name='change_scope',
            field=models.CharField(choices=[('PRODUCT', 'Single Product'), ('GROUP', 'Price Group (all members)')], default='PRODUCT', help_text='Whether this change targets one product or an entire group', max_length=10),
        ),
        migrations.AlterField(
            model_name='pricechangerequest',
            name='is_auto_approved',
            field=models.BooleanField(default=False, help_text='True if this was auto-approved by policy (role/threshold)'),
        ),
        migrations.AlterField(
            model_name='pricechangerequest',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='pricechangerequest',
            name='price_group',
            field=models.ForeignKey(blank=True, help_text='Target price group (for GROUP scope changes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_change_requests', to='inventory.productgroup'),
        ),
        migrations.AlterField(
            model_name='pricechangerequest',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Target product (null if scope=GROUP)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_change_requests', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='pricechangerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied'), ('VERIFIED', 'Verified'), ('CANCELLED', 'Cancelled'), ('AUTO_APPROVED', 'Auto-Approved')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='printerconfig',
            name='address',
            field=models.CharField(blank=True, default='', help_text='IP address, USB port, or Bluetooth address', max_length=255),
        ),
        migrations.AlterField(
            model_name='printerconfig',
            name='default_label_type',
            field=models.CharField(blank=True, default='', help_text='Default label type for this printer (auto-assign)', max_length=10),
        ),
        migrations.AlterField(
            model_name='printerconfig',
            name='device_identifier',
            field=models.CharField(blank=True, default='', help_text='Unique device ID (serial number, MAC, etc.)', max_length=200),
        ),
        migrations.AlterField(
            model_name='printerconfig',
            name='dpi',
            field=models.PositiveIntegerField(default=203, help_text='Print resolution (dots per inch)'),
        ),
        migrations.AlterField(
            model_name='printerconfig',
            name='driver_name',
            field=models.CharField(blank=True, default='', help_text='Driver name (e.g. ZPL, EPL, ESC/POS, PDF)', max_length=100),
        ),
        migrations.AlterField(
            model_name='printerconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='printerconfig',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, help_text='Last time printer was online/responsive', null=True),
        ),
        migrations.AlterField(
            model_name='printerconfig',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Physical location (e.g. Warehouse A, Reception Desk)', max_length=200),
        ),
        migrations.AlterField(
            model_name='printerconfig',
            name='model_name',
            field=models.CharField(blank=True, default='', help_text='Printer model (e.g. Zebra ZD421, Brother QL-820)', max_length=100),
        ),
        migrations.AlterField(
            model_name='printerconfig',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='printerconfig',
            name='paper_width_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max paper width in mm', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='printerconfig',
            name='supported_label_types',
            field=models.JSONField(blank=True, default=list, help_text='List of label types this printer handles (SHELF, BARCODE, etc.)'),
        ),
        migrations.AlterField(
            model_name='printerconfig',
            name='supports_epl',
            field=models.BooleanField(default=False, help_text='Eltron EPL support'),
        ),
        migrations.AlterField(
            model_name='printerconfig',
            name='supports_escpos',
            field=models.BooleanField(default=False, help_text='ESC/POS support'),
        ),
        migrations.AlterField(
            model_name='printerconfig',
            name='supports_zpl',
            field=models.BooleanField(default=False, help_text='Zebra ZPL support'),
        ),
        migrations.AlterField(
            model_name='printerconfig',
            name='test_message',
            field=models.TextField(blank=True, default='', help_text='Detailed test result message'),
        ),
        migrations.AlterField(
            model_name='printerconfig',
            name='test_status',
            field=models.CharField(blank=True, default='', help_text='PASS, FAIL, UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='printsession',
            name='copies',
            field=models.PositiveIntegerField(default=1, help_text='Number of copies per label'),
        ),
        migrations.AlterField(
            model_name='printsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='printsession',
            name='job_reference',
            field=models.CharField(blank=True, default='', help_text='External job/spool ID for printer tracking', max_length=100),
        ),
        migrations.AlterField(
            model_name='printsession',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='printsession',
            name='original_session',
            field=models.ForeignKey(blank=True, help_text='Original session if this is a reprint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprints', to='inventory.printsession'),
        ),
        migrations.AlterField(
            model_name='printsession',
            name='output_checksum',
            field=models.CharField(blank=True, default='', help_text='SHA-256 of the rendered output', max_length=64),
        ),
        migrations.AlterField(
            model_name='printsession',
            name='output_method',
            field=models.CharField(choices=[('PDF', 'PDF export'), ('THERMAL', 'Direct to thermal printer'), ('BROWSER', 'Browser print dialog')], default='PDF', max_length=10),
        ),
        migrations.AlterField(
            model_name='printsession',
            name='output_path',
            field=models.CharField(blank=True, default='', help_text='Path to rendered output file (PDF, etc.)', max_length=500),
        ),
        migrations.AlterField(
            model_name='printsession',
            name='render_context_hash',
            field=models.CharField(blank=True, default='', help_text='Hash of the data used for rendering — detects if reprint would differ', max_length=64),
        ),
        migrations.AlterField(
            model_name='printsession',
            name='reprint_mode',
            field=models.CharField(blank=True, choices=[('EXACT', 'Exact reprint from snapshot'), ('REGENERATE', 'Regenerate from live product data')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='printsession',
            name='session_code',
            field=models.CharField(editable=False, help_text='Auto-generated: LBL-YYYYMMDD-NNNNNN', max_length=30),
        ),
        migrations.AlterField(
            model_name='printsession',
            name='source_context',
            field=models.CharField(choices=[('PRODUCT_LIST', 'Product listing / manual selection'), ('RECEIVING', 'Goods receiving / purchase receipt'), ('STOCK_COUNT', 'Stock count results'), ('STOCK_TRANSFER', 'Stock transfer'), ('PACKAGING', 'Packaging change'), ('PRICE_UPDATE', 'Price update / batch'), ('BARCODE_GEN', 'Barcode generation'), ('SCHEDULER', 'Scheduled / automated')], default='PRODUCT_LIST', help_text='What operation spawned this session', max_length=20),
        ),
        migrations.AlterField(
            model_name='printsession',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft - selecting products'), ('APPROVED', 'Approved - awaiting queue'), ('QUEUED', 'Queued - ready to print'), ('PRINTING', 'Printing in progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15),
        ),
        migrations.AlterField(
            model_name='printsession',
            name='trigger',
            field=models.CharField(choices=[('MANUAL', 'Manually created'), ('PURCHASE', 'Auto - product purchased'), ('TRANSFER', 'Auto - stock transfer'), ('PRICE_CHANGE', 'Auto - price changed'), ('BARCODE_GEN', 'Auto - barcode generated'), ('NEW_PRODUCT', 'Auto - new product created')], default='MANUAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='printsessionitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='printsessionitem',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='printsessionitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Nullable — snapshot survives product deletion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_queue_items', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='printsessionitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of labels to print'),
        ),
        migrations.AlterField(
            model_name='printsessionitem',
            name='snapshot_packaging_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Units per packaging', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='printsessionitem',
            name='snapshot_product_ref',
            field=models.CharField(blank=True, default='', help_text='Internal product reference code', max_length=100),
        ),
        migrations.AlterField(
            model_name='printsessionitem',
            name='snapshot_tax_mode',
            field=models.CharField(blank=True, default='TTC', help_text='HT or TTC — price display mode at print time', max_length=5),
        ),
        migrations.AlterField(
            model_name='printsessionitem',
            name='snapshot_template_version',
            field=models.PositiveIntegerField(default=1, help_text='Template version used at render time'),
        ),
        migrations.AlterField(
            model_name='printsessionitem',
            name='snapshot_variant_summary',
            field=models.CharField(blank=True, default='', help_text='e.g. "Color: Red, Size: XL"', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, help_text='Dynamic attribute values assigned to this product (leaf nodes from attribute tree)', related_name='products_with_attribute', to='inventory.productattribute'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='LEGACY MIRROR — authoritative barcode lives in ProductBarcode table', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the barcode was auto-generated (null if supplier/manual)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_name',
            field=models.CharField(blank=True, help_text='Core product identity without brand or attributes. E.g. "Orange Juice", "Premium Rice", "Eau de Parfum". Used by the nomenclature engine to generate the full display name.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='catalog_description',
            field=models.TextField(blank=True, help_text='Marketing/catalog description for eCommerce and print', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='catalog_ready',
            field=models.BooleanField(default=False, help_text='Product is approved for catalog/eCommerce display'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group_broken_since',
            field=models.DateTimeField(blank=True, help_text='When the group price divergence was detected', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='group_expected_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What the group expected the price to be', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='group_sync_status',
            field=models.CharField(choices=[('SYNCED', 'Synced with group'), ('BROKEN', 'Broken — price differs from group'), ('LOCAL_OVERRIDE', 'Local override — intentional'), ('PENDING', 'Pending group sync'), ('N/A', 'Not in a pricing group')], default='N/A', help_text='Whether this product price matches its pricing group', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_parent',
            field=models.BooleanField(default=False, help_text='True = this product is a variant group parent (not sold directly)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Manually set by controller/manager to mark product as verified'),
        ),
        migrations.AlterField(
            model_name='product',
            name='media_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of media assets (images, videos) attached'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Full display name. Can be auto-generated from base_name + brand + shown attributes.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='product',
            name='parent_product',
            field=models.ForeignKey(blank=True, help_text='Parent product for variant grouping. Null = standalone or is a parent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_children', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pricing_source',
            field=models.CharField(choices=[('LOCAL', 'Local — product-level price'), ('GROUP', 'Group — inherits from ProductGroup')], default='LOCAL', help_text='Whether this product uses its own price or inherits from its group', max_length=5),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='color_hex',
            field=models.CharField(blank=True, help_text='Optional color swatch for visual attributes (e.g. #FF0000 for Red)', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='is_required',
            field=models.BooleanField(default=False, help_text='If True, a value MUST be selected for this attribute when creating products in linked categories. Enforcement is on the frontend form.'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='is_variant',
            field=models.BooleanField(default=False, help_text='If True, values of this attribute define separate variant SKUs (e.g. Size). If False, values are classification only (e.g. Parfum, Gender).'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='name_position',
            field=models.IntegerField(default=99, help_text='Position in the generated product name (0=immediately after base name, 1=second, etc.). Lower = earlier. Only meaningful when show_in_name=True.'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='short_label',
            field=models.CharField(blank=True, help_text='Abbreviated label for name generation. If set, value is suffixed with this label instead of the group name. E.g. short_label="ml" → "180ml" instead of "Volume: 180". Null = use raw value name as-is.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='show_by_default',
            field=models.BooleanField(default=True, help_text='If True, this attribute group appears expanded/visible by default in the Add/Edit Product form. If False, it is collapsed under "More attributes".'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='show_in_name',
            field=models.BooleanField(default=False, help_text='If True, selected values of this group appear in the auto-generated product display name. E.g. Volume=180ml → "Pepsi Orange Juice 180ml". Only meaningful on root attribute groups.'),
        ),
        migrations.AlterField(
            model_name='productaudittrail',
            name='event_type',
            field=models.CharField(choices=[('VERIFIED', 'Product Verified'), ('UNVERIFIED', 'Verification Removed'), ('LEVEL_CHANGE', 'Completeness Level Changed'), ('PRICE_REQUEST', 'Price Change Requested'), ('PRICE_APPROVED', 'Price Change Approved'), ('PRICE_REJECTED', 'Price Change Rejected'), ('PRICE_APPLIED', 'Price Change Applied'), ('FIELD_UPDATE', 'Product Field Updated'), ('BARCODE_GENERATED', 'Barcode Generated'), ('BARCODE_CHANGED', 'Barcode Changed'), ('PKG_CREATED', 'Packaging Created'), ('PKG_UPDATED', 'Packaging Updated'), ('PKG_DELETED', 'Packaging Deleted'), ('PKG_VERIFIED', 'Packaging Verified'), ('SUPPLIER_LINKED', 'Supplier Linked'), ('SUPPLIER_REMOVED', 'Supplier Removed'), ('LABEL_PRINTED', 'Label Printed'), ('GROUP_SYNC', 'Group Price Synced'), ('GROUP_BROKEN', 'Group Price Broken'), ('GROUP_RESTORED', 'Group Price Restored'), ('GROUP_OVERRIDE', 'Local Price Override')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productaudittrail',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='productbarcode',
            name='barcode_type',
            field=models.CharField(choices=[('PRIMARY', 'Primary barcode — single source of truth'), ('ALIAS', 'Alternative barcode (old packaging, regional)'), ('SUPPLIER', 'Supplier-assigned barcode'), ('INTERNAL', 'Internally generated barcode'), ('PACKAGING', 'Packaging-level barcode'), ('RETIRED', 'Retired / historical — kept for audit lookup')], default='PRIMARY', max_length=10),
        ),
        migrations.AlterField(
            model_name='productbarcode',
            name='code',
            field=models.CharField(db_index=True, help_text='The barcode value', max_length=100),
        ),
        migrations.AlterField(
            model_name='productbarcode',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive barcodes are kept for history but not resolved in POS lookup'),
        ),
        migrations.AlterField(
            model_name='productbarcode',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='productbarcode',
            name='packaging',
            field=models.ForeignKey(blank=True, help_text='If set, this barcode is specific to a packaging level', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barcode_records', to='inventory.productpackaging'),
        ),
        migrations.AlterField(
            model_name='productbarcode',
            name='source',
            field=models.CharField(choices=[('SCANNED', 'Scanned from physical product'), ('GENERATED', 'Auto-generated by system'), ('MANUAL', 'Manually entered'), ('IMPORTED', 'Imported from external system')], default='MANUAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='productfreshprofile',
            name='allergens',
            field=models.TextField(blank=True, default='', help_text='Allergen declarations (comma-separated)'),
        ),
        migrations.AlterField(
            model_name='productfreshprofile',
            name='ingredients',
            field=models.TextField(blank=True, default='', help_text='Ingredients list for label printing'),
        ),
        migrations.AlterField(
            model_name='productfreshprofile',
            name='max_weight_grams',
            field=models.IntegerField(default=0, help_text='Maximum weight threshold for QA alert'),
        ),
        migrations.AlterField(
            model_name='productfreshprofile',
            name='min_weight_grams',
            field=models.IntegerField(default=0, help_text='Minimum weight threshold for QA rejection'),
        ),
        migrations.AlterField(
            model_name='productfreshprofile',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='productfreshprofile',
            name='origin_country',
            field=models.CharField(blank=True, default='', help_text='Country of origin for traceability', max_length=100),
        ),
        migrations.AlterField(
            model_name='productfreshprofile',
            name='plu_code',
            field=models.CharField(blank=True, default='', help_text='PLU code for this product (used at POS scale)', max_length=10),
        ),
        migrations.AlterField(
            model_name='productfreshprofile',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per kilogram (the base reference price)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='productfreshprofile',
            name='shelf_life_days',
            field=models.IntegerField(default=3, help_text='Days until best-before from production/weighing date'),
        ),
        migrations.AlterField(
            model_name='productfreshprofile',
            name='storage_instructions',
            field=models.CharField(blank=True, default='', help_text='Storage instructions (e.g. "Keep refrigerated at 4°C")', max_length=255),
        ),
        migrations.AlterField(
            model_name='productfreshprofile',
            name='tare_weight_grams',
            field=models.IntegerField(default=0, help_text='Tare (packaging) weight to deduct from gross weight'),
        ),
        migrations.AlterField(
            model_name='productfreshprofile',
            name='typical_weight_grams',
            field=models.IntegerField(default=0, help_text='Typical weight per unit in grams (for estimation)'),
        ),
        migrations.AlterField(
            model_name='productfreshprofile',
            name='use_by_days',
            field=models.IntegerField(blank=True, help_text='Days until use-by (null = no use-by, only best-before)', null=True),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='margin_floor_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum allowed margin % — system warns below this', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='margin_rule_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For MARGIN_RULE mode: target margin % applied to each member cost', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='override_policy',
            field=models.CharField(choices=[('INHERIT', 'Members inherit group price, no local override'), ('ALLOW_LOCAL', 'Members can override locally'), ('LOCK_LOCAL', 'Members locked to group price')], default='INHERIT', help_text='Whether member products can override the group price', max_length=15),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='price_band_values',
            field=models.JSONField(blank=True, default=list, help_text='Allowed price tiers for BAND mode, e.g. [200, 250, 300, 350]'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='pricing_mode',
            field=models.CharField(choices=[('FIXED', 'Fixed Price — all members sell at same price'), ('MARGIN_RULE', 'Margin Rule — cost + fixed margin %'), ('CEILING', 'Ceiling — members cannot exceed this price'), ('BAND', 'Price Band — snap to allowed price tiers'), ('MANUAL', 'Manual Override — manager pushes price to all')], default='FIXED', help_text='How the group price is applied to members', max_length=15),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='rounding_rule',
            field=models.CharField(choices=[('NONE', 'No rounding'), ('NEAREST_5', 'Round to nearest 5'), ('NEAREST_10', 'Round to nearest 10'), ('NEAREST_25', 'Round to nearest 25'), ('NEAREST_50', 'Round to nearest 50'), ('NEAREST_100', 'Round to nearest 100')], default='NONE', help_text='How final prices are rounded', max_length=15),
        ),
        migrations.AlterField(
            model_name='productlocation',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='barcode',
            field=models.CharField(blank=True, help_text='LEGACY MIRROR — authoritative barcode lives in ProductBarcode table', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='custom_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override selling price (TTC) for this level', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Package-level verification (independent of product verification)'),
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='label_version',
            field=models.PositiveIntegerField(default=0, help_text='Label version counter — increments on each reprint'),
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='is_catalog_ready',
            field=models.BooleanField(default=False, help_text='Product has image, catalog description, and is approved for display'),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='is_label_ready',
            field=models.BooleanField(default=False, help_text='Product has a valid label currently printed (not invalidated)'),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='is_purchase_ready',
            field=models.BooleanField(default=False, help_text='Product has at least one active supplier with valid pricing'),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='is_replenishment_ready',
            field=models.BooleanField(default=False, help_text='Product has min_stock_level set and replenishment rule configured'),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='is_scan_ready',
            field=models.BooleanField(default=False, help_text='Product has a valid primary barcode and is resolvable by POS scanner'),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='is_shelf_ready',
            field=models.BooleanField(default=False, help_text='Product has been placed on shelf with location assigned'),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='last_assessed_at',
            field=models.DateTimeField(auto_now=True, help_text='When readiness was last computed'),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='last_assessed_by',
            field=models.CharField(default='system', help_text='Who/what triggered the last assessment', max_length=50),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='producttask',
            name='assigned_role',
            field=models.CharField(blank=True, default='', help_text='Role hint for unassigned tasks (e.g. shelf_manager, print_center, controller)', max_length=50),
        ),
        migrations.AlterField(
            model_name='producttask',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='producttask',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the source entity (e.g. PriceChangeRequest.id)', null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='purchasesuggestion',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='replenishmentrule',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='seriallog',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='stockadjustmentline',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='stockadjustmentorder',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='stockcostlayer',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='stockmoveline',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='stocktransferline',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='stocktransferorder',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='stockvaluationentry',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='warehouseaisle',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='warehousebin',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='warehouserack',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='warehouseshelf',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='weightedproductpolicy',
            name='default_shelf_life_days',
            field=models.IntegerField(default=3, help_text='Default shelf life in days for fresh products'),
        ),
        migrations.AlterField(
            model_name='weightedproductpolicy',
            name='default_tare_grams',
            field=models.IntegerField(default=0, help_text='Default tare weight in grams (packaging deduction)'),
        ),
        migrations.AlterField(
            model_name='weightedproductpolicy',
            name='encoding_mode',
            field=models.CharField(choices=[('PRICE_EMBEDDED', 'Price embedded in barcode (digits 7-11 = price)'), ('WEIGHT_EMBEDDED', 'Weight embedded in barcode (digits 7-11 = weight in grams)'), ('PLU', 'PLU code lookup (no weight/price in barcode)')], default='PRICE_EMBEDDED', help_text='How weight/price is encoded in the barcode', max_length=15),
        ),
        migrations.AlterField(
            model_name='weightedproductpolicy',
            name='label_template',
            field=models.CharField(default='fresh_weight', help_text='Default label template for fresh products', max_length=50),
        ),
        migrations.AlterField(
            model_name='weightedproductpolicy',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='weightedproductpolicy',
            name='prefix',
            field=models.CharField(default='2', help_text='EAN prefix for variable-weight barcodes (typically "2")', max_length=5),
        ),
        migrations.AlterField(
            model_name='weightedproductpolicy',
            name='require_best_before',
            field=models.BooleanField(default=True, help_text='Require best-before date on fresh product labels'),
        ),
        migrations.AlterField(
            model_name='weightedproductpolicy',
            name='require_tare_entry',
            field=models.BooleanField(default=False, help_text='Require tare weight entry on every weighing'),
        ),
        migrations.AlterField(
            model_name='weightedproductpolicy',
            name='require_use_by',
            field=models.BooleanField(default=False, help_text='Require use-by date (stricter than best-before)'),
        ),
        migrations.AlterField(
            model_name='weightedproductpolicy',
            name='scale_unit',
            field=models.CharField(choices=[('GRAMS', 'Weight in grams (max 99999g)'), ('CENTIGRAMS', 'Weight in centigrams (max 999.99g)'), ('PRICE_CENTS', 'Price in cents (max 999.99)')], default='GRAMS', help_text='Unit system for embedded weight', max_length=15),
        ),
        migrations.AlterField(
            model_name='weightedproductpolicy',
            name='show_allergens',
            field=models.BooleanField(default=False, help_text='Show allergen warnings on label'),
        ),
        migrations.AlterField(
            model_name='weightedproductpolicy',
            name='show_ingredients',
            field=models.BooleanField(default=False, help_text='Show ingredients list on label'),
        ),
        migrations.AlterField(
            model_name='weightedproductpolicy',
            name='show_price_per_kg',
            field=models.BooleanField(default=True, help_text='Show price-per-kg on label'),
        ),
    ]
