# Generated by Django 6.0.4 on 2026-04-20 02:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0059_alter_zatcaconfig_options_and_more'),
        ('inventory', '0053_product_tax_rate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cogs_account',
            field=models.ForeignKey(blank=True, help_text='Cost of Goods Sold GL account override (COGS postings)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_cogs', to='finance.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory_account',
            field=models.ForeignKey(blank=True, help_text='Inventory GL account override (stock valuation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_inventory', to='finance.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='parfum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.parfum'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.productgroup'),
        ),
        migrations.AlterField(
            model_name='product',
            name='revenue_account',
            field=models.ForeignKey(blank=True, help_text='Revenue GL account override for this product (Sales postings)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_revenue', to='finance.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tva_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT rate as a percentage (e.g. 18.00 = 18%). Legacy field — prefer tax_rate_category for multi-rate regimes.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.unit'),
        ),
    ]
