# Generated by Django 6.0.4 on 2026-04-20 23:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_remove_approvalrule_organization_and_more'),
        ('inventory', '0054_product_image_url_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('COUNT', 'Count'), ('WEIGHT', 'Weight'), ('VOLUME', 'Volume'), ('LENGTH', 'Length'), ('AREA', 'Area'), ('TIME', 'Time'), ('OTHER', 'Other')], default='COUNT', max_length=50),
        ),
        migrations.CreateModel(
            name='UnitPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g. "Pack of 6"', max_length=120)),
                ('code', models.CharField(blank=True, help_text='Short code, e.g. "PK6"', max_length=50, null=True)),
                ('ratio', models.DecimalField(decimal_places=4, default=Decimal('1.0'), help_text='How many base UNITS this package contains', max_digits=15)),
                ('is_default', models.BooleanField(default=False, help_text='Primary package for this unit')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (ascending)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_packages', to='inventory.unit')),
            ],
            options={
                'db_table': 'unit_package',
                'ordering': ['unit_id', 'order', 'ratio'],
                'constraints': [models.UniqueConstraint(fields=('unit', 'name', 'organization'), name='unique_unit_package_name_tenant')],
            },
        ),
    ]
