# Generated by Django 6.0.4 on 2026-04-27 22:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_remove_approvalrule_organization_and_more'),
        ('inventory', '0065_brand_parfum_translations_jsonb'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='packagingsuggestionrule',
            new_name='packaging_s_tenant__ed4449_idx',
            old_name='pkg_sug_org_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='packagingsuggestionrule',
            new_name='packaging_s_tenant__846509_idx',
            old_name='pkg_sug_org_brd_idx',
        ),
        migrations.RenameIndex(
            model_name='packagingsuggestionrule',
            new_name='packaging_s_tenant__a4cfc4_idx',
            old_name='pkg_sug_org_att_idx',
        ),
        migrations.RenameIndex(
            model_name='packagingsuggestionrule',
            new_name='packaging_s_tenant__d56f89_idx',
            old_name='pkg_sug_org_pkg_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-deleted categories are hidden from default listings'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Localised brand names keyed by language code, e.g. {"fr":{"name":"...","short_name":"..."}}'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ar',
            field=models.CharField(blank=True, default='', help_text='[legacy] Arabic display name — prefer translations["ar"]', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fr',
            field=models.CharField(blank=True, default='', help_text='[legacy] French display name — prefer translations["fr"]', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Arbitrary localised names keyed by language code, e.g. {"fr":"Boissons","ar":"المشروبات","en":"Drinks"}'),
        ),
        migrations.AlterField(
            model_name='packagingsuggestionrule',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='parfum',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Localised attribute names keyed by language code, e.g. {"fr":{"name":"...","short_name":"..."}}'),
        ),
        migrations.AlterField(
            model_name='unitpackage',
            name='ratio',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0'), help_text='How many base UNITS this package contains (parent.ratio × parent_ratio when chained)', max_digits=15),
        ),
    ]
