# Generated by Django 5.2.11 on 2026-02-24 19:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, help_text='The custom domain, e.g. "shop.acme.com" or "platform.acme.com"', max_length=255, unique=True)),
                ('domain_type', models.CharField(choices=[('SHOP', 'Storefront / Shop'), ('PLATFORM', 'Control Panel / Admin')], default='SHOP', help_text='SHOP = storefront, PLATFORM = admin/control panel', max_length=10)),
                ('is_verified', models.BooleanField(default=False, help_text='DNS verification passed')),
                ('verification_token', models.CharField(blank=True, help_text='DNS TXT record value for domain verification', max_length=64)),
                ('ssl_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROVISIONING', 'Provisioning'), ('ACTIVE', 'Active'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=15)),
                ('is_active', models.BooleanField(default=False, help_text='Domain is verified AND SSL is active → traffic is routed')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary domain for this org + type combo (used for canonical URLs)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(help_text='The organization this domain belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='custom_domains', to='erp.organization')),
            ],
            options={
                'db_table': 'custom_domain',
                'ordering': ['-is_primary', '-is_active', 'domain'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('organization', 'domain_type'), name='unique_primary_domain_per_org_type')],
            },
        ),
    ]
