# Generated by Django 5.2.11 on 2026-03-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_seed_app_change_theme_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planaddon',
            name='addon_type',
            field=models.CharField(choices=[('users', 'Extra Users'), ('sites', 'Extra Sites'), ('storage', 'Extra Storage (GB)'), ('products', 'Extra Products'), ('invoices', 'Extra Invoices/Month'), ('customers', 'Extra Customers'), ('encryption', 'AES-256 Encryption'), ('dual_view', 'Dual View — Internal Scope Access')], max_length=20),
        ),
    ]
