# Generated by Django 5.2.12 on 2026-03-11 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_organization_finance_hard_locked_at_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='approvalrule',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='levelrolemap',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='manageroverridelog',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='site',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='transactiontype',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='transactionverificationconfig',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='transactionverificationpolicy',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
            ],
            database_operations=[]
        )
    ]
