# Generated by Django 6.0.3 on 2026-03-13 00:43

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_alter_approvalrule_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('context', models.CharField(choices=[('inventory.transfer', 'Inventory Transfer'), ('inventory.allocation', 'Order Allocation'), ('inventory.reorder', 'Reorder Point'), ('inventory.approval', 'Approval Workflow')], max_length=100)),
                ('rule_type', models.CharField(choices=[('THRESHOLD', 'Threshold Rule'), ('FORMULA', 'Formula-based Rule'), ('ML', 'Machine Learning Rule'), ('COMPOSITE', 'Composite Rule')], max_length=50)),
                ('config', models.JSONField(default=dict, help_text='Rule parameters (threshold values, formula, ML model name, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100, help_text='Lower number = higher priority')),
                ('execution_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('avg_execution_time_ms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erp_decisionrule_v2_set', to='erp.organization')),
            ],
            options={
                'verbose_name': 'Decision Rule',
                'verbose_name_plural': 'Decision Rules',
                'db_table': 'decision_rule',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=100)),
                ('decision_type', models.CharField(choices=[('APPROVE', 'Approval'), ('REJECT', 'Rejection'), ('RECOMMEND', 'Recommendation'), ('CALCULATE', 'Calculation'), ('OPTIMIZE', 'Optimization')], max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('subject_id', models.CharField(blank=True, max_length=100)),
                ('input_data', models.JSONField(help_text='Input parameters for the decision')),
                ('output_data', models.JSONField(help_text='Decision result, recommendations, calculations')),
                ('rules_applied', models.JSONField(default=list, help_text='List of rule IDs that contributed to this decision')),
                ('execution_time_ms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('was_accepted', models.BooleanField(blank=True, null=True)),
                ('actual_outcome', models.JSONField(blank=True, help_text='Actual results after decision was implemented', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erp_decisionlog_v2_set', to='erp.organization')),
            ],
            options={
                'verbose_name': 'Decision Log',
                'verbose_name_plural': 'Decision Logs',
                'db_table': 'decision_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('model_type', models.CharField(choices=[('FORECAST', 'Demand Forecasting'), ('CLASSIFICATION', 'Classification'), ('REGRESSION', 'Regression'), ('OPTIMIZATION', 'Optimization'), ('CLUSTERING', 'Clustering')], max_length=50)),
                ('algorithm', models.CharField(help_text='e.g., ARIMA, RandomForest, XGBoost', max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('model_path', models.CharField(help_text='Path to serialized model file', max_length=500)),
                ('config', models.JSONField(default=dict, help_text='Hyperparameters and training configuration')),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='Model accuracy (percentage)', max_digits=5, null=True)),
                ('last_trained_at', models.DateTimeField(blank=True, null=True)),
                ('training_samples', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('prediction_count', models.IntegerField(default=0)),
                ('avg_prediction_time_ms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erp_mlmodel_v2_set', to='erp.organization')),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
                'db_table': 'ml_model',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='decisionrule',
            index=models.Index(fields=['organization', 'context', 'is_active'], name='dec_rule_org_ctx_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionlog',
            index=models.Index(fields=['organization', 'context', '-created_at'], name='dec_log_org_ctx_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionlog',
            index=models.Index(fields=['decision_type'], name='dec_log_type_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionlog',
            index=models.Index(fields=['subject_id'], name='dec_log_subj_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['organization', 'model_type', 'is_active'], name='ml_model_org_type_idx'),
        ),
    ]
