# Generated by Django 6.0.3 on 2026-03-31 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_listview_policy'),
        ('reference', '0002_country_isolation'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(

            state_operations=[

                migrations.RenameIndex(

                    model_name='auditlog',

                    new_name='erp_auditlo_tenant__3bae30_idx',

                    old_name='erp_auditlo_organization__3bae30_idx',

                ),

            ],

            database_operations=[

                migrations.RunSQL(

                    sql="ALTER INDEX IF EXISTS erp_auditlo_organization__3bae30_idx RENAME TO erp_auditlo_tenant__3bae30_idx;",

                    reverse_sql="ALTER INDEX IF EXISTS erp_auditlo_tenant__3bae30_idx RENAME TO erp_auditlo_organization__3bae30_idx;",

                ),

            ],

        ),
        migrations.SeparateDatabaseAndState(

            state_operations=[

                migrations.RenameIndex(

                    model_name='auditlog',

                    new_name='erp_auditlo_tenant__7aa361_idx',

                    old_name='erp_auditlo_organization__7aa361_idx',

                ),

            ],

            database_operations=[

                migrations.RunSQL(

                    sql="ALTER INDEX IF EXISTS erp_auditlo_organization__7aa361_idx RENAME TO erp_auditlo_tenant__7aa361_idx;",

                    reverse_sql="ALTER INDEX IF EXISTS erp_auditlo_tenant__7aa361_idx RENAME TO erp_auditlo_organization__7aa361_idx;",

                ),

            ],

        ),
        migrations.SeparateDatabaseAndState(

            state_operations=[

                migrations.RenameIndex(

                    model_name='auditlog',

                    new_name='erp_auditlo_tenant__5422cf_idx',

                    old_name='erp_auditlo_organization__5422cf_idx',

                ),

            ],

            database_operations=[

                migrations.RunSQL(

                    sql="ALTER INDEX IF EXISTS erp_auditlo_organization__5422cf_idx RENAME TO erp_auditlo_tenant__5422cf_idx;",

                    reverse_sql="ALTER INDEX IF EXISTS erp_auditlo_tenant__5422cf_idx RENAME TO erp_auditlo_organization__5422cf_idx;",

                ),

            ],

        ),
        migrations.SeparateDatabaseAndState(

            state_operations=[

                migrations.RenameIndex(

                    model_name='auditlog',

                    new_name='erp_auditlo_tenant__2245f0_idx',

                    old_name='erp_auditlo_organization__2245f0_idx',

                ),

            ],

            database_operations=[

                migrations.RunSQL(

                    sql="ALTER INDEX IF EXISTS erp_auditlo_organization__2245f0_idx RENAME TO erp_auditlo_tenant__2245f0_idx;",

                    reverse_sql="ALTER INDEX IF EXISTS erp_auditlo_tenant__2245f0_idx RENAME TO erp_auditlo_organization__2245f0_idx;",

                ),

            ],

        ),
        migrations.SeparateDatabaseAndState(

            state_operations=[

                migrations.RenameIndex(

                    model_name='audittrail',

                    new_name='erp_audittr_tenant__cab6d8_idx',

                    old_name='erp_audittr_organization__cab6d8_idx',

                ),

            ],

            database_operations=[

                migrations.RunSQL(

                    sql="ALTER INDEX IF EXISTS erp_audittr_organization__cab6d8_idx RENAME TO erp_audittr_tenant__cab6d8_idx;",

                    reverse_sql="ALTER INDEX IF EXISTS erp_audittr_tenant__cab6d8_idx RENAME TO erp_audittr_organization__cab6d8_idx;",

                ),

            ],

        ),
        migrations.SeparateDatabaseAndState(

            state_operations=[

                migrations.RenameIndex(

                    model_name='domainevent',

                    new_name='erp_domaine_tenant__ff3bb3_idx',

                    old_name='erp_domaine_organization__ff3bb3_idx',

                ),

            ],

            database_operations=[

                migrations.RunSQL(

                    sql="ALTER INDEX IF EXISTS erp_domaine_organization__ff3bb3_idx RENAME TO erp_domaine_tenant__ff3bb3_idx;",

                    reverse_sql="ALTER INDEX IF EXISTS erp_domaine_tenant__ff3bb3_idx RENAME TO erp_domaine_organization__ff3bb3_idx;",

                ),

            ],

        ),
        migrations.SeparateDatabaseAndState(

            state_operations=[

                migrations.RenameIndex(

                    model_name='domainevent',

                    new_name='erp_domaine_tenant__c286e5_idx',

                    old_name='erp_domaine_organization__c286e5_idx',

                ),

            ],

            database_operations=[

                migrations.RunSQL(

                    sql="ALTER INDEX IF EXISTS erp_domaine_organization__c286e5_idx RENAME TO erp_domaine_tenant__c286e5_idx;",

                    reverse_sql="ALTER INDEX IF EXISTS erp_domaine_tenant__c286e5_idx RENAME TO erp_domaine_organization__c286e5_idx;",

                ),

            ],

        ),
        migrations.SeparateDatabaseAndState(

            state_operations=[

                migrations.RenameIndex(

                    model_name='featureflag',

                    new_name='erp_feature_tenant__6b9fe1_idx',

                    old_name='erp_feature_organization__6b9fe1_idx',

                ),

            ],

            database_operations=[

                migrations.RunSQL(

                    sql="ALTER INDEX IF EXISTS erp_feature_organization__6b9fe1_idx RENAME TO erp_feature_tenant__6b9fe1_idx;",

                    reverse_sql="ALTER INDEX IF EXISTS erp_feature_tenant__6b9fe1_idx RENAME TO erp_feature_organization__6b9fe1_idx;",

                ),

            ],

        ),
        migrations.SeparateDatabaseAndState(

            state_operations=[

                migrations.RenameIndex(

                    model_name='orgmodule',

                    new_name='erp_orgmodu_tenant__e71a63_idx',

                    old_name='erp_orgmodu_organization__e71a63_idx',

                ),

            ],

            database_operations=[

                migrations.RunSQL(

                    sql="ALTER INDEX IF EXISTS erp_orgmodu_organization__e71a63_idx RENAME TO erp_orgmodu_tenant__e71a63_idx;",

                    reverse_sql="ALTER INDEX IF EXISTS erp_orgmodu_tenant__e71a63_idx RENAME TO erp_orgmodu_organization__e71a63_idx;",

                ),

            ],

        ),
        migrations.SeparateDatabaseAndState(

            state_operations=[

                migrations.RenameIndex(

                    model_name='resourcepermission',

                    new_name='kernel_reso_tenant__63236d_idx',

                    old_name='kernel_reso_organization__63236d_idx',

                ),

            ],

            database_operations=[

                migrations.RunSQL(

                    sql="ALTER INDEX IF EXISTS kernel_reso_organization__63236d_idx RENAME TO kernel_reso_tenant__63236d_idx;",

                    reverse_sql="ALTER INDEX IF EXISTS kernel_reso_tenant__63236d_idx RENAME TO kernel_reso_organization__63236d_idx;",

                ),

            ],

        ),
        migrations.SeparateDatabaseAndState(

            state_operations=[

                migrations.RenameIndex(

                    model_name='role',

                    new_name='kernel_role_tenant__7d80c1_idx',

                    old_name='kernel_role_organization__7d80c1_idx',

                ),

            ],

            database_operations=[

                migrations.RunSQL(

                    sql="ALTER INDEX IF EXISTS kernel_role_organization__7d80c1_idx RENAME TO kernel_role_tenant__7d80c1_idx;",

                    reverse_sql="ALTER INDEX IF EXISTS kernel_role_tenant__7d80c1_idx RENAME TO kernel_role_organization__7d80c1_idx;",

                ),

            ],

        ),
        migrations.SeparateDatabaseAndState(

            state_operations=[

                migrations.RenameIndex(

                    model_name='tenantconfig',

                    new_name='erp_tenantc_tenant__a104e6_idx',

                    old_name='erp_tenantc_organization__a104e6_idx',

                ),

            ],

            database_operations=[

                migrations.RunSQL(

                    sql="ALTER INDEX IF EXISTS erp_tenantc_organization__a104e6_idx RENAME TO erp_tenantc_tenant__a104e6_idx;",

                    reverse_sql="ALTER INDEX IF EXISTS erp_tenantc_tenant__a104e6_idx RENAME TO erp_tenantc_organization__a104e6_idx;",

                ),

            ],

        ),
        migrations.SeparateDatabaseAndState(

            state_operations=[

                migrations.RenameIndex(

                    model_name='userrole',

                    new_name='kernel_user_tenant__e61c89_idx',

                    old_name='kernel_user_organization__e61c89_idx',

                ),

            ],

            database_operations=[

                migrations.RunSQL(

                    sql="ALTER INDEX IF EXISTS kernel_user_organization__e61c89_idx RENAME TO kernel_user_tenant__e61c89_idx;",

                    reverse_sql="ALTER INDEX IF EXISTS kernel_user_tenant__e61c89_idx RENAME TO kernel_user_organization__e61c89_idx;",

                ),

            ],

        ),
        migrations.AddField(
            model_name='organization',
            name='base_country',
            field=models.ForeignKey(blank=True, help_text='Base country for this organization (from reference master data)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_organizations', to='reference.country'),
        ),
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='approvalpolicy',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='approvalpolicystep',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='approvalrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='confighistory',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='customdomain',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', help_text='The organization this domain belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='custom_domains', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='decisionlog',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='decisionrule',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='domainevent',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='levelrolemap',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='listviewpolicy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='listviewpolicy',
            name='view_key',
            field=models.CharField(help_text='List view identifier, e.g. "inventory_products", "crm_contacts", "finance_ledger". Use "*" for global default.', max_length=100),
        ),
        migrations.AlterField(
            model_name='manageroverridelog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='modulemigration',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='orgmodule',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='planaddon',
            name='addon_type',
            field=models.CharField(choices=[('users', 'Extra Users'), ('sites', 'Extra Sites'), ('storage', 'Extra Storage (GB)'), ('products', 'Extra Products'), ('invoices', 'Extra Invoices/Month'), ('customers', 'Extra Customers'), ('encryption', 'AES-256 Encryption'), ('dual_view', 'Dual View — Internal Scope Access'), ('multi_currency', 'Multi-Currency Support'), ('multi_country', 'Multi-Country Branches')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resourcepermission',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='site',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='systemmodule',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - shown on landing page'), ('organization', 'Organization - only visible to assigned orgs'), ('private', 'Private - hidden/internal only')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='transactionverificationconfig',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='transactionverificationpolicy',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='txnapproval',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
    ]
