# Generated by Django 6.0.2 on 2026-03-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerule',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
