# Generated by Django 6.0.2 on 2026-03-11 01:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_alter_scorerule_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeescoreperiod',
            name='compliance_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='employeescoreperiod',
            name='leadership_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='employeescoreperiod',
            name='reliability_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
