# Generated by Django 6.0.2 on 2026-03-11 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_organization_finance_hard_locked_at_and_more'),
        ('hr', '0003_alter_employee_home_site_alter_shift_site'),
        ('workforce', '0003_add_period_family_scores'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeebadge',
            unique_together={('organization', 'employee', 'period_key')},
        ),
    ]
