# Generated by Django 5.2.12 on 2026-03-11 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_alter_approvalrule_organization_and_more'),
        ('hr', '0004_alter_attendance_organization_and_more'),
        ('workforce', '0006_add_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employeescoreevent',
            new_name='workforce_s_organization__d4e395_idx',
            old_name='workforce_ese_tes_idx',
        ),
        migrations.RenameIndex(
            model_name='employeescoreevent',
            new_name='workforce_s_organization__d34d24_idx',
            old_name='workforce_ese_tmec_idx',
        ),
        migrations.RenameIndex(
            model_name='employeescoreevent',
            new_name='workforce_s_organization__d85140_idx',
            old_name='workforce_ese_tea_idx',
        ),
        migrations.RenameIndex(
            model_name='employeescoreevent',
            new_name='workforce_s_organization__71904a_idx',
            old_name='workforce_ese_tds_idx',
        ),
        migrations.RenameIndex(
            model_name='employeescoreevent',
            new_name='workforce_s_employe_e6d54c_idx',
            old_name='workforce_ese_esea_idx',
        ),
        migrations.RenameIndex(
            model_name='employeescoreperiod',
            new_name='workforce_s_organization__dbdc43_idx',
            old_name='workforce_esp_tptpk_idx',
        ),
        migrations.RenameIndex(
            model_name='employeescoreperiod',
            new_name='workforce_s_employe_44bf4b_idx',
            old_name='workforce_esp_epk_idx',
        ),
        migrations.RenameIndex(
            model_name='employeescoresummary',
            new_name='workforce_s_organization__dbb1dc_idx',
            old_name='workforce_ess_tgs_idx',
        ),
        migrations.RenameIndex(
            model_name='employeescoresummary',
            new_name='workforce_s_organization__a1d2e8_idx',
            old_name='workforce_ess_tbgs_idx',
        ),
        migrations.RenameIndex(
            model_name='employeescoresummary',
            new_name='workforce_s_organization__46ae32_idx',
            old_name='workforce_ess_trl_idx',
        ),
        migrations.RenameIndex(
            model_name='employeescoresummary',
            new_name='workforce_s_organization__b8d8fd_idx',
            old_name='workforce_ess_tbl_idx',
        ),
        migrations.RenameIndex(
            model_name='scorerule',
            new_name='workforce_s_organization__9bc68f_idx',
            old_name='workforce_sr_tmec_idx',
        ),
        migrations.RenameIndex(
            model_name='scorerule',
            new_name='workforce_s_organization__3c9f9f_idx',
            old_name='workforce_sr_tactive_idx',
        ),
        migrations.AlterUniqueTogether(
            name='employeebadge',
            unique_together = ('organization', 'employee', 'period_key'),
        ),
        migrations.RemoveField(
            model_name='employeescoreadjustment',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='employeescoreevent',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='employeescoreperiod',
            unique_together = ('organization', 'employee', 'period_type', 'period_key'),
        ),
        migrations.RemoveField(
            model_name='employeescoresummary',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='scorerule',
            unique_together = ('organization', 'code'),
        ),
        migrations.AddField(
            model_name='employeebadge',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='employeescoreadjustment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='employeescoreevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='employeescoreperiod',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='employeescoresummary',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='scorerule',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.RemoveField(
            model_name='employeebadge',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='employeescoreperiod',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='scorerule',
            name='organization',
        ),
    ]
