"""
Inventory Background Tasks
==========================
Celery tasks for automated inventory management:
- Replenishment Bot (Auto-drafting Purchase Orders)
- Expiry Monitoring (Alerting on nearing expirations)
"""
from celery import shared_task
from django.utils import timezone
import logging

logger = logging.getLogger(__name__)

@shared_task(name='apps.inventory.tasks.run_replenishment_bot')
def run_replenishment_bot():
    """
    Automated Replenishment Bot.
    Scans all active organizations, calculates AI purchase suggestions,
    and drafts OperationalRequests (Purchase Orders) for missing stock.
    Runs daily.
    """
    from erp.models import Organization
    from apps.inventory.services import InventoryService
    from apps.inventory.models import OperationalRequest, OperationalRequestLine, Product
    from django.db import transaction

    total_requests_created = 0

    for org in Organization.objects.filter(is_active=True):
        suggestions = InventoryService.get_purchase_suggestions(org)
        if not suggestions:
            continue

        # Filter only high priority suggestions for auto-drafting
        high_priority = [s for s in suggestions if s['priority'] == 'HIGH' and s['suggested_qty'] > 0]
        if not high_priority:
            continue

        with transaction.atomic():
            # Create a single omnibus request for the day
            request = OperationalRequest.objects.create(
                organization=org,
                request_type='PURCHASE_ORDER',
                priority='HIGH',
                status='PENDING',
                date=timezone.now().date(),
                description=f"Auto-generated by Replenishment Bot on {timezone.now().strftime('%Y-%m-%d')}. Contains {len(high_priority)} suggested reorders."
            )
            
            for item in high_priority:
                try:
                    product = Product.objects.get(id=item['product_id'], organization=org)
                    OperationalRequestLine.objects.create(
                        request=request,
                        product=product,
                        quantity=item['suggested_qty'],
                        reason=item['reason']
                    )
                except Product.DoesNotExist:
                    continue
            
            total_requests_created += 1
            logger.info(f"[Replenishment Bot] Drafted Request {request.id} for Org {org.id} with {len(high_priority)} items.")

            # Optional: Notify managers
            try:
                from erp.models import User
                from erp.tasks import send_notification
                managers = User.objects.filter(organization=org, role__in=['ADMIN', 'MANAGER'], is_active=True)
                for manager in managers:
                    send_notification.delay(
                        user_id=manager.id,
                        title="Replenishment Bot: New Purchase Draft",
                        message=f"The Replenishment Bot has drafted a new Purchase Order request for {len(high_priority)} low-stock items.",
                        notification_type='INFO'
                    )
            except ImportError:
                pass

    logger.info(f"[Task] run_replenishment_bot: Created {total_requests_created} operational requests.")
    return {'requests_drafted': total_requests_created}


@shared_task(name='apps.inventory.tasks.check_batch_expiries')
def check_batch_expiries():
    """
    Scans all ProductBatches to identify upcoming expirations
    and generates ExpiryAlert records.
    Runs daily.
    """
    from erp.models import Organization
    from apps.inventory.alert_models import StockAlertService

    total_alerts_generated = 0

    for org in Organization.objects.filter(is_active=True):
        service = StockAlertService(org)
        alerts = service.scan_expiries()
        total_alerts_generated += len(alerts)

    logger.info(f"[Task] check_batch_expiries: {total_alerts_generated} expiration alerts created/updated.")
    return {'alerts_created': total_alerts_generated}
