# Generated by Django 5.2.11 on 2026-03-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_contact_type_contacttag_contact_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer'), ('BOTH', 'Customer & Supplier'), ('LEAD', 'Lead'), ('PARTNER', 'Partner'), ('CREDITOR', 'Creditor'), ('DEBTOR', 'Debtor'), ('CONTACT', 'Contact'), ('SERVICE', 'Service Provider')], max_length=20),
        ),
    ]
