# Generated by Django 5.2.11 on 2026-03-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttag',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('BOTH', 'Customer & Supplier'), ('LEAD', 'Lead'), ('PARTNER', 'Partner'), ('CREDITOR', 'Creditor'), ('DEBTOR', 'Debtor'), ('CONTACT', 'Contact'), ('SERVICE', 'Service Provider')], help_text='Scope this category to a specific contact type. Null = applies to all types.', max_length=20, null=True),
        ),
    ]
