# Generated by Django 5.2.11 on 2026-03-10 23:02

import apps.crm.models.contact_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_contacttag_parent'),
        ('erp', '0020_organization_finance_hard_locked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='airsi_exoneration_expiry',
            field=models.DateField(blank=True, help_text='Expiry date of AIRSI Exoneration certificate', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='dfe_number',
            field=models.CharField(blank=True, help_text='Electronic Invoicing ID / DFE Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_airsi_exonerated',
            field=models.BooleanField(default=False, help_text='Explicit AIRSI Exoneration (No withholding tax)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_vat_exonerated',
            field=models.BooleanField(default=False, help_text="Explicit VAT Exoneration (Certificat d'exonération TVA)"),
        ),
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.crm.models.contact_models.contact_photo_path),
        ),
        migrations.AddField(
            model_name='contact',
            name='reg_number',
            field=models.CharField(blank=True, db_column='reg_number', help_text='Commercial Register Number (e.g., RCCM / Registre de Commerce)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='tax_id',
            field=models.CharField(blank=True, db_column='tax_id', help_text='Official Tax Register Number (e.g., NCC in Ivory Coast)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='vat_exoneration_expiry',
            field=models.DateField(blank=True, help_text='Expiry date of TVA Exoneration certificate', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='commercial_category',
            field=models.CharField(blank=True, choices=[('B2B', 'B2B — Company/Professional (NCC)'), ('B2F', 'B2F — Foreign / International'), ('B2G', 'B2G — Government / Institutional'), ('B2C', 'B2C — Individual / Particular'), ('NORMAL', 'Normal / Standard'), ('RETAIL', 'Retail Merchant'), ('WHOLESALE', 'Wholesale Merchant'), ('MICRO', 'Micro / Non-assujetti'), ('EXPORT', 'Export Account')], default='NORMAL', help_text='Commercial label only — NO fiscal effect. Tax behavior comes from tax_profile_id.', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ContactComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NCC', 'Tax Register (NCC)'), ('RCCM', 'Commercial Register (RCCM)'), ('DFE', 'Electronic Invoicing (DFE)'), ('EXONERATION_TVA', 'VAT Exoneration Certificate'), ('EXONERATION_AIRSI', 'AIRSI Exoneration Certificate'), ('PASSPORT', 'Passport'), ('ID_CARD', 'Identity Card'), ('LICENSE', 'Operating License'), ('OTHER', 'Other Document')], max_length=50)),
                ('document_number', models.CharField(max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('reminder_days', models.IntegerField(default=30, help_text='Days before expiry to trigger alert')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_documents', to='crm.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'contact_compliance_document',
                'ordering': ['-expiry_date'],
            },
        ),
    ]
