# Generated by Django 5.2.11 on 2026-03-10 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_contact_airsi_exoneration_expiry_contact_dfe_number_and_more'),
        ('erp', '0020_organization_finance_hard_locked_at_and_more'),
        ('storage', '0003_alter_storedfile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcompliancedocument',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_documents', to='storage.storedfile'),
        ),
        migrations.CreateModel(
            name='ContactTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('COMPLIANCE_RENEWAL', 'Document Renewal Request'), ('FOLLOW_UP', 'Follow-up / Commercial'), ('KYC_UPDATE', 'KYC Update Needed'), ('OTHER', 'Other')], default='FOLLOW_UP', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical (Blocks Transactions)')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to_user_id', models.IntegerField(blank=True, null=True)),
                ('related_doc_id', models.IntegerField(blank=True, help_text='ID of ComplianceDocument if relevant', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'contact_task',
                'ordering': ['due_date', '-priority'],
            },
        ),
    ]
