# Generated by Django 5.2.11 on 2026-03-10 23:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_contactcompliancedocument_attachment_contacttask'),
        ('erp', '0020_organization_finance_hard_locked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='compliance_last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='compliance_next_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='compliance_risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='compliance_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Overall compliance health score (0-100)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='contact',
            name='compliance_status',
            field=models.CharField(choices=[('COMPLIANT', 'Compliant'), ('MISSING_DOC', 'Missing Required Documents'), ('EXPIRED_DOC', 'Expired Documents'), ('EXPIRING_SOON', 'Expiring Soon (Warning)'), ('BLOCKED', 'Manually Blocked'), ('UNVERIFIED', 'Unverified Documents')], default='COMPLIANT', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactcompliancedocument',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only the latest active version is used for compliance checks'),
        ),
        migrations.AlterField(
            model_name='contactcompliancedocument',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_versions', to='crm.contactcompliancedocument'),
        ),
        migrations.AlterField(
            model_name='contactcompliancedocument',
            name='review_status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded (Pending Review)'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected (Action Required)'), ('SUPERSEDED', 'Superseded by New Version'), ('REVOKED', 'Revoked / Invalidated')], default='UPLOADED', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactcompliancedocument',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ComplianceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('STATUS_CHANGE', 'Compliance Status Changed'), ('DOC_UPLOADED', 'Document Uploaded'), ('DOC_EXPIRED', 'Document Expired'), ('DOC_REJECTED', 'Document Rejected'), ('VIOLATION_BLOCK', 'Transaction Blocked by Compliance'), ('MANUAL_OVERRIDE', 'Manual Compliance Override')], max_length=30)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_events', to='crm.contact')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='crm.contactcompliancedocument')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'compliance_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(help_text='Internal code for the document (e.g. NCC, RCCM, DFE, ID_CARD)', max_length=50)),
                ('name', models.CharField(help_text='Display name of the requirement', max_length=255)),
                ('country_code', models.CharField(default='CI', help_text='ISO alpha-3 code', max_length=3)),
                ('entity_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('BUSINESS', 'Business'), ('BOTH', 'Any')], default='BOTH', max_length=20)),
                ('contact_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('BOTH', 'Any')], default='BOTH', max_length=20)),
                ('tax_regime', models.CharField(blank=True, help_text='Filter by commercial_category/tax regime', max_length=100, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('block_level', models.CharField(choices=[('WARNING', 'Warning Only (No block)'), ('BLOCK_CONFIRMATION', 'Block Order Confirmation'), ('BLOCK_INVOICE', 'Block Invoicing'), ('BLOCK_PAYMENT', 'Block Payment Processing'), ('STRICT', 'Strict (Block All Transactions)')], default='BLOCK_INVOICE', max_length=30)),
                ('renewal_days_before', models.IntegerField(default=30, help_text='Days before expiry to trigger renewal task')),
                ('grace_period_days', models.IntegerField(default=0, help_text='Additional days allowed after expiry before blocking')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'verbose_name': 'Compliance Rule',
                'verbose_name_plural': 'Compliance Rules',
                'db_table': 'compliance_rules',
            },
        ),
        migrations.CreateModel(
            name='ComplianceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(help_text='When this override expires')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_overrides', to='crm.contact')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.compliancerule')),
            ],
            options={
                'db_table': 'compliance_overrides',
            },
        ),
    ]
