# Generated by Django 6.0.4 on 2026-04-20 02:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_tax_engine_phase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Customer wallet balance from stored change or top-ups', max_digits=15),
        ),
    ]
