import {
    ShoppingBag,
    ShoppingCart,
    Package,
    Wallet,
} from 'lucide-react';
import type { MenuItem } from './types';

export const commercial: MenuItem = {
    title: 'Commercial',
    icon: ShoppingBag,
    module: 'pos',
    children: [
        {
            title: 'Point of Sale',
            icon: ShoppingCart,
            children: [
                { title: 'POS Terminal', path: '/sales' },
                { title: 'POS Registers', path: '/sales/registers' },
                { title: 'POS Tickets', path: '/pos/pos-tickets' },
                { title: 'Order History', path: '/sales/history' },
                { title: 'Sales Orders', path: '/sales/orders' },
                { title: 'Sales Analytics', path: '/sales/analytics' },
                { title: 'Sales Summary', path: '/sales/summary' },
                { title: 'POS Sessions', path: '/sales/sessions' },
                { title: 'Quotations', path: '/sales/quotations' },
                { title: 'Deliveries', path: '/sales/deliveries' },
                { title: 'Discount Rules', path: '/sales/discounts' },
                { title: 'Consignment', path: '/sales/consignment' },
                { title: 'Consignment Settlements', path: '/sales/consignment-settlements' },
                { title: 'Delivery Zones', path: '/sales/delivery-zones' },
                { title: 'Sales Returns', path: '/sales/returns' },
                { title: 'Credit Notes', path: '/sales/credit-notes' },
                { title: 'Drivers', path: '/sales/drivers' },
                { title: 'Import Sales', path: '/sales/import' },
                { title: 'Sales Audit', path: '/sales/audit' },
                { title: 'Supermarché', path: '/sales/supermarche' },
            ],
        },
        {
            title: 'POS Settings & Audit',
            icon: Package,
            children: [
                { title: 'POS Settings', path: '/sales/pos-settings', stage: 'in-progress' },
                { title: 'POS Terminal (Alt)', path: '/pos/pos' },
                { title: 'POS Registers', path: '/pos/pos-registers' },
                { title: 'POS Settings (Alt)', path: '/pos/pos-settings' },
                { title: 'POS Orders', path: '/pos/orders' },
                { title: 'POS Deliveries', path: '/pos/deliveries' },
                { title: 'POS Delivery Zones', path: '/pos/delivery-zones' },
                { title: 'POS Discount Rules', path: '/pos/discount-rules' },
                { title: 'POS Quotations', path: '/pos/quotations' },
                { title: 'POS Consignment', path: '/pos/consignment-settlements' },
                { title: 'POS Sales Returns', path: '/pos/sales-returns' },
                { title: 'POS Credit Notes', path: '/pos/credit-notes' },
                { title: 'POS Purchase', path: '/pos/purchase' },
                { title: 'POS Purchase Returns', path: '/pos/purchase-returns' },
                { title: 'Supplier Package Prices', path: '/pos/supplier-package-prices' },
                { title: 'POS Audit Events', path: '/pos/pos-audit-events' },
                { title: 'POS Audit Rules', path: '/pos/pos-audit-rules' },
                { title: 'Supplier Pricing', path: '/pos/supplier-pricing' },
                { title: 'Sourcing', path: '/pos/sourcing' },
                { title: 'Purchase Orders', path: '/pos/purchase-orders' },
                { title: 'PO Lines', path: '/pos/po-lines' },
                { title: 'Address Book', path: '/pos/manager-address-book' },
            ],
        },
        {
            title: 'Purchasing',
            icon: Wallet,
            children: [
                { title: 'Purchase Dashboard', path: '/purchases/dashboard' },
                { title: 'New Order v2', path: '/purchases/new-order-v2' },
                { title: 'Purchase Orders', path: '/purchases/purchase-orders', stage: 'in-progress' },
                { title: 'New Purchase Order', path: '/purchases/purchase-orders/new', stage: 'in-progress' },
                { title: 'New Purchase Invoice', path: '/purchases/invoices/new', stage: 'in-progress' },
                { title: 'Quotations', path: '/purchases/quotations' },
                { title: 'Receiving', path: '/purchases/receiving', stage: 'in-progress' },
                { title: 'Receipts', path: '/purchases/receipts', stage: 'in-progress' },
                { title: 'Invoicing', path: '/purchases/invoicing' },
                { title: 'Invoice Verification', path: '/purchases/invoice-verification' },
                { title: 'Consignments', path: '/purchases/consignments' },
                { title: 'Approvals', path: '/purchases/approvals' },
                { title: 'Purchase Returns', path: '/purchases/returns' },
                { title: 'Credit Notes', path: '/purchases/credit-notes' },
                { title: 'Supplier Sourcing', path: '/purchases/sourcing' },
                { title: 'Invoices', path: '/purchases/invoices' },
                { title: 'Verification', path: '/purchases/verification' },
            ],
        },
    ],
};
