import {
    FileText,
    BookOpen,
    Settings,
    FolderTree,
    Database,
    ListChecks,
    BarChart3,
    Wallet,
    ClipboardList,
    ShieldCheck,
    TrendingUp,
    Calendar,
    DollarSign,
    Bell,
    Scale,
    Sigma,
    Landmark,
    Coins,
    ArrowRightLeft,
    Target,
    Library,
} from 'lucide-react';
import type { MenuItem } from './types';

export const financeProduction: MenuItem = {
    title: 'Finance',
    icon: FileText,
    module: 'finance',
    stage: 'production',
    children: [
        { title: 'Chart of Accounts', path: '/finance/chart-of-accounts', icon: BookOpen },
        { title: 'Fiscal Years', path: '/finance/fiscal-years', icon: Calendar },
        {
            title: 'Settings',
            icon: Settings,
            children: [
                { title: 'COA Templates', path: '/finance/chart-of-accounts/templates', icon: Library },
                { title: 'Migration Tool', path: '/finance/chart-of-accounts/migrate', icon: ArrowRightLeft },
                { title: 'Posting Rules', path: '/finance/settings/posting-rules', icon: Target },
            ],
        },
    ],
};

export const financeInProgress: MenuItem = {
    title: 'Finance',
    icon: FileText,
    module: 'finance',
    stage: 'in-progress',
    children: [
        { title: 'General Ledger', path: '/finance/ledger', icon: BookOpen },
        { title: 'Currencies & FX', path: '/settings/regional?tab=fx', icon: Coins },
        {
            title: 'Accounts',
            icon: Wallet,
            children: [
                { title: 'Accounts & Drawers', path: '/finance/accounts', icon: Wallet },
                { title: 'Account Categories', path: '/finance/account-categories', icon: FolderTree },
                { title: 'Opening Balances', path: '/finance/opening-balances', icon: ClipboardList },
            ],
        },
        {
            title: 'Reports',
            icon: TrendingUp,
            children: [
                { title: 'Trial Balance', path: '/finance/reports/trial-balance', icon: Scale },
                { title: 'Profit & Loss', path: '/finance/reports/pnl', icon: Sigma },
                { title: 'Balance Sheet', path: '/finance/reports/balance-sheet', icon: Landmark },
            ],
        },
        {
            title: 'Tax & Compliance',
            icon: ShieldCheck,
            children: [
                { title: 'Tax Groups', path: '/finance/tax-groups', icon: FolderTree },
                { title: 'Org Tax Policies', path: '/finance/org-tax-policies', icon: Settings },
                { title: 'Custom Tax Rules', path: '/finance/custom-tax-rules', icon: ListChecks },
                { title: 'Counterparty Tax Profiles', path: '/finance/counterparty-tax-profiles', icon: Database },
            ],
        },
    ],
};

export const financeMain: MenuItem = {
    title: 'Finance',
    icon: FileText,
    module: 'finance',
    children: [
        { title: 'Performance Dashboard', path: '/finance/dashboard', icon: BarChart3 },
        { title: 'Financial Setup', path: '/finance/setup', icon: Settings },
        {
            title: 'Accounts & Ledger',
            icon: BookOpen,
            children: [
                { title: 'Account Book', path: '/finance/account-book' },
                { title: 'COA Management', path: '/finance/coa' },
                { title: 'CSV Import', path: '/finance/ledger/import' },
                { title: 'Journal Entries', path: '/finance/journal' },
            ],
        },
        {
            title: 'Balances',
            icon: Wallet,
            children: [
                { title: 'Balances Overview', path: '/finance/balances' },
                { title: 'Customer Balances', path: '/finance/customer-balances' },
                { title: 'Supplier Balances', path: '/finance/supplier-balances' },
            ],
        },
        {
            title: 'Operations',
            icon: ClipboardList,
            children: [
                { title: 'Invoices', path: '/finance/invoices' },
                { title: 'Invoice Lines', path: '/finance/invoice-lines' },
                { title: 'Payments', path: '/finance/payments' },
                { title: 'Payment Allocations', path: '/finance/payment-allocations' },
                { title: 'Payment Approvals', path: '/finance/payment-approvals' },
                { title: 'Vouchers', path: '/finance/vouchers' },
                { title: 'Expenses', path: '/finance/expenses' },
                { title: 'Expense Approvals', path: '/finance/expense-approvals' },
                { title: 'Deferred Expenses', path: '/finance/deferred-expenses' },
                { title: 'Assets & Depreciation', path: '/finance/assets' },
                { title: 'Purchase Returns', path: '/finance/purchase-returns' },
                { title: 'Sales Returns', path: '/finance/sales-returns' },
                { title: 'Financial Events', path: '/finance/financial-events' },
            ],
        },
        {
            title: 'Tax & Compliance',
            icon: ShieldCheck,
            children: [
                { title: 'Tax Policy', path: '/finance/tax-policy' },
                { title: 'Withholding Tax Rules', path: '/finance/withholding-tax-rules' },
                { title: 'VAT Return', path: '/finance/vat-return' },
                { title: 'VAT Settlement', path: '/finance/vat-settlement' },
                { title: 'VAT Rate History', path: '/finance/vat-rate-history' },
                { title: 'Periodic Tax', path: '/finance/periodic-tax' },
                { title: 'Advance Payment VAT', path: '/finance/advance-payment-vat' },
                { title: 'Bad Debt VAT Claims', path: '/finance/bad-debt-vat-claims' },
                { title: 'Credit Note VAT', path: '/finance/credit-note-vat' },
                { title: 'Gift & Sample VAT', path: '/finance/gift-sample-vat' },
                { title: 'Intra-Branch VAT', path: '/finance/intra-branch-vat' },
                { title: 'Reverse Charge', path: '/finance/reverse-charge' },
                { title: 'Self-Supply VAT', path: '/finance/self-supply-vat' },
                { title: 'Margin Scheme', path: '/finance/margin-scheme' },
                { title: 'Import Declarations', path: '/finance/import-declarations' },
                { title: 'E-Invoicing', path: '/finance/einvoicing' },
                { title: 'E-Invoice', path: '/finance/einvoice' },
            ],
        },
        {
            title: 'Reports',
            icon: TrendingUp,
            children: [
                { title: 'Reports Dashboard', path: '/finance/reports/dashboard' },
                { title: 'Report Builder', path: '/finance/reports/builder' },
                { title: 'All Reports', path: '/finance/reports' },
                { title: 'Account Statement', path: '/finance/reports/statement' },
                { title: 'Cash Flow', path: '/finance/reports/cash-flow' },
                { title: 'Aging Report', path: '/finance/reports/aging' },
                { title: 'Aging Overview', path: '/finance/aging' },
                { title: 'Audit Trail', path: '/finance/audit-trail' },
                { title: 'Cash Register', path: '/finance/cash-register' },
                { title: 'Bank Reconciliation', path: '/finance/bank-reconciliation' },
                { title: 'Reconciliation Sessions', path: '/finance/reconciliation-sessions' },
                { title: 'Bank Statements', path: '/finance/bank-statements' },
                { title: 'Period Statements', path: '/finance/statements' },
                { title: 'Tax Reports', path: '/finance/tax-reports' },
                { title: 'Revenue Breakdown', path: '/finance/revenue' },
                { title: 'Audit', path: '/finance/audit' },
                { title: 'Audit Logs', path: '/finance/audit-logs' },
            ],
        },
        {
            title: 'Budget & Planning',
            icon: BarChart3,
            children: [
                { title: 'Budgets', path: '/finance/budgets' },
                { title: 'Budget Alerts', path: '/finance/budgets/alerts' },
                { title: 'Budget Lines', path: '/finance/budget-lines' },
                { title: 'Budget Overview', path: '/finance/budget' },
                { title: 'Profit Centers', path: '/finance/profit-centers' },
                { title: 'Profit Distribution', path: '/finance/profit-distribution' },
            ],
        },
        {
            title: 'Fiscal & Periods',
            icon: Calendar,
            children: [
                { title: 'Fiscal Periods', path: '/finance/fiscal-periods' },
            ],
        },
        {
            title: 'Loans & Gateway',
            icon: DollarSign,
            children: [
                { title: 'Loan Contracts', path: '/finance/loans' },
                { title: 'Pricing Engine', path: '/finance/pricing' },
                { title: 'Payment Gateway', path: '/finance/gateway' },
                { title: 'Gateway Configs', path: '/finance/gateway-configs' },
            ],
        },
        {
            title: 'Events & Automation',
            icon: Bell,
            children: [
                { title: 'Financial Events', path: '/finance/events' },
            ],
        },
        {
            title: 'Finance Settings',
            icon: Settings,
            children: [
                { title: 'General Settings', path: '/finance/settings' },
                { title: 'Payment Methods', path: '/finance/settings/payment-methods' },
                { title: 'Barcode Settings', path: '/finance/settings/barcode' },
                { title: 'Form Definitions', path: '/finance/settings/form-definitions' },
            ],
        },
    ],
};
