# Generated by Django 6.0.2 on 2026-02-23 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0004_initial'),
        ('inventory', '0003_productattribute_productattributevalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorderline',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productvariant'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productvariant'),
        ),
    ]
