# Generated by Django 6.0.2 on 2026-02-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0005_clientorderline_variant_quoteitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientportalconfig',
            name='layout',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration for the storefront layout/sections'),
        ),
    ]
