# Generated by Django 5.1.7 on 2026-02-21 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0005_clientportalconfig_storefront_type'),
        ('crm', '0002_initial'),
        ('erp', '0002_initial'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientportalconfig',
            name='storefront_type',
            field=models.CharField(choices=[('PRODUCT_STORE', 'Product Store — full e-commerce with cart and checkout'), ('CATALOGUE', 'Catalogue — browse products, request quotes, no direct checkout'), ('SUBSCRIPTION', 'Subscription Store — recurring plans and pricing tiers'), ('LANDING_PAGE', 'Landing Page — company website with hero, about, and contact'), ('PORTFOLIO', 'Portfolio — showcase projects, case studies, and inquiries')], default='PRODUCT_STORE', help_text='Type of storefront layout (product store, catalogue, subscription, landing page, portfolio)', max_length=30),
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('product_name', models.CharField(help_text='Snapshot of product name', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=15)),
                ('message', models.TextField(help_text='Customer requirements or questions')),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assessment'), ('REPLIED', 'Proposal Sent'), ('CONVERTED', 'Converted to Order'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('source_url', models.URLField(blank=True, default='', help_text='The page where the quote was requested')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='crm.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
            ],
            options={
                'db_table': 'client_quote_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
