# Generated by Django 5.2.11 on 2026-02-25 01:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0008_productreview_wishlistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='delivery_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='payment_method',
            field=models.CharField(default='WALLET', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='wallet_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='clientorderline',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientportalaccess',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientportalaccess',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='allow_guest_browsing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='allow_wallet_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='auto_assign_tickets',
            field=models.BooleanField(default=False),
        ),
        # v3.5.0 cleanup: AlterField → AddField (field never created by prior migration)
        migrations.AddField(
            model_name='clientportalconfig',
            name='custom_css',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='default_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='default_ticket_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='ecommerce_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='enabled_ticket_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='free_delivery_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='inventory_check_mode',
            field=models.CharField(choices=[('STRICT', 'Strict — Prevent order if stock is insufficient'), ('ALLOW_OVERSALE', 'Allow Oversale — Proceed even if stock is low (goes negative)'), ('DISABLED', 'Disabled — Do not check or reduce stock during checkout')], default='STRICT', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='layout',
            field=models.JSONField(blank=True, default=dict),
        ),
        # v3.5.0 cleanup: AlterField → AddField (field never created by prior migration)
        migrations.AddField(
            model_name='clientportalconfig',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='loyalty_earn_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='loyalty_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='loyalty_max_redeem_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='loyalty_min_redeem',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='loyalty_redemption_ratio',
            field=models.DecimalField(decimal_places=4, default=Decimal('100.0000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        # v3.5.0 cleanup: AlterField → AddField (field never created by prior migration)
        migrations.AddField(
            model_name='clientportalconfig',
            name='og_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        # v3.5.0 cleanup: AlterField → AddField (field never created by prior migration)
        migrations.AddField(
            model_name='clientportalconfig',
            name='primary_color',
            field=models.CharField(default='#10b981', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='require_approval_for_orders',
            field=models.BooleanField(default=False),
        ),
        # v3.5.0 cleanup: AlterField → AddField (field never created by prior migration)
        migrations.AddField(
            model_name='clientportalconfig',
            name='secondary_color',
            field=models.CharField(default='#0f172a', max_length=20),
        ),
        # v3.5.0 cleanup: AlterField → AddField (field never created by prior migration)
        migrations.AddField(
            model_name='clientportalconfig',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        # v3.5.0 cleanup: AlterField → AddField (field never created by prior migration)
        migrations.AddField(
            model_name='clientportalconfig',
            name='seo_keywords',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        # v3.5.0 cleanup: AlterField → AddField (field never created by prior migration)
        migrations.AddField(
            model_name='clientportalconfig',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='show_stock_levels',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='store_mode',
            field=models.CharField(choices=[('B2C', 'B2C eCommerce — standard retail prices'), ('B2B', 'B2B Order Portal — tier/negotiated prices'), ('CATALOG_QUOTE', 'Catalog + Quote — browse and request quotes'), ('HYBRID', 'Hybrid — B2C interface, B2B pricing for wholesale/retail clients')], default='HYBRID', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='storefront_tagline',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='storefront_theme',
            field=models.CharField(default='midnight', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='storefront_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='storefront_type',
            field=models.CharField(choices=[('PRODUCT_STORE', 'Product Store — full e-commerce with cart and checkout'), ('CATALOGUE', 'Catalogue — browse products, request quotes, no direct checkout'), ('SUBSCRIPTION', 'Subscription Store — recurring plans and pricing tiers'), ('LANDING_PAGE', 'Landing Page — company website with hero, about, and contact'), ('PORTFOLIO', 'Portfolio — showcase projects, case studies, and inquiries')], default='PRODUCT_STORE', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='tickets_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='wallet_auto_create',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='wallet_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='wallet_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='wallet_max_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('999999.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='clientticket',
            name='satisfaction_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientwallet',
            name='lifetime_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientwallet',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='source_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='reference_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
