# Generated by Django 5.2.11 on 2026-03-03 11:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0009_alter_clientorder_delivery_rating_and_more'),
        ('crm', '0008_contact_supplier_vat_regime_and_more'),
        ('erp', '0009_alter_planaddon_addon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percentage Discount'), ('FIXED', 'Fixed Amount Discount')], default='PERCENT', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 25 for 25%) or fixed amount in org currency', max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum subtotal required to apply this coupon', max_digits=15)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap the discount at this amount (optional)', max_digits=15, null=True)),
                ('max_uses', models.IntegerField(blank=True, help_text='Total uses allowed. Leave blank for unlimited.', null=True)),
                ('used_count', models.IntegerField(default=0)),
                ('one_per_customer', models.BooleanField(default=False, help_text='Each customer can only use this coupon once')),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'client_coupon',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=15)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='crm.contact')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='client_portal.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='client_portal.clientorder')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'client_coupon_usage',
                'ordering': ['-used_at'],
            },
        ),
    ]
