# Generated by Django 5.2.11 on 2026-03-03 12:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0013_merge_0012'),
        ('erp', '0009_alter_planaddon_addon_type'),
        ('pos', '0044_gap10_generated_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartpromotion',
            name='conditions',
            field=models.JSONField(help_text='Rule-specific conditions. Examples:\n          SPEND_THRESHOLD: {"min_subtotal": 50000}\n          BOGO:            {"product_id": 42, "buy_quantity": 2}\n          BUNDLE:          {"product_ids": [42, 55]}\n          MIN_QUANTITY:    {"product_id": 42, "min_quantity": 5}'),
        ),
        migrations.AlterField(
            model_name='cartpromotion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cartpromotion',
            name='max_uses',
            field=models.IntegerField(blank=True, help_text='Total uses allowed across all customers. Null = unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='cartpromotion',
            name='one_per_customer',
            field=models.BooleanField(default=False, help_text='Each customer can only benefit from this promotion once.'),
        ),
        migrations.AlterField(
            model_name='cartpromotion',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='cartpromotion',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher value = evaluated first. Only highest-priority non-stackable promo applies.'),
        ),
        migrations.AlterField(
            model_name='cartpromotion',
            name='reward',
            field=models.JSONField(help_text='Discount to apply when conditions are met. Examples:\n          {"type": "PERCENT_OFF_CART",   "value": 10}\n          {"type": "FIXED_OFF_CART",     "value": 5000}\n          {"type": "FREE_QUANTITY",      "product_id": 42, "free_quantity": 1}\n          {"type": "PERCENT_OFF_LINE",   "value": 20}'),
        ),
        migrations.AlterField(
            model_name='cartpromotion',
            name='stackable',
            field=models.BooleanField(default=False, help_text='If True, this promo can combine with other promotions on the same order.'),
        ),
        migrations.AlterField(
            model_name='cartpromotionusage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cartpromotionusage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='estimated_days',
            field=models.PositiveIntegerField(blank=True, help_text='Override zone.estimated_days for this specific tier', null=True),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shipping fee for orders matching this tier', max_digits=15),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='max_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum order subtotal (exclusive). Null = no ceiling.', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='max_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum cart weight in kg (exclusive). Null = no ceiling.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='min_order_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum order subtotal for this tier to apply (inclusive)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='min_weight_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Minimum cart weight in kg (inclusive)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Lower number = evaluated first when multiple tiers match'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='zone',
            field=models.ForeignKey(help_text='The delivery zone this rate tier belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='pos.deliveryzone'),
        ),
    ]
