# Generated by Django 6.0.4 on 2026-04-12 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0006_alter_clientportalconfig_storefront_type_and_more'),
        ('client_portal', '0015_alter_cartpromotion_organization_and_more'),
    ]

    operations = [
    ]
