# Generated by Django 6.0.3 on 2026-05-02 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.IntegerField()),
                ('granted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kernel_resource_permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kernel_role',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kernel_user_role',
            },
        ),
        migrations.CreateModel(
            name='UserThemePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_mode', models.CharField(choices=[('dark', 'Dark Mode'), ('light', 'Light Mode'), ('auto', 'Auto (system preference)')], default='dark', help_text='Color mode override', max_length=10)),
                ('custom_overrides', models.JSONField(blank=True, default=dict, help_text='User-specific overrides to active theme (optional)')),
            ],
            options={
                'db_table': 'core_user_theme_preference',
            },
        ),
        migrations.CreateModel(
            name='UserTourCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_id', models.CharField(help_text='e.g. finance-chart-of-accounts', max_length=128)),
                ('completed_version', models.IntegerField(default=1, help_text='Tour version at completion; bump to force re-show')),
                ('completed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_tour_completions',
            },
        ),
        migrations.CreateModel(
            name='KernelPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Format: module.action_resource (e.g., finance.create_invoice)', max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('module', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('is_dangerous', models.BooleanField(default=False, help_text='Mark as dangerous (delete, modify critical data)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kernel_permission',
                'indexes': [models.Index(fields=['code'], name='kernel_perm_code_b750f5_idx'), models.Index(fields=['module'], name='kernel_perm_module_e995ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Finance Pro', 'My Custom Theme')", max_length=100)),
                ('slug', models.SlugField(help_text='URL-safe identifier (auto-generated from name)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='User-friendly description of the theme')),
                ('preset_data', models.JSONField(help_text='\n        Complete theme configuration:\n        {\n            "colors": {\n                "dark": { "primary": "#10B981", "bg": "#020617", ... },\n                "light": { "primary": "#10B981", "bg": "#FFFFFF", ... }\n            },\n            "layout": {\n                "density": "dense",\n                "whitespace": "minimal",\n                "structure": "grid",\n                "spacing": { "container": "1rem", ... }\n            },\n            "components": {\n                "cards": { "borderRadius": "0.5rem", ... },\n                "buttons": { "height": "2.5rem", ... },\n                "inputs": { "height": "2.5rem", ... },\n                "typography": { "headingFont": "Inter", ... }\n            },\n            "navigation": {\n                "position": "side",\n                "style": "compact",\n                "width": "220px",\n                "collapsible": true\n            }\n        }\n        ')),
                ('category', models.CharField(choices=[('professional', 'Professional'), ('creative', 'Creative'), ('efficiency', 'Efficiency'), ('specialized', 'Specialized'), ('design-system', 'Design System'), ('custom', 'Custom')], default='custom', help_text='Theme category for organization', max_length=50)),
                ('is_system', models.BooleanField(default=False, help_text='System preset (built-in, cannot be edited/deleted)')),
                ('is_active', models.BooleanField(default=True, help_text='Active themes appear in selector')),
                ('is_default', models.BooleanField(default=False, help_text='Default theme for new users in this organization')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of users currently using this theme')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this theme was selected', null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags for search/filter (e.g., ['dark', 'compact', 'blue'])")),
                ('base_theme', models.ForeignKey(blank=True, help_text='Parent theme if this is a customized variant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='apps_core.organizationtheme')),
            ],
            options={
                'db_table': 'core_organization_theme',
                'ordering': ['-is_system', 'category', 'name'],
            },
        ),
    ]
