# Generated by Django 6.0.3 on 2026-05-02 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_core', '0001_initial'),
        ('erp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtheme',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='resourcepermission',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcepermission',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='resourcepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_core.kernelpermission'),
        ),
        migrations.AddField(
            model_name='resourcepermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='role',
            name='parent_role',
            field=models.ForeignKey(blank=True, help_text='Inherit permissions from parent role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roles', to='apps_core.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='apps_core.kernelpermission'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='apps_core.role'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userthemepreference',
            name='active_theme',
            field=models.ForeignKey(blank=True, help_text='Currently selected theme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_preferences', to='apps_core.organizationtheme'),
        ),
        migrations.AddField(
            model_name='userthemepreference',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='userthemepreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertourcompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='organizationtheme',
            index=models.Index(fields=['organization', 'slug'], name='core_organi_tenant__a7367b_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtheme',
            index=models.Index(fields=['organization', 'is_active'], name='core_organi_tenant__c1599e_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtheme',
            index=models.Index(fields=['organization', 'is_default'], name='core_organi_tenant__60bfdb_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtheme',
            index=models.Index(fields=['is_system', 'is_active'], name='core_organi_is_syst_2712a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationtheme',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_theme_slug_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='resourcepermission',
            index=models.Index(fields=['organization', 'user', 'resource_type', 'resource_id'], name='kernel_reso_tenant__63236d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcepermission',
            unique_together={('organization', 'user', 'permission', 'resource_type', 'resource_id')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization', 'name'], name='kernel_role_tenant__7d80c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['organization', 'user'], name='kernel_user_tenant__e61c89_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role'], name='kernel_user_role_id_386945_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('organization', 'user', 'role', 'resource_type', 'resource_id')},
        ),
        migrations.AddIndex(
            model_name='userthemepreference',
            index=models.Index(fields=['organization', 'user'], name='core_user_t_tenant__a598bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='userthemepreference',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_user_org_theme_pref'),
        ),
        migrations.AddIndex(
            model_name='usertourcompletion',
            index=models.Index(fields=['user', 'tour_id'], name='user_tour_c_user_id_dec172_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usertourcompletion',
            unique_together={('user', 'tour_id')},
        ),
    ]
