# Generated by Django 6.0.4 on 2026-04-20 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_core', '0003_seed_fiscal_permissions'),
        ('erp', '0028_remove_approvalrule_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KernelPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Format: module.action_resource (e.g., finance.create_invoice)', max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('module', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('is_dangerous', models.BooleanField(default=False, help_text='Mark as dangerous (delete, modify critical data)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kernel_permission',
            },
        ),
        migrations.CreateModel(
            name='ResourcePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.IntegerField()),
                ('granted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kernel_resource_permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kernel_role',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kernel_user_role',
            },
        ),
        migrations.AlterModelOptions(
            name='organizationtheme',
            options={'ordering': ['-is_system', 'category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='userthemepreference',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='organizationtheme',
            name='apps_core_o_organiz_idx',
        ),
        migrations.RemoveIndex(
            model_name='userthemepreference',
            name='apps_core_u_user_id_idx',
        ),
        migrations.AddField(
            model_name='organizationtheme',
            name='last_used_at',
            field=models.DateTimeField(blank=True, help_text='Last time this theme was selected', null=True),
        ),
        migrations.AddField(
            model_name='organizationtheme',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Tags for search/filter (e.g., ['dark', 'compact', 'blue'])"),
        ),
        migrations.AddField(
            model_name='userthemepreference',
            name='custom_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='User-specific overrides to active theme (optional)'),
        ),
        migrations.AlterField(
            model_name='organizationtheme',
            name='category',
            field=models.CharField(choices=[('professional', 'Professional'), ('creative', 'Creative'), ('efficiency', 'Efficiency'), ('specialized', 'Specialized'), ('design-system', 'Design System'), ('custom', 'Custom')], default='custom', help_text='Theme category for organization', max_length=50),
        ),
        migrations.AlterField(
            model_name='organizationtheme',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='organizationtheme',
            name='preset_data',
            field=models.JSONField(help_text='\n        Complete theme configuration:\n        {\n            "colors": {\n                "dark": { "primary": "#10B981", "bg": "#020617", ... },\n                "light": { "primary": "#10B981", "bg": "#FFFFFF", ... }\n            },\n            "layout": {\n                "density": "dense",\n                "whitespace": "minimal",\n                "structure": "grid",\n                "spacing": { "container": "1rem", ... }\n            },\n            "components": {\n                "cards": { "borderRadius": "0.5rem", ... },\n                "buttons": { "height": "2.5rem", ... },\n                "inputs": { "height": "2.5rem", ... },\n                "typography": { "headingFont": "Inter", ... }\n            },\n            "navigation": {\n                "position": "side",\n                "style": "compact",\n                "width": "220px",\n                "collapsible": true\n            }\n        }\n        '),
        ),
        migrations.AlterField(
            model_name='userthemepreference',
            name='active_theme',
            field=models.ForeignKey(blank=True, help_text='Currently selected theme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_preferences', to='apps_core.organizationtheme'),
        ),
        migrations.AlterField(
            model_name='userthemepreference',
            name='color_mode',
            field=models.CharField(choices=[('dark', 'Dark Mode'), ('light', 'Light Mode'), ('auto', 'Auto (system preference)')], default='dark', help_text='Color mode override', max_length=10),
        ),
        migrations.AlterField(
            model_name='userthemepreference',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddIndex(
            model_name='organizationtheme',
            index=models.Index(fields=['organization', 'slug'], name='core_organi_tenant__a7367b_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtheme',
            index=models.Index(fields=['organization', 'is_active'], name='core_organi_tenant__c1599e_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtheme',
            index=models.Index(fields=['organization', 'is_default'], name='core_organi_tenant__60bfdb_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtheme',
            index=models.Index(fields=['is_system', 'is_active'], name='core_organi_is_syst_2712a8_idx'),
        ),
        migrations.AddIndex(
            model_name='userthemepreference',
            index=models.Index(fields=['organization', 'user'], name='core_user_t_tenant__a598bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationtheme',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_theme_slug_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='kernelpermission',
            index=models.Index(fields=['code'], name='kernel_perm_code_b750f5_idx'),
        ),
        migrations.AddIndex(
            model_name='kernelpermission',
            index=models.Index(fields=['module'], name='kernel_perm_module_e995ba_idx'),
        ),
        migrations.AddField(
            model_name='resourcepermission',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcepermission',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='resourcepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_core.kernelpermission'),
        ),
        migrations.AddField(
            model_name='resourcepermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='role',
            name='parent_role',
            field=models.ForeignKey(blank=True, help_text='Inherit permissions from parent role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roles', to='apps_core.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='apps_core.kernelpermission'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='apps_core.role'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='resourcepermission',
            index=models.Index(fields=['organization', 'user', 'resource_type', 'resource_id'], name='kernel_reso_tenant__63236d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcepermission',
            unique_together={('organization', 'user', 'permission', 'resource_type', 'resource_id')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization', 'name'], name='kernel_role_tenant__7d80c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['organization', 'user'], name='kernel_user_tenant__e61c89_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role'], name='kernel_user_role_id_386945_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('organization', 'user', 'role', 'resource_type', 'resource_id')},
        ),
    ]
