# Generated by Django 6.0.2 on 2026-02-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount',
            new_name='discount_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='extra_fees',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Dispatched tracking ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tracking_url',
            field=models.URLField(blank=True, help_text='Link to carrier tracking page', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ORDERED', 'Ordered (Sent to Supplier)'), ('CONFIRMED', 'Confirmed by Supplier'), ('IN_TRANSIT', 'In Transit / Dispatched'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Fully Received'), ('INVOICED', 'Invoiced'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=25),
        ),
    ]
