# Generated by Django 5.2.11 on 2026-02-26 02:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_user_pos_pin'),
        ('finance', '0003_alter_journalentryline_employee_alter_taxgroup_rate_and_more'),
        ('inventory', '0004_alter_category_barcode_sequence_and_more'),
        ('pos', '0004_rename_airsi_amount_orderline_subtotal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Caisse 1, Register A', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('allowed_accounts', models.ManyToManyField(blank=True, help_text='Payment accounts available at this register (Wave, OM, Card, etc.)', related_name='register_allowed', to='finance.financialaccount')),
                ('authorized_users', models.ManyToManyField(blank=True, help_text='Users who can operate this register', related_name='authorized_registers', to=settings.AUTH_USER_MODEL)),
                ('cash_account', models.ForeignKey(blank=True, help_text='Cash drawer account for this register', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_cash', to='finance.financialaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_registers', to='erp.site')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Default warehouse for stock deduction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'pos_register',
                'ordering': ['site__name', 'name'],
                'unique_together': {('name', 'site', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='RegisterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSING', 'Closing'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('opening_notes', models.TextField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('expected_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('closing_notes', models.TextField(blank=True, null=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_cash_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_cash_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_sessions', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_sessions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='pos.posregister')),
            ],
            options={
                'db_table': 'pos_register_session',
                'ordering': ['-opened_at'],
            },
        ),
    ]
