# Generated by Django 5.2.11 on 2026-02-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_alter_quotation_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='posregister',
            name='cashier_can_see_software',
            field=models.BooleanField(default=False, help_text='If true, cashier can see software amounts. If false, manager PIN required to reveal.'),
        ),
        migrations.AddField(
            model_name='posregister',
            name='opening_mode',
            field=models.CharField(choices=[('STANDARD', 'Standard — Quick cash open'), ('ADVANCED', 'Advanced — Full reconciliation')], default='STANDARD', help_text='How this register opens: standard (cash only) or advanced (full reconciliation)', max_length=20),
        ),
    ]
