# Generated by Django 5.2.11 on 2026-02-27 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_user_home_site'),
        ('pos', '0013_delivery_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='confirmation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='driver_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='driver_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='last_gps_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='POSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_confirmation_enabled', models.BooleanField(default=False, help_text='When enabled, a 6-digit confirmation code is generated for each delivery. The cashier shares it with the client; the client gives it to the driver to confirm delivery.')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'pos_settings',
            },
        ),
    ]
