# Generated by Django 5.2.11 on 2026-03-02 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0026_possettings_invoice_footer_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possettings',
            name='invoice_footer_text',
        ),
        migrations.RemoveField(
            model_name='possettings',
            name='invoice_header_text',
        ),
        migrations.RemoveField(
            model_name='possettings',
            name='invoice_show_logo',
        ),
        migrations.RemoveField(
            model_name='possettings',
            name='invoice_show_qr',
        ),
    ]
