# Generated by Django 5.2.11 on 2026-03-02 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0031_rename_tax_entry_line_idx_order_line__order_l_a38ac0_idx_and_more'),
        ('pos', '0032_sales_daily_summary'),
    ]

    operations = [
    ]
