# Generated by Django 6.0.2 on 2026-03-02 22:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_seed_app_change_theme_permission'),
        ('inventory', '0010_stock_move'),
        ('pos', '0034_sales_payment_leg'),
    ]

    operations = [
        # Operations that were trying to rename legacy indexes have been removed because 
        # those indexes were already handled or don't exist on the DB as expected.
        migrations.AlterField(
            model_name='salesauditlog',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Arbitrary extra context (e.g. stock_qty, amount_paid)'),
        ),
        migrations.AlterField(
            model_name='salesauditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salesdailysummary',
            name='airsi_withheld',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='AÏRSI tax withheld total', max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesdailysummary',
            name='cogs_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sum of effective_cost × qty across all paid/delivered order lines', max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesdailysummary',
            name='computed_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time this row was (re)computed'),
        ),
        migrations.AlterField(
            model_name='salesdailysummary',
            name='credit_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='A/R credit sales (not yet collected)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesdailysummary',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total discount amount granted', max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesdailysummary',
            name='gross_margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='revenue_ht − cogs_total', max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesdailysummary',
            name='gross_margin_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='gross_margin / revenue_ht × 100', max_digits=7),
        ),
        migrations.AlterField(
            model_name='salesdailysummary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salesdailysummary',
            name='items_sold',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Total quantity of items sold (sum of OrderLine.quantity)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='salesdailysummary',
            name='mobile_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Wave, Orange Money, etc.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesdailysummary',
            name='order_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of Order PKs used in this summary (for debugging)'),
        ),
        migrations.AlterField(
            model_name='salesdailysummary',
            name='scope',
            field=models.CharField(default='OFFICIAL', help_text='OFFICIAL or INTERNAL — matches Order.scope', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesdailysummary',
            name='site',
            field=models.ForeignKey(blank=True, help_text='The site/warehouse this summary covers. NULL = cross-site aggregate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_summaries', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='salesdailysummary',
            name='tax_collected',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='VAT / TVA collected (revenue_ttc - revenue_ht)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesdailysummary',
            name='unique_customers',
            field=models.IntegerField(default=0, help_text='Distinct customer (contact) count'),
        ),
        migrations.AlterField(
            model_name='salesdailysummary',
            name='unique_products',
            field=models.IntegerField(default=0, help_text='Distinct product count for this day/site'),
        ),
        migrations.AlterField(
            model_name='salespaymentleg',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salespaymentleg',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
    ]
