# Generated by Django 6.0.2 on 2026-03-03 02:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_contact_supplier_vat_regime_and_more'),
        ('erp', '0008_seed_app_change_theme_permission'),
        ('inventory', '0011_gap10_performance_indexes'),
        ('pos', '0040_orderlinetaxentry_custom_tax_rule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status', 'created_at'], name='pos_order_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['contact', 'payment_status'], name='pos_order_contact_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['site', 'delivery_status'], name='pos_order_site_delivery_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='pos_order_cashier_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'type', 'created_at'], name='pos_order_org_type_date_idx'),
        ),
    ]
