# Generated by Django 5.2.11 on 2026-03-07 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_goodsreceipt_branch_inventory_branch_and_more'),
        ('pos', '0049_landedcost_landedcostline_purchaseattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Auto-derived from site — do not set manually', limit_choices_to={'location_type': 'BRANCH'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_orders', to='inventory.warehouse'),
        ),
    ]
