# Generated by Django 5.2.11 on 2026-03-08 01:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_clientpricerule_packaging_level_id_and_more'),
        ('erp', '0015_user_assigned_branches'),
        ('inventory', '0019_goodsreceipt_branch_inventory_branch_and_more'),
        ('pos', '0050_order_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('TRANSFER', 'Internal Transfer'), ('PURCHASE', 'Purchase from Supplier')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Executed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('suggested_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('from_warehouse', models.ForeignKey(blank=True, help_text='Source warehouse (for transfers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_requests', to='inventory.warehouse')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_requests', to='inventory.product')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('source_po', models.ForeignKey(blank=True, help_text='The PO being created when this request was generated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_requests', to='pos.purchaseorder')),
                ('supplier', models.ForeignKey(blank=True, limit_choices_to={'type': 'SUPPLIER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='crm.contact')),
                ('to_warehouse', models.ForeignKey(blank=True, help_text='Destination warehouse (for transfers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_requests', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'procurement_request',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='procurement_organiz_59f95e_idx'), models.Index(fields=['organization', 'request_type'], name='procurement_organiz_47c365_idx')],
            },
        ),
    ]
