# Generated by Django 5.2.11 on 2026-03-08 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0051_procurementrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User responsible for following up on this PO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('SUPPLIER_DELIVERS', 'Supplier Delivers'), ('WE_PICKUP', 'We Pick Up')], default='SUPPLIER_DELIVERS', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Driver assigned for pickup/delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check'), ('MOBILE_MONEY', 'Mobile Money'), ('CREDIT', 'On Credit'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
