# Generated by Django 5.2.11 on 2026-03-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0052_purchaseorder_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('100_DELIVERY', '100% at Delivery'), ('NET_30', 'Net 30 Days'), ('NET_60', 'Net 60 Days'), ('NET_90', 'Net 90 Days'), ('PREPAID', 'Prepaid'), ('COD', 'Cash on Delivery'), ('50_50', '50% Advance / 50% Delivery'), ('CUSTOM', 'Custom Terms')], default='100_DELIVERY', max_length=20),
        ),
    ]
