# Generated by Django 6.0.4 on 2026-04-20 02:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_remove_approvalrule_organization_and_more'),
        ('pos', '0077_fne_credit_note_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_info', models.CharField(blank=True, help_text='e.g. Toyota Corolla (ABC-123)', max_length=200, null=True)),
                ('status', models.CharField(choices=[('ONLINE', 'Online / Available'), ('BUSY', 'Busy / Delivering'), ('OFFLINE', 'Offline / Away')], default='OFFLINE', max_length=20)),
                ('is_active_fleet', models.BooleanField(default=True, help_text='Set to False to exclude from auto-dispatch')),
                ('commission_type', models.CharField(choices=[('FLAT', 'Flat Fee per Delivery'), ('PERCENT', 'Percentage of Order Total')], default='FLAT', max_length=10)),
                ('commission_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('last_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_location_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'db_table': 'pos_driver',
            },
        ),
        migrations.RemoveIndex(
            model_name='supplierpackageprice',
            name='spp_supplier_pkg_active_idx',
        ),
        migrations.RemoveConstraint(
            model_name='supplierpackageprice',
            name='unique_spp_per_supplier_pkg_qty',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_sub_type',
            field=models.CharField(choices=[('STANDARD', 'Standard Purchase'), ('WHOLESALE', 'Wholesale Purchase'), ('CONSIGNEE', 'Consignee Purchase')], default='STANDARD', help_text='Sub-classification: Standard/Wholesale (better unit cost)/Consignee (pay on sale)', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SupplierPackagePrice',
        ),
    ]
