"""
WorkspaceAutoTaskService — Auto-task rule engine.

Fires tasks automatically when system events occur, matching
AutoTaskRule conditions against the event context (amount, site,
client, cashier, payment_method).
"""
from decimal import Decimal


def fire_auto_tasks(organization, trigger_event, context: dict):
    """
    Public entry point. Call this from any part of the system when an event occurs.

    Args:
        organization: Organization instance
        trigger_event: str — one of AutoTaskRule.TRIGGER_CHOICES keys
        context: dict with any of:
            amount        — Decimal sale/invoice amount
            site_id       — warehouse/site id
            client_id     — CRM contact id
            cashier_id    — User id of the cashier
            payment_method — str, e.g. 'CREDIT', 'CASH'
            user          — User instance (cashier/actor)
            reference     — str reference (invoice no, order ref)
            extra         — any extra detail for the task description

    Returns: list of created Task instances (may be empty)
    """
    try:
        return _fire_auto_tasks_inner(organization, trigger_event, context)
    except Exception:
        return []  # Never crash the caller


def _fire_auto_tasks_inner(organization, trigger_event, context):
    from apps.workspace.models import AutoTaskRule, Task
    from django.utils import timezone
    from datetime import timedelta

    rules = AutoTaskRule.objects.filter(
        organization=organization,
        trigger_event=trigger_event,
        is_active=True,
    ).select_related('template', 'template__assign_to_role', 'assign_to_user')

    if not rules.exists():
        return []

    amount      = Decimal(str(context.get('amount', 0)))
    site_id     = context.get('site_id')
    client_id   = context.get('client_id')
    cashier_id  = context.get('cashier_id')
    pay_method  = (context.get('payment_method') or '').upper()
    actor_user  = context.get('user')
    reference   = context.get('reference') or ''
    extra       = context.get('extra') or {}

    created_tasks = []

    for rule in rules:
        cond = rule.conditions or {}

        # ── Condition matching ───────────────────────────────────────────────
        min_amount = cond.get('min_amount')
        if min_amount is not None and amount < Decimal(str(min_amount)):
            continue

        max_amount = cond.get('max_amount')
        if max_amount is not None and amount > Decimal(str(max_amount)):
            continue

        cond_site = cond.get('site_id')
        if cond_site is not None and str(site_id) != str(cond_site):
            continue

        cond_client = cond.get('client_id')
        if cond_client is not None and str(client_id) != str(cond_client):
            continue

        cond_cashier = cond.get('cashier_id')
        if cond_cashier is not None and str(cashier_id) != str(cond_cashier):
            continue

        cond_method = cond.get('payment_method')
        if cond_method and pay_method and pay_method != cond_method.upper():
            continue

        # ── Build task from template ─────────────────────────────────────────
        tmpl = rule.template
        actor_name = (
            actor_user.get_full_name() or actor_user.username
            if actor_user else 'System'
        )

        # Build a rich description
        description_lines = [
            f"Auto-generated by rule: {rule.name}",
            f"Trigger: {rule.get_trigger_event_display()}",
        ]
        if reference:
            description_lines.append(f"Reference: {reference}")
        if amount:
            description_lines.append(f"Amount: {amount:,.0f}")
        if actor_name != 'System':
            description_lines.append(f"Cashier/Actor: {actor_name}")
        if client_id:
            description_lines.append(f"Client ID: {client_id}")
        if site_id:
            description_lines.append(f"Site ID: {site_id}")
        if extra:
            description_lines.append(f"Details: {extra}")

        # Due date: 24h from now unless template gives estimated_minutes
        due = timezone.now() + timedelta(hours=24)

        try:
            task = Task.objects.create(
                organization=organization,
                title=f"🤖 {tmpl.name}" if tmpl.name else f"Auto Task: {rule.get_trigger_event_display()}",
                description="\n".join(description_lines),
                priority=tmpl.default_priority or 'HIGH',
                status='PENDING',
                source='SYSTEM',
                auto_rule=rule,
                template=tmpl,
                # Assignment: specific user > role
                assigned_to=rule.assign_to_user or None,
                assigned_to_group=tmpl.assign_to_role if not rule.assign_to_user else None,
                due_date=due,
                related_object_type='AutoTaskRule',
                related_object_id=rule.id,
                related_object_label=reference or rule.name,
                points=tmpl.default_points or 1,
                estimated_minutes=tmpl.estimated_minutes or 30,
            )
            created_tasks.append(task)
        except Exception:
            continue

    return created_tasks
