"""
Barcode Governance Models — BarcodePolicy and ProductBarcode.
"""
from django.db import models
from django.conf import settings
from kernel.tenancy.models import TenantOwnedModel
from kernel.audit.mixins import AuditLogMixin


class BarcodePolicy(AuditLogMixin, TenantOwnedModel):
    """
    Organization-level barcode configuration.
    Singleton per org — governs how barcodes are generated, validated, and managed.
    """
    MODE_CHOICES = (
        ('SUPPLIER', 'Use supplier barcodes only'),
        ('INTERNAL_AUTO', 'Auto-generate internal barcodes'),
        ('MANUAL', 'Manual entry only'),
        ('HYBRID', 'Supplier preferred, auto-generate if missing'),
    )
    FORMAT_CHOICES = (
        ('EAN13', 'EAN-13 (13 digits, European standard)'),
        ('EAN8', 'EAN-8 (8 digits, small items)'),
        ('CODE128', 'Code 128 (alphanumeric, variable length)'),
        ('UPC_A', 'UPC-A (12 digits, North America)'),
        ('FREE', 'Free format (no validation)'),
    )
    SCOPE_CHOICES = (
        ('ORGANIZATION', 'Unique within organization'),
        ('GLOBAL', 'Globally unique across all orgs'),
    )

    mode = models.CharField(max_length=15, choices=MODE_CHOICES, default='HYBRID',
        help_text='How barcodes are sourced for new products')
    prefix = models.CharField(max_length=20, default='2',
        help_text='Org-level prefix for internally generated barcodes')
    category_prefix_enabled = models.BooleanField(default=True,
        help_text='Include category.code in generated barcodes')
    format = models.CharField(max_length=10, choices=FORMAT_CHOICES, default='EAN13',
        help_text='Expected barcode format for validation')
    checksum_enabled = models.BooleanField(default=True,
        help_text='Validate check digit on barcode entry')
    uniqueness_scope = models.CharField(max_length=15, choices=SCOPE_CHOICES, default='ORGANIZATION',
        help_text='Scope of barcode uniqueness enforcement')
    auto_generate_on_create = models.BooleanField(default=True,
        help_text='Auto-generate barcode when product is created without one')
    change_requires_approval = models.BooleanField(default=False,
        help_text='Barcode changes require BarcodeChangeRequest approval')
    prefix_max_length = models.PositiveSmallIntegerField(default=3,
        help_text='Max digits from category code used in barcode prefix')
    prefix_lock_after_generation = models.BooleanField(default=True,
        help_text='Prevent category code change if barcodes were already generated under it')

    class Meta:
        db_table = 'barcode_policy'
        constraints = [
            models.UniqueConstraint(fields=['organization'], name='unique_barcode_policy_per_org'),
        ]
        permissions = [
            ('generate_barcode', 'Can auto/manual generate barcodes'),
            ('change_barcode', 'Can modify existing barcodes'),
            ('verify_packaging', 'Can verify a packaging level'),
            ('reprint_label', 'Can request label reprint'),
            ('edit_barcode_policy', 'Can modify BarcodePolicy settings'),
            ('approve_barcode_change', 'Can approve BarcodeChangeRequests'),
        ]

    def __str__(self):
        return f'BarcodePolicy ({self.mode}) for org {self.organization_id}'


class ProductBarcode(AuditLogMixin, TenantOwnedModel):
    """
    Multi-barcode support per product/packaging.
    Product.barcode remains the primary barcode for backward compat.
    This table stores all barcodes including aliases and supplier codes.
    """
    TYPE_CHOICES = (
        ('PRIMARY', 'Primary barcode — single source of truth'),
        ('ALIAS', 'Alternative barcode (old packaging, regional)'),
        ('SUPPLIER', 'Supplier-assigned barcode'),
        ('INTERNAL', 'Internally generated barcode'),
        ('PACKAGING', 'Packaging-level barcode'),
        ('RETIRED', 'Retired / historical — kept for audit lookup'),
    )
    SOURCE_CHOICES = (
        ('SCANNED', 'Scanned from physical product'),
        ('GENERATED', 'Auto-generated by system'),
        ('MANUAL', 'Manually entered'),
        ('IMPORTED', 'Imported from external system'),
    )

    product = models.ForeignKey(
        'inventory.Product', on_delete=models.CASCADE,
        related_name='barcodes',
    )
    packaging = models.ForeignKey(
        'inventory.ProductPackaging', on_delete=models.CASCADE,
        null=True, blank=True, related_name='barcode_records',
        help_text='If set, this barcode is specific to a packaging level'
    )
    code = models.CharField(max_length=100, db_index=True,
        help_text='The barcode value')
    barcode_type = models.CharField(max_length=10, choices=TYPE_CHOICES, default='PRIMARY')
    source = models.CharField(max_length=10, choices=SOURCE_CHOICES, default='MANUAL')
    is_active = models.BooleanField(default=True,
        help_text='Inactive barcodes are kept for history but not resolved in POS lookup')

    # Generation tracking
    generated_at = models.DateTimeField(null=True, blank=True)
    generated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
        null=True, blank=True, related_name='generated_barcodes',
    )

    class Meta:
        db_table = 'product_barcode'
        ordering = ['-barcode_type', 'code']
        indexes = [
            models.Index(fields=['organization', 'code'], name='pbc_org_code_idx'),
            models.Index(fields=['product', 'barcode_type'], name='pbc_product_type_idx'),
        ]
        constraints = [
            # No duplicate active barcode within an org
            models.UniqueConstraint(
                fields=['code', 'organization'],
                name='unique_barcode_code_per_org',
                condition=models.Q(is_active=True),
            ),
            # One PRIMARY active barcode per product (product-level only)
            models.UniqueConstraint(
                fields=['product', 'organization'],
                name='one_primary_barcode_per_product',
                condition=models.Q(is_active=True, barcode_type='PRIMARY', packaging__isnull=True),
            ),
            # One PRIMARY active barcode per packaging level
            models.UniqueConstraint(
                fields=['packaging', 'organization'],
                name='one_primary_barcode_per_packaging',
                condition=models.Q(is_active=True, barcode_type='PRIMARY', packaging__isnull=False),
            ),
        ]

    def __str__(self):
        return f'{self.barcode_type}: {self.code} → {self.product.sku}'
