"""
Inventory Snapshots & Freeze Periods
======================================
InventoryBalance:      Denormalized snapshot rebuilt async from StockLedger
InventoryBalanceHistory: Daily snapshot for period-close reporting
InventoryFreezePeriod: Blocks movements during accounting close
"""
from decimal import Decimal
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError
from kernel.tenancy.models import TenantOwnedModel
from kernel.audit.mixins import AuditLogMixin


class InventoryBalance(AuditLogMixin, TenantOwnedModel):
    """
    Denormalized snapshot — rebuilt asynchronously from StockLedger.
    Dashboards read from this table, never from the ledger directly.
    """
    product = models.ForeignKey(
        'inventory.Product', on_delete=models.CASCADE,
        related_name='balance_snapshots'
    )
    warehouse = models.ForeignKey(
        'inventory.Warehouse', on_delete=models.CASCADE,
        related_name='balance_snapshots'
    )

    on_hand = models.DecimalField(max_digits=15, decimal_places=3, default=Decimal('0'))
    reserved = models.DecimalField(max_digits=15, decimal_places=3, default=Decimal('0'))
    available = models.DecimalField(
        max_digits=15, decimal_places=3, default=Decimal('0'),
        help_text='Computed: on_hand - reserved'
    )

    avg_cost = models.DecimalField(
        max_digits=15, decimal_places=4, default=Decimal('0'),
        help_text='Weighted average cost from cost layers'
    )
    total_value = models.DecimalField(
        max_digits=15, decimal_places=2, default=Decimal('0'),
        help_text='on_hand × avg_cost'
    )

    last_movement_at = models.DateTimeField(null=True, blank=True)
    last_synced_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'inventory_balance'
        unique_together = ('product', 'warehouse', 'tenant')
        indexes = [
            models.Index(fields=['tenant', 'warehouse']),
            models.Index(fields=['tenant', 'product']),
            models.Index(fields=['tenant', 'available']),
        ]

    def __str__(self):
        return f"{self.product} @ {self.warehouse}: {self.on_hand} on_hand, {self.reserved} reserved"

    def recompute(self):
        """Recompute derived fields."""
        self.available = self.on_hand - self.reserved
        self.total_value = self.on_hand * self.avg_cost


class InventoryBalanceHistory(AuditLogMixin, TenantOwnedModel):
    """
    Daily snapshot for trend analysis and period-close reporting.
    Generated by a scheduled job at end of each business day.
    """
    product = models.ForeignKey(
        'inventory.Product', on_delete=models.CASCADE,
        related_name='balance_history'
    )
    warehouse = models.ForeignKey(
        'inventory.Warehouse', on_delete=models.CASCADE,
        related_name='balance_history'
    )
    snapshot_date = models.DateField(db_index=True)

    on_hand = models.DecimalField(max_digits=15, decimal_places=3)
    reserved = models.DecimalField(max_digits=15, decimal_places=3)
    available = models.DecimalField(max_digits=15, decimal_places=3)
    avg_cost = models.DecimalField(max_digits=15, decimal_places=4)
    total_value = models.DecimalField(max_digits=15, decimal_places=2)

    class Meta:
        db_table = 'inventory_balance_history'
        unique_together = ('product', 'warehouse', 'snapshot_date', 'tenant')
        ordering = ['-snapshot_date']
        indexes = [
            models.Index(fields=['tenant', 'snapshot_date']),
            models.Index(fields=['tenant', 'product', 'snapshot_date']),
        ]

    def __str__(self):
        return f"{self.product} @ {self.warehouse} [{self.snapshot_date}]: {self.on_hand}"


class InventoryFreezePeriod(AuditLogMixin, TenantOwnedModel):
    """
    Blocks all inventory movements during accounting close.
    StockService checks for active freeze before any movement.
    """
    label = models.CharField(max_length=100, help_text='e.g. "March 2026 Close"')
    start_date = models.DateField()
    end_date = models.DateField()
    is_locked = models.BooleanField(default=False)

    locked_by = models.ForeignKey(
        'erp.User', on_delete=models.SET_NULL,
        null=True, blank=True, related_name='frozen_periods'
    )
    locked_at = models.DateTimeField(null=True, blank=True)
    notes = models.TextField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'inventory_freeze_period'
        ordering = ['-start_date']
        indexes = [
            models.Index(fields=['tenant', 'start_date', 'end_date']),
        ]

    def __str__(self):
        status = "🔒 LOCKED" if self.is_locked else "OPEN"
        return f"{self.label} ({self.start_date} → {self.end_date}) [{status}]"

    def lock(self, user):
        """Lock the freeze period."""
        self.is_locked = True
        self.locked_by = user
        self.locked_at = timezone.now()
        self.save()

    def unlock(self, user):
        """Unlock the freeze period (requires authorization)."""
        self.is_locked = False
        self.locked_by = None
        self.locked_at = None
        self.save()

    @classmethod
    def is_date_frozen(cls, tenant, date):
        """Check if a given date falls within a locked freeze period."""
        return cls.objects.filter(
            tenant=tenant,
            is_locked=True,
            start_date__lte=date,
            end_date__gte=date
        ).exists()
