# Generated by Django 6.0.4 on 2026-04-20 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_contact_wallet_balance'),
        ('erp', '0028_remove_approvalrule_organization_and_more'),
        ('iam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactportalaccess',
            name='can_access_ecommerce',
            field=models.BooleanField(default=True, help_text='Can access eCommerce storefront (clients only)'),
        ),
        migrations.AlterField(
            model_name='contactportalaccess',
            name='can_access_portal',
            field=models.BooleanField(default=True, help_text='Can access the portal dashboard'),
        ),
        migrations.AlterField(
            model_name='contactportalaccess',
            name='contact',
            field=models.ForeignKey(help_text='Business entity this user represents', on_delete=django.db.models.deletion.CASCADE, related_name='portal_access_records', to='crm.contact'),
        ),
        migrations.AlterField(
            model_name='contactportalaccess',
            name='created_via',
            field=models.CharField(choices=[('AUTO_LINK', 'Auto-linked on registration'), ('ADMIN_CREATE', 'Created by admin'), ('SELF_REGISTER', 'Self-registration'), ('APPROVAL', 'Created after approval'), ('TRANSFER', 'Persona transfer')], default='ADMIN_CREATE', help_text='How this access record was created (audit trail)', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactportalaccess',
            name='granted_by',
            field=models.ForeignKey(blank=True, help_text='Admin who granted this access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_access_granted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactportalaccess',
            name='is_primary',
            field=models.BooleanField(default=True, help_text='Primary representative for this contact'),
        ),
        migrations.AlterField(
            model_name='contactportalaccess',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='contactportalaccess',
            name='portal_type',
            field=models.CharField(choices=[('CLIENT', 'Client Portal'), ('SUPPLIER', 'Supplier Portal')], help_text='Which portal this access record controls', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactportalaccess',
            name='relationship_role',
            field=models.CharField(choices=[('OWNER', 'Business Owner'), ('REPRESENTATIVE', 'Representative'), ('ACCOUNTING', 'Accounting Contact'), ('LOGISTICS', 'Logistics Contact'), ('PURCHASER', 'Purchaser'), ('SELF', 'Self (Individual)')], default='SELF', help_text='Role of this user relative to the contact entity', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactportalaccess',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('REVOKED', 'Revoked')], default='ACTIVE', help_text='Access grant status (ACTIVE/BLOCKED/REVOKED). No PENDING here — use PortalApprovalRequest for pending state.', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactportalaccess',
            name='user',
            field=models.ForeignKey(help_text='Login identity with portal access', on_delete=django.db.models.deletion.CASCADE, related_name='portal_access_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactportalaccess',
            name='visibility_scope',
            field=models.JSONField(blank=True, default=dict, help_text='Fine-grained visibility scope overrides (future)'),
        ),
        migrations.AlterField(
            model_name='portalapprovalrequest',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='portalapprovalrequest',
            name='resulting_access',
            field=models.ForeignKey(blank=True, help_text='The ContactPortalAccess created as a result of this approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_request', to='iam.contactportalaccess'),
        ),
        migrations.AlterField(
            model_name='portalapprovalrequest',
            name='submitted_data',
            field=models.JSONField(blank=True, default=dict, help_text='Registration form data submitted by the user (company name, phone, tax ID, etc.)'),
        ),
        migrations.AlterField(
            model_name='portalapprovalrequest',
            name='target_contact',
            field=models.ForeignKey(blank=True, help_text='The contact to link to (may be set by admin during approval)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_approval_requests', to='crm.contact'),
        ),
        migrations.AlterField(
            model_name='portalapprovalrequest',
            name='target_user',
            field=models.ForeignKey(help_text='The user requesting access', on_delete=django.db.models.deletion.CASCADE, related_name='portal_approval_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
