# Generated by Django 5.1.7 on 2026-02-19 11:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_initial'),
        ('erp', '0002_initial'),
        ('inventory', '0002_initial'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('SELLING', 'Selling Price Adjustment'), ('PURCHASE', 'Purchase Price Proposal')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COUNTER', 'Counter-Proposal Sent'), ('ACCEPTED', 'Accepted by Supplier')], default='PENDING', max_length=20)),
                ('current_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('proposed_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('counter_price', models.DecimalField(blank=True, decimal_places=2, help_text='Counter-proposal price from admin', max_digits=15, null=True)),
                ('reason', models.TextField(blank=True, help_text='Supplier justification', null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Admin review notes', null=True)),
                ('effective_date', models.DateField(blank=True, help_text='When the new price should take effect', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_price_changes', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_change_requests', to='crm.contact')),
            ],
            options={
                'db_table': 'supplier_price_change_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ORDER_UPDATE', 'Order Status Update'), ('PROFORMA_STATUS', 'Proforma Status Change'), ('PRICE_RESPONSE', 'Price Request Response'), ('STOCK_ALERT', 'Low Stock Alert'), ('GENERAL', 'General Notification')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_notifications', to='crm.contact')),
            ],
            options={
                'db_table': 'supplier_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPortalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked'), ('PENDING', 'Pending Activation')], default='PENDING', max_length=20)),
                ('permissions', models.JSONField(blank=True, default=list, help_text='List of granted permission codes, e.g. ["VIEW_OWN_ORDERS", "CREATE_PROFORMA"]')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contact', models.OneToOneField(help_text='The supplier Contact this portal access is linked to', on_delete=django.db.models.deletion.CASCADE, related_name='portal_access', to='crm.contact')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_supplier_accesses', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('user', models.OneToOneField(help_text='The User account used for portal login', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Supplier Portal Accesses',
                'db_table': 'supplier_portal_access',
            },
        ),
        migrations.CreateModel(
            name='SupplierPortalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proforma_auto_approve_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Auto-approve proformas below this amount (0 = manual only)', max_digits=15)),
                ('require_negotiation_notes', models.BooleanField(default=True)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('enable_price_requests', models.BooleanField(default=True)),
                ('enable_stock_visibility', models.BooleanField(default=True)),
                ('enable_statement_view', models.BooleanField(default=True)),
                ('proforma_status_config', models.JSONField(blank=True, default=dict, help_text='JSON: {"DRAFT": {"label": "Draft", "color": "#94a3b8"}, ...}')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'verbose_name': 'Supplier Portal Configuration',
                'verbose_name_plural': 'Supplier Portal Configurations',
                'db_table': 'supplier_portal_config',
            },
        ),
        migrations.CreateModel(
            name='SupplierProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proforma_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('status', models.CharField(default='DRAFT', help_text='Internal status code', max_length=20)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_terms', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valid_until', models.DateField(blank=True, help_text='Proforma validity expiration', null=True)),
                ('supplier_notes', models.TextField(blank=True, help_text='Notes from supplier', null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal review notes', null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('negotiation_notes', models.TextField(blank=True, help_text='Counter-proposal details', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by_supplier', models.ForeignKey(blank=True, help_text='Supplier portal user who created this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proformas', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_proforma', to='pos.purchaseorder')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_proformas', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(help_text='The supplier who created this proforma', on_delete=django.db.models.deletion.PROTECT, related_name='supplier_proformas', to='crm.contact')),
            ],
            options={
                'db_table': 'supplier_proforma',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProformaLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('sort_order', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='supplier_portal.supplierproforma')),
            ],
            options={
                'db_table': 'supplier_proforma_line',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
