# Generated by Django 6.0.2 on 2026-03-05 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_transactionstatuslog_meta_transactiontype_and_more'),
        ('supplier_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricechangerequest',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='proformaline',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='suppliernotification',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='supplierportalaccess',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='supplierportalconfig',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='supplierproforma',
            name='organization',
        ),
        migrations.AddField(
            model_name='pricechangerequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='proformaline',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='suppliernotification',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='supplierportalaccess',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='supplierportalconfig',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='supplierproforma',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
    ]
