# Generated by Django 6.0.4 on 2026-04-20 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_remove_approvalrule_organization_and_more'),
        ('supplier_portal', '0002_remove_pricechangerequest_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricechangerequest',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proformaline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suppliernotification',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierportalaccess',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierportalconfig',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierproforma',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
    ]
