# Generated by Django 5.2.12 on 2026-03-11 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0014_alter_cartpromotion_conditions_and_more'),
        ('erp', '0021_alter_approvalrule_organization_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='cartpromotion',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='cartpromotionusage',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='clientorder',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='clientorderline',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='clientportalaccess',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='clientportalconfig',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='clientticket',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='clientwallet',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='coupon',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='couponusage',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='productreview',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='quoteitem',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='quoterequest',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='shippingrate',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='wallettransaction',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
                migrations.AlterField(
                    model_name='wishlistitem',
                    name='organization',
                    field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
                ),
            ],
            database_operations=[]
        )
    ]
