# Generated by Django 6.0.4 on 2026-04-20 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0016_merge_20260412_0207'),
        ('erp', '0028_remove_approvalrule_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='product',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='cartpromotion',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='cartpromotionusage',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='clientorderline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='clientportalaccess',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='allow_guest_browsing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='require_approval_for_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='show_stock_levels',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='store_mode',
            field=models.CharField(choices=[('B2C', 'B2C eCommerce — standard retail prices'), ('B2B', 'B2B Order Portal — tier/negotiated prices'), ('CATALOG_QUOTE', 'Catalog + Quote — browse and request quotes'), ('HYBRID', 'Hybrid — B2C interface, B2B pricing for wholesale/retail clients')], default='HYBRID', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='storefront_tagline',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='storefront_theme',
            field=models.CharField(default='midnight', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='storefront_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='storefront_type',
            field=models.CharField(choices=[('PRODUCT_STORE', 'Product Store — full e-commerce with cart and checkout'), ('CATALOGUE', 'Catalogue — browse products, request quotes, no direct checkout'), ('SUBSCRIPTION', 'Subscription Store — recurring plans and pricing tiers'), ('LANDING_PAGE', 'Landing Page — company website with hero, about, and contact'), ('PORTFOLIO', 'Portfolio — showcase projects, case studies, and inquiries')], default='PRODUCT_STORE', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientticket',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='clientwallet',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='source_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
    ]
