# Generated by Django 5.1.7 on 2026-02-16 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UltimatePOS Migration', max_length=255)),
                ('source_type', models.CharField(choices=[('SQL_DUMP', 'SQL Dump File'), ('DIRECT_DB', 'Direct MySQL Connection')], default='SQL_DUMP', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARSING', 'Parsing Source'), ('RUNNING', 'Running Migration'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled Back')], default='PENDING', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('db_host', models.CharField(blank=True, max_length=255, null=True)),
                ('db_port', models.IntegerField(blank=True, default=3306, null=True)),
                ('db_name', models.CharField(blank=True, max_length=255, null=True)),
                ('db_user', models.CharField(blank=True, max_length=255, null=True)),
                ('db_password', models.CharField(blank=True, max_length=255, null=True)),
                ('total_units', models.IntegerField(default=0)),
                ('total_categories', models.IntegerField(default=0)),
                ('total_brands', models.IntegerField(default=0)),
                ('total_products', models.IntegerField(default=0)),
                ('total_contacts', models.IntegerField(default=0)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_accounts', models.IntegerField(default=0)),
                ('total_inventory', models.IntegerField(default=0)),
                ('total_errors', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=100, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'migration_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('UNIT', 'Unit'), ('CATEGORY', 'Category'), ('BRAND', 'Brand'), ('PRODUCT', 'Product'), ('CONTACT', 'Contact'), ('TRANSACTION', 'Transaction'), ('ORDER_LINE', 'Order Line'), ('ACCOUNT', 'Account'), ('INVENTORY', 'Inventory'), ('SITE', 'Site')], max_length=20)),
                ('source_id', models.IntegerField(help_text='Original ID from UltimatePOS')),
                ('target_id', models.IntegerField(help_text='New ID in TSF system')),
                ('source_table', models.CharField(help_text='Original table name', max_length=100)),
                ('extra_data', models.JSONField(blank=True, help_text='Any unmapped fields stored for reference', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='data_migration.migrationjob')),
            ],
            options={
                'db_table': 'migration_mapping',
                'indexes': [models.Index(fields=['job', 'entity_type'], name='migration_m_job_id_ac568f_idx'), models.Index(fields=['entity_type', 'source_id'], name='migration_m_entity__25f0d4_idx')],
                'unique_together': {('job', 'entity_type', 'source_id')},
            },
        ),
    ]
