# Generated by Django 5.1.7 on 2026-02-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='migration_mode',
            field=models.CharField(choices=[('FULL', 'Full Import'), ('SYNC', 'Sync (only new records)')], default='FULL', help_text='FULL = import all, SYNC = skip records already imported', max_length=10),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='source_business_id',
            field=models.IntegerField(blank=True, help_text='UltimatePOS business_id to migrate. NULL = all businesses.', null=True),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='source_business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
