# Generated by Django 6.0.2 on 2026-02-22 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration', '0001_initial'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='stored_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_jobs', to='storage.storedfile'),
        ),
        migrations.AlterField(
            model_name='migrationjob',
            name='file_path',
            field=models.CharField(blank=True, help_text='Legacy local path fallback', max_length=500, null=True),
        ),
    ]
