# Generated by Django 6.0.2 on 2026-02-23 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_migration', '0001_initial'),
        ('erp', '0001_initial'),
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='stored_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_jobs', to='storage.storedfile'),
        ),
        migrations.AddField(
            model_name='migrationmapping',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='data_migration.migrationjob'),
        ),
        migrations.AddIndex(
            model_name='migrationmapping',
            index=models.Index(fields=['job', 'entity_type'], name='migration_m_job_id_ac568f_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationmapping',
            index=models.Index(fields=['entity_type', 'source_id'], name='migration_m_entity__25f0d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='migrationmapping',
            unique_together={('job', 'entity_type', 'source_id')},
        ),
    ]
