# Generated by Django 5.2.11 on 2026-02-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='discovered_data',
            field=models.JSONField(blank=True, help_text='JSON result of source analysis (businesses, table counts)', null=True),
        ),
        migrations.AlterField(
            model_name='migrationmapping',
            name='entity_type',
            field=models.CharField(choices=[('UNIT', 'Unit'), ('CATEGORY', 'Category'), ('BRAND', 'Brand'), ('PRODUCT', 'Product'), ('CONTACT', 'Contact'), ('TRANSACTION', 'Transaction'), ('ORDER_LINE', 'Order Line'), ('ACCOUNT', 'Account'), ('INVENTORY', 'Inventory'), ('SITE', 'Site'), ('TAX_GROUP', 'Tax Group')], max_length=20),
        ),
    ]
