# Generated by Django 5.2.11 on 2026-02-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration', '0003_migrationjob_discovered_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='error_summary',
            field=models.JSONField(blank=True, help_text='Counts of errors by type', null=True),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
