# Generated by Django 5.2.11 on 2026-02-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration', '0004_migrationjob_error_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationmapping',
            name='entity_type',
            field=models.CharField(choices=[('UNIT', 'Unit'), ('CATEGORY', 'Category'), ('BRAND', 'Brand'), ('PRODUCT', 'Product'), ('CONTACT', 'Contact'), ('TRANSACTION', 'Transaction'), ('ORDER_LINE', 'Order Line'), ('ACCOUNT', 'Account'), ('INVENTORY', 'Inventory'), ('SITE', 'Site'), ('TAX_GROUP', 'Tax Group'), ('PAYMENT', 'Payment'), ('EXPENSE', 'Expense'), ('COMBO_LINK', 'Combo Component Link')], max_length=20),
        ),
    ]
