# Generated by Django 5.2.11 on 2026-02-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration', '0006_alter_migrationmapping_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='completed_steps',
            field=models.JSONField(blank=True, default=list, help_text='List of step names that completed successfully', null=True),
        ),
        migrations.AlterField(
            model_name='migrationjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARSING', 'Parsing Source'), ('RUNNING', 'Running Migration'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('STALLED', 'Stalled / Crashed'), ('ROLLED_BACK', 'Rolled Back')], default='PENDING', max_length=20),
        ),
    ]
