# Generated by Django 6.0.2 on 2026-03-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration', '0011_migrationmapping_audit_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='total_flagged',
            field=models.IntegerField(default=0, help_text='Total entities flagged for review'),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='total_verified',
            field=models.IntegerField(default=0, help_text='Total entities verified by auditing'),
        ),
    ]
