# Generated by Django 5.2.11 on 2026-03-01 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration', '0012_migrationjob_total_flagged_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migrationjob',
            name='total_flagged',
        ),
        migrations.RemoveField(
            model_name='migrationjob',
            name='total_verified',
        ),
        migrations.RemoveField(
            model_name='migrationmapping',
            name='audit_at',
        ),
        migrations.RemoveField(
            model_name='migrationmapping',
            name='audit_notes',
        ),
        migrations.RemoveField(
            model_name='migrationmapping',
            name='audit_status',
        ),
        migrations.RemoveField(
            model_name='migrationmapping',
            name='audited_by',
        ),
    ]
