# Generated by Django 6.0.2 on 2026-03-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration', '0014_migrationjob_total_flagged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARSING', 'Parsing Source'), ('RUNNING', 'Running Migration'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('STALLED', 'Stalled / Crashed'), ('ROLLED_BACK', 'Rolled Back'), ('HIDDEN', 'Hidden / Deleted')], default='PENDING', max_length=20),
        ),
    ]
