# Generated by Django 5.2.12 on 2026-03-11 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration', '0015_alter_migrationjob_status'),
        ('erp', '0021_alter_approvalrule_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationjob',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
    ]
