# Generated by Django 6.0.4 on 2026-04-20 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration', '0016_alter_migrationjob_organization'),
        ('erp', '0028_remove_approvalrule_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migrationjob',
            name='completed_steps',
        ),
        migrations.RemoveField(
            model_name='migrationjob',
            name='current_step_detail',
        ),
        migrations.RemoveField(
            model_name='migrationjob',
            name='db_password_encrypted',
        ),
        migrations.RemoveField(
            model_name='migrationjob',
            name='discovered_data',
        ),
        migrations.RemoveField(
            model_name='migrationjob',
            name='error_summary',
        ),
        migrations.RemoveField(
            model_name='migrationjob',
            name='last_heartbeat',
        ),
        migrations.RemoveField(
            model_name='migrationjob',
            name='stored_file',
        ),
        migrations.RemoveField(
            model_name='migrationjob',
            name='total_flagged',
        ),
        migrations.RemoveField(
            model_name='migrationjob',
            name='total_verified',
        ),
        migrations.RemoveField(
            model_name='migrationmapping',
            name='audit_at',
        ),
        migrations.RemoveField(
            model_name='migrationmapping',
            name='audit_notes',
        ),
        migrations.RemoveField(
            model_name='migrationmapping',
            name='audit_status',
        ),
        migrations.RemoveField(
            model_name='migrationmapping',
            name='audited_by',
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='db_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='migrationjob',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='migration_jobs', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='migrationjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARSING', 'Parsing Source'), ('RUNNING', 'Running Migration'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled Back')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='migrationmapping',
            name='entity_type',
            field=models.CharField(choices=[('UNIT', 'Unit'), ('CATEGORY', 'Category'), ('BRAND', 'Brand'), ('PRODUCT', 'Product'), ('CONTACT', 'Contact'), ('TRANSACTION', 'Transaction'), ('ORDER_LINE', 'Order Line'), ('ACCOUNT', 'Account'), ('INVENTORY', 'Inventory'), ('SITE', 'Site')], max_length=20),
        ),
    ]
