# Generated by Django 6.0.2 on 2026-02-21 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_portal', '0007_remove_quoterequest_product_and_more'),
        ('erp', '0003_plancategory_linked_inventory_category_and_more'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('SHOPIFY', 'Shopify'), ('WOOCOMMERCE', 'WooCommerce')], max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('api_url', models.URLField(help_text='Store base URL (e.g., https://mystore.myshopify.com)')),
                ('api_key_encrypted', models.TextField(blank=True, null=True)),
                ('api_secret_encrypted', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'ecommerce_integration',
                'unique_together': {('organization', 'platform', 'api_url')},
            },
        ),
        migrations.CreateModel(
            name='ExternalOrderMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('external_number', models.CharField(blank=True, max_length=100, null=True)),
                ('last_sync_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_mappings', to='integrations.ecommerceintegration')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_mappings', to='client_portal.clientorder')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'external_order_mapping',
                'unique_together': {('integration', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='ExternalProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('external_variant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_sync_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='integrations.ecommerceintegration')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_mappings', to='inventory.product')),
            ],
            options={
                'db_table': 'external_product_mapping',
                'unique_together': {('integration', 'external_id', 'external_variant_id')},
            },
        ),
    ]
