# Generated by Django 6.0.3 on 2026-05-02 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order.placed', 'Order Placed'), ('order.confirmed', 'Order Confirmed'), ('order.shipped', 'Order Shipped'), ('order.delivered', 'Order Delivered'), ('order.cancelled', 'Order Cancelled'), ('order.returned', 'Order Returned'), ('payment.confirmed', 'Payment Confirmed')], help_text="Event type to subscribe to (e.g. 'order.placed')", max_length=50)),
                ('target_url', models.URLField(help_text='URL that will receive POST requests with the event payload')),
                ('secret', models.CharField(blank=True, default='', help_text='HMAC-SHA256 secret for payload signing. Set and share with the receiver.', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'webhook_subscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='integrations.webhooksubscription')),
            ],
            options={
                'db_table': 'webhook_delivery_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
