"""
Chart of Accounts Templates
Keys must match the frontend coa-templates.ts exactly.
"""

TEMPLATES = {
    "IFRS_COA": {
        "name": "IFRS COA",
        "description": "International Financial Reporting Standards",
        "accounts": [
            {"code": "1000", "name": "ASSETS", "type": "ASSET"},
            {"code": "1100", "name": "Current Assets", "type": "ASSET", "parent_code": "1000"},
            {"code": "1101", "name": "Cash & Cash Equivalents", "type": "ASSET", "parent_code": "1100"},
            {"code": "1101.01", "name": "Cash in Hand", "type": "ASSET", "sub_type": "CASH", "parent_code": "1101", "syscohada_code": "57", "syscohada_class": "5"},
            {"code": "1101.02", "name": "Cash Register (POS)", "type": "ASSET", "sub_type": "CASH", "parent_code": "1101", "syscohada_code": "57", "syscohada_class": "5"},
            {"code": "1101.03", "name": "Main Bank Account", "type": "ASSET", "sub_type": "BANK", "parent_code": "1101", "syscohada_code": "52", "syscohada_class": "5"},
            {"code": "1110", "name": "Accounts Receivable", "type": "ASSET", "sub_type": "RECEIVABLE", "parent_code": "1100"},
            {"code": "1120", "name": "Inventory", "type": "ASSET", "parent_code": "1100"},
            {"code": "1121", "name": "Raw Materials", "type": "ASSET", "sub_type": "INVENTORY", "parent_code": "1120"},
            {"code": "1122", "name": "Finished Goods", "type": "ASSET", "sub_type": "INVENTORY", "parent_code": "1120"},
            {"code": "1123", "name": "Work in Progress", "type": "ASSET", "sub_type": "INVENTORY", "parent_code": "1120"},
            {"code": "1124", "name": "Goods in Transit", "type": "ASSET", "sub_type": "INVENTORY", "parent_code": "1120"},
            {"code": "1130", "name": "Prepaid Expenses", "type": "ASSET", "parent_code": "1100"},
            {"code": "1131", "name": "Prepaid Insurance", "type": "ASSET", "parent_code": "1130"},
            {"code": "1132", "name": "Prepaid Rent", "type": "ASSET", "parent_code": "1130"},
            {"code": "1140", "name": "Employee Advances", "type": "ASSET", "sub_type": "RECEIVABLE", "parent_code": "1100"},
            {"code": "1150", "name": "Deposits & Guarantees", "type": "ASSET", "parent_code": "1100"},
            {"code": "1160", "name": "Short-Term Investments", "type": "ASSET", "parent_code": "1100"},
            {"code": "1200", "name": "Non-Current Assets", "type": "ASSET", "parent_code": "1000"},
            {"code": "1201", "name": "Land", "type": "ASSET", "parent_code": "1200"},
            {"code": "1202", "name": "Buildings", "type": "ASSET", "parent_code": "1200"},
            {"code": "1203", "name": "Furniture & Fixtures", "type": "ASSET", "parent_code": "1200"},
            {"code": "1204", "name": "Equipment", "type": "ASSET", "parent_code": "1200"},
            {"code": "1205", "name": "Vehicles", "type": "ASSET", "parent_code": "1200"},
            {"code": "1206", "name": "Software / Intangible Assets", "type": "ASSET", "parent_code": "1200"},
            {"code": "1207", "name": "Leasehold Improvements", "type": "ASSET", "parent_code": "1200"},
            {"code": "1210", "name": "Accumulated Depreciation", "type": "ASSET", "parent_code": "1000"},
            {"code": "1211", "name": "Accum. Depr. - Equipment", "type": "ASSET", "parent_code": "1210"},
            {"code": "1212", "name": "Accum. Depr. - Vehicles", "type": "ASSET", "parent_code": "1210"},
            {"code": "1213", "name": "Accum. Amort. - Software", "type": "ASSET", "parent_code": "1210"},
            {"code": "2000", "name": "LIABILITIES", "type": "LIABILITY"},
            {"code": "2100", "name": "Current Liabilities", "type": "LIABILITY", "parent_code": "2000"},
            {"code": "2101", "name": "Accounts Payable", "type": "LIABILITY", "sub_type": "PAYABLE", "parent_code": "2100"},
            {"code": "2102", "name": "Accrued Liabilities", "type": "LIABILITY", "parent_code": "2100"},
            {"code": "2103", "name": "Customer Deposits", "type": "LIABILITY", "parent_code": "2100"},
            {"code": "2104", "name": "Goods Received Not Invoiced", "type": "LIABILITY", "parent_code": "2100"},
            {"code": "2110", "name": "Taxes Payable", "type": "LIABILITY", "parent_code": "2100"},
            {"code": "2111", "name": "VAT Payable", "type": "LIABILITY", "parent_code": "2110"},
            {"code": "2112", "name": "Income Tax Payable", "type": "LIABILITY", "parent_code": "2110"},
            {"code": "2113", "name": "Payroll Tax Payable", "type": "LIABILITY", "parent_code": "2110"},
            {"code": "2114", "name": "Reverse Charge VAT", "type": "LIABILITY", "parent_code": "2110"},
            {"code": "2115", "name": "VAT Refund Receivable", "type": "ASSET", "parent_code": "2110"},
            {"code": "2116", "name": "VAT Suspense (Cash-Basis)", "type": "LIABILITY", "parent_code": "2110"},
            {"code": "2117", "name": "VAT Collected (Output)", "type": "LIABILITY", "parent_code": "2110"},
            {"code": "2118", "name": "VAT Deductible (Input)", "type": "ASSET", "parent_code": "2110"},
            {"code": "2119", "name": "Withholding Tax – AIRSI", "type": "LIABILITY", "parent_code": "2110"},
            {"code": "2120", "name": "Accrued Expenses", "type": "LIABILITY", "parent_code": "2100"},
            {"code": "2121", "name": "Salaries Payable", "type": "LIABILITY", "parent_code": "2120"},
            {"code": "2122", "name": "Rent Payable", "type": "LIABILITY", "parent_code": "2120"},
            {"code": "2123", "name": "Utilities Payable", "type": "LIABILITY", "parent_code": "2120"},
            {"code": "2124", "name": "Accrued Interest", "type": "LIABILITY", "parent_code": "2120"},
            {"code": "2130", "name": "Deferred Revenue", "type": "LIABILITY", "parent_code": "2100"},
            {"code": "2200", "name": "Long-Term Liabilities", "type": "LIABILITY", "parent_code": "2000"},
            {"code": "2201", "name": "Bank Loan", "type": "LIABILITY", "parent_code": "2200"},
            {"code": "2202", "name": "Lease Liability", "type": "LIABILITY", "parent_code": "2200"},
            {"code": "3000", "name": "EQUITY", "type": "EQUITY"},
            {"code": "3001", "name": "Owner Capital", "type": "EQUITY", "parent_code": "3000"},
            {"code": "3002", "name": "Additional Capital", "type": "EQUITY", "parent_code": "3000"},
            {"code": "3003", "name": "Retained Earnings", "type": "EQUITY", "parent_code": "3000"},
            {"code": "3004", "name": "Current Year Profit / Loss", "type": "EQUITY", "parent_code": "3000"},
            {"code": "3005", "name": "Owner Draws / Withdrawals", "type": "EQUITY", "parent_code": "3000"},
            {"code": "3006", "name": "Reserves", "type": "EQUITY", "parent_code": "3000"},
            {"code": "4000", "name": "REVENUE", "type": "INCOME"},
            {"code": "4100", "name": "Sales Revenue", "type": "INCOME", "parent_code": "4000"},
            {"code": "4101", "name": "Sales - Cash", "type": "INCOME", "parent_code": "4100"},
            {"code": "4102", "name": "Sales - Credit", "type": "INCOME", "parent_code": "4100"},
            {"code": "4103", "name": "Sales - Online", "type": "INCOME", "parent_code": "4100"},
            {"code": "4104", "name": "Sales Returns & Allowances", "type": "INCOME", "parent_code": "4100"},
            {"code": "4200", "name": "Other Income", "type": "INCOME", "parent_code": "4000"},
            {"code": "4201", "name": "Discount Received", "type": "INCOME", "parent_code": "4200"},
            {"code": "4202", "name": "Interest Income", "type": "INCOME", "parent_code": "4200"},
            {"code": "4203", "name": "Inventory Adjustment Gain", "type": "INCOME", "parent_code": "4200"},
            {"code": "4204", "name": "Foreign Exchange Gain", "type": "INCOME", "parent_code": "4200"},
            {"code": "4205", "name": "Commission Income", "type": "INCOME", "parent_code": "4200"},
            {"code": "5000", "name": "COST OF GOODS SOLD (COGS)", "type": "EXPENSE"},
            {"code": "5100", "name": "Cost of Sales", "type": "EXPENSE", "parent_code": "5000"},
            {"code": "5101", "name": "Cost of Goods Purchased", "type": "EXPENSE", "parent_code": "5100"},
            {"code": "5102", "name": "Freight In", "type": "EXPENSE", "parent_code": "5100"},
            {"code": "5103", "name": "Import Duties", "type": "EXPENSE", "parent_code": "5100"},
            {"code": "5104", "name": "Inventory Adjustment", "type": "EXPENSE", "parent_code": "5100"},
            {"code": "5105", "name": "Packaging & Materials", "type": "EXPENSE", "parent_code": "5100"},
            {"code": "6000", "name": "OPERATING EXPENSES", "type": "EXPENSE"},
            {"code": "6100", "name": "Operating Expenses", "type": "EXPENSE", "parent_code": "6000"},
            {"code": "6101", "name": "Salaries & Wages", "type": "EXPENSE", "parent_code": "6100"},
            {"code": "6102", "name": "Transport Allowance", "type": "EXPENSE", "parent_code": "6100"},
            {"code": "6103", "name": "Rent Expense", "type": "EXPENSE", "parent_code": "6100"},
            {"code": "6104", "name": "Utilities Expense", "type": "EXPENSE", "parent_code": "6100"},
            {"code": "6105", "name": "Internet & Phone", "type": "EXPENSE", "parent_code": "6100"},
            {"code": "6106", "name": "Insurance Expense", "type": "EXPENSE", "parent_code": "6100"},
            {"code": "6107", "name": "Repairs & Maintenance", "type": "EXPENSE", "parent_code": "6100"},
            {"code": "6200", "name": "Administrative Expenses", "type": "EXPENSE", "parent_code": "6000"},
            {"code": "6201", "name": "Office Supplies", "type": "EXPENSE", "parent_code": "6200"},
            {"code": "6202", "name": "Software / POS Subscription", "type": "EXPENSE", "parent_code": "6200"},
            {"code": "6203", "name": "Professional Fees", "type": "EXPENSE", "parent_code": "6200"},
            {"code": "6204", "name": "Travel & Entertainment", "type": "EXPENSE", "parent_code": "6200"},
            {"code": "6205", "name": "Marketing & Advertising", "type": "EXPENSE", "parent_code": "6200"},
            {"code": "6206", "name": "Legal Fees", "type": "EXPENSE", "parent_code": "6200"},
            {"code": "6300", "name": "Financial Expenses", "type": "EXPENSE", "parent_code": "6000"},
            {"code": "6301", "name": "Bank Charges", "type": "EXPENSE", "parent_code": "6300"},
            {"code": "6302", "name": "Interest Expense", "type": "EXPENSE", "parent_code": "6300"},
            {"code": "6303", "name": "Depreciation & Amortization", "type": "EXPENSE", "parent_code": "6300"},
            {"code": "6304", "name": "Bad Debt Expense", "type": "EXPENSE", "parent_code": "6300"},
            {"code": "6305", "name": "Foreign Exchange Loss", "type": "EXPENSE", "parent_code": "6300"},
            {"code": "6306", "name": "Discount Given", "type": "EXPENSE", "parent_code": "6300"},
            {"code": "9000", "name": "SYSTEM & CLEARING ACCOUNTS", "type": "EXPENSE", "is_hidden": True},
            {"code": "9001", "name": "Stock Adjustment Control", "type": "EXPENSE", "parent_code": "9000", "is_system_only": True, "requires_zero_balance": True},
            {"code": "9002", "name": "POS Rounding Difference", "type": "INCOME", "parent_code": "9000", "is_system_only": True},
            {"code": "9003", "name": "Exchange Difference", "type": "INCOME", "parent_code": "9000", "is_system_only": True},
        ]
    },
    "LEBANESE_PCN": {
        "name": "Lebanese PCN",
        "description": "Plan Comptable National Libanais",
        "accounts": [
            {"code": "1", "name": "Capitaux et Passif Non Courant", "type": "EQUITY"},
            {"code": "10", "name": "Capital", "type": "EQUITY", "parent_code": "1"},
            {"code": "11", "name": "Reserves", "type": "EQUITY", "parent_code": "1"},
            {"code": "12", "name": "Resultat reporte", "type": "EQUITY", "parent_code": "1"},
            {"code": "13", "name": "Resultat de l'exercice", "type": "EQUITY", "parent_code": "1"},
            {"code": "2", "name": "Actif Non Courant (Immobilisations)", "type": "ASSET"},
            {"code": "21", "name": "Immobilisations Incorporelles", "type": "ASSET", "parent_code": "2"},
            {"code": "22", "name": "Immobilisations Corporelles", "type": "ASSET", "parent_code": "2"},
            {"code": "24", "name": "Immobilisations Financieres", "type": "ASSET", "parent_code": "2"},
            {"code": "3", "name": "Stocks et En-cours", "type": "ASSET"},
            {"code": "31", "name": "Marchandises", "type": "ASSET", "parent_code": "3"},
            {"code": "32", "name": "Matieres Premieres", "type": "ASSET", "parent_code": "3"},
            {"code": "4", "name": "Comptes de Tiers", "type": "LIABILITY"},
            {"code": "40", "name": "Fournisseurs", "type": "LIABILITY", "sub_type": "PAYABLE", "parent_code": "4"},
            {"code": "41", "name": "Clients (Creances)", "type": "ASSET", "sub_type": "RECEIVABLE", "parent_code": "4"},
            {"code": "42", "name": "Personnel", "type": "LIABILITY", "parent_code": "4"},
            {"code": "43", "name": "Organismes Sociaux", "type": "LIABILITY", "parent_code": "4"},
            {"code": "44", "name": "Etat et Collectivites Publiques", "type": "LIABILITY", "parent_code": "4"},
            {"code": "5", "name": "Comptes Financiers", "type": "ASSET"},
            {"code": "51", "name": "Banques", "type": "ASSET", "sub_type": "BANK", "parent_code": "5"},
            {"code": "53", "name": "Caisse", "type": "ASSET", "sub_type": "CASH", "parent_code": "5"},
            {"code": "6", "name": "Comptes de Charges", "type": "EXPENSE"},
            {"code": "60", "name": "Achats", "type": "EXPENSE", "parent_code": "6"},
            {"code": "61", "name": "Services Exterieurs", "type": "EXPENSE", "parent_code": "6"},
            {"code": "62", "name": "Autres Services Exterieurs", "type": "EXPENSE", "parent_code": "6"},
            {"code": "63", "name": "Impots et Taxes", "type": "EXPENSE", "parent_code": "6"},
            {"code": "64", "name": "Charges de Personnel", "type": "EXPENSE", "parent_code": "6"},
            {"code": "66", "name": "Charges Financieres", "type": "EXPENSE", "parent_code": "6"},
            {"code": "7", "name": "Comptes de Produits", "type": "INCOME"},
            {"code": "70", "name": "Ventes de Marchandises", "type": "INCOME", "parent_code": "7"},
            {"code": "71", "name": "Production Vendue", "type": "INCOME", "parent_code": "7"},
            {"code": "76", "name": "Produits Financiers", "type": "INCOME", "parent_code": "7"},
            {"code": "77", "name": "Produits Exceptionnels", "type": "INCOME", "parent_code": "7"},
        ]
    },
    "FRENCH_PCG": {
        "name": "French PCG",
        "description": "Plan Comptable General (France)",
        "accounts": [
            {"code": "1", "name": "Comptes de capitaux", "type": "EQUITY"},
            {"code": "10", "name": "Capital et reserves", "type": "EQUITY", "parent_code": "1"},
            {"code": "11", "name": "Report a nouveau", "type": "EQUITY", "parent_code": "1"},
            {"code": "12", "name": "Resultat de l'exercice", "type": "EQUITY", "parent_code": "1"},
            {"code": "16", "name": "Emprunts et dettes assimilees", "type": "LIABILITY", "parent_code": "1"},
            {"code": "2", "name": "Comptes d'immobilisations", "type": "ASSET"},
            {"code": "20", "name": "Immobilisations incorporelles", "type": "ASSET", "parent_code": "2"},
            {"code": "21", "name": "Immobilisations corporelles", "type": "ASSET", "parent_code": "2"},
            {"code": "27", "name": "Autres immobilisations financieres", "type": "ASSET", "parent_code": "2"},
            {"code": "28", "name": "Amortissements des immobilisations", "type": "ASSET", "parent_code": "2"},
            {"code": "3", "name": "Comptes de stocks et d'en-cours", "type": "ASSET"},
            {"code": "31", "name": "Matieres premieres", "type": "ASSET", "parent_code": "3"},
            {"code": "37", "name": "Stocks de marchandises", "type": "ASSET", "parent_code": "3"},
            {"code": "4", "name": "Comptes de tiers", "type": "LIABILITY"},
            {"code": "40", "name": "Fournisseurs et comptes rattaches", "type": "LIABILITY", "sub_type": "PAYABLE", "parent_code": "4"},
            {"code": "41", "name": "Clients et comptes rattaches", "type": "ASSET", "sub_type": "RECEIVABLE", "parent_code": "4"},
            {"code": "42", "name": "Personnel et comptes rattaches", "type": "LIABILITY", "parent_code": "4"},
            {"code": "43", "name": "Securite sociale et organismes sociaux", "type": "LIABILITY", "parent_code": "4"},
            {"code": "44", "name": "Etat et autres collectivites publiques", "type": "LIABILITY", "parent_code": "4"},
            {"code": "5", "name": "Comptes financiers", "type": "ASSET"},
            {"code": "51", "name": "Banques", "type": "ASSET", "sub_type": "BANK", "parent_code": "5"},
            {"code": "53", "name": "Caisse", "type": "ASSET", "sub_type": "CASH", "parent_code": "5"},
            {"code": "6", "name": "Comptes de charges", "type": "EXPENSE"},
            {"code": "60", "name": "Achats", "type": "EXPENSE", "parent_code": "6"},
            {"code": "61", "name": "Services exterieurs", "type": "EXPENSE", "parent_code": "6"},
            {"code": "62", "name": "Autres services exterieurs", "type": "EXPENSE", "parent_code": "6"},
            {"code": "63", "name": "Impots, taxes et versements assimiles", "type": "EXPENSE", "parent_code": "6"},
            {"code": "64", "name": "Charges de personnel", "type": "EXPENSE", "parent_code": "6"},
            {"code": "65", "name": "Autres charges de gestion courante", "type": "EXPENSE", "parent_code": "6"},
            {"code": "66", "name": "Charges financieres", "type": "EXPENSE", "parent_code": "6"},
            {"code": "67", "name": "Charges exceptionnelles", "type": "EXPENSE", "parent_code": "6"},
            {"code": "68", "name": "Dotations aux amortissements et provisions", "type": "EXPENSE", "parent_code": "6"},
            {"code": "7", "name": "Comptes de produits", "type": "INCOME"},
            {"code": "70", "name": "Ventes de produits et services", "type": "INCOME", "parent_code": "7"},
            {"code": "71", "name": "Production stockee", "type": "INCOME", "parent_code": "7"},
            {"code": "74", "name": "Subventions d'exploitation", "type": "INCOME", "parent_code": "7"},
            {"code": "75", "name": "Autres produits de gestion courante", "type": "INCOME", "parent_code": "7"},
            {"code": "76", "name": "Produits financiers", "type": "INCOME", "parent_code": "7"},
            {"code": "77", "name": "Produits exceptionnels", "type": "INCOME", "parent_code": "7"},
            {"code": "78", "name": "Reprises sur amortissements et provisions", "type": "INCOME", "parent_code": "7"},
        ]
    },
    "USA_GAAP": {
        "name": "USA GAAP",
        "description": "Generally Accepted Accounting Principles (US)",
        "accounts": [
            {"code": "1000", "name": "Assets", "type": "ASSET"},
            {"code": "1100", "name": "Cash and Cash Equivalents", "type": "ASSET", "sub_type": "CASH", "parent_code": "1000"},
            {"code": "1200", "name": "Accounts Receivable", "type": "ASSET", "sub_type": "RECEIVABLE", "parent_code": "1000"},
            {"code": "1300", "name": "Inventory", "type": "ASSET", "parent_code": "1000"},
            {"code": "1500", "name": "Fixed Assets", "type": "ASSET", "parent_code": "1000"},
            {"code": "2000", "name": "Liabilities", "type": "LIABILITY"},
            {"code": "2100", "name": "Accounts Payable", "type": "LIABILITY", "sub_type": "PAYABLE", "parent_code": "2000"},
            {"code": "2200", "name": "Accrued Liabilities", "type": "LIABILITY", "parent_code": "2000"},
            {"code": "2500", "name": "Long-term Debt", "type": "LIABILITY", "parent_code": "2000"},
            {"code": "3000", "name": "Equity", "type": "EQUITY"},
            {"code": "3100", "name": "Owner's Capital", "type": "EQUITY", "parent_code": "3000"},
            {"code": "3200", "name": "Retained Earnings", "type": "EQUITY", "parent_code": "3000"},
            {"code": "4000", "name": "Revenue", "type": "INCOME"},
            {"code": "4100", "name": "Sales Revenue", "type": "INCOME", "parent_code": "4000"},
            {"code": "4500", "name": "Service Revenue", "type": "INCOME", "parent_code": "4000"},
            {"code": "5000", "name": "Cost of Goods Sold", "type": "EXPENSE"},
            {"code": "6000", "name": "Operating Expenses", "type": "EXPENSE"},
            {"code": "6100", "name": "Payroll Expenses", "type": "EXPENSE", "parent_code": "6000"},
            {"code": "6200", "name": "Rent or Lease", "type": "EXPENSE", "parent_code": "6000"},
            {"code": "6300", "name": "Utilities", "type": "EXPENSE", "parent_code": "6000"},
        ]
    },
    "SYSCOHADA_REVISED": {
        "name": "SYSCOHADA Revised",
        "description": "Systeme Comptable OHADA Revise",
        "accounts": [
            {"code": "1", "name": "Comptes de capitaux", "type": "EQUITY"},
            {"code": "10", "name": "Capital", "type": "EQUITY", "parent_code": "1"},
            {"code": "11", "name": "Reserves", "type": "EQUITY", "parent_code": "1"},
            {"code": "12", "name": "Report a nouveau", "type": "EQUITY", "parent_code": "1"},
            {"code": "13", "name": "Resultat net de l'exercice", "type": "EQUITY", "parent_code": "1"},
            {"code": "16", "name": "Emprunts et dettes assimilees", "type": "LIABILITY", "parent_code": "1"},
            {"code": "2", "name": "Comptes d'immobilisations", "type": "ASSET"},
            {"code": "21", "name": "Immobilisations incorporelles", "type": "ASSET", "parent_code": "2"},
            {"code": "22", "name": "Terrains", "type": "ASSET", "parent_code": "2"},
            {"code": "23", "name": "Batiments, Installations techniques", "type": "ASSET", "parent_code": "2"},
            {"code": "24", "name": "Materiel", "type": "ASSET", "parent_code": "2"},
            {"code": "25", "name": "Materiel de transport", "type": "ASSET", "parent_code": "2"},
            {"code": "28", "name": "Amortissements", "type": "ASSET", "parent_code": "2"},
            {"code": "3", "name": "Comptes de stocks", "type": "ASSET"},
            {"code": "31", "name": "Marchandises", "type": "ASSET", "sub_type": "INVENTORY", "parent_code": "3"},
            {"code": "32", "name": "Matieres premieres", "type": "ASSET", "parent_code": "3"},
            {"code": "33", "name": "En-cours de production", "type": "ASSET", "parent_code": "3"},
            {"code": "4", "name": "Comptes de tiers", "type": "ASSET"},
            {"code": "40", "name": "Fournisseurs et comptes rattaches", "type": "LIABILITY", "sub_type": "PAYABLE", "parent_code": "4"},
            {"code": "41", "name": "Clients et comptes rattaches", "type": "ASSET", "sub_type": "RECEIVABLE", "parent_code": "4"},
            {"code": "42", "name": "Personnel", "type": "LIABILITY", "parent_code": "4"},
            {"code": "44", "name": "Etat et collectivites publiques", "type": "LIABILITY", "parent_code": "4"},
            {"code": "5", "name": "Comptes financiers", "type": "ASSET"},
            {"code": "52", "name": "Banques", "type": "ASSET", "sub_type": "BANK", "parent_code": "5"},
            {"code": "57", "name": "Caisse", "type": "ASSET", "sub_type": "CASH", "parent_code": "5"},
            {"code": "6", "name": "Comptes de charges", "type": "EXPENSE"},
            {"code": "60", "name": "Achats et variations de stocks", "type": "EXPENSE", "parent_code": "6"},
            {"code": "61", "name": "Transports", "type": "EXPENSE", "parent_code": "6"},
            {"code": "62", "name": "Services exterieurs A", "type": "EXPENSE", "parent_code": "6"},
            {"code": "63", "name": "Services exterieurs B", "type": "EXPENSE", "parent_code": "6"},
            {"code": "64", "name": "Impots et taxes", "type": "EXPENSE", "parent_code": "6"},
            {"code": "66", "name": "Charges de personnel", "type": "EXPENSE", "parent_code": "6"},
            {"code": "7", "name": "Comptes de produits", "type": "INCOME"},
            {"code": "70", "name": "Ventes", "type": "INCOME", "parent_code": "7"},
            {"code": "71", "name": "Subventions d'exploitation", "type": "INCOME", "parent_code": "7"},
            {"code": "75", "name": "Autres produits", "type": "INCOME", "parent_code": "7"},
            {"code": "77", "name": "Revenus financiers", "type": "INCOME", "parent_code": "7"},
        ]
    },
}
