# Generated by Django 6.0.2 on 2026-05-04 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_rename_bufferedreq_organiz_3f8ed5_idx_bufferedreq_tenant__076e1c_idx_and_more'),
        # Was '0001_initial' — chained through repair migrations so:
        #   0001b creates pos_driver if missing
        #   0001c backfills pos_driver columns 0002 will add
        # On healthy DBs both repairs are no-ops (CREATE/ALTER ...
        # IF NOT EXISTS); on the drifted dev DB they fill the gap.
        ('pos', '0001c_repair_pos_driver_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='generateddocument',
            new_name='pos_generat_tenant__823587_idx',
            old_name='pos_generat_organiz_00eec3_idx',
        ),
        migrations.RenameIndex(
            model_name='salesauditlog',
            new_name='sales_audit_tenant__61430d_idx',
            old_name='sales_audit_organiz_25ab8f_idx',
        ),
        migrations.RenameIndex(
            model_name='salesauditlog',
            new_name='sales_audit_tenant__94c9e6_idx',
            old_name='sales_audit_organiz_1558b9_idx',
        ),
        migrations.AddField(
            model_name='driver',
            name='available_for_purchase',
            field=models.BooleanField(default=True, help_text='Show this driver in the purchase-order driver picker.'),
        ),
        migrations.AddField(
            model_name='driver',
            name='available_for_sales',
            field=models.BooleanField(default=True, help_text='Show this driver in the sales/POS delivery picker.'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_plate',
            field=models.CharField(blank=True, help_text='Numeric plate printed on dispatch slips and PO handover.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='is_recovered',
            field=models.BooleanField(db_index=True, default=False, help_text='Marked by the recover_terminal_procurement cron once the terminal-state cooldown matured. Recovered rows are hidden from active queries.'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='recovered_at',
            field=models.DateTimeField(blank=True, help_text='When the cron archived this row. Pair with is_recovered.', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='User responsible for tracking this PO through to completion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='driver_source',
            field=models.CharField(choices=[('INTERNAL', 'Our driver'), ('SUPPLIER', 'Supplier-provided'), ('EXTERNAL', 'External / one-off')], default='INTERNAL', help_text='Who is providing the driver for this PO.', max_length=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='driver_user',
            field=models.ForeignKey(blank=True, help_text='Internal driver — only set when driver_source=INTERNAL.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='external_driver_name',
            field=models.CharField(blank=True, help_text='Free-text name for a one-off external driver.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='external_driver_phone',
            field=models.CharField(blank=True, help_text='Free-text phone for a one-off external driver.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='posauditevent',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='pos_audit_events', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='posauditrule',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='pos_audit_rules', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('ORDERED', 'Ordered'), ('EXECUTED', 'Executed (alias for Ordered)'), ('SUPPLIER_CONFIRMED', 'Supplier Confirmed'), ('IN_TRANSIT', 'In Transit'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Received'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesauditlog',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='sales_audit_logs', to='erp.organization'),
        ),
    ]
