# Generated by Django 6.0.2 on 2026-02-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_sub_type',
            field=models.CharField(choices=[('STANDARD', 'Standard Purchase'), ('WHOLESALE', 'Wholesale Purchase'), ('CONSIGNEE', 'Consignee Purchase')], default='STANDARD', help_text='Sub-classification: Standard/Wholesale (better unit cost)/Consignee (pay on sale)', max_length=20),
        ),
    ]
