# Generated by Django 6.0.2 on 2026-05-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_rename_pos_generat_organiz_00eec3_idx_pos_generat_tenant__823587_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[('MOTORCYCLE', 'Motorcycle'), ('CAR', 'Car'), ('VAN', 'Van'), ('TRUCK', 'Truck'), ('BICYCLE', 'Bicycle')], default='MOTORCYCLE', help_text='Vehicle category — drives icon/badge rendering.', max_length=20),
        ),
    ]
