# Generated by Django 5.1.7 on 2026-02-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_order_discount_order_invoice_price_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='price_override_detected',
            field=models.BooleanField(default=False),
        ),
    ]
