# Generated by Django 6.0.2 on 2026-05-04 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_rename_bufferedreq_organiz_3f8ed5_idx_bufferedreq_tenant__076e1c_idx_and_more'),
        ('pos', '0003_driver_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='external_driver_name',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='external_driver_phone',
        ),
        migrations.CreateModel(
            name='ExternalDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name on dispatch slips and the picker.', max_length=120)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_plate', models.CharField(blank=True, help_text='License plate printed on the handover document.', max_length=50, null=True)),
                ('vehicle_info', models.CharField(blank=True, help_text='Free-text vehicle description, e.g. "White Hilux".', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, help_text='Operator notes — preferred routes, working hours, etc.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Hides from the picker without deleting the row.')),
                ('organization', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'verbose_name': 'External Driver',
                'verbose_name_plural': 'External Drivers',
                'db_table': 'pos_external_driver',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='external_driver',
            field=models.ForeignKey(blank=True, help_text='Saved one-off / contractor driver — only set when driver_source=EXTERNAL.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='pos.externaldriver'),
        ),
        migrations.AddConstraint(
            model_name='externaldriver',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_external_driver_name_per_org'),
        ),
    ]
