# Generated by Django 6.0.2 on 2026-02-25 11:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_category_barcode_sequence_and_more'),
        ('pos', '0003_posticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='airsi_amount',
            new_name='subtotal',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='consignment_payout',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='consignment_settled',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='effective_cost',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='is_consignment',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='price_override_detected',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='qty_invoiced',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='qty_received',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='total',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='unit_cost_ht',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='unit_cost_ttc',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='vat_amount',
        ),
        migrations.RemoveField(
            model_name='posticket',
            name='cart_data',
        ),
        migrations.RemoveField(
            model_name='posticket',
            name='client_id',
        ),
        migrations.AddField(
            model_name='orderline',
            name='airsi_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='orderline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='posticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='posticket',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='posticket',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='posticket',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='posticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='posticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
