# Generated by Django 5.2.11 on 2026-02-26 03:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_user_pos_pin'),
        ('finance', '0003_alter_journalentryline_employee_alter_taxgroup_rate_and_more'),
        ('pos', '0005_posregister_registersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='posregister',
            name='reserve_account',
            field=models.ForeignKey(blank=True, help_text='Account to transfer excess cash to on close', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_reserve', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='registersession',
            name='address_book_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net balance from the cashier address book (in - out)', max_digits=15),
        ),
        migrations.AddField(
            model_name='registersession',
            name='cash_counted',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual physical cash counted by cashier', max_digits=15),
        ),
        migrations.AddField(
            model_name='registersession',
            name='cash_difference',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='cash_counted - cash_expected. Positive = excess, negative = shortage', max_digits=15),
        ),
        migrations.AddField(
            model_name='registersession',
            name='cash_expected',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected cash after calibration: opening + cash_sales + calibration_adjustments', max_digits=15),
        ),
        migrations.AddField(
            model_name='registersession',
            name='excess_transferred_to',
            field=models.ForeignKey(blank=True, help_text='Where excess cash was transferred to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_excess', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='registersession',
            name='reconciliation_data',
            field=models.JSONField(blank=True, default=dict, help_text='Per-account reconciliation: software vs real statement', null=True),
        ),
        migrations.AddField(
            model_name='registersession',
            name='shortage_deducted_from',
            field=models.ForeignKey(blank=True, help_text='Cashier who was debited for the shortage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_shortages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CashierAddressBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_book_entries', to='pos.registersession')),
            ],
            options={
                'db_table': 'pos_cashier_address_book',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionAccountReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total recorded in software for this account during session', max_digits=15)),
                ('statement_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Real amount from provider statement', max_digits=15)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='software - statement. Positive = over-recorded, negative = under-recorded', max_digits=15)),
                ('calibrated_to_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount moved to/from cash to calibrate. Negative = moved from cash', max_digits=15)),
                ('is_controlled', models.BooleanField(default=True, help_text='True = provider statement is truth (Wave, OM, Bank). False = manual (Cash)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.financialaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_reconciliations', to='pos.registersession')),
            ],
            options={
                'db_table': 'pos_session_account_reconciliation',
                'unique_together': {('session', 'account')},
            },
        ),
    ]
