# Generated by Django 5.1.7 on 2026-02-16 15:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0043_transaction_lifecycle'),
        ('inventory', '0008_add_product_type_and_combo_component'),
        ('pos', '0006_add_delivery_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, help_text='Promo code for manual entry', max_length=50, null=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Off'), ('FIXED', 'Fixed Amount Off'), ('BUY_X_GET_Y', 'Buy X Get Y Free')], default='PERCENTAGE', max_length=20)),
                ('scope', models.CharField(choices=[('ORDER', 'Entire Order'), ('PRODUCT', 'Specific Product'), ('CATEGORY', 'Product Category'), ('BRAND', 'Product Brand')], default='ORDER', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% for PERCENTAGE, amount for FIXED, X for BUY_X_GET_Y', max_digits=15)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap for percentage discounts', max_digits=15, null=True)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order total to qualify', max_digits=15, null=True)),
                ('min_quantity', models.PositiveIntegerField(blank=True, help_text='Minimum item quantity to qualify', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_apply', models.BooleanField(default=False, help_text='Automatically apply at checkout')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Max times this rule can be used', null=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher = applied first')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'db_table': 'pos_discount_rule',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('applied_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_logs', to='pos.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='pos.discountrule')),
            ],
            options={
                'db_table': 'pos_discount_usage_log',
                'ordering': ['-applied_at'],
            },
        ),
    ]
