# Generated by Django 5.2.11 on 2026-02-26 03:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_posregister_reserve_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashieraddressbook',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_book_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='reference',
            field=models.CharField(blank=True, help_text='Reference number, receipt number, or link', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='rejection_notes',
            field=models.TextField(blank=True, help_text='Reason for rejection by manager', null=True),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='cashieraddressbook',
            name='amount_in',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Money received', max_digits=15),
        ),
        migrations.AlterField(
            model_name='cashieraddressbook',
            name='amount_out',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Money paid out', max_digits=15),
        ),
        migrations.AlterField(
            model_name='cashieraddressbook',
            name='cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_book_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashieraddressbook',
            name='description',
            field=models.CharField(help_text='What was this payment for?', max_length=255),
        ),
    ]
