# Generated by Django 5.1.7 on 2026-02-16 16:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_add_discount_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='qty_invoiced',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='orderline',
            name='qty_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
