# Generated by Django 5.2.11 on 2026-02-26 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_warehouse_unique_together_warehouse_address_and_more'),
        ('pos', '0008_rename_site_to_branch'),
    ]

    operations = [
        # Null out orphan site_id references before FK re-pointing
        migrations.RunSQL(
            sql="""
                UPDATE pos_order SET site_id = NULL WHERE site_id IS NOT NULL AND site_id NOT IN (SELECT id FROM warehouse);
                UPDATE purchase_order SET site_id = NULL WHERE site_id IS NOT NULL AND site_id NOT IN (SELECT id FROM warehouse);
                UPDATE pos_quotation SET site_id = NULL WHERE site_id IS NOT NULL AND site_id NOT IN (SELECT id FROM warehouse);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='order',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Branch/location where this order was made', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch/location this register belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_registers', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Default warehouse for stock deduction (if different from branch)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_register_stock', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_as_site', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Default receiving warehouse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_as_warehouse', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
    ]
