# Generated by Django 5.1.7 on 2026-02-16 16:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_add_pricing_models'),
        ('erp', '0044_user_override_pin_manageroverridelog'),
        ('inventory', '0008_add_product_type_and_combo_component'),
        ('pos', '0008_orderline_qty_invoiced_orderline_qty_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('reference_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.order')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.contact')),
            ],
            options={
                'db_table': 'pos_supplier_price_history',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_sku', models.CharField(blank=True, help_text="Supplier's internal part number", max_length=100, null=True)),
                ('lead_time_days', models.IntegerField(default=7, help_text='Typical delay in days from order to reception')),
                ('min_order_qty', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('last_purchased_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('last_purchased_date', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualified_suppliers', to='inventory.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplied_products', to='crm.contact')),
            ],
            options={
                'db_table': 'pos_product_supplier',
                'unique_together': {('product', 'supplier', 'organization')},
            },
        ),
    ]
