# Generated by Django 5.1.7 on 2026-02-16 16:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_add_pricing_models'),
        ('erp', '0044_user_override_pin_manageroverridelog'),
        ('pos', '0009_supplierpricehistory_productsupplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='consignment_payout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount to be paid to supplier', max_digits=15),
        ),
        migrations.AddField(
            model_name='orderline',
            name='consignment_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderline',
            name='is_consignment',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ConsignmentSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid / Finalized'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignment_settlements', to='crm.contact')),
            ],
            options={
                'db_table': 'pos_consignment_settlement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsignmentSettlementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('order_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consignment_settlement_link', to='pos.orderline')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.consignmentsettlement')),
            ],
            options={
                'db_table': 'pos_consignment_settlement_line',
            },
        ),
    ]
