# Generated by Django 5.2.11 on 2026-02-26 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_warehouse_unique_together_warehouse_address_and_more'),
        ('pos', '0009_alter_order_site_alter_posregister_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_at_site', to='inventory.warehouse'),
        ),
    ]
