# Generated by Django 6.0.2 on 2026-02-27 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_user_home_site'),
        ('pos', '0011_add_opening_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=150)),
                ('details', models.JSONField(default=dict)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_audit_events', to='erp.organization')),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='pos.posregister')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pos_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pos_audit_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSAuditRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('send_notification', models.BooleanField(default=False)),
                ('create_task', models.BooleanField(default=False)),
                ('notify_roles', models.CharField(blank=True, help_text="Roles to notify (e.g. 'Manager,Admin')", max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_audit_rules', to='erp.organization')),
            ],
            options={
                'db_table': 'pos_audit_rule',
                'unique_together': {('organization', 'event_type')},
            },
        ),
    ]
