# Generated by Django 5.2.11 on 2026-02-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_possettings_sms_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possettings',
            name='require_client_delivery_code',
            field=models.BooleanField(default=False, help_text='Client receives a code; driver must enter it to confirm delivery.'),
        ),
        migrations.AlterField(
            model_name='possettings',
            name='require_driver_pos_code',
            field=models.BooleanField(default=False, help_text='Driver must show a code to cashier when returning cash.'),
        ),
    ]
