# Generated by Django 5.2.11 on 2026-02-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_alter_possettings_require_client_delivery_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
