# Generated by Django 5.2.11 on 2026-02-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_orderline_batch_number_orderline_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='possettings',
            name='loyalty_earn_rate',
            field=models.DecimalField(decimal_places=4, default='10.0000', help_text='Amount of currency spent to earn 1 loyalty point (e.g. 10000 means spend 10,000 to earn 1 point).', max_digits=12),
        ),
        migrations.AddField(
            model_name='possettings',
            name='loyalty_point_value',
            field=models.DecimalField(decimal_places=4, default='1.0000', help_text='Monetary value of 1 loyalty point (e.g. 500 means 1 point = 500 of your currency).', max_digits=12),
        ),
    ]
