# Generated by Django 5.2.11 on 2026-02-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_possettings_loyalty_earn_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posregister',
            name='payment_methods',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of payment methods for this register: [{key, label, accountId}]'),
        ),
    ]
