# Generated by Django 5.2.11 on 2026-02-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_posregister_payment_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registersession',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSING', 'Closing'), ('CLOSED', 'Closed'), ('FORCE_CLOSED', 'Force Closed')], default='OPEN', max_length=20),
        ),
    ]
