# Generated by Django 5.2.11 on 2026-03-01 06:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_user_is_driver'),
        ('pos', '0022_possettings_allow_negative_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashieraddressbook',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='cashier_response',
            field=models.TextField(blank=True, help_text='Cashier explanation after rejection or info request', null=True),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='client_id',
            field=models.IntegerField(blank=True, help_text='Contact ID of client (for CLIENT_PAYMENT / PREPAYMENT)', null=True),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='client_invoice_id',
            field=models.IntegerField(blank=True, help_text='Invoice ID for client payment', null=True),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='client_invoice_ref',
            field=models.CharField(blank=True, help_text='Invoice reference for display', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='client_name',
            field=models.CharField(blank=True, help_text='Client name for display', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_book_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='direction',
            field=models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie')], default='IN', help_text='Entrée (IN) or Sortie (OUT)', max_length=3),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='entry_type',
            field=models.CharField(choices=[('SUPPLIER_PAYMENT', 'Supplier Payment'), ('EXPENSE', 'Expense'), ('PARTNER_CONTRIBUTION', 'Partner Contribution'), ('PARTNER_WITHDRAWAL', 'Partner Withdrawal'), ('CLIENT_PAYMENT', 'Client Payment'), ('CLIENT_PREPAYMENT', 'Client Prepayment'), ('SALE_DEPOSIT', 'Sale Deposit'), ('SALES_RETURN', 'Sales Return / Refund'), ('CASH_OVERAGE', 'Cash Overage (Écart +)'), ('CASH_SHORTAGE', 'Cash Shortage (Écart -)'), ('MONEY_TRANSFER', 'Money Transfer'), ('OTHER_IN', 'Other (Money In)'), ('OTHER_OUT', 'Other (Money Out)')], default='OTHER_IN', help_text='Type of transaction — determines auto-linking after approval', max_length=30),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='expense_category',
            field=models.CharField(blank=True, help_text='Expense category (for EXPENSE type)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='hidden_from_cashier',
            field=models.BooleanField(default=False, help_text='If True, only visible to managers (e.g. CASH_OVERAGE)'),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft-delete flag — keeps audit trail'),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='linked_order_id',
            field=models.IntegerField(blank=True, help_text='POS Order ID (for SALES_RETURN)', null=True),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='linked_order_ref',
            field=models.CharField(blank=True, help_text='POS Order reference (for SALES_RETURN)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='original_entry_id',
            field=models.IntegerField(blank=True, help_text='If this is a modification, links to original entry', null=True),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='partner_name',
            field=models.CharField(blank=True, help_text='Partner/owner name (for PARTNER_CONTRIBUTION / WITHDRAWAL)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='supplier_id',
            field=models.IntegerField(blank=True, help_text='Contact ID of supplier (for SUPPLIER_PAYMENT)', null=True),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='supplier_invoice_id',
            field=models.IntegerField(blank=True, help_text='Invoice ID for supplier payment', null=True),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='supplier_invoice_ref',
            field=models.CharField(blank=True, help_text='Invoice reference for display', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='supplier_name',
            field=models.CharField(blank=True, help_text='Supplier name for display', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='target_account_id',
            field=models.IntegerField(blank=True, help_text='COA Account ID for direct posting after approval', null=True),
        ),
        migrations.AddField(
            model_name='cashieraddressbook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cashieraddressbook',
            name='rejection_notes',
            field=models.TextField(blank=True, help_text='Reason for rejection / info request by manager', null=True),
        ),
        migrations.AlterField(
            model_name='cashieraddressbook',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEED_INFO', 'Need More Info'), ('MODIFIED', 'Modified (Re-submitted)')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='DailyAddressBookSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('pending_count', models.IntegerField(default=0)),
                ('approved_count', models.IntegerField(default=0)),
                ('rejected_count', models.IntegerField(default=0)),
                ('entries_json', models.JSONField(default=list, help_text='Full snapshot of all entries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_book_snapshots', to='pos.posregister')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_book_snapshots', to='pos.registersession')),
            ],
            options={
                'db_table': 'pos_daily_address_book_snapshot',
                'ordering': ['-date'],
                'unique_together': {('organization', 'session', 'date')},
            },
        ),
    ]
