# Generated by Django 6.0.2 on 2026-03-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0023_address_book_v2_full_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashieraddressbook',
            name='partner_id',
            field=models.IntegerField(blank=True, help_text='Contact ID of partner (for PARTNER_CONTRIBUTION / WITHDRAWAL)', null=True),
        ),
    ]
