# Generated by Django 6.0.2 on 2026-03-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0024_add_partner_id_to_address_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashieraddressbook',
            name='entry_type',
            field=models.CharField(choices=[('SUPPLIER_PAYMENT', 'Supplier Payment'), ('EXPENSE', 'Expense'), ('PARTNER_CAPITAL_IN', 'Partner Capital Injection'), ('PARTNER_CASH_IN', 'Partner Cash Transfer (In)'), ('PARTNER_CAPITAL_OUT', 'Partner Capital Withdrawal'), ('PARTNER_CASH_OUT', 'Partner Cash Transfer (Out)'), ('CLIENT_PAYMENT', 'Client Payment'), ('CLIENT_PREPAYMENT', 'Client Prepayment'), ('SALE_DEPOSIT', 'Sale Deposit'), ('SALES_RETURN', 'Sales Return / Refund'), ('CASH_OVERAGE', 'Cash Overage (Écart +)'), ('CASH_SHORTAGE', 'Cash Shortage (Écart -)'), ('MONEY_TRANSFER', 'Money Transfer'), ('OTHER_IN', 'Other (Money In)'), ('OTHER_OUT', 'Other (Money Out)')], default='OTHER_IN', help_text='Type of transaction — determines auto-linking after approval', max_length=30),
        ),
        migrations.AlterField(
            model_name='cashieraddressbook',
            name='partner_id',
            field=models.IntegerField(blank=True, help_text='Contact ID of partner', null=True),
        ),
        migrations.AlterField(
            model_name='cashieraddressbook',
            name='partner_name',
            field=models.CharField(blank=True, help_text='Partner/owner name', max_length=255, null=True),
        ),
    ]
