# Generated by Django 5.2.11 on 2026-03-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_alter_cashieraddressbook_entry_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='possettings',
            name='invoice_footer_text',
            field=models.TextField(blank=True, help_text='Default global terms, conditions or thank you notes printed at the bottom of invoices.', null=True),
        ),
        migrations.AddField(
            model_name='possettings',
            name='invoice_header_text',
            field=models.TextField(blank=True, help_text='Custom text (e.g. slogans or official registrations) displayed under the logo on invoices.', null=True),
        ),
        migrations.AddField(
            model_name='possettings',
            name='invoice_show_logo',
            field=models.BooleanField(default=True, help_text='Toggle to show or hide the Organization logo on the invoice.'),
        ),
        migrations.AddField(
            model_name='possettings',
            name='invoice_show_qr',
            field=models.BooleanField(default=False, help_text='Toggle to show a QR code on the invoice (if applicable).'),
        ),
    ]
