# Generated by Django 5.2.11 on 2026-03-02 20:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_seed_app_change_theme_permission'),
        ('pos', '0030_order_workflow_status_axes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderlinetaxentry',
            new_name='order_line__order_l_a38ac0_idx',
            old_name='tax_entry_line_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('TVA_INVOICE', 'Official TVA Invoice (HT + TVA + TTC)'), ('RECEIPT', 'Simple Receipt (TTC only, VAT embedded)'), ('INTERNAL_RECEIPT', 'Internal Receipt (no VAT posted)'), ('SIMPLE_INVOICE', 'Simple Invoice (org not VAT-registered)')], default='RECEIPT', help_text='Auto-resolved from org policy + client profile + scope at checkout.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_export',
            field=models.BooleanField(default=False, help_text='True = export sale → VAT rate overridden to 0'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='airsi_withheld',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='AIRSI withholding on this line (if applicable)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='tax_amount_ttc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total including VAT (TTC) — stored for audit', max_digits=15),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='unit_cost_ht',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Average Moving Cost at time of sale (AMC)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderlinetaxentry',
            name='airsi_treatment',
            field=models.CharField(blank=True, choices=[('CAPITALIZE', 'Added to inventory cost'), ('RECOVER', 'Booked as AIRSI Récupérable'), ('EXPENSE', 'Expensed to P&L')], help_text='Only set for AIRSI tax type', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='orderlinetaxentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax amount (rate × base_amount)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='orderlinetaxentry',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The amount this tax was calculated on (usually HT)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='orderlinetaxentry',
            name='cost_impact_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='amount × cost_impact_ratio — added to inventory cost', max_digits=15),
        ),
        migrations.AlterField(
            model_name='orderlinetaxentry',
            name='cost_impact_ratio',
            field=models.DecimalField(decimal_places=3, default=0, help_text='0=no cost impact, 1=full cost impact, 0.5=partial', max_digits=4),
        ),
        migrations.AlterField(
            model_name='orderlinetaxentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderlinetaxentry',
            name='journal_account_id',
            field=models.IntegerField(blank=True, help_text='COA account used in the journal entry for this tax line', null=True),
        ),
        migrations.AlterField(
            model_name='orderlinetaxentry',
            name='order_line_id',
            field=models.IntegerField(db_column='order_line_id', help_text='FK to OrderLine or PurchaseOrderLine (by transaction_type)'),
        ),
        migrations.AlterField(
            model_name='orderlinetaxentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='orderlinetaxentry',
            name='tax_type',
            field=models.CharField(choices=[('VAT', 'Value Added Tax (TVA)'), ('VAT_REVERSE_CHARGE', 'VAT Reverse Charge (Autoliquidation)'), ('AIRSI', 'AIRSI Withholding Tax'), ('PURCHASE_TAX', 'Purchase Tax / Taxe sur Achat'), ('SALES_TAX', 'Sales Tax (per transaction)'), ('EXCISE', 'Excise Duty'), ('STAMP', 'Stamp Duty'), ('OTHER', 'Other Tax')], max_length=25),
        ),
        migrations.AlterField(
            model_name='orderlinetaxentry',
            name='transaction_type',
            field=models.CharField(choices=[('SALE', 'Sale (POS Order)'), ('PURCHASE', 'Purchase Order')], default='SALE', max_length=10),
        ),
    ]
