# Generated by Django 6.0.2 on 2026-03-02 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0033_merge_20260302_2036'),
        ('pos', '0033_merge_20260302_2038'),
    ]

    operations = [
    ]
