# Generated by Django 5.2.11 on 2026-03-02 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0034_merge_20260302_2042'),
        ('pos', '0034_merge_20260302_2044'),
        ('pos', '0034_sales_payment_leg'),
    ]

    operations = [
    ]
