# Generated by Django 5.2.11 on 2026-03-02 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0035_merge_20260302_2226'),
        ('pos', '0035_stock_move'),
    ]

    operations = [
    ]
