# Generated by Django 6.0.2 on 2026-03-03 00:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0038_purchaseorder_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='qty_damaged',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Arrived damaged or broken', max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='qty_missing',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Supplier failed to deliver (Out of stock/forgot)', max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='qty_rejected',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rejected by warehouse (e.g. wrong spec, expired)', max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='receipt_notes',
            field=models.TextField(blank=True, help_text='Notes regarding discrepancies during receipt', null=True),
        ),
    ]
