# Generated by Django 6.0.2 on 2026-03-03 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_customtaxrule'),
        ('pos', '0039_purchaseorderline_qty_damaged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlinetaxentry',
            name='custom_tax_rule',
            field=models.ForeignKey(blank=True, help_text='FK to CustomTaxRule if this line was generated by a dynamic rule', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.customtaxrule'),
        ),
        migrations.AlterField(
            model_name='orderlinetaxentry',
            name='tax_type',
            field=models.CharField(choices=[('VAT', 'Value Added Tax (TVA)'), ('VAT_REVERSE_CHARGE', 'VAT Reverse Charge (Autoliquidation)'), ('AIRSI', 'AIRSI Withholding Tax'), ('PURCHASE_TAX', 'Purchase Tax / Taxe sur Achat'), ('SALES_TAX', 'Sales Tax (per transaction)'), ('EXCISE', 'Excise Duty'), ('STAMP', 'Stamp Duty'), ('OTHER', 'Other Tax'), ('CUSTOM', 'Custom User-Defined Tax')], max_length=25),
        ),
    ]
