# Generated by Django 5.2.11 on 2026-03-03 03:05
# PATCHED: Original migration renamed custom indexes that may not exist yet on all servers.
# Replaced with RunSQL that performs the renames only if the source index exists.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0041_gap10_performance_indexes'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'sal_org_order_idx') THEN
        ALTER INDEX sal_org_order_idx RENAME TO sales_audit_organiz_25ab8f_idx;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'sal_org_action_idx') THEN
        ALTER INDEX sal_org_action_idx RENAME TO sales_audit_organiz_1558b9_idx;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'spl_order_status_idx') THEN
        ALTER INDEX spl_order_status_idx RENAME TO sales_payme_order_i_de7156_idx;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'spl_org_method_status_idx') THEN
        ALTER INDEX spl_org_method_status_idx RENAME TO sales_payme_organiz_8d21f4_idx;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'spl_reference_idx') THEN
        ALTER INDEX spl_reference_idx RENAME TO sales_payme_referen_45ebdf_idx;
    END IF;
END$$;
""",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
