# Generated by Django 5.2.11 on 2026-03-03 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0042_rename_sal_org_order_idx_sales_audit_organiz_25ab8f_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salesauditlog',
            new_name='sales_audit_organiz_25ab8f_idx',
            old_name='sal_org_order_idx',
        ),
        migrations.RenameIndex(
            model_name='salesauditlog',
            new_name='sales_audit_organiz_1558b9_idx',
            old_name='sal_org_action_idx',
        ),
        migrations.RenameIndex(
            model_name='salespaymentleg',
            new_name='sales_payme_order_i_de7156_idx',
            old_name='spl_order_status_idx',
        ),
        migrations.RenameIndex(
            model_name='salespaymentleg',
            new_name='sales_payme_organiz_8d21f4_idx',
            old_name='spl_org_method_status_idx',
        ),
        migrations.RenameIndex(
            model_name='salespaymentleg',
            new_name='sales_payme_referen_45ebdf_idx',
            old_name='spl_reference_idx',
        ),
    ]
