# Generated by Django 6.0.2 on 2026-03-03 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_seed_app_change_theme_permission'),
        ('pos', '0043_rename_sal_org_order_idx_sales_audit_organiz_25ab8f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('purchase_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('doc_type', models.CharField(choices=[('INVOICE', 'Sales Invoice'), ('RECEIPT', 'POS Receipt'), ('PURCHASE_ORDER', 'Purchase Order'), ('TAX_CERT', 'Tax Certificate')], default='INVOICE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('task_id', models.CharField(blank=True, max_length=155, null=True)),
                ('file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='erp.organization')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['organization', 'order_id', 'doc_type'], name='pos_generat_organiz_00eec3_idx'), models.Index(fields=['task_id'], name='pos_generat_task_id_cc9557_idx')],
            },
        ),
    ]
