# Generated by Django 6.0.2 on 2026-03-05 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0046_posregister_account_book_rules_override'),
        ('pos', '0047_phase3_partial_invoiced_policy'),
    ]

    operations = [
    ]
