# Generated by Django 6.0.2 on 2026-03-05 02:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_transactionstatuslog_meta_transactiontype_and_more'),
        ('finance', '0014_invoice_current_verification_level_and_more'),
        ('pos', '0048_merge_20260305_0130'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('allocation_method', models.CharField(choices=[('BY_VALUE', 'By Value (proportional to line total)'), ('BY_QUANTITY', 'By Quantity (evenly per unit)'), ('BY_WEIGHT', 'By Weight')], default='BY_VALUE', max_length=15)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landed_costs', to='pos.purchaseorder')),
            ],
            options={
                'db_table': 'landed_cost',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandedCostLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('FREIGHT', 'Freight / Shipping'), ('CUSTOMS', 'Customs Duty'), ('INSURANCE', 'Insurance'), ('HANDLING', 'Handling / Port Fees'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('account', models.ForeignKey(blank=True, help_text='Ledger account for this cost', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.chartofaccount')),
                ('landed_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.landedcost')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'landed_cost_line',
            },
        ),
        migrations.CreateModel(
            name='PurchaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='purchase/attachments/')),
                ('attachment_type', models.CharField(choices=[('QUOTATION', 'Supplier Quotation'), ('CONTRACT', 'Contract'), ('BL', 'Bill of Lading'), ('PROFORMA', 'Proforma Invoice'), ('CUSTOMS', 'Customs Document'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='pos.purchaseorder')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchase_attachment',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
