# Generated by Django 5.2.11 on 2026-03-08 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0054_paymentterm_alter_purchaseorder_payment_terms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked records cannot be edited even by admins'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Manual verification by auditor'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_pos', to=settings.AUTH_USER_MODEL),
        ),
    ]
