# Generated by Django 5.2.11 on 2026-03-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0055_purchaseorder_is_locked_purchaseorder_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='scope',
            field=models.CharField(choices=[('OFFICIAL', 'Official (Statutory)'), ('INTERNAL', 'Internal (Management)')], default='OFFICIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='wait_for_invoice',
            field=models.BooleanField(default=False, help_text='Manual tag for pending balance invoices'),
        ),
    ]
