# Generated by Django 5.2.11 on 2026-03-09 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0056_purchaseorder_scope_purchaseorder_wait_for_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='from_warehouse',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='product',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='source_po',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='to_warehouse',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='locked_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='locked_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='wait_for_invoice',
        ),
        migrations.DeleteModel(
            name='PaymentTerm',
        ),
        migrations.DeleteModel(
            name='ProcurementRequest',
        ),
    ]
