# Generated by Django 5.2.11 on 2026-03-09 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_remove_user_driver_scope_delete_exchangerate'),
        ('pos', '0057_remove_purchaseorder_payment_terms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, help_text='Driver assigned for pickup/delivery coordination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_po_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g. "Net 30 Days"', max_length=100)),
                ('code', models.CharField(help_text='Short code, e.g. NET_30', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the terms', null=True)),
                ('days', models.IntegerField(default=0, help_text='Number of days until payment is due (0 = immediate)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Early payment discount %% (e.g. 2%% discount if paid within discount_days)', max_digits=5)),
                ('discount_days', models.IntegerField(default=0, help_text='Days within which discount applies (0 = no discount)')),
                ('is_default', models.BooleanField(default=False, help_text='Set as default for new POs')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'payment_term',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_term',
            field=models.ForeignKey(blank=True, help_text='Payment conditions (Net 30, 60/90, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='pos.paymentterm'),
        ),
    ]
