# Generated by Django 5.2.11 on 2026-03-10 21:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_alter_contact_avg_lead_time_days_and_more'),
        ('erp', '0020_organization_finance_hard_locked_at_and_more'),
        ('finance', '0021_chartofaccount_financial_section_and_more'),
        ('pos', '0060_postable_journal_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='actual_credit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual credit received from supplier', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='expected_credit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected credit note amount from supplier', max_digits=15),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Formal purchase order', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='pos.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='received_by_supplier_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='return_number',
            field=models.CharField(blank=True, help_text='Auto-generated return reference (e.g. PRET-2026-001)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='return_type',
            field=models.CharField(choices=[('DEFECTIVE', 'Defective Product'), ('DAMAGED', 'Damaged in Transit'), ('WRONG_ITEM', 'Wrong Item Delivered'), ('OVERDELIVERY', 'Over-delivery'), ('QUALITY', 'Quality Issue'), ('EXPIRED', 'Expired/Near-expiry'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturnline',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturnline',
            name='po_line',
            field=models.ForeignKey(blank=True, help_text='Original formal PO line', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='pos.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='purchasereturnline',
            name='return_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='original_order',
            field=models.ForeignKey(blank=True, help_text='Legacy purchase order (Order type=PURCHASE)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='pos.order'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='reference',
            field=models.CharField(blank=True, help_text='External reference (e.g. RMA number from supplier)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('SENT', 'Sent to Supplier'), ('RECEIVED_BY_SUPPLIER', 'Received by Supplier'), ('CREDIT_PENDING', 'Awaiting Credit Note'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=25),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='original_line',
            field=models.ForeignKey(blank=True, help_text='Original legacy order line', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_lines', to='pos.orderline'),
        ),
        migrations.CreateModel(
            name='SupplierCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_number', models.CharField(help_text='Supplier credit note number', max_length=100)),
                ('date_received', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RECEIVED', 'Received'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('journal_entry', models.ForeignKey(blank=True, help_text='AP adjustment journal entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_credit_notes', to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='pos.purchasereturn')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_credit_notes', to='crm.contact')),
            ],
            options={
                'db_table': 'supplier_credit_note',
                'ordering': ['-date_received', '-created_at'],
                'unique_together': {('credit_number', 'organization')},
            },
        ),
    ]
