# Generated by Django 6.0.2 on 2026-03-11 00:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_contact_assigned_owner_and_more'),
        ('erp', '0020_organization_finance_hard_locked_at_and_more'),
        ('inventory', '0021_goodsreceipt_approved_by_goodsreceipt_assigned_to_and_more'),
        ('pos', '0061_purchasereturn_actual_credit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='invoiced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SupplierClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('claim_type', models.CharField(choices=[('DAMAGED', 'Damaged Goods'), ('EXPIRED', 'Expired Goods'), ('MISSING', 'Missing Goods / Shortage'), ('QUALITY', 'Quality Issue'), ('WRONG_PRODUCT', 'Wrong Product Sent'), ('BATCH_ERROR', 'Batch/Expiry Discrepancy'), ('OVERCHARGE', 'Price Overcharge'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to Supplier'), ('ACCEPTED', 'Accepted by Supplier'), ('REJECTED', 'Rejected by Supplier'), ('CREDITED', 'Credit Note Received'), ('REPLACED', 'Replacement Received'), ('RESOLVED', 'Resolved (Other)'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('claim_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('description', models.TextField()),
                ('evidence_urls', models.JSONField(blank=True, default=list)),
                ('supplier_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('purchase_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='pos.purchasereturn')),
                ('receipt_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='inventory.goodsreceiptline')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_claims', to='crm.contact')),
            ],
            options={
                'db_table': 'supplier_claim',
                'ordering': ['-created_at'],
            },
        ),
    ]
