# Generated by Django 5.2.12 on 2026-03-11 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_remove_contact_idx_contact_org_type_and_more'),
        ('erp', '0021_alter_approvalrule_organization_and_more'),
        ('finance', '0023_rename_account_bal_organiz_54abac_idx_account_bal_organization__c281f2_idx_and_more'),
        ('inventory', '0022_remove_product_unique_product_sku_per_org_and_more'),
        ('pos', '0064_add_procurement_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='disputecase',
            name='pos_dc_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='disputecase',
            name='pos_dc_toa_idx',
        ),
        migrations.RemoveIndex(
            model_name='disputecase',
            name='pos_dc_po_idx',
        ),
        migrations.RemoveIndex(
            model_name='disputecase',
            name='pos_dc_tdts_idx',
        ),
        migrations.RemoveIndex(
            model_name='procurementbudget',
            name='pos_pb_tpspe_idx',
        ),
        migrations.RemoveIndex(
            model_name='procurementbudget',
            name='pos_pb_ta_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequisition',
            name='pos_pr_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequisition',
            name='pos_pr_tca_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequisition',
            name='pos_pr_tps_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierperformancesnapshot',
            name='pos_sps_tsps_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierperformancesnapshot',
            name='pos_sps_tscore_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierquotation',
            name='pos_sq_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierquotation',
            name='pos_sq_tca_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierquotation',
            name='pos_sq_req_idx',
        ),
        migrations.RemoveIndex(
            model_name='threewaymatchresult',
            name='pos_twmr_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='threewaymatchresult',
            name='pos_twmr_tma_idx',
        ),
        migrations.RemoveIndex(
            model_name='threewaymatchresult',
            name='pos_twmr_po_idx',
        ),
        migrations.RemoveIndex(
            model_name='threewaymatchresult',
            name='pos_twmr_tpb_idx',
        ),
        migrations.RenameIndex(
            model_name='disputecase',
            new_name='dispute_cas_organization__d28382_idx',
            old_name='dispute_cas_organiz_686fc4_idx',
        ),
        migrations.RenameIndex(
            model_name='procurementbudget',
            new_name='procurement_organization__38d42e_idx',
            old_name='procurement_organiz_0b885f_idx',
        ),
        migrations.RenameIndex(
            model_name='procurementbudget',
            new_name='procurement_site_id_f55af4_idx',
            old_name='pos_pb_sps_idx',
        ),
        migrations.RenameIndex(
            model_name='procurementbudget',
            new_name='procurement_categor_457d07_idx',
            old_name='pos_pb_cps_idx',
        ),
        migrations.RenameIndex(
            model_name='procurementrequest',
            new_name='procurement_organization__b53807_idx',
            old_name='procurement_organiz_59f95e_idx',
        ),
        migrations.RenameIndex(
            model_name='procurementrequest',
            new_name='procurement_organization__d6b670_idx',
            old_name='procurement_organiz_47c365_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='purchase_or_organization__7a0535_idx',
            old_name='purchase_or_organiz_1906ba_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='purchase_or_organization__7229bc_idx',
            old_name='purchase_or_organiz_61e53d_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaserequisition',
            new_name='purchase_re_organization__99d105_idx',
            old_name='purchase_re_organiz_2b6047_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaserequisition',
            new_name='purchase_re_site_id_c18581_idx',
            old_name='pos_pr_ss_idx',
        ),
        migrations.RenameIndex(
            model_name='salespaymentleg',
            new_name='sales_payme_organization__9f8baa_idx',
            old_name='sales_payme_organiz_8d21f4_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierperformancesnapshot',
            new_name='supplier_pe_organization__1d73be_idx',
            old_name='supplier_pe_organiz_170c37_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierperformancesnapshot',
            new_name='supplier_pe_supplie_a483d9_idx',
            old_name='pos_sps_spe_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierquotation',
            new_name='supplier_qu_organization__046ab6_idx',
            old_name='supplier_qu_organiz_5fc0b3_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierquotation',
            new_name='supplier_qu_supplie_cf2919_idx',
            old_name='pos_sq_ss_idx',
        ),
        migrations.RenameIndex(
            model_name='threewaymatchresult',
            new_name='three_way_m_organization__a63391_idx',
            old_name='three_way_m_organiz_3451ac_idx',
        ),
        migrations.RenameIndex(
            model_name='threewaymatchresult',
            new_name='three_way_m_invoice_e49f52_idx',
            old_name='pos_twmr_inv_idx',
        ),
        migrations.AlterField(
            model_name='budgetcommitment',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='cashieraddressbook',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='consignmentsettlement',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='consignmentsettlementline',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='dailyaddressbooksnapshot',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='discountusagelog',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='disputecase',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='landedcost',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='landedcostline',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='orderlinetaxentry',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='possettings',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='posticket',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='procurementbudget',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='purchaseattachment',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='purchaserequisitionline',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='registersession',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='salesdailysummary',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='salespaymentleg',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='sessionaccountreconciliation',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='supplierclaim',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='suppliercreditnote',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='supplierperformancesnapshot',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='supplierpricehistory',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='supplierquotation',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='supplierquotationline',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='threewaymatchline',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='threewaymatchresult',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AddIndex(
            model_name='disputecase',
            index=models.Index(fields=['organization', 'opened_at'], name='dispute_cas_organization__9e4087_idx'),
        ),
        migrations.AddIndex(
            model_name='disputecase',
            index=models.Index(fields=['organization', 'dispute_type', 'status'], name='dispute_cas_organization__4b433f_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementbudget',
            index=models.Index(fields=['organization', 'is_active'], name='procurement_organization__eda36d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['organization', 'created_at'], name='purchase_re_organization__9e593a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['organization', 'priority', 'status'], name='purchase_re_organization__ee20c0_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierperformancesnapshot',
            index=models.Index(fields=['organization', '-score'], name='supplier_pe_organization__6c3f35_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierquotation',
            index=models.Index(fields=['organization', 'created_at'], name='supplier_qu_organization__ff34b7_idx'),
        ),
        migrations.AddIndex(
            model_name='threewaymatchresult',
            index=models.Index(fields=['organization', 'matched_at'], name='three_way_m_organization__700529_idx'),
        ),
        migrations.AddIndex(
            model_name='threewaymatchresult',
            index=models.Index(fields=['organization', 'payment_blocked'], name='three_way_m_organization__c78c95_idx'),
        ),
    ]
