# Generated by Django 6.0.3 on 2026-04-02 01:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_rename_erp_auditlo_organization__3bae30_idx_erp_auditlo_tenant__3bae30_idx_and_more'),
        ('finance', '0047_tax_engine_phase1'),
        ('inventory', '0049_alter_printsession_options_and_more'),
        ('pos', '0074_snapshot_governance_expansion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'pos_register_payment_method',
                'ordering': ['sort_order', 'payment_method__name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='budgetcommitment',
            name='budget_comm_purchas_83f8dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='budgetcommitment',
            name='budget_comm_budget__e61aba_idx',
        ),
        migrations.RemoveIndex(
            model_name='disputecase',
            name='dispute_cas_organization__d28382_idx',
        ),
        migrations.RemoveIndex(
            model_name='disputecase',
            name='dispute_cas_purchas_79330c_idx',
        ),
        migrations.RemoveIndex(
            model_name='disputecase',
            name='dispute_cas_organization__9e4087_idx',
        ),
        migrations.RemoveIndex(
            model_name='disputecase',
            name='dispute_cas_organization__4b433f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='paymentterm',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='paymentterm',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='payment_term',
        ),
        migrations.RemoveIndex(
            model_name='procurementbudget',
            name='procurement_organization__38d42e_idx',
        ),
        migrations.RemoveIndex(
            model_name='procurementbudget',
            name='procurement_organization__eda36d_idx',
        ),
        migrations.RemoveIndex(
            model_name='procurementrequest',
            name='procurement_organization__b53807_idx',
        ),
        migrations.RemoveIndex(
            model_name='procurementrequest',
            name='procurement_organization__d6b670_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequisition',
            name='purchase_re_organization__99d105_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequisition',
            name='purchase_re_organization__9e593a_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequisition',
            name='purchase_re_organization__ee20c0_idx',
        ),
        migrations.RemoveField(
            model_name='purchaserequisitionline',
            name='requisition',
        ),
        migrations.RemoveField(
            model_name='purchaserequisitionline',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='purchaserequisitionline',
            name='preferred_supplier',
        ),
        migrations.RemoveField(
            model_name='purchaserequisitionline',
            name='product',
        ),
        migrations.RemoveField(
            model_name='supplierquotationline',
            name='requisition_line',
        ),
        migrations.RemoveField(
            model_name='supplierclaim',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='supplierclaim',
            name='purchase_return',
        ),
        migrations.RemoveField(
            model_name='supplierclaim',
            name='receipt_line',
        ),
        migrations.RemoveField(
            model_name='supplierclaim',
            name='supplier',
        ),
        migrations.AlterUniqueTogether(
            name='suppliercreditnote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='suppliercreditnote',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='suppliercreditnote',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='suppliercreditnote',
            name='purchase_return',
        ),
        migrations.RemoveField(
            model_name='suppliercreditnote',
            name='supplier',
        ),
        migrations.AlterUniqueTogether(
            name='supplierperformancesnapshot',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='supplierperformancesnapshot',
            name='supplier_pe_organization__1d73be_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierperformancesnapshot',
            name='supplier_pe_organization__6c3f35_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierquotation',
            name='supplier_qu_organization__046ab6_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierquotation',
            name='supplier_qu_requisi_15f081_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierquotation',
            name='supplier_qu_organization__ff34b7_idx',
        ),
        migrations.RemoveField(
            model_name='supplierquotationline',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='supplierquotationline',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='supplierquotationline',
            name='product',
        ),
        migrations.RemoveIndex(
            model_name='threewaymatchline',
            name='three_way_m_match_r_351c7f_idx',
        ),
        migrations.RemoveIndex(
            model_name='threewaymatchresult',
            name='three_way_m_organization__a63391_idx',
        ),
        migrations.RemoveIndex(
            model_name='threewaymatchresult',
            name='three_way_m_purchas_adcd8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='threewaymatchresult',
            name='three_way_m_organization__700529_idx',
        ),
        migrations.RemoveIndex(
            model_name='threewaymatchresult',
            name='three_way_m_organization__c78c95_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='purchase_or_organiz_1906ba_idx',
            old_name='purchase_or_organization__7a0535_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='purchase_or_organiz_61e53d_idx',
            old_name='purchase_or_organization__7229bc_idx',
        ),
        migrations.RenameIndex(
            model_name='salespaymentleg',
            new_name='sales_payme_organiz_8d21f4_idx',
            old_name='sales_payme_organization__9f8baa_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='assigned_driver',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='invoiced_at',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='actual_credit_amount',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='expected_credit_amount',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='received_by_supplier_at',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='return_number',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='return_type',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='purchasereturnline',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='purchasereturnline',
            name='po_line',
        ),
        migrations.RemoveField(
            model_name='purchasereturnline',
            name='return_reason',
        ),
        migrations.RemoveField(
            model_name='supplierpackageprice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supplierpackageprice',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='cashieraddressbook',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='consignmentsettlement',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='consignmentsettlementline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='dailyaddressbooksnapshot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='discountusagelog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='landedcost',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='landedcostline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='order',
            name='destination_country',
            field=models.CharField(blank=True, help_text='ISO country code of delivery destination (null = same as org origin)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='destination_region',
            field=models.CharField(blank=True, help_text='State/province/region for sub-national taxes (e.g. CA, ON)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_jurisdiction_code',
            field=models.CharField(blank=True, help_text='Resolved jurisdiction code (e.g. CI, US-CA, EU-DE) — read-only after calculation', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='orderlinetaxentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='possettings',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='posticket',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='supplier_barcode',
            field=models.CharField(blank=True, help_text='Barcode the supplier uses for this product (may differ from product barcode)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseattachment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='original_order',
            field=models.ForeignKey(help_text='The original purchase order', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='pos.order'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='original_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_lines', to='pos.orderline'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='registersession',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='salesdailysummary',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='salespaymentleg',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='sessionaccountreconciliation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='supplierpackageprice',
            name='is_default_purchase_price',
            field=models.BooleanField(default=False, help_text='Use this price as default when creating PO lines'),
        ),
        migrations.AlterField(
            model_name='supplierpackageprice',
            name='max_qty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum quantity for this price (null = unlimited)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='supplierpackageprice',
            name='min_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Minimum quantity for this price to apply', max_digits=15),
        ),
        migrations.AlterField(
            model_name='supplierpackageprice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='supplierpackageprice',
            name='packaging',
            field=models.ForeignKey(blank=True, help_text='Null = base unit price (no specific packaging)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='inventory.productpackaging'),
        ),
        migrations.AlterField(
            model_name='supplierpackageprice',
            name='purchase_price_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Purchase price excl. tax', max_digits=15),
        ),
        migrations.AlterField(
            model_name='supplierpackageprice',
            name='purchase_price_ttc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Purchase price incl. tax', max_digits=15),
        ),
        migrations.AlterField(
            model_name='supplierpackageprice',
            name='supplier_barcode',
            field=models.CharField(blank=True, help_text='Supplier barcode for this product/packaging combo', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplierpackageprice',
            name='supplier_ref',
            field=models.CharField(blank=True, help_text='Supplier reference/part number for this packaging', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplierpackageprice',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Price effective date (null = always valid)', null=True),
        ),
        migrations.AlterField(
            model_name='supplierpackageprice',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Price expiry date (null = no expiry)', null=True),
        ),
        migrations.AlterField(
            model_name='supplierpricehistory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='registerpaymentmethod',
            name='financial_account',
            field=models.ForeignKey(blank=True, help_text='Financial account for this payment method on this register', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_method_links', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='registerpaymentmethod',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='registerpaymentmethod',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_links', to='finance.paymentmethod'),
        ),
        migrations.AddField(
            model_name='registerpaymentmethod',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_methods', to='pos.posregister'),
        ),
        migrations.RemoveField(
            model_name='budgetcommitment',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='budgetcommitment',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='budgetcommitment',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='disputecase',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='disputecase',
            name='match_result',
        ),
        migrations.RemoveField(
            model_name='disputecase',
            name='opened_by',
        ),
        migrations.RemoveField(
            model_name='disputecase',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='disputecase',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='disputecase',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='disputecase',
            name='supplier_credit_note',
        ),
        migrations.DeleteModel(
            name='PaymentTerm',
        ),
        migrations.RemoveField(
            model_name='procurementbudget',
            name='category',
        ),
        migrations.RemoveField(
            model_name='procurementbudget',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='procurementbudget',
            name='site',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='from_warehouse',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='product',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='source_po',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='to_warehouse',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='converted_po',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='site',
        ),
        migrations.DeleteModel(
            name='PurchaseRequisitionLine',
        ),
        migrations.DeleteModel(
            name='SupplierClaim',
        ),
        migrations.DeleteModel(
            name='SupplierCreditNote',
        ),
        migrations.RemoveField(
            model_name='supplierperformancesnapshot',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='supplierperformancesnapshot',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='converted_po',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='requisition',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='SupplierQuotationLine',
        ),
        migrations.RemoveField(
            model_name='threewaymatchline',
            name='match_result',
        ),
        migrations.RemoveField(
            model_name='threewaymatchline',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='threewaymatchline',
            name='product',
        ),
        migrations.RemoveField(
            model_name='threewaymatchline',
            name='purchase_order_line',
        ),
        migrations.RemoveField(
            model_name='threewaymatchresult',
            name='goods_receipt',
        ),
        migrations.RemoveField(
            model_name='threewaymatchresult',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='threewaymatchresult',
            name='matched_by',
        ),
        migrations.RemoveField(
            model_name='threewaymatchresult',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='threewaymatchresult',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='threewaymatchresult',
            name='resolved_by',
        ),
        migrations.AlterUniqueTogether(
            name='registerpaymentmethod',
            unique_together={('register', 'payment_method')},
        ),
        migrations.DeleteModel(
            name='BudgetCommitment',
        ),
        migrations.DeleteModel(
            name='DisputeCase',
        ),
        migrations.DeleteModel(
            name='ProcurementBudget',
        ),
        migrations.DeleteModel(
            name='ProcurementRequest',
        ),
        migrations.DeleteModel(
            name='SupplierPerformanceSnapshot',
        ),
        migrations.DeleteModel(
            name='PurchaseRequisition',
        ),
        migrations.DeleteModel(
            name='SupplierQuotation',
        ),
        migrations.DeleteModel(
            name='ThreeWayMatchLine',
        ),
        migrations.DeleteModel(
            name='ThreeWayMatchResult',
        ),
    ]
