# Generated by Django 6.0.3 on 2026-04-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_einvoice_standard'),
        ('pos', '0075_tax_engine_phase1'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='purchase_or_tenant__7a0535_idx',
            old_name='purchase_or_organiz_1906ba_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='purchase_or_tenant__7229bc_idx',
            old_name='purchase_or_organiz_61e53d_idx',
        ),
        migrations.RenameIndex(
            model_name='salespaymentleg',
            new_name='sales_payme_tenant__9f8baa_idx',
            old_name='sales_payme_organiz_8d21f4_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='fne_error',
            field=models.TextField(blank=True, help_text='Error message from last failed FNE certification attempt', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fne_reference',
            field=models.CharField(blank=True, help_text='FNE-assigned invoice reference (e.g. 2026TK00000001)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fne_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('CERTIFIED', 'Certified'), ('FAILED', 'Failed')], db_index=True, help_text='FNE certification status', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fne_token',
            field=models.TextField(blank=True, help_text='FNE QR code token URL for printing on invoices', null=True),
        ),
        migrations.AlterField(
            model_name='cashieraddressbook',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='consignmentsettlement',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='consignmentsettlementline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='dailyaddressbooksnapshot',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='discountusagelog',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='landedcost',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='landedcostline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='orderlinetaxentry',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='posregister',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='possettings',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='posticket',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='purchaseattachment',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='registerpaymentmethod',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='registersession',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='salesdailysummary',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='salespaymentleg',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='sessionaccountreconciliation',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='supplierpackageprice',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='supplierpricehistory',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
    ]
