# Generated by Django 6.0.3 on 2026-04-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0076_add_fne_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fne_invoice_id',
            field=models.CharField(blank=True, help_text='FNE platform invoice UUID (required for /refund credit note endpoint)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fne_raw_response',
            field=models.JSONField(blank=True, help_text='Full FNE certification response including line item IDs (needed for credit note mapping)', null=True),
        ),
    ]
