# Generated by Django 6.0.3 on 2026-04-30 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_remove_approvalrule_organization_and_more'),
        ('pos', '0079_procurementrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddocument',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='posauditevent',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='pos_audit_events', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='posauditrule',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='pos_audit_rules', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='salesauditlog',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='sales_audit_logs', to='erp.organization'),
        ),
    ]
