"""
Automated Replenishment Service — Phase 4
=========================================
Dynamically evaluates stock levels against `Product.min_stock_level`.
Auto-generates DRAFT Purchase Orders mapped to preferred suppliers.
"""
from decimal import Decimal
from django.db import transaction
from django.db.models import Sum
from apps.inventory.models import Product, Inventory, StockLedger
from apps.pos.models import PurchaseOrder, PurchaseOrderLine, ProductSupplier

class AutomatedReplenishmentService:

    @classmethod
    def run_auto_replenishment(cls, organization) -> dict:
        """
        Scans all active products. If (available_qty + incoming_qty) < min_stock_level,
        groups them by the preferred supplier and creates DRAFT Purchase Orders.
        """
        products = Product.objects.filter(is_active=True, organization=organization)
        
        # Group needed items by supplier: { supplier_id: [ {product, qty_needed}, ... ] }
        supplier_needs = {}
        
        for product in products:
            # Skip if min_stock is not defined or 0
            if not product.min_stock_level or product.min_stock_level <= 0:
                continue
                
            on_hand = Inventory.objects.filter(product=product, organization=organization).aggregate(t=Sum('quantity'))['t'] or Decimal('0')
            reserved = StockLedger.objects.filter(product=product, organization=organization).aggregate(t=Sum('reserved_delta'))['t'] or Decimal('0')
            available = max(Decimal('0'), on_hand - reserved)
            
            # Incoming purchases (Orders that haven't been fully received yet)
            # Exclude CANCELLED, REJECTED, and COMPLETED
            # We subtract qty_received from quantity to get the pending incoming balance
            incoming_data = PurchaseOrderLine.objects.filter(
                product=product,
                order__organization=organization,
                order__status__in=[
                    'DRAFT', 'SUBMITTED', 'APPROVED', 'SENT', 
                    'CONFIRMED', 'IN_TRANSIT', 'PARTIALLY_RECEIVED'
                ]
            ).aggregate(
                total_qty=Sum('quantity'),
                total_rec=Sum('qty_received')
            )
            
            incoming_qty = (incoming_data['total_qty'] or Decimal('0')) - (incoming_data['total_rec'] or Decimal('0'))
            incoming_qty = max(Decimal('0'), incoming_qty)
            
            effective_available = available + incoming_qty
            
            if effective_available < product.min_stock_level:
                # Need to reorder
                deficit = Decimal(str(product.min_stock_level)) - effective_available
                reorder_qty = product.reorder_quantity if getattr(product, 'reorder_quantity', None) and product.reorder_quantity > 0 else deficit
                
                # It's possible reorder_qty is smaller than deficit if misconfigured, ensure we order at least deficit
                reorder_qty = max(Decimal(str(reorder_qty)), deficit)
                
                # Find preferred supplier
                pref_supp = ProductSupplier.objects.filter(
                    product=product, organization=organization, is_preferred=True
                ).first()
                if not pref_supp:
                    pref_supp = ProductSupplier.objects.filter(
                        product=product, organization=organization
                    ).first()
                    
                if pref_supp and pref_supp.supplier:
                    # Enforce MOQ (Minimum Order Quantity)
                    min_order = getattr(pref_supp, 'min_order_qty', Decimal('1.00'))
                    order_qty = max(reorder_qty, min_order)
                    
                    supp_id = pref_supp.supplier.id
                    if supp_id not in supplier_needs:
                        supplier_needs[supp_id] = []
                    
                    supplier_needs[supp_id].append({
                        'product': product,
                        'qty': order_qty,
                        'pref_supp': pref_supp
                    })
        
        # Now create DRAFT POs
        created_pos = []
        with transaction.atomic():
            for supp_id, items in supplier_needs.items():
                if not items:
                    continue
                    
                supplier = items[0]['pref_supp'].supplier
                
                po = PurchaseOrder.objects.create(
                    organization=organization,
                    supplier=supplier,
                    supplier_name=supplier.name,
                    status='DRAFT',
                    priority='NORMAL',
                    notes="Auto-generated by Min/Max Replenishment Engine."
                )
                
                for item in items:
                    PurchaseOrderLine.objects.create(
                        organization=organization,
                        order=po,
                        product=item['product'],
                        product_name=item['product'].name,
                        product_sku=item['product'].sku,
                        quantity=item['qty'],
                        unit_price=item['pref_supp'].last_purchased_price or getattr(item['product'], 'cost_price_ht', Decimal('0.00')),
                        discount_percent=Decimal('0.00'),
                        tax_rate=getattr(item['product'], 'tva_rate', Decimal('0.00')),
                    )
                
                created_pos.append(po.id)
                
        return {
            'products_scanned': products.count(),
            'pos_created': len(created_pos),
            'po_ids': created_pos
        }
