'use client'
/**
 * Reverse Charge Self-Assessment — Management Page
 */
import { useState, useEffect, useMemo, useRef } from 'react'
import { erpFetch } from '@/lib/erp-api'
import { Plus, Search, Loader2, X, Maximize2, Minimize2, ArrowLeft, Save, ArrowUpDown, DollarSign, CheckCircle2, Clock, Send } from 'lucide-react'
type Rec = Record<string, any>
const TRIGGERS = ['FOREIGN_SERVICE','FOREIGN_GOODS','INTRA_COMMUNITY','DIGITAL_SERVICE','CONSTRUCTION','OTHER']
const TRIGGER_LABELS: Record<string,string> = { FOREIGN_SERVICE:'Foreign Service', FOREIGN_GOODS:'Foreign Goods', INTRA_COMMUNITY:'Intra-Community (EU)', DIGITAL_SERVICE:'Digital Service', CONSTRUCTION:'Construction', OTHER:'Other' }
const STATUSES = ['PENDING','ASSESSED','DECLARED','CANCELLED']
const STATUS_COLORS: Record<string,{bg:string;fg:string}> = { PENDING:{bg:'color-mix(in srgb, var(--app-warning, #f59e0b) 10%, transparent)',fg:'var(--app-warning, #f59e0b)'}, ASSESSED:{bg:'color-mix(in srgb, var(--app-info, #3b82f6) 10%, transparent)',fg:'var(--app-info, #3b82f6)'}, DECLARED:{bg:'color-mix(in srgb, var(--app-success, #22c55e) 10%, transparent)',fg:'var(--app-success, #22c55e)'}, CANCELLED:{bg:'color-mix(in srgb, var(--app-error, #ef4444) 10%, transparent)',fg:'var(--app-error, #ef4444)'} }
const inputCls = 'w-full text-[12px] font-bold bg-app-surface/60 border border-app-border/50 rounded-xl px-3 py-2 text-app-foreground placeholder:text-app-muted-foreground focus:bg-app-surface focus:border-app-primary/40 focus:ring-2 focus:ring-app-primary/10 outline-none transition-all'
const labelCls = 'text-[9px] font-black text-app-muted-foreground uppercase tracking-widest mb-1 block'

function Editor({ item, onSave, onCancel }: { item: Rec|null; onSave:(d:Rec)=>void; onCancel:()=>void }) {
  const [form, setForm] = useState<Rec>(item || { assessment_date: new Date().toISOString().split('T')[0], trigger_type:'FOREIGN_SERVICE', description:'', supplier_invoice_ref:'', supplier_country:'', purchase_amount_ht:0, local_vat_rate:0.18, recovery_rate:1.0, currency_code:'XOF', status:'PENDING', vat_return_period:'', notes:'' })
  const [saving, setSaving] = useState(false); const upd = (k:string,v:any) => setForm(p=>({...p,[k]:v}))
  const outputVAT = parseFloat(form.purchase_amount_ht||0) * parseFloat(form.local_vat_rate||0)
  const inputVAT = outputVAT * parseFloat(form.recovery_rate||0)
  const netCost = outputVAT - inputVAT
  return (
    <div className="flex flex-col h-full p-4 md:p-6 animate-in fade-in duration-300">
      <div className="flex items-center gap-3 mb-4 flex-shrink-0"><button onClick={onCancel} className="flex items-center gap-1.5 text-[11px] font-bold text-app-muted-foreground hover:text-app-foreground border border-app-border px-2.5 py-1.5 rounded-xl hover:bg-app-surface transition-all"><ArrowLeft size={13}/> Back</button><div className="flex items-center gap-3 flex-1 min-w-0"><div className="page-header-icon bg-app-primary" style={{boxShadow:'0 4px 14px color-mix(in srgb, var(--app-primary) 30%, transparent)'}}><ArrowUpDown size={20} className="text-white"/></div><div className="min-w-0"><h1 className="truncate">{item ? 'Edit Assessment' : 'New Assessment'}</h1><p className="text-[10px] font-bold text-app-muted-foreground uppercase tracking-widest">Reverse Charge VAT</p></div></div><button onClick={async()=>{setSaving(true);await onSave({...form,output_vat:outputVAT,input_vat:inputVAT,net_vat_cost:netCost});setSaving(false)}} disabled={saving} className="flex items-center gap-1.5 text-[11px] font-bold bg-app-primary hover:brightness-110 text-white px-3 py-1.5 rounded-xl transition-all" style={{boxShadow:'0 2px 8px color-mix(in srgb, var(--app-primary) 25%, transparent)',opacity:saving?0.7:1}}>{saving?<Loader2 size={14} className="animate-spin"/>:<Save size={14}/>} Save</button></div>
      <div className="flex-1 overflow-y-auto custom-scrollbar space-y-4">
        <div className="rounded-2xl p-4" style={{background:'linear-gradient(135deg, color-mix(in srgb, var(--app-info, #3b82f6) 6%, transparent), color-mix(in srgb, var(--app-surface) 80%, transparent))',border:'1px solid color-mix(in srgb, var(--app-info, #3b82f6) 15%, transparent)'}}>
          <div className="text-[9px] font-black text-app-muted-foreground uppercase tracking-widest mb-2">SELF-ASSESSMENT BREAKDOWN</div>
          <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit, minmax(100px, 1fr))',gap:'12px'}}>
            {[{label:'Purchase HT',value:parseFloat(form.purchase_amount_ht||0),color:'var(--app-muted-foreground)'},{label:'Output VAT',value:outputVAT,color:'var(--app-error, #ef4444)'},{label:`Input VAT (${(parseFloat(form.recovery_rate||0)*100).toFixed(0)}%)`,value:inputVAT,color:'var(--app-success, #22c55e)'},{label:'Net Cost',value:netCost,color:netCost>0?'var(--app-warning, #f59e0b)':'var(--app-success, #22c55e)'}].map(c=>(<div key={c.label} className="text-center"><div className="text-[9px] font-bold uppercase tracking-wider" style={{color:'var(--app-muted-foreground)'}}>{c.label}</div><div className="text-lg font-black tabular-nums" style={{color:c.color}}>{c.value.toLocaleString(undefined,{maximumFractionDigits:2})}</div></div>))}
          </div>
          <p className="text-[10px] font-bold mt-2" style={{color:netCost===0?'var(--app-success, #22c55e)':'var(--app-warning, #f59e0b)'}}>{netCost===0?'✓ Fully recoverable — net VAT cost is zero':'⚠ Partial recovery — net cost applies because recovery rate < 100%'}</p>
        </div>
        <div className="rounded-2xl p-4" style={{background:'color-mix(in srgb, var(--app-surface) 50%, transparent)',border:'1px solid color-mix(in srgb, var(--app-border) 50%, transparent)'}}>
          <div className="text-[9px] font-black text-app-muted-foreground uppercase tracking-widest mb-3">DETAILS</div>
          <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit, minmax(180px, 1fr))',gap:'12px'}}>
            <div><label className={labelCls}>Assessment Date</label><input className={inputCls} type="date" value={form.assessment_date} onChange={e=>upd('assessment_date',e.target.value)}/></div>
            <div><label className={labelCls}>Trigger Type</label><select className={inputCls} value={form.trigger_type} onChange={e=>upd('trigger_type',e.target.value)}>{TRIGGERS.map(t=><option key={t} value={t}>{TRIGGER_LABELS[t]}</option>)}</select></div>
            <div><label className={labelCls}>Purchase Amount HT</label><input className={inputCls} type="number" min={0} step={0.01} value={form.purchase_amount_ht} onChange={e=>upd('purchase_amount_ht',e.target.value)}/></div>
            <div><label className={labelCls}>Local VAT Rate</label><input className={inputCls} type="number" min={0} max={1} step={0.0001} value={form.local_vat_rate} onChange={e=>upd('local_vat_rate',e.target.value)}/></div>
            <div><label className={labelCls}>Recovery Rate</label><input className={inputCls} type="number" min={0} max={1} step={0.01} value={form.recovery_rate} onChange={e=>upd('recovery_rate',e.target.value)}/><p className="text-[9px] font-bold text-app-muted-foreground mt-0.5">1.0 = 100% recoverable</p></div>
            <div><label className={labelCls}>Supplier Invoice Ref</label><input className={inputCls} value={form.supplier_invoice_ref} onChange={e=>upd('supplier_invoice_ref',e.target.value)} placeholder="INV-2026-001"/></div>
            <div><label className={labelCls}>Supplier Country</label><input className={inputCls} value={form.supplier_country} onChange={e=>upd('supplier_country',e.target.value)} placeholder="FR" maxLength={3}/></div>
            <div><label className={labelCls}>VAT Return Period</label><input className={inputCls} value={form.vat_return_period} onChange={e=>upd('vat_return_period',e.target.value)} placeholder="2026-Q1"/></div>
          </div>
        </div>
        <div className="rounded-2xl p-4" style={{background:'color-mix(in srgb, var(--app-surface) 50%, transparent)',border:'1px solid color-mix(in srgb, var(--app-border) 50%, transparent)'}}><div className="text-[9px] font-black text-app-muted-foreground uppercase tracking-widest mb-3">NOTES</div><textarea className={inputCls} rows={3} value={form.notes} onChange={e=>upd('notes',e.target.value)} placeholder="Additional notes..."/></div>
      </div>
    </div>
  )
}

export default function ReverseChargePage() {
  const [items, setItems] = useState<Rec[]>([]); const [dashboard, setDashboard] = useState<Record<string,any>>({}); const [loading, setLoading] = useState(true); const [searchQuery, setSearchQuery] = useState(''); const [focusMode, setFocusMode] = useState(false); const [editing, setEditing] = useState<Rec|null|'new'>(null); const searchRef = useRef<HTMLInputElement>(null)
  useEffect(()=>{load()},[])
  async function load(){try{setLoading(true);const[d,s]=await Promise.all([erpFetch('finance/reverse-charge/'),erpFetch('finance/reverse-charge/dashboard/')]);setItems(Array.isArray(d)?d:d?.results||[]);setDashboard(s||{})}catch(e){console.error(e)}finally{setLoading(false)}}
  async function handleSave(data:Rec){try{if(data.id){await erpFetch(`finance/reverse-charge/${data.id}/`,{method:'PATCH',body:JSON.stringify(data)})}else{await erpFetch('finance/reverse-charge/',{method:'POST',body:JSON.stringify(data)})};setEditing(null);load()}catch(e){console.error(e);alert('Save failed')}}
  async function handleAssess(id:number){try{await erpFetch(`finance/reverse-charge/${id}/assess/`,{method:'POST'});load()}catch(e){console.error(e);alert('Assess failed')}}
  const filtered = useMemo(()=>{if(!searchQuery.trim())return items;const q=searchQuery.toLowerCase();return items.filter(i=>i.trigger_type?.toLowerCase().includes(q)||i.supplier_invoice_ref?.toLowerCase().includes(q)||i.supplier_country?.toLowerCase().includes(q))},[items,searchQuery])
  const kpis = [{label:'Assessments',value:dashboard.total_assessments??items.length,icon:<ArrowUpDown size={11}/>,color:'var(--app-primary)'},{label:'Pending',value:dashboard.pending??0,icon:<Clock size={11}/>,color:'var(--app-warning, #f59e0b)'},{label:'Output VAT',value:(dashboard.total_output_vat??0).toLocaleString(),icon:<DollarSign size={11}/>,color:'var(--app-error, #ef4444)'},{label:'Net Cost',value:(dashboard.total_net_cost??0).toLocaleString(),icon:<DollarSign size={11}/>,color:'var(--app-info, #3b82f6)'}]
  if(editing)return<Editor item={editing==='new'?null:editing} onSave={handleSave} onCancel={()=>setEditing(null)}/>
  return (
    <div className="flex flex-col h-full p-4 md:p-6 animate-in fade-in duration-300"><div className={`flex-shrink-0 space-y-4 ${focusMode?'pb-2':'pb-4'}`}>
      {!focusMode&&(<><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div className="flex items-center gap-3"><div className="page-header-icon bg-app-primary" style={{boxShadow:'0 4px 14px color-mix(in srgb, var(--app-primary) 30%, transparent)'}}><ArrowUpDown size={20} className="text-white"/></div><div><h1>Reverse Charge</h1><p className="text-[10px] md:text-[11px] font-bold text-app-muted-foreground uppercase tracking-widest">Self-Assessment · Foreign Purchases</p></div></div><div className="flex items-center gap-1.5 flex-shrink-0"><button onClick={()=>setEditing('new')} className="flex items-center gap-1.5 text-[11px] font-bold bg-app-primary hover:brightness-110 text-white px-3 py-1.5 rounded-xl transition-all" style={{boxShadow:'0 2px 8px color-mix(in srgb, var(--app-primary) 25%, transparent)'}}><Plus size={14}/> New</button><button onClick={()=>setFocusMode(true)} className="flex items-center gap-1 text-[11px] font-bold text-app-muted-foreground hover:text-app-foreground border border-app-border px-2 py-1.5 rounded-xl hover:bg-app-surface transition-all"><Maximize2 size={13}/></button></div></div>
        <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit, minmax(140px, 1fr))',gap:'8px'}}>{kpis.map(s=>(<div key={s.label} className="flex items-center gap-2 px-3 py-2 rounded-xl" style={{background:'color-mix(in srgb, var(--app-surface) 50%, transparent)',border:'1px solid color-mix(in srgb, var(--app-border) 50%, transparent)'}}><div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{background:`color-mix(in srgb, ${s.color} 10%, transparent)`,color:s.color}}>{s.icon}</div><div className="min-w-0"><div className="text-[10px] font-bold uppercase tracking-wider" style={{color:'var(--app-muted-foreground)'}}>{s.label}</div><div className="text-sm font-black text-app-foreground tabular-nums truncate">{s.value}</div></div></div>))}</div>
      </>)}
      <div className="flex items-center gap-2">{focusMode&&<div className="flex items-center gap-2 flex-shrink-0"><div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{background:'var(--app-primary)'}}><ArrowUpDown size={14} style={{color:'#fff'}}/></div></div>}<div className="flex-1 relative"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-app-muted-foreground"/><input ref={searchRef} type="text" value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} placeholder="Search..." className="w-full pl-9 pr-3 py-2 text-[12px] bg-app-surface/50 border border-app-border/50 rounded-xl text-app-foreground placeholder:text-app-muted-foreground focus:bg-app-surface focus:border-app-border focus:ring-2 focus:ring-app-primary/10 outline-none transition-all"/></div>{focusMode&&<><button onClick={()=>setEditing('new')} className="flex items-center gap-1 text-[10px] font-bold bg-app-primary text-white px-2 py-1.5 rounded-lg"><Plus size={12}/></button><button onClick={()=>setFocusMode(false)} className="p-1.5 rounded-lg border border-app-border text-app-muted-foreground hover:text-app-foreground hover:bg-app-surface transition-all"><Minimize2 size={13}/></button></>}{searchQuery&&<button onClick={()=>setSearchQuery('')} className="text-[11px] font-bold px-2 py-2 rounded-xl border" style={{color:'var(--app-error)',borderColor:'color-mix(in srgb, var(--app-error) 20%, transparent)'}}><X size={13}/></button>}</div>
    </div>
    <div className="flex-1 min-h-0 bg-app-surface/30 border border-app-border/50 rounded-2xl overflow-hidden flex flex-col">
      <div className="flex-shrink-0 flex items-center gap-2 md:gap-3 px-3 py-2 bg-app-surface/60 border-b border-app-border/50 text-[10px] font-black text-app-muted-foreground uppercase tracking-wider"><div className="w-7 flex-shrink-0"/><div className="flex-1 min-w-0">Type / Invoice</div><div className="hidden sm:block w-24 flex-shrink-0 text-right">Amount</div><div className="hidden md:block w-24 flex-shrink-0 text-right">Output</div><div className="hidden lg:block w-24 flex-shrink-0 text-right">Net</div><div className="hidden lg:block w-20 flex-shrink-0">Status</div><div className="w-10 flex-shrink-0"/></div>
      <div className="flex-1 overflow-y-auto custom-scrollbar">
        {loading?<div className="flex items-center justify-center py-20"><Loader2 size={24} className="animate-spin text-app-primary"/></div>:filtered.length>0?filtered.map(item=>{const sc=STATUS_COLORS[item.status]||STATUS_COLORS.PENDING;return<div key={item.id} className="group flex items-center gap-2 md:gap-3 transition-all cursor-pointer border-b border-app-border/30 hover:bg-app-surface/40 py-2.5 px-3" onClick={()=>setEditing(item)}><div className="w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0" style={{background:sc.bg,color:sc.fg}}><ArrowUpDown size={13}/></div><div className="flex-1 min-w-0"><span className="truncate text-[13px] font-bold text-app-foreground block">{TRIGGER_LABELS[item.trigger_type]||item.trigger_type}</span><span className="text-[10px] font-bold text-app-muted-foreground">{item.supplier_invoice_ref||`#${item.id}`} · {item.supplier_country||'—'} · {item.assessment_date}</span></div><div className="hidden sm:block w-24 flex-shrink-0 text-right font-mono text-[13px] font-black text-app-foreground tabular-nums">{parseFloat(item.purchase_amount_ht||0).toLocaleString()}</div><div className="hidden md:block w-24 flex-shrink-0 text-right font-mono text-[13px] font-black tabular-nums" style={{color:'var(--app-error, #ef4444)'}}>{parseFloat(item.output_vat||0).toLocaleString()}</div><div className="hidden lg:block w-24 flex-shrink-0 text-right font-mono text-[13px] font-black tabular-nums" style={{color:parseFloat(item.net_vat_cost||0)>0?'var(--app-warning, #f59e0b)':'var(--app-success, #22c55e)'}}>{parseFloat(item.net_vat_cost||0).toLocaleString()}</div><div className="hidden lg:block w-20 flex-shrink-0"><span className="text-[10px] font-bold px-1.5 py-0.5 rounded-lg" style={{background:sc.bg,color:sc.fg}}>{item.status}</span></div><div className="flex items-center gap-0.5 flex-shrink-0 opacity-0 group-hover:opacity-100 transition-opacity">{item.status==='PENDING'&&<button onClick={e=>{e.stopPropagation();handleAssess(item.id)}} className="p-1.5 hover:bg-app-border/50 rounded-lg text-app-info hover:text-app-info transition-colors" title="Assess"><Send size={12}/></button>}</div></div>}):<div className="flex flex-col items-center justify-center py-20 px-4 text-center"><ArrowUpDown size={36} className="text-app-muted-foreground mb-3 opacity-40"/><p className="text-sm font-bold text-app-muted-foreground">No reverse charge assessments</p></div>}
      </div>
    </div></div>
  )
}
