# Generated by Django 6.0.2 on 2026-02-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='break_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
