# Generated by Django 5.2.11 on 2026-02-26 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_shift_break_minutes_alter_shift_name'),
        ('inventory', '0005_alter_warehouse_unique_together_warehouse_address_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE employee SET home_site_id = NULL WHERE home_site_id IS NOT NULL AND home_site_id NOT IN (SELECT id FROM warehouse);
                UPDATE shift SET site_id = NULL WHERE site_id IS NOT NULL AND site_id NOT IN (SELECT id FROM warehouse);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='employee',
            name='home_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='inventory.warehouse'),
        ),
    ]
