# Generated by Django 5.2.11 on 2026-03-01 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_auto_tasking_engine_expansion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='autotaskrule',
            new_name='workspace_a_module_0a58d8_idx',
            old_name='wk_atr_module_active_idx',
        ),
        migrations.RenameIndex(
            model_name='autotaskrule',
            new_name='workspace_a_rule_ty_5b215a_idx',
            old_name='wk_atr_ruletype_active_idx',
        ),
        migrations.RenameIndex(
            model_name='autotaskrule',
            new_name='workspace_a_trigger_f667c0_idx',
            old_name='wk_atr_trigger_idx',
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='broadcast_to_role',
            field=models.BooleanField(default=False, help_text='If True, create a task for EVERY user in the assigned role'),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='chain_delay_minutes',
            field=models.IntegerField(default=0, help_text='Wait X minutes after parent task completes before creating this task'),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='chain_parent',
            field=models.ForeignKey(blank=True, help_text="Only fire when this parent rule's task is COMPLETED", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chain_children', to='workspace.autotaskrule'),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='code',
            field=models.CharField(blank=True, help_text='Rule code e.g. INV-01, PUR-03. Unique per organization.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Conditions: min_amount, max_amount, site_id, client_id, cashier_id, payment_method, stale_days'),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='is_system_default',
            field=models.BooleanField(default=False, help_text='True if this is a pre-seeded system default (user can disable but not delete)'),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='priority',
            field=models.CharField(blank=True, help_text='Override the template default priority (URGENT, HIGH, MEDIUM, LOW)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='recurrence_day_of_month',
            field=models.IntegerField(blank=True, help_text='1-28 (for MONTHLY rules). Use 28 for end-of-month.', null=True),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='recurrence_day_of_week',
            field=models.IntegerField(blank=True, help_text='0=Monday, 6=Sunday (for WEEKLY rules)', null=True),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='recurrence_interval',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], help_text='How often to fire (for RECURRING rules)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='recurrence_time',
            field=models.TimeField(blank=True, help_text='What time of day to fire (e.g. 08:00)', null=True),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='stale_threshold_days',
            field=models.IntegerField(default=3, help_text='Number of days after which to trigger (for stale/overdue rules)'),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='trigger_event',
            field=models.CharField(choices=[('PRICE_CHANGE', 'Product Price Changed'), ('LOW_STOCK', 'Low Stock Alert'), ('EXPIRY_APPROACHING', 'Product Expiry Approaching'), ('PRODUCT_EXPIRED', 'Product Has Expired'), ('PRODUCT_CREATED', 'New Product Created'), ('BARCODE_MISSING_PURCHASE', 'Product Purchased Without Barcode'), ('BARCODE_MISSING_TRANSFER', 'Product Transferred Without Barcode'), ('BARCODE_DAILY_CHECK', 'Daily: Products Without Barcodes'), ('STOCK_ADJUSTMENT', 'Stock Adjustment Made'), ('INVENTORY_COUNT', 'Inventory Count Needed'), ('NEGATIVE_STOCK', 'Negative Stock Sale'), ('PURCHASE_ENTERED', 'Purchase Order Entered'), ('PURCHASE_NO_ATTACHMENT', 'Purchase Without Invoice Attachment'), ('PO_APPROVED', 'Purchase Order Approved'), ('RECEIPT_VOUCHER', 'Receipt Voucher Arrived'), ('PROFORMA_RECEIVED', 'Proforma Received'), ('TRANSFER_CREATED', 'Transfer Order Created'), ('DELIVERY_COMPLETED', 'Delivery Completed'), ('NEW_SUPPLIER', 'New Supplier Onboarded'), ('CREDIT_SALE', 'Credit Sale — No Cash Collected'), ('HIGH_VALUE_SALE', 'High-Value Sale Threshold Crossed'), ('ORDER_COMPLETED', 'Order Completed'), ('POS_RETURN', 'POS Return / Refund Processed'), ('CASHIER_DISCOUNT', 'Cashier Applied Discount'), ('OVERDUE_INVOICE', 'Invoice Overdue'), ('LATE_PAYMENT', 'Late Payment Detected'), ('PAYMENT_DUE_SUPPLIER', 'Supplier Payment Due'), ('NEW_INVOICE', 'New Invoice Received'), ('BANK_STATEMENT', 'Bank Statement Received'), ('DAILY_SUMMARY', 'End-of-Day Financial Summary'), ('MONTH_END', 'Month-End Close'), ('CLIENT_FOLLOWUP_DUE', 'Client Follow-Up Strategy Due'), ('SUPPLIER_FOLLOWUP_DUE', 'Supplier Follow-Up Due'), ('NEW_CLIENT', 'New Client Registered'), ('CLIENT_INACTIVE', 'Client Inactive > X Days'), ('CLIENT_COMPLAINT', 'Client Complaint Filed'), ('ADDRESS_BOOK_VERIFY', 'Address Book Verification'), ('EMPLOYEE_ONBOARD', 'New Employee Onboarded'), ('LEAVE_REQUEST', 'Leave Request Submitted'), ('ATTENDANCE_ANOMALY', 'Attendance Anomaly Detected'), ('USER_REGISTRATION', 'New User Registration'), ('REPORT_NEEDS_REVIEW', 'Report Needs Review'), ('ORDER_STALE', 'Order Not Treated After X Days'), ('APPROVAL_PENDING', 'Approval Pending > X Days'), ('CUSTOM', 'Custom Event')], max_length=30),
        ),
    ]
