# Generated by Django 6.0.4 on 2026-04-26 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0017_task_remind_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotaskrule',
            name='assign_to_user_group',
            field=models.ForeignKey(blank=True, help_text='Assign generated task to every member of this ad-hoc user group (overrides role)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_task_rules_assigned', to='workspace.usergroup'),
        ),
        migrations.AlterField(
            model_name='autotaskrule',
            name='trigger_event',
            field=models.CharField(choices=[('PRICE_CHANGE', 'Product Price Changed'), ('LOW_STOCK', 'Low Stock Alert'), ('NEGATIVE_STOCK', 'Negative Stock Detected'), ('NEW_INVOICE', 'New Invoice Received'), ('EXPIRY_APPROACHING', 'Product Expiry Approaching'), ('PRODUCT_EXPIRED', 'Product Expired'), ('PRODUCT_CREATED', 'New Product Created'), ('PO_APPROVED', 'Purchase Order Approved'), ('CLIENT_COMPLAINT', 'Client Complaint Filed'), ('NEW_SUPPLIER', 'New Supplier Onboarded'), ('NEW_CLIENT', 'New Client Registered'), ('DELIVERY_COMPLETED', 'Delivery Completed'), ('ORDER_COMPLETED', 'Order Completed'), ('INVENTORY_COUNT', 'Inventory Count Needed'), ('STOCK_ADJUSTMENT', 'Stock Adjustment Made'), ('BARCODE_MISSING_PURCHASE', 'Barcode Missing on Purchase'), ('BARCODE_MISSING_TRANSFER', 'Barcode Missing on Transfer'), ('BARCODE_DAILY_CHECK', 'Daily Barcode Check'), ('PURCHASE_ENTERED', 'Purchase Entered'), ('PURCHASE_NO_ATTACHMENT', 'Purchase Without Attachment'), ('RECEIPT_VOUCHER', 'Receipt Voucher Arrived'), ('PROFORMA_RECEIVED', 'Proforma Received'), ('TRANSFER_CREATED', 'Transfer Order Created'), ('ORDER_STALE', 'Order Stale / Untreated'), ('CREDIT_SALE', 'Credit Sale Made'), ('HIGH_VALUE_SALE', 'High-Value Sale'), ('OVERDUE_INVOICE', 'Invoice Overdue'), ('PAYMENT_DUE_SUPPLIER', 'Supplier Payment Due'), ('POS_RETURN', 'POS Return Processed'), ('CASHIER_DISCOUNT', 'Cashier Applied Discount'), ('DAILY_SUMMARY', 'End-of-Day Summary'), ('BANK_STATEMENT', 'Bank Statement Received'), ('MONTH_END', 'Month-End Close'), ('PERIOD_CLOSING_SOON', 'Fiscal Period Closing Soon'), ('PERIOD_STARTING_SOON', 'Next Fiscal Period Starting Soon'), ('PERIOD_REOPEN_REQUEST', 'Fiscal Period Reopen Requested'), ('YEAR_CLOSING_SOON', 'Fiscal Year Closing Soon'), ('YEAR_STARTING_SOON', 'Next Fiscal Year Starting Soon'), ('CHECKLIST_READY_TO_CLOSE', 'Close Checklist Ready'), ('CHECKLIST_ITEM_OVERDUE', 'Close Checklist Item Overdue'), ('LATE_PAYMENT', 'Late Payment Detected'), ('CLIENT_FOLLOWUP_DUE', 'Client Follow-Up Due'), ('SUPPLIER_FOLLOWUP_DUE', 'Supplier Follow-Up Due'), ('CLIENT_INACTIVE', 'Client Inactive'), ('ADDRESS_BOOK_VERIFY', 'Address Book Verification'), ('USER_REGISTRATION', 'New User Registration'), ('REPORT_NEEDS_REVIEW', 'Report Needs Review'), ('APPROVAL_PENDING', 'Approval Pending'), ('EMPLOYEE_ONBOARD', 'Employee Onboarding'), ('LEAVE_REQUEST', 'Leave Request'), ('ATTENDANCE_ANOMALY', 'Attendance Anomaly'), ('CUSTOM', 'Custom Event')], max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to_user_group',
            field=models.ForeignKey(blank=True, help_text='Ad-hoc user group the task was broadcast to (for provenance)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_received', to='workspace.usergroup'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='User who marked the task as done / resolved its source action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='completion_checklist',
            field=models.JSONField(blank=True, default=list, help_text='List of {label, checked} items the assignee ticks off before closing.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completion_note',
            field=models.TextField(blank=True, help_text='What did you do? Captured when the task is completed.', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='require_completion_note',
            field=models.BooleanField(default=False, help_text='If true, the UI forces the assignee to explain their work before marking done.'),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='Category owner/lead — visible on the category row.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_task_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userhierarchy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userhierarchy',
            name='parent_user',
            field=models.ForeignKey(blank=True, help_text='Direct superior — this user reports up to them.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hierarchy_children', to=settings.AUTH_USER_MODEL),
        ),
    ]
