# Generated by Django 6.0.2 on 2026-03-02 22:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_seed_app_change_theme_permission'),
        ('inventory', '0009_rename_sl_org_prod_wh_idx_stock_ledge_organiz_0e48ba_idx_and_more'),
        ('pos', '0034_sales_payment_leg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, db_index=True, help_text='Auto-generated sequence reference', max_length=50, null=True)),
                ('move_type', models.CharField(choices=[('TRANSFER', 'Inter-Warehouse Transfer'), ('SALE', 'Fulfilment from alternate warehouse'), ('RETURN', 'Customer return to warehouse'), ('DROPSHIP', 'Dropship — vendor ships to customer')], default='TRANSFER', max_length=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft — not yet submitted'), ('PENDING', 'Pending — awaiting dispatch'), ('IN_TRANSIT', 'In Transit — goods dispatched'), ('DONE', 'Done — received at destination'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, help_text='Expected dispatch/transit date', null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_moves', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(help_text='Source warehouse (stock leaves here)', on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_moves', to='inventory.warehouse')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves', to='pos.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_moves', to=settings.AUTH_USER_MODEL)),
                ('to_warehouse', models.ForeignKey(help_text='Destination warehouse (stock arrives here)', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_moves', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'stock_move',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMoveLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity requested for transfer', max_digits=15)),
                ('quantity_done', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Quantity actually transferred (may differ from requested)', max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='AMC at time of dispatch (for COGS accuracy)', max_digits=15)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockmove')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
            options={
                'db_table': 'stock_move_line',
            },
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['organization', 'status'], name='stock_move_organiz_a5badb_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['from_warehouse', 'to_warehouse'], name='stock_move_from_wa_69dca7_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['ref_code'], name='stock_move_ref_cod_f55022_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockmoveline',
            unique_together={('move', 'product')},
        ),
    ]
