# Generated by Django 5.2.11 on 2026-03-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_productgroup_base_selling_price_ht_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_available_expiry_days',
            field=models.IntegerField(blank=True, help_text='Typical remaining shelf life when product arrives, in days (e.g. 120 = 4 months)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_valuation_method',
            field=models.CharField(choices=[('WAVG', 'Weighted Average Cost (Moving Average)'), ('FIFO', 'First In, First Out'), ('LIFO', 'Last In, First Out'), ('STANDARD', 'Standard Cost (Fixed)')], default='WAVG', help_text='How the cost of goods is calculated when stock is consumed', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='lot_management',
            field=models.CharField(choices=[('NONE', 'No lot tracking'), ('FIFO_AUTO', 'FIFO — Automatic (oldest lot consumed first)'), ('FEFO', 'FEFO — First Expiry, First Out (shortest life consumed first)'), ('MANUAL', 'Manual — Operator selects lot/layer at POS or picking')], default='NONE', help_text='How lots/batches are selected when consuming stock', max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_shelf_life_days',
            field=models.IntegerField(blank=True, help_text='Total shelf life as per manufacturer, in days (e.g. 240 = 8 months)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_duration_days',
            field=models.IntegerField(blank=True, help_text='Average shipping/transit time in days — auto-populated from purchase invoices', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tracks_lots',
            field=models.BooleanField(default=False, help_text='Enable lot/batch number tracking for this product'),
        ),
    ]
