# Generated by Django 5.2.11 on 2026-03-07 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_clientpricerule_packaging_level_id_and_more'),
        ('erp', '0015_user_assigned_branches'),
        ('inventory', '0018_merge_20260307_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Auto-derived from warehouse — do not set manually', limit_choices_to={'location_type': 'BRANCH'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_goods_receipts', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Auto-derived from warehouse', limit_choices_to={'location_type': 'BRANCH'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_inventory', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Auto-derived from warehouse', limit_choices_to={'location_type': 'BRANCH'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_movements', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='dest_branch',
            field=models.ForeignKey(blank=True, help_text='Auto-derived from to_warehouse', limit_choices_to={'location_type': 'BRANCH'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_branch_moves', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='source_branch',
            field=models.ForeignKey(blank=True, help_text='Auto-derived from from_warehouse', limit_choices_to={'location_type': 'BRANCH'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_branch_moves', to='inventory.warehouse'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['organization', 'branch'], name='inv_org_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['organization', 'branch'], name='invmov_org_branch_idx'),
        ),
    ]
