# Generated by Django 6.0.2 on 2026-03-10 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_postable_journal_link'),
        ('inventory', '0019_goodsreceipt_branch_inventory_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingorder',
            name='posted_journal_entry',
            field=models.ForeignKey(blank=True, help_text='The JournalEntry generated when this document was posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_source_docs', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='picklist',
            name='posted_journal_entry',
            field=models.ForeignKey(blank=True, help_text='The JournalEntry generated when this document was posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_source_docs', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='posted_journal_entry',
            field=models.ForeignKey(blank=True, help_text='The JournalEntry generated when this document was posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_source_docs', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='stockadjustmentorder',
            name='posted_journal_entry',
            field=models.ForeignKey(blank=True, help_text='The JournalEntry generated when this document was posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_source_docs', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='posted_journal_entry',
            field=models.ForeignKey(blank=True, help_text='The JournalEntry generated when this document was posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_source_docs', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='posted_journal_entry',
            field=models.ForeignKey(blank=True, help_text='The JournalEntry generated when this document was posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_source_docs', to='finance.journalentry'),
        ),
    ]
