# Generated by Django 5.2.12 on 2026-03-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_grouping_and_pricing_modes'),
        ('inventory', '0040_seed_system_label_templates'),
    ]

    operations = [
    ]
