# Generated by Django 6.0.3 on 2026-04-07 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_einvoice_standard'),
        ('inventory', '0049_alter_printsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransferorder',
            name='destination_vat_registration',
            field=models.CharField(blank=True, default='', help_text='VAT registration number at destination branch', max_length=50),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='goods_value_for_vat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Transfer value of goods for VAT assessment', max_digits=15),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='source_vat_registration',
            field=models.CharField(blank=True, default='', help_text='VAT registration number at source branch', max_length=50),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='vat_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Net VAT adjustment (+ = additional VAT due, - = credit)', max_digits=15),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='vat_rate_destination',
            field=models.DecimalField(decimal_places=4, default=0, help_text='VAT rate at destination jurisdiction', max_digits=7),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='vat_rate_source',
            field=models.DecimalField(decimal_places=4, default=0, help_text='VAT rate at source jurisdiction', max_digits=7),
        ),
        migrations.AddField(
            model_name='stocktransferorder',
            name='vat_transfer_type',
            field=models.CharField(choices=[('SAME_JURISDICTION', 'Same Jurisdiction (no VAT impact)'), ('CROSS_JURISDICTION', 'Cross Jurisdiction (VAT adjustment)'), ('FREE_ZONE_IN', 'Into Free Trade Zone (VAT exempt)'), ('FREE_ZONE_OUT', 'Out of Free Trade Zone (VAT applies)'), ('CROSS_BORDER', 'Cross-Border Inter-company')], default='SAME_JURISDICTION', help_text='VAT treatment for this transfer based on source/destination jurisdictions', max_length=20),
        ),
        migrations.AlterField(
            model_name='brand',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='combocomponent',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='parfum',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
    ]
