# Generated by Django 6.0.2 on 2026-03-06 13:51

import django.db.models.deletion
import erp.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0014_alter_txnapproval_action'),
        ('storage', '0002_alter_storageprovider_max_file_size_mb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Migration job name', max_length=255)),
                ('coa_template_used', models.CharField(blank=True, help_text='COA template name (SYSCOHADA, IFRS, etc.)', max_length=50, null=True)),
                ('posting_rules_snapshot', models.JSONField(blank=True, help_text='Snapshot of posting rules at the time of migration', null=True)),
                ('account_type_mappings', models.JSONField(default=dict, help_text='Map of UPOS account_type_id → TSF ChartOfAccount.id')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft - Setting Up'), ('VALIDATING', 'Running Pre-Flight Validation'), ('MAPPING', 'Account Mapping in Progress'), ('READY', 'Ready to Execute'), ('RUNNING', 'Migration in Progress'), ('COMPLETED', 'Completed Successfully'), ('FAILED', 'Failed with Errors'), ('ROLLED_BACK', 'Rolled Back')], default='DRAFT', max_length=20)),
                ('current_step', models.CharField(blank=True, max_length=100, null=True)),
                ('current_step_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('progress_percent', models.IntegerField(default=0)),
                ('total_units', models.IntegerField(default=0)),
                ('total_categories', models.IntegerField(default=0)),
                ('total_brands', models.IntegerField(default=0)),
                ('total_products', models.IntegerField(default=0)),
                ('total_contacts', models.IntegerField(default=0)),
                ('total_sales', models.IntegerField(default=0)),
                ('total_purchases', models.IntegerField(default=0)),
                ('total_payments', models.IntegerField(default=0)),
                ('total_stock_records', models.IntegerField(default=0)),
                ('imported_units', models.IntegerField(default=0)),
                ('imported_categories', models.IntegerField(default=0)),
                ('imported_brands', models.IntegerField(default=0)),
                ('imported_products', models.IntegerField(default=0)),
                ('imported_customers', models.IntegerField(default=0)),
                ('imported_suppliers', models.IntegerField(default=0)),
                ('imported_sales', models.IntegerField(default=0)),
                ('imported_purchases', models.IntegerField(default=0)),
                ('imported_payments', models.IntegerField(default=0)),
                ('imported_stock_records', models.IntegerField(default=0)),
                ('total_verified', models.IntegerField(default=0)),
                ('total_flagged', models.IntegerField(default=0)),
                ('errors', models.JSONField(default=list, help_text='List of error objects: [{entity_type, source_id, error}]')),
                ('warnings', models.JSONField(default=list, help_text='List of warning objects')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_jobs_v2', to='storage.storedfile')),
                ('target_organization', models.ForeignKey(help_text='Organization where data will be migrated', on_delete=django.db.models.deletion.CASCADE, related_name='migrations_v2', to='erp.organization')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization')),
            ],
            options={
                'db_table': 'migration_v2_job',
                'ordering': ['-id'],
            },
            bases=(erp.mixins.AuditLogMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MigrationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('UNIT', 'Unit of Measure'), ('CATEGORY', 'Product Category'), ('BRAND', 'Brand'), ('TAX_RATE', 'Tax Rate'), ('PRODUCT', 'Product'), ('VARIATION', 'Product Variation'), ('CONTACT_CUSTOMER', 'Customer Contact'), ('CONTACT_SUPPLIER', 'Supplier Contact'), ('COA_ACCOUNT', 'Chart of Account (Auto-Created)'), ('TRANSACTION_SALE', 'Sale Transaction'), ('TRANSACTION_PURCHASE', 'Purchase Transaction'), ('PAYMENT', 'Payment'), ('JOURNAL_ENTRY', 'Journal Entry (Ledger Posting)'), ('STOCK', 'Stock Record'), ('STOCK_ADJUSTMENT', 'Stock Adjustment')], db_index=True, max_length=30)),
                ('source_id', models.IntegerField(help_text='Original ID from UltimatePOS')),
                ('target_id', models.IntegerField(help_text='New ID in TSFSYSTEM')),
                ('source_data', models.JSONField(blank=True, help_text='Snapshot of original record from UltimatePOS', null=True)),
                ('verify_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified ✓'), ('FLAGGED', 'Flagged for Review ⚠')], db_index=True, default='PENDING', max_length=20)),
                ('verify_notes', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='migration_v2.migrationjob')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_migrations_v2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'migration_v2_mapping',
            },
        ),
        migrations.CreateModel(
            name='MigrationValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=False)),
                ('has_coa', models.BooleanField(default=False)),
                ('coa_account_count', models.IntegerField(default=0)),
                ('has_posting_rules', models.BooleanField(default=False)),
                ('missing_posting_rules', models.JSONField(default=list)),
                ('customer_root_valid', models.BooleanField(default=False)),
                ('supplier_root_valid', models.BooleanField(default=False)),
                ('errors', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_result', to='migration_v2.migrationjob')),
            ],
            options={
                'db_table': 'migration_v2_validation_result',
            },
        ),
        migrations.AddIndex(
            model_name='migrationjob',
            index=models.Index(fields=['target_organization', 'status'], name='migration_v_target__ed797a_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationjob',
            index=models.Index(fields=['status'], name='migration_v_status_5418b3_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationmapping',
            index=models.Index(fields=['job', 'entity_type'], name='migration_v_job_id_0ef19c_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationmapping',
            index=models.Index(fields=['job', 'verify_status'], name='migration_v_job_id_5dace5_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationmapping',
            index=models.Index(fields=['entity_type', 'source_id'], name='migration_v_entity__e27306_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='migrationmapping',
            unique_together={('job', 'entity_type', 'source_id')},
        ),
    ]
