# Generated by Django 5.2.11 on 2026-03-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='source_business_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='source_business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
