# Generated by Django 5.2.11 on 2026-03-09 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migration_v2', '0003_migrationjob_created_at_migrationjob_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migrationjob',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='migrationjob',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='migrationjob',
            name='source_business_id',
        ),
        migrations.RemoveField(
            model_name='migrationjob',
            name='source_business_name',
        ),
        migrations.RemoveField(
            model_name='migrationjob',
            name='updated_at',
        ),
    ]
