# Generated by Django 6.0.2 on 2026-02-23 01:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('CART', 'In Cart'), ('PLACED', 'Order Placed'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='CART', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('PARTIAL', 'Partially Paid'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20)),
                ('payment_method', models.CharField(default='WALLET', help_text='WALLET, CASH, CARD, MOBILE_MONEY', max_length=50)),
                ('delivery_address', models.TextField(blank=True, default='')),
                ('delivery_phone', models.CharField(blank=True, default='', max_length=50)),
                ('delivery_notes', models.TextField(blank=True, default='')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_rating', models.IntegerField(blank=True, help_text='1-5 star rating', null=True)),
                ('delivery_feedback', models.TextField(blank=True, default='')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('wallet_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid from wallet', max_digits=15)),
                ('loyalty_points_used', models.IntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Snapshot at time of order', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
            ],
            options={
                'db_table': 'client_order_line',
            },
        ),
        migrations.CreateModel(
            name='ClientPortalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('permissions', models.JSONField(blank=True, default=list, help_text='List of permission codes')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, help_text='Scannable barcode for POS identification', max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Client Portal Accesses',
                'db_table': 'client_portal_access',
            },
        ),
        migrations.CreateModel(
            name='ClientPortalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_mode', models.CharField(choices=[('B2C', 'B2C eCommerce — standard retail prices'), ('B2B', 'B2B Order Portal — tier/negotiated prices'), ('CATALOG_QUOTE', 'Catalog + Quote — browse and request quotes'), ('HYBRID', 'Hybrid — B2C interface, B2B pricing for wholesale/retail clients')], default='HYBRID', help_text='Controls pricing logic and checkout behavior', max_length=20)),
                ('show_stock_levels', models.BooleanField(default=False, help_text='Show exact stock quantities (vs just In Stock / Out of Stock)')),
                ('allow_guest_browsing', models.BooleanField(default=True, help_text='Allow unauthenticated users to browse the catalog')),
                ('require_approval_for_orders', models.BooleanField(default=False, help_text='Orders require admin approval before processing (B2B mode)')),
                ('storefront_title', models.CharField(blank=True, default='', help_text='Custom title for the storefront (blank = org name)', max_length=255)),
                ('storefront_tagline', models.CharField(blank=True, default='', help_text='Tagline shown on the storefront landing page', max_length=500)),
                ('storefront_theme', models.CharField(default='midnight', help_text='Active theme ID for the storefront (e.g. midnight, boutique)', max_length=50)),
                ('storefront_type', models.CharField(choices=[('PRODUCT_STORE', 'Product Store — full e-commerce with cart and checkout'), ('CATALOGUE', 'Catalogue — browse products, request quotes, no direct checkout'), ('SUBSCRIPTION', 'Subscription Store — recurring plans and pricing tiers'), ('LANDING_PAGE', 'Landing Page — company website with hero, about, and contact'), ('PORTFOLIO', 'Portfolio — showcase projects, case studies, and inquiries')], default='PRODUCT_STORE', help_text='Type of storefront layout (product store, catalogue, subscription, landing page, portfolio)', max_length=30)),
                ('seo_title', models.CharField(blank=True, default='', help_text='SEO Meta Title', max_length=255)),
                ('seo_description', models.TextField(blank=True, default='', help_text='SEO Meta Description')),
                ('seo_keywords', models.CharField(blank=True, default='', help_text='SEO Keywords', max_length=500)),
                ('og_image_url', models.URLField(blank=True, default='', help_text='Social Share Image (OG Image) URL')),
                ('logo_url', models.URLField(blank=True, default='', help_text='Organization Logo URL')),
                ('primary_color', models.CharField(default='#10b981', help_text='Primary Brand Color', max_length=20)),
                ('secondary_color', models.CharField(default='#0f172a', help_text='Secondary Brand Color', max_length=20)),
                ('custom_css', models.TextField(blank=True, default='', help_text='Custom CSS for the storefront')),
                ('loyalty_enabled', models.BooleanField(default=True, help_text='Enable loyalty points system')),
                ('loyalty_earn_rate', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Points earned per 1 currency unit spent (e.g. 1.0 = 1 pt/$1, 2.5 = 2.5 pt/$1)', max_digits=10)),
                ('loyalty_redemption_ratio', models.DecimalField(decimal_places=4, default=Decimal('100.0000'), help_text='Points needed for 1 currency unit (e.g. 100 = 100 pts = $1, 50 = 50 pts = $1)', max_digits=10)),
                ('loyalty_min_redeem', models.IntegerField(default=100, help_text='Minimum points required before redemption is allowed')),
                ('loyalty_max_redeem_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Max % of order total payable with loyalty (e.g. 50 = up to 50%)', max_digits=5)),
                ('wallet_enabled', models.BooleanField(default=True, help_text='Enable digital wallet')),
                ('wallet_currency', models.CharField(default='USD', help_text='Wallet currency code', max_length=10)),
                ('wallet_auto_create', models.BooleanField(default=True, help_text='Auto-create wallet when client access is activated')),
                ('wallet_max_balance', models.DecimalField(decimal_places=2, default=Decimal('999999.00'), help_text='Maximum wallet balance (0 = unlimited)', max_digits=15)),
                ('default_delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default delivery fee for eCommerce orders', max_digits=15)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Order amount above which delivery is free (0 = never free)', max_digits=15)),
                ('tickets_enabled', models.BooleanField(default=True, help_text='Enable support ticket system')),
                ('enabled_ticket_types', models.JSONField(blank=True, default=list, help_text='List of enabled ticket type codes. Empty = all enabled.')),
                ('auto_assign_tickets', models.BooleanField(default=False, help_text='Auto-assign new tickets to a default agent')),
                ('ecommerce_enabled', models.BooleanField(default=True, help_text='Allow clients to place orders')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum order subtotal', max_digits=15)),
                ('allow_wallet_payment', models.BooleanField(default=True, help_text='Allow paying with wallet balance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Portal Configuration',
                'verbose_name_plural': 'Client Portal Configurations',
                'db_table': 'client_portal_config',
            },
        ),
        migrations.CreateModel(
            name='ClientTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ticket_type', models.CharField(choices=[('GENERAL', 'General Inquiry'), ('ORDER_ISSUE', 'Order Issue'), ('DELIVERY_PROBLEM', 'Delivery Problem'), ('RETURN_REQUEST', 'Return Request'), ('PRODUCT_FEEDBACK', 'Product Feedback'), ('COMPLAINT', 'Complaint'), ('SUGGESTION', 'Suggestion')], default='GENERAL', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('WAITING_CLIENT', 'Waiting for Client'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('satisfaction_rating', models.IntegerField(blank=True, help_text='1-5 star rating', null=True)),
                ('satisfaction_feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('loyalty_points', models.IntegerField(default=0, help_text='Current redeemable loyalty points')),
                ('lifetime_points', models.IntegerField(default=0, help_text='Total points ever earned')),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_wallet',
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Snapshot of product name', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'client_quote_item',
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(help_text='Customer requirements or questions')),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assessment'), ('REPLIED', 'Proposal Sent'), ('CONVERTED', 'Converted to Order'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('source_url', models.URLField(blank=True, default='', help_text='The page where the quote was requested')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_quote_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('reference_type', models.CharField(blank=True, default='', help_text='e.g. ClientOrder, LoyaltyRedemption, POSChange', max_length=50)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wallet_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
