# Generated by Django 6.0.3 on 2026-05-02 00:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0001_initial'),
        ('crm', '0024_contact_wallet_balance'),
        ('erp', '0029_orglistdefault_active_profile_id_and_more'),
        ('finance', '0079_merge_branches'),
        ('inventory', '0066_rename_pkg_sug_org_cat_idx_packaging_s_tenant__ed4449_idx_and_more'),
        ('pos', '0080_tenant_isolation_audit_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientorder',
            name='pos_order',
        ),
        migrations.AddField(
            model_name='clientorder',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_orders', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='clientorderline',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productvariant'),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='allow_guest_browsing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='custom_css',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='inventory_check_mode',
            field=models.CharField(choices=[('STRICT', 'Strict — Prevent order if stock is insufficient'), ('ALLOW_OVERSALE', 'Allow Oversale — Proceed even if stock is low (goes negative)'), ('DISABLED', 'Disabled — Do not check or reduce stock during checkout')], default='STRICT', max_length=20),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='layout',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='og_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='primary_color',
            field=models.CharField(default='#10b981', max_length=20),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='require_approval_for_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='secondary_color',
            field=models.CharField(default='#0f172a', max_length=20),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='seo_keywords',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='show_stock_levels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='store_mode',
            field=models.CharField(choices=[('B2C', 'B2C eCommerce — standard retail prices'), ('B2B', 'B2B Order Portal — tier/negotiated prices'), ('CATALOG_QUOTE', 'Catalog + Quote — browse and request quotes'), ('HYBRID', 'Hybrid — B2C interface, B2B pricing for wholesale/retail clients')], default='HYBRID', max_length=20),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='storefront_tagline',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='storefront_theme',
            field=models.CharField(default='midnight', max_length=50),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='storefront_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='storefront_type',
            field=models.CharField(choices=[('PRODUCT_STORE', 'Product Store — full e-commerce with cart and checkout'), ('CATALOGUE', 'Catalogue — browse products, request quotes, no direct checkout'), ('SUBSCRIPTION', 'Subscription Store — recurring plans and pricing tiers'), ('LANDING_PAGE', 'Landing Page — company website with hero, about, and contact'), ('PORTFOLIO', 'Portfolio — showcase projects, case studies, and inquiries')], default='PRODUCT_STORE', max_length=30),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productvariant'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='delivery_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='payment_method',
            field=models.CharField(default='WALLET', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='wallet_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='clientorderline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='clientorderline',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientportalaccess',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientportalaccess',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='clientportalaccess',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='allow_wallet_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='auto_assign_tickets',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='default_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='default_ticket_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='ecommerce_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='enabled_ticket_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='free_delivery_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='loyalty_earn_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='loyalty_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='loyalty_max_redeem_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='loyalty_min_redeem',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='loyalty_redemption_ratio',
            field=models.DecimalField(decimal_places=4, default=Decimal('100.0000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='tickets_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='wallet_auto_create',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='wallet_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='wallet_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientportalconfig',
            name='wallet_max_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('999999.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='clientticket',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='clientticket',
            name='satisfaction_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientwallet',
            name='lifetime_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientwallet',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientwallet',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='reference_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='CartPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('rule_type', models.CharField(choices=[('SPEND_THRESHOLD', 'Spend Threshold — spend X → get discount'), ('BOGO', 'Buy X Get Y Free'), ('BUNDLE', 'Bundle — buy products A+B → get discount'), ('MIN_QUANTITY', 'Min Quantity — buy N of a product → get discount')], max_length=20)),
                ('conditions', models.JSONField(help_text='Rule-specific conditions. Examples:\n          SPEND_THRESHOLD: {"min_subtotal": 50000}\n          BOGO:            {"product_id": 42, "buy_quantity": 2}\n          BUNDLE:          {"product_ids": [42, 55]}\n          MIN_QUANTITY:    {"product_id": 42, "min_quantity": 5}')),
                ('reward', models.JSONField(help_text='Discount to apply when conditions are met. Examples:\n          {"type": "PERCENT_OFF_CART",   "value": 10}\n          {"type": "FIXED_OFF_CART",     "value": 5000}\n          {"type": "FREE_QUANTITY",      "product_id": 42, "free_quantity": 1}\n          {"type": "PERCENT_OFF_LINE",   "value": 20}')),
                ('priority', models.IntegerField(default=0, help_text='Higher value = evaluated first. Only highest-priority non-stackable promo applies.')),
                ('stackable', models.BooleanField(default=False, help_text='If True, this promo can combine with other promotions on the same order.')),
                ('max_uses', models.IntegerField(blank=True, help_text='Total uses allowed across all customers. Null = unlimited.', null=True)),
                ('used_count', models.IntegerField(default=0)),
                ('one_per_customer', models.BooleanField(default=False, help_text='Each customer can only benefit from this promotion once.')),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'cart_promotion',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartPromotionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=15)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_usages', to='crm.contact')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_usages', to='client_portal.clientorder')),
                ('organization', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='client_portal.cartpromotion')),
            ],
            options={
                'db_table': 'cart_promotion_usage',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percentage Discount'), ('FIXED', 'Fixed Amount Discount')], default='PERCENT', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 25 for 25%) or fixed amount in org currency', max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum subtotal required to apply this coupon', max_digits=15)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap the discount at this amount (optional)', max_digits=15, null=True)),
                ('max_uses', models.IntegerField(blank=True, help_text='Total uses allowed. Leave blank for unlimited.', null=True)),
                ('used_count', models.IntegerField(default=0)),
                ('one_per_customer', models.BooleanField(default=False, help_text='Each customer can only use this coupon once')),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'client_coupon',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=15)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='crm.contact')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='client_portal.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='client_portal.clientorder')),
                ('organization', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'client_coupon_usage',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=5)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField()),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to='crm.contact')),
                ('organization', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='inventory.product')),
            ],
            options={
                'db_table': 'client_product_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum order subtotal for this tier to apply (inclusive)', max_digits=15)),
                ('max_order_value', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum order subtotal (exclusive). Null = no ceiling.', max_digits=15, null=True)),
                ('min_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Minimum cart weight in kg (inclusive)', max_digits=10)),
                ('max_weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Maximum cart weight in kg (exclusive). Null = no ceiling.', max_digits=10, null=True)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shipping fee for orders matching this tier', max_digits=15)),
                ('estimated_days', models.PositiveIntegerField(blank=True, help_text='Override zone.estimated_days for this specific tier', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower number = evaluated first when multiple tiers match')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('zone', models.ForeignKey(help_text='The delivery zone this rate tier belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='pos.deliveryzone')),
            ],
            options={
                'db_table': 'ecommerce_shipping_rate',
                'ordering': ['sort_order', 'min_order_value'],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='crm.contact')),
                ('organization', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='inventory.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productvariant')),
            ],
            options={
                'db_table': 'client_wishlist_item',
                'ordering': ['-created_at'],
                'unique_together': {('contact', 'product', 'variant')},
            },
        ),
    ]
