# Generated by Django 6.0.2 on 2026-02-23 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_portal', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_orders', to='crm.contact'),
        ),
    ]
