# Generated by Django 6.0.2 on 2026-02-21 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0006_alter_clientportalconfig_storefront_type_and_more'),
        ('erp', '0003_plancategory_linked_inventory_category_and_more'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='product',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='quantity',
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='custom_css',
            field=models.TextField(blank=True, default='', help_text='Custom CSS for the storefront'),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text='Organization Logo URL'),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='og_image_url',
            field=models.URLField(blank=True, default='', help_text='Social Share Image (OG Image) URL'),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='primary_color',
            field=models.CharField(default='#10b981', help_text='Primary Brand Color', max_length=20),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='secondary_color',
            field=models.CharField(default='#0f172a', help_text='Secondary Brand Color', max_length=20),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='seo_description',
            field=models.TextField(blank=True, default='', help_text='SEO Meta Description'),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='seo_keywords',
            field=models.CharField(blank=True, default='', help_text='SEO Keywords', max_length=500),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='SEO Meta Title', max_length=255),
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Snapshot of product name', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='client_portal.quoterequest')),
            ],
            options={
                'db_table': 'client_quote_item',
            },
        ),
    ]
