# Generated by Django 6.0.2 on 2026-02-23 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0006_clientportalconfig_layout'),
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientorder',
            name='pos_order',
        ),
        migrations.AddField(
            model_name='clientorder',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_orders', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='clientportalconfig',
            name='inventory_check_mode',
            field=models.CharField(choices=[('STRICT', 'Strict — Prevent order if stock is insufficient'), ('ALLOW_OVERSALE', 'Allow Oversale — Proceed even if stock is low (goes negative)'), ('DISABLED', 'Disabled — Do not check or reduce stock during checkout')], default='STRICT', help_text='Controls how the storefront interacts with Inventory stock levels', max_length=20),
        ),
    ]
