# Generated by Django 5.2.11 on 2026-03-03 12:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0011_merge_0010_coupon'),
        ('crm', '0008_contact_supplier_vat_regime_and_more'),
        ('erp', '0009_alter_planaddon_addon_type'),
        ('pos', '0044_gap10_generated_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('rule_type', models.CharField(choices=[('SPEND_THRESHOLD', 'Spend Threshold — spend X → get discount'), ('BOGO', 'Buy X Get Y Free'), ('BUNDLE', 'Bundle — buy products A+B → get discount'), ('MIN_QUANTITY', 'Min Quantity — buy N of a product → get discount')], max_length=20)),
                ('conditions', models.JSONField(help_text='Rule-specific conditions. Examples:\n          SPEND_THRESHOLD: {"min_subtotal": 50000}\n          BOGO:            {"product_id": 42, "buy_quantity": 2}\n          BUNDLE:          {"product_ids": [42, 55]}\n          MIN_QUANTITY:    {"product_id": 42, "min_quantity": 5}')),
                ('reward', models.JSONField(help_text='Discount to apply when conditions are met. Examples:\n          {"type": "PERCENT_OFF_CART",   "value": 10}\n          {"type": "FIXED_OFF_CART",     "value": 5000}\n          {"type": "FREE_QUANTITY",      "product_id": 42, "free_quantity": 1}\n          {"type": "PERCENT_OFF_LINE",   "value": 20}')),
                ('priority', models.IntegerField(default=0, help_text='Higher value = evaluated first. Only highest-priority non-stackable promo applies.')),
                ('stackable', models.BooleanField(default=False, help_text='If True, this promo can combine with other promotions on the same order.')),
                ('max_uses', models.IntegerField(blank=True, help_text='Total uses allowed across all customers. Null = unlimited.', null=True)),
                ('used_count', models.IntegerField(default=0)),
                ('one_per_customer', models.BooleanField(default=False, help_text='Each customer can only benefit from this promotion once.')),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'cart_promotion',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartPromotionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=15)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_usages', to='crm.contact')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_usages', to='client_portal.clientorder')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='client_portal.cartpromotion')),
            ],
            options={
                'db_table': 'cart_promotion_usage',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum order subtotal for this tier to apply (inclusive)', max_digits=15)),
                ('max_order_value', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum order subtotal (exclusive). Null = no ceiling.', max_digits=15, null=True)),
                ('min_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Minimum cart weight in kg (inclusive)', max_digits=10)),
                ('max_weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Maximum cart weight in kg (exclusive). Null = no ceiling.', max_digits=10, null=True)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shipping fee for orders matching this tier', max_digits=15)),
                ('estimated_days', models.PositiveIntegerField(blank=True, help_text='Override zone.estimated_days for this specific tier', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower number = evaluated first when multiple tiers match')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('zone', models.ForeignKey(help_text='The delivery zone this rate tier belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='pos.deliveryzone')),
            ],
            options={
                'db_table': 'ecommerce_shipping_rate',
                'ordering': ['sort_order', 'min_order_value'],
            },
        ),
    ]
