# Generated by Django 6.0.3 on 2026-05-02 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0003_initial'),
        ('erp', '0002_initial'),
        ('finance', '0001_initial'),
        ('inventory', '0001_initial'),
        ('pos', '0001_initial'),
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnotevatreversal',
            name='credit_note',
            field=models.ForeignKey(blank=True, help_text='The credit note document', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vat_reversals', to='pos.creditnote'),
        ),
        migrations.AddField(
            model_name='creditnotevatreversal',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='currency',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='currencyratepolicy',
            name='from_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_policies_from', to='finance.currency'),
        ),
        migrations.AddField(
            model_name='currencyratepolicy',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='currencyratepolicy',
            name='to_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_policies_to', to='finance.currency'),
        ),
        migrations.AddField(
            model_name='currencyrevaluation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_revaluation_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencyrevaluation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_revaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencyrevaluation',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='currencyrevaluationline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='currencyrevaluationline',
            name='currency',
            field=models.ForeignKey(help_text='Foreign currency of this account', on_delete=django.db.models.deletion.PROTECT, to='finance.currency'),
        ),
        migrations.AddField(
            model_name='currencyrevaluationline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='currencyrevaluationline',
            name='revaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.currencyrevaluation'),
        ),
        migrations.AddField(
            model_name='customerbalance',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_balance', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='customerbalance',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='customtaxrule',
            name='expense_account',
            field=models.ForeignKey(blank=True, help_text='COA to debit if purchase_cost_treatment = EXPENSE.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_tax_expenses', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='customtaxrule',
            name='liability_account',
            field=models.ForeignKey(blank=True, help_text='COA to credit when collecting tax on sales or withholding it on purchases.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_tax_liabilities', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='customtaxrule',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='deferredexpense',
            name='deferred_coa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_assets', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='deferredexpense',
            name='expense_coa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_expenses', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='deferredexpense',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='deferredrevenue',
            name='deferred_coa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_revenue_liabilities', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='deferredrevenue',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='deferredrevenue',
            name='revenue_coa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_revenue_recognitions', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='expense_coa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_expenses', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_locked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='finance.directexpense'),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dunningreminder',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='dunningreminder',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dunning_reminders_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='countrytaxtemplate',
            name='e_invoice_standard',
            field=models.ForeignKey(blank=True, help_text='E-invoicing standard for this country (e.g. FNE for CI, ZATCA for SA)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_templates', to='finance.einvoicestandard'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='from_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='finance.currency'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='to_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='finance.currency'),
        ),
        migrations.AddField(
            model_name='financedailysummary',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_daily_summaries', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='digital_gateway',
            field=models.ForeignKey(blank=True, help_text='Payment gateway (inherited from category or overridden)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_accounts', to='reference.orgpaymentgateway'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='ledger_account',
            field=models.ForeignKey(blank=True, db_column='ledger_account_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_expenses', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='deferredexpense',
            name='source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_sources', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='account',
            field=models.ForeignKey(help_text='Bank account for this statement', on_delete=django.db.models.deletion.PROTECT, related_name='bank_statements', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='asset',
            name='source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_purchases', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='financialaccountcategory',
            name='coa_parent',
            field=models.ForeignKey(blank=True, help_text='Parent COA account — new financial accounts become sub-accounts of this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_account_categories', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='financialaccountcategory',
            name='digital_gateway',
            field=models.ForeignKey(blank=True, help_text="Default payment gateway for child accounts (from org's activated gateways)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_categories', to='reference.orgpaymentgateway'),
        ),
        migrations.AddField(
            model_name='financialaccountcategory',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Dynamic category (replaces hardcoded type field)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='finance.financialaccountcategory'),
        ),
        migrations.AddField(
            model_name='financialevent',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact'),
        ),
        migrations.AddField(
            model_name='financialevent',
            name='financial_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='financialevent',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='financial_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_expenses', to='finance.financialevent'),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_fiscal_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='currencyrevaluation',
            name='fiscal_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revaluations', to='finance.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='consolidationrun',
            name='fiscal_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='closechecklistrun',
            name='fiscal_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='close_checklist_runs', to='finance.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='fiscal_period',
            field=models.ForeignKey(blank=True, help_text='Null = annual budget (not broken down by period)', null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='accountbalancesnapshot',
            name='fiscal_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='finance.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='fiscalperiodclosesnapshot',
            name='captured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fp_close_snapshots_captured', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalperiodclosesnapshot',
            name='fiscal_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_snapshots', to='finance.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='fiscalperiodclosesnapshot',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_fiscal_years', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='finance.fiscalyear'),
        ),
        migrations.AddField(
            model_name='closechecklistrun',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='close_checklist_runs', to='finance.fiscalyear'),
        ),
        migrations.AddField(
            model_name='budget',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='finance.fiscalyear'),
        ),
        migrations.AddField(
            model_name='fiscalyearclosesnapshot',
            name='captured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fy_close_snapshots_captured', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalyearclosesnapshot',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_snapshots', to='finance.fiscalyear'),
        ),
        migrations.AddField(
            model_name='fiscalyearclosesnapshot',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='forensicauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forensicauditlog',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='formdefinition',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='form_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='finance.formdefinition'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='gatewayconfig',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='giftsampleevent',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='giftsampleevent',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product gifted (if single product)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_events', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='giftsampleevent',
            name='recipient_contact',
            field=models.ForeignKey(blank=True, help_text='Contact who received the gift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_gifts', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='giftsampleevent',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse from which goods were issued', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_events', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='importdeclaration',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='importdeclaration',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='The purchase order for the imported goods', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_declarations', to='pos.purchaseorder'),
        ),
        migrations.AddField(
            model_name='intercompanyrule',
            name='account_a',
            field=models.ForeignKey(help_text='Account to eliminate in entity A', on_delete=django.db.models.deletion.PROTECT, related_name='ic_elimination_a', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='intercompanyrule',
            name='account_b',
            field=models.ForeignKey(help_text='Offsetting account in entity B', on_delete=django.db.models.deletion.PROTECT, related_name='ic_elimination_b', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='intercompanyrule',
            name='entity_a',
            field=models.ForeignKey(help_text='First entity in the intercompany pair', on_delete=django.db.models.deletion.CASCADE, related_name='ic_rules_as_a', to='finance.consolidationentity'),
        ),
        migrations.AddField(
            model_name='intercompanyrule',
            name='entity_b',
            field=models.ForeignKey(help_text='Second entity in the intercompany pair', on_delete=django.db.models.deletion.CASCADE, related_name='ic_rules_as_b', to='finance.consolidationentity'),
        ),
        migrations.AddField(
            model_name='intercompanyrule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercompany_rules', to='finance.consolidationgroup'),
        ),
        migrations.AddField(
            model_name='intercompanyrule',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='internalconsumptionevent',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='internalconsumptionevent',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product consumed internally', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_events', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='internalconsumptionevent',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse from which goods were consumed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_events', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='intrabranchvattransfer',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contact',
            field=models.ForeignKey(help_text='Customer (sales) or Supplier (purchase)', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.site'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='source_order',
            field=models.ForeignKey(blank=True, help_text='Linked POS order that generated this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='pos.order'),
        ),
        migrations.AddField(
            model_name='creditnotevatreversal',
            name='original_invoice',
            field=models.ForeignKey(help_text='The original invoice being credited', on_delete=django.db.models.deletion.PROTECT, related_name='vat_reversals', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='baddebtvatclaim',
            name='invoice',
            field=models.ForeignKey(help_text='The unpaid invoice for which VAT recovery is claimed', on_delete=django.db.models.deletion.PROTECT, related_name='bad_debt_claims', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='advancepaymentvat',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='The final invoice that supersedes deposit VAT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_vat_records', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='fiscal_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='finance.fiscalperiod'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.fiscalyear'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='Newer JE that replaced this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='intrabranchvattransfer',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intra_branch_vat_entries', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='internalconsumptionevent',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='Journal entry recording the output VAT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_consumption_entries', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='importdeclaration',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='Journal entry recording customs duties and import VAT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_declarations', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='giftsampleevent',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_sample_entries', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='fiscalyearclosesnapshot',
            name='closing_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='close_snapshots_closing', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='fiscalyearclosesnapshot',
            name='opening_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='close_snapshots_opening', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='closing_journal_entry',
            field=models.ForeignKey(blank=True, help_text='OFFICIAL-scope year-end closing JE (audit-trail anchor). PROTECT prevents accidental deletion.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_fiscal_year', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='internal_closing_journal_entry',
            field=models.ForeignKey(blank=True, help_text='INTERNAL-scope year-end closing JE (management book). PROTECT prevents accidental deletion.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internal_closed_fiscal_year', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='financialevent',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_expenses', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='posted_journal_entry',
            field=models.ForeignKey(blank=True, help_text='The JournalEntry generated when this document was posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_source_docs', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='currencyrevaluation',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revaluation_source', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='currencyrevaluation',
            name='reversal_journal_entry',
            field=models.ForeignKey(blank=True, help_text='The auto-posted reversing JE on day 1 of next period.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revaluation_reversed_source', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='creditnotevatreversal',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_note_vat_reversals', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='baddebtvatclaim',
            name='claim_journal_entry',
            field=models.ForeignKey(blank=True, help_text='Journal entry created when claim is filed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bad_debt_claims', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='baddebtvatclaim',
            name='reversal_journal_entry',
            field=models.ForeignKey(blank=True, help_text='Journal entry if customer pays after claim (reversal)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bad_debt_reversals', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='amortizationschedule',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='advancepaymentvat',
            name='adjustment_journal',
            field=models.ForeignKey(blank=True, help_text='JE for adjustment when invoice is issued', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_adjustment_entries', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='advancepaymentvat',
            name='deposit_journal',
            field=models.ForeignKey(blank=True, help_text='JE for deposit VAT declaration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_deposit_entries', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='financial_account',
            field=models.ForeignKey(blank=True, help_text='Physical bank/cash account (for cash flow tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product linked to this line (for COGS/inventory analysis)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='matched_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_bank_lines', to='finance.journalentryline'),
        ),
        migrations.AddField(
            model_name='loan',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='loan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='financialevent',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.loan'),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.loan'),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='marginschemetransaction',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='margin_buyer_txns', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='marginschemetransaction',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='margin_scheme_entries', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='marginschemetransaction',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='marginschemetransaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='margin_supplier_txns', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opening_balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='finance.fiscalyear'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='orgtaxpolicy',
            name='airsi_account',
            field=models.ForeignKey(blank=True, help_text='AIRSI withholding: LIABILITY if non-refundable, ASSET if RECOVER', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_policy_airsi', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='orgtaxpolicy',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='orgtaxpolicy',
            name='reverse_charge_account',
            field=models.ForeignKey(blank=True, help_text='Reverse charge / autoliquidation VAT account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_policy_reverse_charge', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='orgtaxpolicy',
            name='vat_collected_account',
            field=models.ForeignKey(blank=True, help_text='Output VAT liability on sales invoices (TVA Collectée)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_policy_vat_collected', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='orgtaxpolicy',
            name='vat_payable_account',
            field=models.ForeignKey(blank=True, help_text='Net VAT due clearing account for settlement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_policy_vat_payable', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='orgtaxpolicy',
            name='vat_recoverable_account',
            field=models.ForeignKey(blank=True, help_text='Input VAT asset on purchases (TVA Récupérable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_policy_vat_recoverable', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='orgtaxpolicy',
            name='vat_refund_receivable_account',
            field=models.ForeignKey(blank=True, help_text='VAT credit receivable when input > output', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_policy_vat_refund', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='orgtaxpolicy',
            name='vat_suspense_account',
            field=models.ForeignKey(blank=True, help_text='VAT suspense for cash-basis accounting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_policy_vat_suspense', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='credit_note',
            field=models.ForeignKey(blank=True, help_text='Linked credit note (for refunds)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='pos.creditnote'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Primary invoice this payment applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_payments', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_account',
            field=models.ForeignKey(help_text='Account used for payment', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sales_order',
            field=models.ForeignKey(blank=True, help_text='Linked sales order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to='pos.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='supplier_invoice',
            field=models.ForeignKey(blank=True, help_text='Linked purchase order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to='pos.order'),
        ),
        migrations.AddField(
            model_name='advancepaymentvat',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='The advance payment that triggered VAT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_vat_records', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='periodictaxaccrual',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='postingrule',
            name='account',
            field=models.ForeignKey(help_text='GL account mapped to this event', on_delete=django.db.models.deletion.PROTECT, related_name='posting_rules', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='postingrule',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='contextualpostingrule',
            name='base_rule',
            field=models.ForeignKey(help_text='The base posting rule this overrides', on_delete=django.db.models.deletion.CASCADE, related_name='contextual_overrides', to='finance.postingrule'),
        ),
        migrations.AddField(
            model_name='postingrulehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postingrulehistory',
            name='new_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='postingrulehistory',
            name='old_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='postingrulehistory',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_distributions', to='finance.fiscalyear'),
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='reconciliationline',
            name='journal_entry_line',
            field=models.ForeignKey(help_text='The matched journal entry line', on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_lines', to='finance.journalentryline'),
        ),
        migrations.AddField(
            model_name='reconciliationline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='reconciliationmatch',
            name='account',
            field=models.ForeignKey(help_text='The control/reconcilable account (AR, AP, Bank)', on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_matches', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='reconciliationmatch',
            name='matched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationmatch',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='reconciliationmatch',
            name='unmatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmatched_reconciliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationline',
            name='reconciliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.reconciliationmatch'),
        ),
        migrations.AddField(
            model_name='reconciliationsession',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='reconciliationsession',
            name='started_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_reconciliation_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationsession',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='finance.bankstatement'),
        ),
        migrations.AddField(
            model_name='recurringjournalexecution',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_source', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='recurringjournalexecution',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='recurringjournalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='recurringjournalline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='recurringjournaltemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_journals_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringjournaltemplate',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='recurringjournalline',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.recurringjournaltemplate'),
        ),
        migrations.AddField(
            model_name='recurringjournalexecution',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='finance.recurringjournaltemplate'),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportdefinition',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='finance.reportdefinition'),
        ),
        migrations.AddField(
            model_name='revenueperformanceobligation',
            name='deferred_revenue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='finance.deferredrevenue'),
        ),
        migrations.AddField(
            model_name='revenueperformanceobligation',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='revenueperformanceobligation',
            name='release_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_obligations_released', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='reversechargeselfassessment',
            name='input_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_charge_input_entries', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='reversechargeselfassessment',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='reversechargeselfassessment',
            name='output_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_charge_output_entries', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='reversechargeselfassessment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_charge_assessments', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='supplierbalance',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_balance', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='supplierbalance',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='taxaccountmapping',
            name='account',
            field=models.ForeignKey(blank=True, help_text='GL account for this tax type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_account_mappings', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='taxaccountmapping',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='taxaccountmapping',
            name='policy',
            field=models.ForeignKey(help_text='Tax policy this mapping belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='account_mappings', to='finance.orgtaxpolicy'),
        ),
        migrations.AddField(
            model_name='taxgroup',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='tax_line',
            field=models.ForeignKey(blank=True, help_text='Tax code applied to this line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='finance.taxgroup'),
        ),
        migrations.AddField(
            model_name='taxjurisdictionrule',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='taxratecategory',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='financialevent',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_events', to='finance.transaction'),
        ),
        migrations.AddField(
            model_name='transactionsequence',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='vatratechangehistory',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='vatratechangehistory',
            name='tax_group',
            field=models.ForeignKey(help_text='The tax group whose rate changed', on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='finance.taxgroup'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='destination_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_in', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='financial_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='finance.financialevent'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_locked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='posted_journal_entry',
            field=models.ForeignKey(blank=True, help_text='The JournalEntry generated when this document was posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_source_docs', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='finance.voucher'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_out', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withholdingtaxrule',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Direct contact link (when no tax profile exists)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withholding_rules', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='withholdingtaxrule',
            name='counterparty_profile',
            field=models.ForeignKey(blank=True, help_text='Counterparty tax profile this rule belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withholding_rules', to='finance.counterpartytaxprofile'),
        ),
        migrations.AddField(
            model_name='withholdingtaxrule',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='zatcaconfig',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['organization', 'class_code'], name='chartofacco_tenant__9dbbcd_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['organization', 'type'], name='chartofacco_tenant__f942bd_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['organization', 'is_active'], name='chartofacco_tenant__425576_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['organization', 'system_role'], name='chartofacco_tenant__0ff896_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['path'], name='chartofacco_path_7a6f32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chartofaccount',
            unique_together={('code', 'organization')},
        ),
        migrations.AddIndex(
            model_name='closechecklistitemstate',
            index=models.Index(fields=['organization', 'run', 'is_complete'], name='finance_clo_tenant__40e957_idx'),
        ),
        migrations.AddConstraint(
            model_name='closechecklistitemstate',
            constraint=models.UniqueConstraint(fields=('run', 'item'), name='close_checklist_state_uniq_run_item'),
        ),
        migrations.AddIndex(
            model_name='closechecklisttemplate',
            index=models.Index(fields=['organization', 'scope', 'is_default'], name='finance_clo_tenant__643c06_idx'),
        ),
        migrations.AddIndex(
            model_name='closechecklistitem',
            index=models.Index(fields=['organization', 'template', 'order'], name='finance_clo_tenant__2bc03b_idx'),
        ),
        migrations.AddIndex(
            model_name='coamigrationaccountplan',
            index=models.Index(fields=['session', 'migration_mode'], name='coamigacct_mode_idx'),
        ),
        migrations.AddIndex(
            model_name='coamigrationaccountplan',
            index=models.Index(fields=['session', 'is_executed'], name='coamigacct_exec_idx'),
        ),
        migrations.AddIndex(
            model_name='coatemplate',
            index=models.Index(fields=['key', 'organization'], name='coatpl_key_org_idx'),
        ),
        migrations.AddConstraint(
            model_name='coatemplate',
            constraint=models.UniqueConstraint(fields=('key', 'version', 'organization'), name='unique_template_key_version_org'),
        ),
        migrations.AddIndex(
            model_name='coamigrationsession',
            index=models.Index(fields=['organization', 'status'], name='coamig_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='coatemplateaccount',
            index=models.Index(fields=['template', 'system_role'], name='coatplacct_role_idx'),
        ),
        migrations.AddIndex(
            model_name='coatemplateaccount',
            index=models.Index(fields=['template', 'type', 'sub_type'], name='coatplacct_type_idx'),
        ),
        migrations.AddIndex(
            model_name='coatemplateaccount',
            index=models.Index(fields=['template', 'business_domain'], name='coatplacct_domain_idx'),
        ),
        migrations.AddIndex(
            model_name='coatemplateaccount',
            index=models.Index(fields=['template', 'semantic_group'], name='coatplacct_semgrp_idx'),
        ),
        migrations.AddIndex(
            model_name='coatemplateaccount',
            index=models.Index(fields=['template', 'is_dirty'], name='coatplacct_dirty_idx'),
        ),
        migrations.AddConstraint(
            model_name='coatemplateaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('system_role__isnull', False)), fields=('template', 'system_role'), name='unique_role_per_template'),
        ),
        migrations.AlterUniqueTogether(
            name='coatemplateaccount',
            unique_together={('template', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='coatemplatemigrationmap',
            unique_together={('source_template', 'target_template', 'source_account_code', 'target_account_code')},
        ),
        migrations.AlterUniqueTogether(
            name='coatemplatepostingrule',
            unique_together={('template', 'event_code')},
        ),
        migrations.AlterUniqueTogether(
            name='consolidationentity',
            unique_together={('group', 'entity_organization')},
        ),
        migrations.AddIndex(
            model_name='consolidationline',
            index=models.Index(fields=['run', 'account'], name='finance_con_run_id_f17fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='consolidationline',
            index=models.Index(fields=['run', 'entity'], name='finance_con_run_id_98e531_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='currencyratepolicy',
            index=models.Index(fields=['organization', 'auto_sync'], name='finance_cur_tenant__d81c58_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='currencyratepolicy',
            unique_together={('organization', 'from_currency', 'to_currency', 'rate_type')},
        ),
        migrations.AddIndex(
            model_name='deferredrevenue',
            index=models.Index(fields=['organization', 'status'], name='deferredrev_tenant__0cca66_idx'),
        ),
        migrations.AddIndex(
            model_name='deferredrevenue',
            index=models.Index(fields=['organization', 'start_date'], name='deferredrev_tenant__f23628_idx'),
        ),
        migrations.AddIndex(
            model_name='dunningreminder',
            index=models.Index(fields=['organization', 'contact_id'], name='finance_dun_tenant__f13cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='dunningreminder',
            index=models.Index(fields=['organization', 'level'], name='finance_dun_tenant__0428cb_idx'),
        ),
        migrations.AddIndex(
            model_name='dunningreminder',
            index=models.Index(fields=['organization', 'status'], name='finance_dun_tenant__77d062_idx'),
        ),
        migrations.AddIndex(
            model_name='dunningreminder',
            index=models.Index(fields=['organization', 'sent_at'], name='finance_dun_tenant__bfc882_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['organization', 'from_currency', 'to_currency', 'effective_date'], name='finance_exc_tenant__509586_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('organization', 'from_currency', 'to_currency', 'effective_date', 'rate_type', 'rate_side')},
        ),
        migrations.AddIndex(
            model_name='financedailysummary',
            index=models.Index(fields=['organization', 'date', 'scope'], name='fin_daily_org_date_scope_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='financedailysummary',
            unique_together={('organization', 'date', 'scope')},
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['organization', 'account', 'statement_date'], name='bank_statem_tenant__6a76fc_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['organization', 'status'], name='bank_statem_tenant__48f269_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='financialaccountcategory',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='consolidationrun',
            index=models.Index(fields=['group', 'fiscal_period'], name='finance_con_group_i_29f039_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['budget', 'account'], name='finance_bud_budget__816b22_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['budget', 'fiscal_period'], name='finance_bud_budget__546370_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['budget', 'cost_center'], name='finance_bud_budget__036559_idx'),
        ),
        migrations.AddIndex(
            model_name='accountbalancesnapshot',
            index=models.Index(fields=['organization', 'fiscal_period', 'scope'], name='account_bal_tenant__c281f2_idx'),
        ),
        migrations.AddIndex(
            model_name='accountbalancesnapshot',
            index=models.Index(fields=['organization', 'account'], name='account_bal_tenant__a38ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='accountbalancesnapshot',
            index=models.Index(fields=['is_stale'], name='account_bal_is_stal_0f7a35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountbalancesnapshot',
            unique_together={('account', 'fiscal_period', 'scope', 'organization')},
        ),
        migrations.AddIndex(
            model_name='fiscalperiodclosesnapshot',
            index=models.Index(fields=['organization', 'fiscal_period'], name='finance_fp__tenant__9052b7_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalperiodclosesnapshot',
            index=models.Index(fields=['fiscal_period', 'scope'], name='finance_fp__fiscal__550dde_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscalperiodclosesnapshot',
            constraint=models.UniqueConstraint(fields=('fiscal_period', 'scope'), name='fp_close_snapshot_uniq_period_scope'),
        ),
        migrations.AlterUniqueTogether(
            name='fiscalperiod',
            unique_together={('name', 'fiscal_year')},
        ),
        migrations.AddConstraint(
            model_name='closechecklistrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'READY'])), fields=('fiscal_period', 'template'), name='close_checklist_one_active_per_period'),
        ),
        migrations.AddConstraint(
            model_name='closechecklistrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'READY'])), fields=('fiscal_year', 'template'), name='close_checklist_one_active_per_year'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['organization', 'fiscal_year', 'status'], name='finance_bud_tenant__cc5c16_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('organization', 'fiscal_year', 'version')},
        ),
        migrations.AddIndex(
            model_name='forensicauditlog',
            index=models.Index(fields=['organization', 'model_name', 'object_id'], name='forensicaud_tenant__e91fcc_idx'),
        ),
        migrations.AddIndex(
            model_name='forensicauditlog',
            index=models.Index(fields=['organization', 'timestamp'], name='forensicaud_tenant__a96361_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formdefinition',
            unique_together={('organization', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='gatewayconfig',
            unique_together={('organization', 'gateway_type')},
        ),
        migrations.AddIndex(
            model_name='intercompanyrule',
            index=models.Index(fields=['group', 'elimination_type'], name='finance_int_group_i_8b7bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['organization', 'transaction_date'], name='journalentr_tenant__8a56b4_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['organization', 'scope'], name='journalentr_tenant__2aaed0_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['organization', 'status'], name='journalentr_tenant__1f43db_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['reference'], name='journalentr_referen_762bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['organization', 'is_superseded'], name='journalentr_tenant__902e76_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['organization', 'journal_role'], name='journalentr_tenant__b9b068_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_superseded', False), ('journal_role', 'SYSTEM_OPENING'), ('journal_type', 'OPENING'), ('status', 'POSTED')), fields=('fiscal_year', 'scope', 'organization'), name='unique_active_opening_je_per_fy_scope'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('reference', 'organization')},
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'status'], name='invoice_tenant__622a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'type'], name='invoice_tenant__5ad5ff_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'contact'], name='invoice_tenant__54699b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'due_date'], name='invoice_tenant__e6fe4b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoice_invoice_5b7137_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalyearclosesnapshot',
            index=models.Index(fields=['organization', 'fiscal_year'], name='finance_fy__tenant__c7dd3c_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalyearclosesnapshot',
            index=models.Index(fields=['fiscal_year', 'scope'], name='finance_fy__fiscal__29a44d_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscalyearclosesnapshot',
            constraint=models.UniqueConstraint(fields=('fiscal_year', 'scope'), name='fy_close_snapshot_uniq_year_scope'),
        ),
        migrations.AlterUniqueTogether(
            name='fiscalyear',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='currencyrevaluation',
            index=models.Index(fields=['organization', 'fiscal_period'], name='finance_cur_tenant__f78f72_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['organization', 'statement', 'is_matched'], name='bank_statem_tenant__4074b1_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['organization', 'transaction_date'], name='bank_statem_tenant__d01167_idx'),
        ),
        migrations.AddIndex(
            model_name='openingbalance',
            index=models.Index(fields=['organization', 'fiscal_year'], name='opening_bal_tenant__e1cf48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='openingbalance',
            unique_together={('account', 'fiscal_year', 'scope', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='orgtaxpolicy',
            unique_together={('name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('code', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='periodictaxaccrual',
            unique_together={('organization', 'period_start', 'period_end', 'tax_type')},
        ),
        migrations.AddIndex(
            model_name='postingrule',
            index=models.Index(fields=['organization', 'is_active'], name='pr_org_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postingrule',
            unique_together={('organization', 'event_code')},
        ),
        migrations.AddIndex(
            model_name='contextualpostingrule',
            index=models.Index(fields=['organization', 'event_code', 'is_active'], name='cpr_org_event_idx'),
        ),
        migrations.AddIndex(
            model_name='contextualpostingrule',
            index=models.Index(fields=['organization', 'context_type', 'context_value'], name='cpr_ctx_idx'),
        ),
        migrations.AddIndex(
            model_name='postingrulehistory',
            index=models.Index(fields=['organization', 'event_code'], name='finance_pos_tenant__c43dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='postingrulehistory',
            index=models.Index(fields=['organization', 'timestamp'], name='finance_pos_tenant__1f958a_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationmatch',
            index=models.Index(fields=['organization', 'account'], name='reconciliat_tenant__d70831_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationmatch',
            index=models.Index(fields=['organization', 'status'], name='reconciliat_tenant__0a19cf_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationmatch',
            index=models.Index(fields=['partner_type', 'partner_id'], name='reconciliat_partner_5a0bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationline',
            index=models.Index(fields=['reconciliation'], name='reconciliat_reconci_8d7017_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationline',
            index=models.Index(fields=['journal_entry_line'], name='reconciliat_journal_2d060b_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationsession',
            index=models.Index(fields=['organization', 'statement'], name='reconciliat_tenant__9afff2_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationsession',
            index=models.Index(fields=['organization', 'status', 'started_at'], name='reconciliat_tenant__41c198_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringjournaltemplate',
            index=models.Index(fields=['organization', 'status'], name='finance_rec_tenant__d7d68e_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringjournaltemplate',
            index=models.Index(fields=['next_run_date'], name='finance_rec_next_ru_212ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringjournalexecution',
            index=models.Index(fields=['template', 'execution_date'], name='finance_rec_templat_1860c1_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueperformanceobligation',
            index=models.Index(fields=['deferred_revenue', 'is_satisfied'], name='revenueperf_deferre_5f6e8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxaccountmapping',
            unique_together={('policy', 'tax_type')},
        ),
        migrations.AlterUniqueTogether(
            name='taxgroup',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['organization', 'account'], name='journalentr_tenant__655ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['journal_entry'], name='journalentr_journal_012f87_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['organization', 'debit', 'credit'], name='journalentr_tenant__d96f42_idx'),
        ),
        migrations.AddIndex(
            model_name='taxjurisdictionrule',
            index=models.Index(fields=['country_code', 'region_code', 'tax_type'], name='tax_juris_country_region_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxratecategory',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='transactionsequence',
            unique_together={('type', 'organization')},
        ),
    ]
