# Generated by Django 5.1.7 on 2026-02-16 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_initial'),
        ('erp', '0002_initial'),
        ('finance', '0001_initial'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='credit_note',
            field=models.ForeignKey(blank=True, help_text='Linked credit note (for refunds)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='pos.creditnote'),
        ),
        migrations.AddField(
            model_name='payment',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_account',
            field=models.ForeignKey(help_text='Account used for payment', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sales_order',
            field=models.ForeignKey(blank=True, help_text='Linked sales order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to='pos.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='supplier_invoice',
            field=models.ForeignKey(blank=True, help_text='Linked purchase order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to='pos.order'),
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_distributions', to='finance.fiscalyear'),
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='profitdistribution',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='supplierbalance',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_balance', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='supplierbalance',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='taxgroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.site'),
        ),
        migrations.AddField(
            model_name='financialevent',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_events', to='finance.transaction'),
        ),
        migrations.AddField(
            model_name='transactionsequence',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='destination_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_in', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='financial_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='finance.financialevent'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_out', to='finance.financialaccount'),
        ),
        migrations.AlterUniqueTogether(
            name='chartofaccount',
            unique_together={('code', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='fiscalyear',
            unique_together={('name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='fiscalperiod',
            unique_together={('name', 'fiscal_year')},
        ),
        migrations.AddIndex(
            model_name='forensicauditlog',
            index=models.Index(fields=['organization', 'model_name', 'object_id'], name='forensicaud_organiz_15cd02_idx'),
        ),
        migrations.AddIndex(
            model_name='forensicauditlog',
            index=models.Index(fields=['organization', 'timestamp'], name='forensicaud_organiz_f6ab40_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['organization', 'transaction_date'], name='journalentr_organiz_5c542f_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['organization', 'scope'], name='journalentr_organiz_339014_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['organization', 'status'], name='journalentr_organiz_cdf611_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['reference'], name='journalentr_referen_762bbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('reference', 'organization')},
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['organization', 'account'], name='journalentr_organiz_d847f4_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['journal_entry'], name='journalentr_journal_012f87_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['organization', 'debit', 'credit'], name='journalentr_organiz_ebb715_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxgroup',
            unique_together={('name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='transactionsequence',
            unique_together={('type', 'organization')},
        ),
    ]
