# Generated by Django 5.1.7 on 2026-02-19 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Primary invoice this payment applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_payments', to='finance.invoice'),
        ),
    ]
