# Generated by Django 6.0.2 on 2026-02-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='is_pos_enabled',
            field=models.BooleanField(default=False, help_text='Whether this account is available for POS transactions'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of this invoice', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='previous_invoice_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the previous invoice in the chain (ZATCA requirement)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale'), ('CONSIGNEE', 'Consignee'), ('STANDARD', 'Standard'), ('WHOLESALE', 'Wholesale'), ('CONSIGNEE', 'Consignee')], default='RETAIL', help_text='Sub-classification: Retail/Wholesale/Consignee (sales) or Standard/Wholesale/Consignee (purchase)', max_length=20),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='type',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash Drawer'), ('BANK', 'Bank Account'), ('MOBILE', 'Mobile Wallet'), ('PETTY_CASH', 'Petty Cash'), ('SAVINGS', 'Savings Account'), ('FOREIGN', 'Foreign Currency Account'), ('ESCROW', 'Escrow Account'), ('INVESTMENT', 'Investment Account')], max_length=50, null=True),
        ),
    ]
