# Generated by Django 6.0.2 on 2026-02-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_barcodesettings_is_enabled_barcodesettings_length_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscalperiod',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('FUTURE', 'Future')], default='OPEN', max_length=10),
        ),
    ]
