# Generated by Django 6.0.2 on 2026-02-25 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentryline',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
