# Generated by Django 6.0.2 on 2026-02-21 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_financialaccount_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_hash',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='previous_invoice_hash',
        ),
    ]
