# Generated by Django 6.0.4 on 2026-05-05 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_rename_bufferedreq_organiz_3f8ed5_idx_bufferedreq_tenant__076e1c_idx_and_more'),
        ('finance', '0003_template_numbering_rules'),
        ('inventory', '0008_rename_inv_ai_cr_org_cat_hash_idx_inventory_a_tenant__fc55bd_idx_and_more'),
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankstatement',
            new_name='bank_statem_organiz_5b3b8b_idx',
            old_name='bank_statem_tenant__6a76fc_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatement',
            new_name='bank_statem_organiz_19d2a6_idx',
            old_name='bank_statem_tenant__48f269_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatementline',
            new_name='bank_statem_organiz_2763f8_idx',
            old_name='bank_statem_tenant__4074b1_idx',
        ),
        migrations.RenameIndex(
            model_name='bankstatementline',
            new_name='bank_statem_organiz_b8ff9f_idx',
            old_name='bank_statem_tenant__d01167_idx',
        ),
        migrations.RenameIndex(
            model_name='reconciliationsession',
            new_name='reconciliat_organiz_3a1508_idx',
            old_name='reconciliat_tenant__9afff2_idx',
        ),
        migrations.RenameIndex(
            model_name='reconciliationsession',
            new_name='reconciliat_organiz_e03a69_idx',
            old_name='reconciliat_tenant__41c198_idx',
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='financedailysummary',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='finance_daily_summaries', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='reconciliationsession',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='taxratecategory',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['organization', 'is_active'], name='financialac_tenant__5b01d2_idx'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['organization', 'type'], name='financialac_tenant__30a3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['organization', 'is_pos_enabled'], name='financialac_tenant__3b1a83_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalperiod',
            index=models.Index(fields=['organization', 'status'], name='fiscalperio_tenant__171547_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalperiod',
            index=models.Index(fields=['organization', 'fiscal_year', 'status'], name='fiscalperio_tenant__be44b1_idx'),
        ),
    ]
