# Generated by Django 5.2.11 on 2026-02-26 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_journalentryline_employee_alter_taxgroup_rate_and_more'),
        ('inventory', '0005_alter_warehouse_unique_together_warehouse_address_and_more'),
    ]

    operations = [
        # Null out orphan site_id references before FK re-pointing
        migrations.RunSQL(
            sql="""
                UPDATE financialaccount SET site_id = NULL WHERE site_id IS NOT NULL AND site_id NOT IN (SELECT id FROM warehouse);
                UPDATE invoice SET site_id = NULL WHERE site_id IS NOT NULL AND site_id NOT IN (SELECT id FROM warehouse);
                UPDATE journalentry SET site_id = NULL WHERE site_id IS NOT NULL AND site_id NOT IN (SELECT id FROM warehouse);
                UPDATE transaction SET site_id = NULL WHERE site_id IS NOT NULL AND site_id NOT IN (SELECT id FROM warehouse);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
    ]
