# Generated by Django 6.0.2 on 2026-02-14 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_contact_linked_account_and_more'),
        ('erp', '0040_add_scope_pins_to_user'),
        ('finance', '0003_alter_fiscalperiod_options_fiscalperiod_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('change_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('POST', 'Post'), ('REVERSE', 'Reverse')], max_length=20)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'forensicauditlog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='financialevent',
            name='scope',
            field=models.CharField(default='OFFICIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='entry_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='scope',
            field=models.CharField(default='OFFICIAL', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('reference', 'organization')},
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['organization', 'transaction_date'], name='journalentr_organiz_5c542f_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['organization', 'scope'], name='journalentr_organiz_339014_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['organization', 'status'], name='journalentr_organiz_cdf611_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['reference'], name='journalentr_referen_762bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['organization', 'account'], name='journalentr_organiz_d847f4_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['journal_entry'], name='journalentr_journal_012f87_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['organization', 'debit', 'credit'], name='journalentr_organiz_ebb715_idx'),
        ),
        migrations.AddField(
            model_name='forensicauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forensicauditlog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddIndex(
            model_name='forensicauditlog',
            index=models.Index(fields=['organization', 'model_name', 'object_id'], name='forensicaud_organiz_15cd02_idx'),
        ),
        migrations.AddIndex(
            model_name='forensicauditlog',
            index=models.Index(fields=['organization', 'timestamp'], name='forensicaud_organiz_f6ab40_idx'),
        ),
    ]
