# Generated by Django 5.1.7 on 2026-02-16 11:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_contact_linked_account_and_more'),
        ('erp', '0043_transaction_lifecycle'),
        ('finance', '0004_forensicauditlog_financialevent_scope_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialevent',
            name='financial_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='finance.financialaccount'),
        ),
        migrations.AlterField(
            model_name='financialevent',
            name='event_type',
            field=models.CharField(choices=[('PARTNER_WITHDRAWAL', 'Partner Withdrawal'), ('PARTNER_INJECTION', 'Partner Injection'), ('CAPITAL_INJECTION', 'Capital Injection'), ('PARTNER_LOAN', 'Partner Loan'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('EXPENSE', 'Expense'), ('SALARY_PAYMENT', 'Salary Payment'), ('DEFERRED_EXPENSE_CREATION', 'Deferred Expense Creation'), ('DEFERRED_EXPENSE_RECOGNITION', 'Deferred Expense Recognition'), ('ASSET_ACQUISITION', 'Asset Acquisition'), ('ASSET_DEPRECIATION', 'Asset Depreciation'), ('ASSET_DISPOSAL', 'Asset Disposal')], max_length=50),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('VEHICLE', 'Vehicle'), ('EQUIPMENT', 'Equipment'), ('IT', 'IT Equipment'), ('FURNITURE', 'Furniture'), ('BUILDING', 'Building'), ('LAND', 'Land'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purchase_date', models.DateField()),
                ('useful_life_years', models.PositiveIntegerField(default=5)),
                ('residual_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('depreciation_method', models.CharField(choices=[('LINEAR', 'Straight Line'), ('DECLINING', 'Declining Balance')], default='LINEAR', max_length=20)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('scope', models.CharField(default='OFFICIAL', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISPOSED', 'Disposed'), ('WRITTEN_OFF', 'Written Off'), ('FULLY_DEPRECIATED', 'Fully Depreciated')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('accumulated_depreciation_coa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accumulated_depreciations', to='finance.chartofaccount')),
                ('asset_coa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='finance.chartofaccount')),
                ('depreciation_expense_coa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_expenses', to='finance.chartofaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('source_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_purchases', to='finance.financialaccount')),
            ],
            options={
                'db_table': 'asset',
            },
        ),
        migrations.CreateModel(
            name='AmortizationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_posted', models.BooleanField(default=False)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortization_lines', to='finance.asset')),
            ],
            options={
                'db_table': 'amortizationschedule',
                'ordering': ['period_date'],
            },
        ),
        migrations.CreateModel(
            name='DeferredExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('RENOVATION', 'Renovation'), ('ADVERTISING', 'Advertising'), ('INSURANCE', 'Insurance'), ('RENT_ADVANCE', 'Rent Advance'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField()),
                ('duration_months', models.PositiveIntegerField()),
                ('monthly_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('months_recognized', models.PositiveIntegerField(default=0)),
                ('scope', models.CharField(default='OFFICIAL', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deferred_coa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_assets', to='finance.chartofaccount')),
                ('expense_coa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_expenses', to='finance.chartofaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('source_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_sources', to='finance.financialaccount')),
            ],
            options={
                'db_table': 'deferredexpense',
            },
        ),
        migrations.CreateModel(
            name='DirectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('OFFICE_SUPPLIES', 'Office Supplies'), ('SALARIES', 'Salaries'), ('MAINTENANCE', 'Maintenance'), ('TRANSPORT', 'Transport'), ('TELECOM', 'Telecom'), ('PROFESSIONAL_FEES', 'Professional Fees'), ('TAXES_FEES', 'Taxes & Fees'), ('MARKETING', 'Marketing'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('scope', models.CharField(default='OFFICIAL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('expense_coa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_expenses', to='finance.chartofaccount')),
                ('financial_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_expenses', to='finance.financialevent')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_expenses', to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('source_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_expenses', to='finance.financialaccount')),
            ],
            options={
                'db_table': 'directexpense',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfitDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('distribution_date', models.DateField()),
                ('allocations', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_distributions', to='finance.fiscalyear')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'profitdistribution',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifecycle_status', models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked'), ('VERIFIED', 'Verified'), ('CONFIRMED', 'Confirmed')], default='OPEN', help_text='Current lifecycle stage', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('current_verification_level', models.IntegerField(default=0, help_text='How many verification levels have been completed')),
                ('voucher_type', models.CharField(choices=[('TRANSFER', 'Transfer Voucher'), ('RECEIPT', 'Receipt Voucher'), ('PAYMENT', 'Payment Voucher')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('scope', models.CharField(default='OFFICIAL', max_length=20)),
                ('is_posted', models.BooleanField(default=False, help_text='Whether the voucher has been posted to the ledger')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact')),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_in', to='finance.financialaccount')),
                ('financial_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='finance.financialevent')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('source_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_out', to='finance.financialaccount')),
            ],
            options={
                'db_table': 'voucher',
            },
        ),
        migrations.CreateModel(
            name='TaxGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate as percentage, e.g. 11.00 for 11%', max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'taxgroup',
                'ordering': ['-is_default', 'name'],
                'unique_together': {('name', 'organization')},
            },
        ),
    ]
