# Generated by Django 5.2.11 on 2026-03-01 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_financialaccount_site_alter_invoice_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialaccount',
            name='linked_coa',
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='ledger_account',
            field=models.ForeignKey(blank=True, db_column='ledger_account_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.chartofaccount'),
        ),
    ]
