# Generated by Django 5.1.7 on 2026-02-16 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_contact_linked_account_and_more'),
        ('erp', '0043_transaction_lifecycle'),
        ('finance', '0006_supplierbalance_customerbalance_payment'),
        ('pos', '0004_creditnote_purchasereturn_purchasereturnline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='credit_note',
            field=models.ForeignKey(blank=True, help_text='Linked credit note (for refunds)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='pos.creditnote'),
        ),
        migrations.AddField(
            model_name='payment',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_account',
            field=models.ForeignKey(help_text='Account used for payment', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sales_order',
            field=models.ForeignKey(blank=True, help_text='Linked sales order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to='pos.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='supplier_invoice',
            field=models.ForeignKey(blank=True, help_text='Linked purchase order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to='pos.order'),
        ),
        migrations.AddField(
            model_name='supplierbalance',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_balance', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='supplierbalance',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
    ]
