# Generated by Django 5.2.11 on 2026-03-02 20:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_seed_app_change_theme_permission'),
        ('finance', '0007_periodic_tax_accrual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterpartytaxprofile',
            name='airsi_subject',
            field=models.BooleanField(default=False, help_text='Buying from this supplier triggers AIRSI withholding'),
        ),
        migrations.AlterField(
            model_name='counterpartytaxprofile',
            name='allowed_scopes',
            field=models.JSONField(default=list, help_text='Scopes allowed when transacting with this counterparty'),
        ),
        migrations.AlterField(
            model_name='counterpartytaxprofile',
            name='country_code',
            field=models.CharField(default='CI', help_text='ISO country code of the counterparty', max_length=3),
        ),
        migrations.AlterField(
            model_name='counterpartytaxprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='counterpartytaxprofile',
            name='is_system_preset',
            field=models.BooleanField(default=False, help_text='True = created by system seed, shared across orgs'),
        ),
        migrations.AlterField(
            model_name='counterpartytaxprofile',
            name='name',
            field=models.CharField(help_text='e.g. "Assujetti TVA", "Non-Assujetti", "Foreign B2B"', max_length=150),
        ),
        migrations.AlterField(
            model_name='counterpartytaxprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='counterpartytaxprofile',
            name='reverse_charge',
            field=models.BooleanField(default=False, help_text='True for foreign B2B suppliers only — triggers autoliquidation. NOT for export; use Order.is_export for that.'),
        ),
        migrations.AlterField(
            model_name='counterpartytaxprofile',
            name='vat_registered',
            field=models.BooleanField(default=True, help_text='Supplier: do they charge VAT on their invoices? Client: are they VAT-registered (eligible for TVA Invoice)?'),
        ),
        migrations.AlterField(
            model_name='orgtaxpolicy',
            name='airsi_treatment',
            field=models.CharField(choices=[('CAPITALIZE', 'Capitalize into inventory cost'), ('RECOVER', 'Book as AIRSI Récupérable (offsets profit tax)'), ('EXPENSE', 'Expense to P&L')], default='CAPITALIZE', max_length=12),
        ),
        migrations.AlterField(
            model_name='orgtaxpolicy',
            name='allowed_scopes',
            field=models.JSONField(default=list, help_text='e.g. ["OFFICIAL"] or ["OFFICIAL","INTERNAL"]'),
        ),
        migrations.AlterField(
            model_name='orgtaxpolicy',
            name='country_code',
            field=models.CharField(default='CI', help_text='ISO 3166-1 alpha-2/3 country code', max_length=3),
        ),
        migrations.AlterField(
            model_name='orgtaxpolicy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orgtaxpolicy',
            name='internal_cost_mode',
            field=models.CharField(choices=[('TTC_ALWAYS', 'Internal scope always uses TTC as cost'), ('SAME_AS_OFFICIAL', 'Internal scope follows same recoverability as official'), ('CUSTOM', 'Custom logic (override in code)')], default='TTC_ALWAYS', max_length=20),
        ),
        migrations.AlterField(
            model_name='orgtaxpolicy',
            name='name',
            field=models.CharField(help_text='e.g. "Standard VAT Policy", "Micro Regime"', max_length=150),
        ),
        migrations.AlterField(
            model_name='orgtaxpolicy',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='orgtaxpolicy',
            name='periodic_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed periodic tax amount (forfait, minimum légal)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='orgtaxpolicy',
            name='profit_tax_mode',
            field=models.CharField(choices=[('STANDARD', 'Standard corporate tax'), ('FORFAIT', 'Fixed/forfait tax'), ('EXEMPT', 'Tax exempt')], default='STANDARD', max_length=10),
        ),
        migrations.AlterField(
            model_name='orgtaxpolicy',
            name='purchase_tax_mode',
            field=models.CharField(choices=[('CAPITALIZE', 'Add to inventory cost'), ('EXPENSE', 'Expense to P&L')], default='CAPITALIZE', max_length=12),
        ),
        migrations.AlterField(
            model_name='orgtaxpolicy',
            name='purchase_tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='e.g. 0.0200 for 2% purchase tax', max_digits=5),
        ),
        migrations.AlterField(
            model_name='orgtaxpolicy',
            name='sales_tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='orgtaxpolicy',
            name='sales_tax_trigger',
            field=models.CharField(choices=[('ON_TURNOVER', 'Percentage of total revenue (period)'), ('ON_PROFIT', 'Percentage of gross profit (period)')], default='ON_TURNOVER', max_length=12),
        ),
        migrations.AlterField(
            model_name='orgtaxpolicy',
            name='vat_input_recoverability',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='0.000=none, 0.500=50%, 1.000=fully refundable', max_digits=4),
        ),
        migrations.AlterField(
            model_name='orgtaxpolicy',
            name='vat_output_enabled',
            field=models.BooleanField(default=True, help_text='True = you charge VAT on OFFICIAL scope sales'),
        ),
        migrations.AlterField(
            model_name='periodictaxaccrual',
            name='accrual_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='periodictaxaccrual',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Revenue or Profit base used for calculation', max_digits=15),
        ),
        migrations.AlterField(
            model_name='periodictaxaccrual',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='periodictaxaccrual',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='periodictaxaccrual',
            name='policy_name',
            field=models.CharField(blank=True, help_text='Name of OrgTaxPolicy at accrual time', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='periodictaxaccrual',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Rate applied (0 for FORFAIT)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='periodictaxaccrual',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft — not yet posted'), ('POSTED', 'Posted — journal entry created'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='periodictaxaccrual',
            name='tax_type',
            field=models.CharField(choices=[('TURNOVER', 'Turnover / Sales Tax (% of revenue)'), ('PROFIT', 'Profit Tax (% of gross profit)'), ('FORFAIT', 'Fixed Forfait / Minimum')], max_length=10),
        ),
    ]
