# Generated by Django 6.0.2 on 2026-03-03 00:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_seed_app_change_theme_permission'),
        ('finance', '0008_alter_counterpartytaxprofile_airsi_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the custom tax (e.g., Eco Tax)', max_length=150)),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase Only'), ('SALE', 'Sale Only'), ('BOTH', 'Purchases & Sales')], default='BOTH', max_length=20)),
                ('math_behavior', models.CharField(choices=[('ADDED_TO_TTC', 'Add to Invoice (like Sales Tax)'), ('WITHHELD_FROM_AP', 'Withhold from Counterparty (like AIRSI)')], default='ADDED_TO_TTC', max_length=20)),
                ('purchase_cost_treatment', models.CharField(choices=[('CAPITALIZE', 'Add to Inventory Base Cost'), ('EXPENSE', 'Expense immediately to P&L')], default='EXPENSE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('expense_account', models.ForeignKey(blank=True, help_text='COA to debit if purchase_cost_treatment = EXPENSE.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_tax_expenses', to='finance.chartofaccount')),
                ('liability_account', models.ForeignKey(blank=True, help_text='COA to credit when collecting tax on sales or withholding it on purchases.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_tax_liabilities', to='finance.chartofaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'finance_customtaxrule',
                'ordering': ['name'],
            },
        ),
    ]
