# Generated by Django 6.0.2 on 2026-03-03 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_seed_app_change_theme_permission'),
        ('finance', '0009_customtaxrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scope', models.CharField(default='OFFICIAL', max_length=10)),
                ('vat_collected', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('vat_recoverable', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('net_vat_due', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('airsi_withheld', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('custom_tax_total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('reverse_charge_total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('purchase_tax_total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('rebuilt_at', models.DateTimeField(auto_now=True)),
                ('order_line_count', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_daily_summaries', to='erp.organization')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['organization', 'date', 'scope'], name='fin_daily_org_date_scope_idx')],
                'unique_together': {('organization', 'date', 'scope')},
            },
        ),
    ]
