# Generated by Django 6.0.2 on 2026-03-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_gap10_finance_daily_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgtaxpolicy',
            name='internal_sales_vat_mode',
            field=models.CharField(choices=[('NONE', 'No VAT — totals are HT only'), ('DISPLAY_ONLY', 'Show VAT in UI, but no statutory liability in ledger')], default='NONE', help_text='NONE: INTERNAL sales totals are HT only. DISPLAY_ONLY: VAT shown in UI but never posted as a statutory liability.', max_length=15),
        ),
        migrations.AddField(
            model_name='orgtaxpolicy',
            name='internal_vat_treatment',
            field=models.CharField(choices=[('RECOVERABLE', 'Recoverable / Standard'), ('CAPITALIZE', 'Capitalize into cost (Expense/Asset)'), ('EXPENSE', 'Expense to P&L')], default='CAPITALIZE', help_text='How VAT is treated on internal purchases (default: CAPITALIZE)', max_length=15),
        ),
        migrations.AddField(
            model_name='orgtaxpolicy',
            name='official_vat_treatment',
            field=models.CharField(choices=[('RECOVERABLE', 'Recoverable / Standard'), ('CAPITALIZE', 'Capitalize into cost (Expense/Asset)'), ('EXPENSE', 'Expense to P&L')], default='RECOVERABLE', help_text='How VAT is treated on official purchases (default: RECOVERABLE)', max_length=15),
        ),
    ]
