# Generated by Django 6.0.2 on 2026-03-06 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_contact_supplier_vat_regime_and_more'),
        ('erp', '0013_approvalpolicy_approvalpolicystep_txnapproval'),
        ('finance', '0014_invoice_current_verification_level_and_more'),
        ('inventory', '0012_remove_brand_unique_brand_name_org_and_more'),
        ('pos', '0049_landedcost_landedcostline_purchaseattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Add 'tenant' field to all models first
        migrations.AddField(
            model_name='amortizationschedule',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='customerbalance',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='deferredexpense',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='supplierbalance',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='erp.organization'),
        ),

        # 2. Now constraints and indexes can use 'tenant'
        migrations.AlterUniqueTogether(
            name='customerbalance',
            unique_together={('contact', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='supplierbalance',
            unique_together={('contact', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'status'], name='invoice_tenant__622a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'type'], name='invoice_tenant__5ad5ff_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'contact'], name='invoice_tenant__54699b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'due_date'], name='invoice_tenant__e6fe4b_idx'),
        ),

        # 3. Cleanup old indexes and fields
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_organiz_b92a54_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_organiz_4066d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_organiz_1dbfd3_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_organiz_c15765_idx',
        ),
        migrations.RemoveField(
            model_name='amortizationschedule',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='customerbalance',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='deferredexpense',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='directexpense',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='paymentallocation',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='supplierbalance',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='organization',
        ),

        # 4. Lifecycle fields and other fixes
        migrations.RenameField(
            model_name='voucher',
            old_name='is_posted',
            new_name='is_locked',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='current_verification_level',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='lifecycle_status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='policy_snapshot',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='required_levels_frozen',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='current_verification_level',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='lifecycle_status',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='policy_snapshot',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='required_levels_frozen',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='current_verification_level',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='lifecycle_status',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='policy_snapshot',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='required_levels_frozen',
        ),

        migrations.AddField(
            model_name='directexpense',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_locked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='finance.directexpense'),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='finance.voucher'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('LOCKED', 'Locked'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='voucher',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='directexpense',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('LOCKED', 'Locked'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_locked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('LOCKED', 'Locked'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_locked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('LOCKED', 'Locked'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_locked', to=settings.AUTH_USER_MODEL),
        ),
    ]
