# Generated by Django 5.2.11 on 2026-03-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_exchangerate'),
        ('finance', '0015_remove_invoice_invoice_organiz_b92a54_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionsequence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='transactionsequence',
            name='scope',
            field=models.CharField(choices=[('OFFICIAL', 'Official'), ('INTERNAL', 'Internal')], default='OFFICIAL', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='transactionsequence',
            unique_together={('type', 'organization', 'scope')},
        ),
    ]
