# Generated by Django 5.2.11 on 2026-03-09 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_remove_user_driver_scope_delete_exchangerate'),
        ('finance', '0016_alter_transactionsequence_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionsequence',
            unique_together={('type', 'organization')},
        ),
        migrations.RemoveField(
            model_name='transactionsequence',
            name='scope',
        ),
    ]
