# Generated by Django 6.0.2 on 2026-03-10 21:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_paymentterm'),
        ('finance', '0019_postable_journal_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(choices=[('ORIGINAL', 'Original Budget'), ('REVISED', 'Revised Budget'), ('FORECAST', 'Forecast')], default='ORIGINAL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('scope', models.CharField(default='OFFICIAL', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='finance.fiscalyear')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'finance_budget',
                'ordering': ['-fiscal_year__start_date', 'version'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_center', models.CharField(blank=True, help_text='Optional cost center for departmental budgets', max_length=50, null=True)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Planned amount for this account/period', max_digits=15)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual amount from posted JEs — refreshed periodically', max_digits=15)),
                ('committed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Committed but not yet posted (POs, requisitions)', max_digits=15)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Budget - Actual (positive = under budget)', max_digits=15)),
                ('variance_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Variance as percentage of budget', max_digits=8)),
                ('available_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Budget - Actual - Committed', max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.chartofaccount')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.budget')),
                ('fiscal_period', models.ForeignKey(blank=True, help_text='Null = annual budget (not broken down by period)', null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.fiscalperiod')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'finance_budget_line',
            },
        ),
        migrations.CreateModel(
            name='ConsolidationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_currency', models.CharField(default='XOF', help_text='Reporting currency of the consolidated group', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'finance_consolidation_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConsolidationEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Parent ownership percentage (0-100)', max_digits=5)),
                ('method', models.CharField(choices=[('FULL', 'Full Consolidation'), ('PROPORTIONAL', 'Proportional Consolidation'), ('EQUITY', 'Equity Method'), ('EXCLUDED', 'Excluded')], default='FULL', max_length=20)),
                ('functional_currency', models.CharField(blank=True, help_text='Functional currency of this entity', max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entity_organization', models.ForeignKey(help_text='The subsidiary organization', on_delete=django.db.models.deletion.CASCADE, related_name='consolidation_memberships', to='erp.organization')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='finance.consolidationgroup')),
            ],
            options={
                'db_table': 'finance_consolidation_entity',
            },
        ),
        migrations.CreateModel(
            name='ConsolidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('entities_processed', models.PositiveIntegerField(default=0)),
                ('eliminations_applied', models.PositiveIntegerField(default=0)),
                ('fx_adjustments_applied', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidation_runs_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.fiscalperiod')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='finance.consolidationgroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'finance_consolidation_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsolidationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('ENTITY', 'Entity Balance'), ('ELIMINATION', 'IC Elimination'), ('FX_TRANSLATION', 'Currency Translation'), ('ADJUSTMENT', 'Manual Adjustment')], default='ENTITY', max_length=20)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('debit_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Debit in group reporting currency', max_digits=15)),
                ('credit_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit in group reporting currency', max_digits=15)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=10, help_text='Rate used for currency translation', max_digits=18, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.chartofaccount')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.consolidationentity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.consolidationrun')),
            ],
            options={
                'db_table': 'finance_consolidation_line',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 4217 code, e.g. USD, EUR, XOF', max_length=10)),
                ('name', models.CharField(help_text='Currency name, e.g. US Dollar', max_length=100)),
                ('symbol', models.CharField(default='$', max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('is_base', models.BooleanField(default=False, help_text='Functional/base currency for this organization')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'finance_currency',
                'ordering': ['-is_base', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRevaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revaluation_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20)),
                ('scope', models.CharField(default='OFFICIAL', max_length=20)),
                ('total_gain', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_impact', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('accounts_processed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_revaluations', to=settings.AUTH_USER_MODEL)),
                ('fiscal_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revaluations', to='finance.fiscalperiod')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revaluation_source', to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'finance_currency_revaluation',
                'ordering': ['-revaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRevaluationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_in_currency', models.DecimalField(decimal_places=2, help_text='Account balance in foreign currency', max_digits=15)),
                ('old_rate', models.DecimalField(decimal_places=10, help_text='Rate at which the balance was originally booked (average)', max_digits=18)),
                ('new_rate', models.DecimalField(decimal_places=10, help_text='Period-end closing rate', max_digits=18)),
                ('old_base_amount', models.DecimalField(decimal_places=2, help_text='Balance in base currency at old rate', max_digits=15)),
                ('new_base_amount', models.DecimalField(decimal_places=2, help_text='Balance in base currency at new rate', max_digits=15)),
                ('difference', models.DecimalField(decimal_places=2, help_text='Unrealized gain (+) or loss (-) in base currency', max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.chartofaccount')),
                ('currency', models.ForeignKey(help_text='Foreign currency of this account', on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('revaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.currencyrevaluation')),
            ],
            options={
                'db_table': 'finance_currency_revaluation_line',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=10, help_text='1 unit of from_currency = rate units of to_currency', max_digits=18)),
                ('rate_type', models.CharField(choices=[('SPOT', 'Spot Rate'), ('AVERAGE', 'Monthly Average'), ('CLOSING', 'Period Closing Rate'), ('BUDGET', 'Budget Rate')], default='SPOT', max_length=20)),
                ('effective_date', models.DateField(db_index=True)),
                ('source', models.CharField(blank=True, help_text='Rate source: MANUAL, ECB, BCEAO, IMPORT', max_length=50, null=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='finance.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='finance.currency')),
            ],
            options={
                'db_table': 'finance_exchange_rate',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='IntercompanyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elimination_type', models.CharField(choices=[('REVENUE_EXPENSE', 'Revenue & Expense Elimination'), ('RECEIVABLE_PAYABLE', 'Receivable & Payable Elimination'), ('INVESTMENT_EQUITY', 'Investment & Equity Elimination'), ('DIVIDEND', 'Dividend Elimination'), ('UNREALIZED_PROFIT', 'Unrealized Profit Elimination')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('account_a', models.ForeignKey(help_text='Account to eliminate in entity A', on_delete=django.db.models.deletion.PROTECT, related_name='ic_elimination_a', to='finance.chartofaccount')),
                ('account_b', models.ForeignKey(help_text='Offsetting account in entity B', on_delete=django.db.models.deletion.PROTECT, related_name='ic_elimination_b', to='finance.chartofaccount')),
                ('entity_a', models.ForeignKey(help_text='First entity in the intercompany pair', on_delete=django.db.models.deletion.CASCADE, related_name='ic_rules_as_a', to='finance.consolidationentity')),
                ('entity_b', models.ForeignKey(help_text='Second entity in the intercompany pair', on_delete=django.db.models.deletion.CASCADE, related_name='ic_rules_as_b', to='finance.consolidationentity')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercompany_rules', to='finance.consolidationgroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'finance_intercompany_rule',
            },
        ),
        migrations.CreateModel(
            name='RecurringJournalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('journal_type', models.CharField(default='GENERAL', max_length=20)),
                ('scope', models.CharField(default='OFFICIAL', max_length=20)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMI_ANNUAL', 'Semi-Annual'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateField(help_text='First occurrence date')),
                ('end_date', models.DateField(blank=True, help_text='Last occurrence (null = no end)', null=True)),
                ('next_run_date', models.DateField(blank=True, help_text='Next scheduled generation', null=True)),
                ('total_occurrences', models.PositiveIntegerField(blank=True, help_text='Max occurrences (null = unlimited until end_date)', null=True)),
                ('occurrences_created', models.PositiveIntegerField(default=0)),
                ('auto_post', models.BooleanField(default=False, help_text='If True, generated entries are posted immediately (no DRAFT stage)')),
                ('notify_on_creation', models.BooleanField(default=True, help_text='Send notification when a recurring entry is generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_journals_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'db_table': 'finance_recurring_journal_template',
                'ordering': ['next_run_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurringJournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_type', models.CharField(blank=True, max_length=20, null=True)),
                ('partner_id', models.IntegerField(blank=True, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=50, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.chartofaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.recurringjournaltemplate')),
            ],
            options={
                'db_table': 'finance_recurring_journal_line',
            },
        ),
        migrations.CreateModel(
            name='RecurringJournalExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateField()),
                ('occurrence_number', models.PositiveIntegerField()),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_source', to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='finance.recurringjournaltemplate')),
            ],
            options={
                'db_table': 'finance_recurring_journal_execution',
                'ordering': ['-execution_date'],
            },
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['organization', 'fiscal_year', 'status'], name='finance_bud_organiz_3e6611_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('organization', 'fiscal_year', 'version')},
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['budget', 'account'], name='finance_bud_budget__816b22_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['budget', 'fiscal_period'], name='finance_bud_budget__546370_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['budget', 'cost_center'], name='finance_bud_budget__036559_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consolidationentity',
            unique_together={('group', 'entity_organization')},
        ),
        migrations.AddIndex(
            model_name='consolidationrun',
            index=models.Index(fields=['group', 'fiscal_period'], name='finance_con_group_i_29f039_idx'),
        ),
        migrations.AddIndex(
            model_name='consolidationline',
            index=models.Index(fields=['run', 'account'], name='finance_con_run_id_f17fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='consolidationline',
            index=models.Index(fields=['run', 'entity'], name='finance_con_run_id_98e531_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='currencyrevaluation',
            index=models.Index(fields=['organization', 'fiscal_period'], name='finance_cur_organiz_ab65da_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['organization', 'from_currency', 'to_currency', 'effective_date'], name='finance_exc_organiz_2b0a91_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('organization', 'from_currency', 'to_currency', 'effective_date', 'rate_type')},
        ),
        migrations.AddIndex(
            model_name='intercompanyrule',
            index=models.Index(fields=['group', 'elimination_type'], name='finance_int_group_i_8b7bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringjournaltemplate',
            index=models.Index(fields=['organization', 'status'], name='finance_rec_organiz_c86bac_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringjournaltemplate',
            index=models.Index(fields=['next_run_date'], name='finance_rec_next_ru_212ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringjournalexecution',
            index=models.Index(fields=['template', 'execution_date'], name='finance_rec_templat_1860c1_idx'),
        ),
    ]
