# Generated by Django 5.2.11 on 2026-03-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_chartofaccount_financial_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterpartytaxprofile',
            name='enforce_compliance',
            field=models.BooleanField(default=False, help_text='If True, block transactions if required documents are missing or expired'),
        ),
        migrations.AddField(
            model_name='counterpartytaxprofile',
            name='required_documents',
            field=models.JSONField(blank=True, default=list, help_text='List of required document types (e.g. ["NCC", "RCCM", "DFE"])'),
        ),
    ]
