# Generated by Django 5.2.12 on 2026-03-11 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_alter_approvalrule_organization_and_more'),
        ('finance', '0022_counterpartytaxprofile_enforce_compliance_and_more'),
    ]

    operations = [
        # ZATCAConfig was created outside the normal migration flow.
        # This SeparateDatabaseAndState registers it in the migration state
        # so subsequent AlterField operations can reference it.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ZATCAConfig',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                        ('vat_registration_number', models.CharField(max_length=15)),
                        ('seller_name', models.CharField(max_length=255)),
                        ('certificate_pem', models.TextField(blank=True, null=True)),
                        ('private_key_pem', models.TextField(blank=True, null=True)),
                        ('csr_request_id', models.CharField(blank=True, max_length=255, null=True)),
                        ('compliance_certificate_pem', models.TextField(blank=True, null=True)),
                        ('production_certificate_pem', models.TextField(blank=True, null=True)),
                        ('is_sandbox', models.BooleanField(default=True)),
                        ('is_active', models.BooleanField(default=False)),
                        ('last_invoice_hash', models.CharField(default='0' * 64, max_length=64)),
                        ('invoice_counter', models.IntegerField(default=0)),
                        ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                        ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                    ],
                    options={'db_table': 'zatca_config'},
                ),
            ],
            database_operations=[],  # Table already exists in DB
        ),
        migrations.RenameIndex(
            model_name='accountbalancesnapshot',
            new_name='account_bal_organization__c281f2_idx',
            old_name='account_bal_organiz_54abac_idx',
        ),
        migrations.RenameIndex(
            model_name='accountbalancesnapshot',
            new_name='account_bal_organization__a38ba6_idx',
            old_name='account_bal_organiz_1d029d_idx',
        ),
        migrations.RenameIndex(
            model_name='budget',
            new_name='finance_bud_organization__cc5c16_idx',
            old_name='finance_bud_organiz_3e6611_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='chartofacco_organization__9dbbcd_idx',
            old_name='chartofacco_organiz_8a6b47_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='chartofacco_organization__f942bd_idx',
            old_name='chartofacco_organiz_b882b3_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='chartofacco_organization__425576_idx',
            old_name='chartofacco_organiz_8b07f0_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='chartofacco_organization__0ff896_idx',
            old_name='chartofacco_organiz_af93d7_idx',
        ),
        migrations.RenameIndex(
            model_name='currencyrevaluation',
            new_name='finance_cur_organization__f78f72_idx',
            old_name='finance_cur_organiz_ab65da_idx',
        ),
        migrations.RenameIndex(
            model_name='exchangerate',
            new_name='finance_exc_organization__509586_idx',
            old_name='finance_exc_organiz_2b0a91_idx',
        ),
        migrations.RenameIndex(
            model_name='forensicauditlog',
            new_name='forensicaud_organization__e91fcc_idx',
            old_name='forensicaud_organiz_15cd02_idx',
        ),
        migrations.RenameIndex(
            model_name='forensicauditlog',
            new_name='forensicaud_organization__a96361_idx',
            old_name='forensicaud_organiz_f6ab40_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='journalentr_organization__8a56b4_idx',
            old_name='journalentr_organiz_5c542f_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='journalentr_organization__2aaed0_idx',
            old_name='journalentr_organiz_339014_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='journalentr_organization__1f43db_idx',
            old_name='journalentr_organiz_cdf611_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentryline',
            new_name='journalentr_organization__655ba8_idx',
            old_name='journalentr_organiz_d847f4_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentryline',
            new_name='journalentr_organization__d96f42_idx',
            old_name='journalentr_organiz_ebb715_idx',
        ),
        migrations.RenameIndex(
            model_name='openingbalance',
            new_name='opening_bal_organization__e1cf48_idx',
            old_name='opening_bal_organiz_f2c4ba_idx',
        ),
        migrations.RenameIndex(
            model_name='reconciliationmatch',
            new_name='reconciliat_organization__d70831_idx',
            old_name='reconciliat_organiz_2f6525_idx',
        ),
        migrations.RenameIndex(
            model_name='reconciliationmatch',
            new_name='reconciliat_organization__0a19cf_idx',
            old_name='reconciliat_organiz_dee980_idx',
        ),
        migrations.RenameIndex(
            model_name='recurringjournaltemplate',
            new_name='finance_rec_organization__d7d68e_idx',
            old_name='finance_rec_organiz_c86bac_idx',
        ),
        migrations.AlterField(
            model_name='accountbalancesnapshot',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='barcodesettings',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='consolidationentity',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='consolidationgroup',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='consolidationline',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='consolidationrun',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='counterpartytaxprofile',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='currencyrevaluation',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='currencyrevaluationline',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='customtaxrule',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='financialevent',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='fiscalperiod',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='forensicauditlog',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='gatewayconfig',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='intercompanyrule',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='loaninstallment',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='openingbalance',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='orgtaxpolicy',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='periodictaxaccrual',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='reconciliationline',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='reconciliationmatch',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='recurringjournalexecution',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='recurringjournalline',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='recurringjournaltemplate',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='reportdefinition',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='reportexecution',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='transactionsequence',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='zatcaconfig',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_legacy_set', to='erp.organization'),
        ),
    ]
