# Generated by Django 6.0.3 on 2026-04-02 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_tax_engine_phase1'),
        ('erp', '0025_rename_erp_auditlo_organization__3bae30_idx_erp_auditlo_tenant__3bae30_idx_and_more'),
        ('finance', '0047_tax_engine_phase1'),
        ('pos', '0075_tax_engine_phase1'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePaymentVAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(decimal_places=2, help_text='Gross deposit amount received (TTC)', max_digits=15)),
                ('deposit_ht', models.DecimalField(decimal_places=2, default=0, help_text='Deposit amount excluding VAT', max_digits=15)),
                ('vat_rate', models.DecimalField(decimal_places=4, help_text='VAT rate applicable', max_digits=7)),
                ('vat_amount', models.DecimalField(decimal_places=2, help_text='VAT due on the deposit', max_digits=15)),
                ('currency_code', models.CharField(default='XOF', max_length=3)),
                ('deposit_date', models.DateField(help_text='Date deposit was received')),
                ('invoice_date', models.DateField(blank=True, help_text='Date final invoice was issued', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Deposit received — VAT not yet declared'), ('VAT_DECLARED', 'VAT declared on deposit'), ('INVOICED', 'Invoice issued — VAT adjusted'), ('CANCELLED', 'Deposit cancelled/refunded')], default='PENDING', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('adjustment_journal', models.ForeignKey(blank=True, help_text='JE for adjustment when invoice is issued', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_adjustment_entries', to='finance.journalentry')),
                ('contact', models.ForeignKey(help_text='Customer who made the deposit', on_delete=django.db.models.deletion.PROTECT, related_name='advance_payment_vat', to='crm.contact')),
                ('deposit_journal', models.ForeignKey(blank=True, help_text='JE for deposit VAT declaration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_deposit_entries', to='finance.journalentry')),
                ('invoice', models.ForeignKey(blank=True, help_text='The final invoice that supersedes deposit VAT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_vat_records', to='finance.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('payment', models.ForeignKey(blank=True, help_text='The advance payment that triggered VAT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_vat_records', to='finance.payment')),
            ],
            options={
                'verbose_name': 'Advance Payment VAT',
                'db_table': 'advance_payment_vat',
                'ordering': ['-deposit_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteVATReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reversal_type', models.CharField(choices=[('FULL', 'Full credit — entire invoice reversed'), ('PARTIAL', 'Partial credit — specific lines or amounts'), ('CORRECTION', 'Correction — original invoice had errors'), ('DISCOUNT', 'Post-sale discount or rebate')], default='FULL', max_length=12)),
                ('original_vat_amount', models.DecimalField(decimal_places=2, help_text='VAT on the original invoice', max_digits=15)),
                ('reversed_vat_amount', models.DecimalField(decimal_places=2, help_text='VAT being reversed by this credit note', max_digits=15)),
                ('credit_amount_ht', models.DecimalField(decimal_places=2, help_text='Credit note amount excluding VAT', max_digits=15)),
                ('vat_rate', models.DecimalField(decimal_places=4, help_text='VAT rate', max_digits=7)),
                ('currency_code', models.CharField(default='XOF', max_length=3)),
                ('is_output_adjustment', models.BooleanField(default=True, help_text='True = reduces output VAT (seller), False = reduces input VAT (buyer)')),
                ('vat_return_period', models.CharField(blank=True, default='', help_text='VAT return period this reversal will be included in (YYYY-MM/YYYY-QN)', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('credit_note', models.ForeignKey(blank=True, help_text='The credit note document', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vat_reversals', to='pos.creditnote')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_note_vat_reversals', to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('original_invoice', models.ForeignKey(help_text='The original invoice being credited', on_delete=django.db.models.deletion.PROTECT, related_name='vat_reversals', to='finance.invoice')),
            ],
            options={
                'verbose_name': 'Credit Note VAT Reversal',
                'db_table': 'credit_note_vat_reversal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftSampleVAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_date', models.DateField(help_text='Date of gift/sample')),
                ('gift_type', models.CharField(choices=[('GIFT', 'Business gift to client/partner'), ('SAMPLE', 'Product sample'), ('PROMOTIONAL', 'Promotional item'), ('EMPLOYEE', 'Employee gift/perk'), ('CHARITY', 'Charitable donation (in kind)')], default='GIFT', max_length=16)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('recipient_name', models.CharField(blank=True, default='', help_text='Name if not a CRM contact', max_length=200)),
                ('cost_value', models.DecimalField(decimal_places=2, default=0, help_text='Cost/book value of items gifted', max_digits=15)),
                ('market_value', models.DecimalField(decimal_places=2, default=0, help_text='Fair market value (used for VAT base if required)', max_digits=15)),
                ('cumulative_value_ytd', models.DecimalField(decimal_places=2, default=0, help_text='Year-to-date cumulative gift value to this recipient', max_digits=15)),
                ('threshold', models.DecimalField(decimal_places=2, default=0, help_text='Country threshold for gift VAT', max_digits=15)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, help_text='Output VAT due (if above threshold)', max_digits=15)),
                ('currency_code', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('BELOW_THRESHOLD', 'Below threshold — no VAT'), ('VAT_DUE', 'Above threshold — VAT assessed'), ('DECLARED', 'VAT included in return')], default='BELOW_THRESHOLD', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_sample_vat_entries', to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
                ('recipient_contact', models.ForeignKey(blank=True, help_text='Contact who received the gift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_gifts_vat', to='crm.contact')),
            ],
            options={
                'verbose_name': 'Gift/Sample VAT',
                'db_table': 'gift_sample_vat',
                'ordering': ['-gift_date'],
            },
        ),
        migrations.CreateModel(
            name='SelfSupplyVATEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(help_text='Date of self-supply event')),
                ('trigger_type', models.CharField(choices=[('INTERNAL_USE', 'Internal consumption'), ('EMPLOYEE_BENEFIT', 'Employee benefit/gift'), ('CROSS_BRANCH', 'Cross-branch (different VAT regime)'), ('EXEMPT_PROJECT', 'Used on VAT-exempt project'), ('MARKETING', 'Marketing/promotional use'), ('OTHER', 'Other')], default='INTERNAL_USE', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('cost_value', models.DecimalField(decimal_places=2, default=0, help_text='Cost/book value of goods used', max_digits=15)),
                ('fair_market_value', models.DecimalField(decimal_places=2, default=0, help_text='Fair market value for VAT assessment (if > threshold)', max_digits=15)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=0, help_text='VAT rate applied on self-supply', max_digits=7)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, help_text='Output VAT amount due on self-supply', max_digits=15)),
                ('currency_code', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending assessment'), ('ASSESSED', 'VAT assessed'), ('DECLARED', 'Included in VAT return'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Journal entry recording the output VAT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_supply_events', to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
            options={
                'verbose_name': 'Self-Supply VAT Event',
                'db_table': 'self_supply_vat_event',
                'ordering': ['-event_date'],
            },
        ),
    ]
