# Generated by Django 6.0.3 on 2026-04-07 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_tax_engine_phase1'),
        ('erp', '0026_einvoice_standard'),
        ('finance', '0050_countrytaxtemplate_custom_tax_rule_presets'),
        ('inventory', '0050_einvoice_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoiceStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code (e.g. ZATCA, UBL_PEPPOL, FACTUR_X)', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Display name (e.g. "ZATCA FATOORA (Saudi Arabia)")', max_length=120)),
                ('description', models.TextField(blank=True, default='', help_text='When and why this standard is used')),
                ('region', models.CharField(blank=True, default='', help_text='Geographic region or country (e.g. "European Union", "Saudi Arabia")', max_length=100)),
                ('invoice_format', models.CharField(choices=[('XML', 'XML (UBL / CII)'), ('JSON', 'JSON'), ('PDF_A3', 'PDF/A-3 (Factur-X / ZUGFeRD)'), ('HYBRID', 'Hybrid (XML embedded in PDF)')], default='XML', help_text='Primary document format for this standard', max_length=20)),
                ('schema_version', models.CharField(blank=True, default='', help_text='Schema version (e.g. "UBL 2.1", "ZATCA Phase 2")', max_length=30)),
                ('required_credentials', models.JSONField(blank=True, default=list, help_text='JSON array of credential field definitions tenants must fill')),
                ('branding_fields', models.JSONField(blank=True, default=list, help_text='JSON array of branding field definitions tenants can customize')),
                ('setup_guide', models.TextField(blank=True, default='', help_text='Step-by-step instructions for tenant onboarding (markdown)')),
                ('portal_url', models.URLField(blank=True, default='', help_text='Official portal URL for registration')),
                ('documentation_url', models.URLField(blank=True, default='', help_text='Link to official API/standard documentation')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'E-Invoice Standard',
                'verbose_name_plural': 'E-Invoice Standards',
                'db_table': 'einvoice_standard',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GiftSampleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_date', models.DateField(help_text='Date of gift/sample')),
                ('gift_type', models.CharField(choices=[('GIFT', 'Business gift to client/partner'), ('SAMPLE', 'Product sample'), ('PROMOTIONAL', 'Promotional item'), ('EMPLOYEE', 'Employee gift/perk'), ('CHARITY', 'Charitable donation (in kind)')], default='GIFT', max_length=16)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('recipient_name', models.CharField(blank=True, default='', help_text='Name if not a CRM contact', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, help_text='Quantity of items gifted', max_digits=15)),
                ('cost_value', models.DecimalField(decimal_places=2, default=0, help_text='Cost/book value of items gifted', max_digits=15)),
                ('market_value', models.DecimalField(decimal_places=2, default=0, help_text='Fair market value (used for VAT base if required)', max_digits=15)),
                ('cumulative_value_ytd', models.DecimalField(decimal_places=2, default=0, help_text='Year-to-date cumulative gift value to this recipient', max_digits=15)),
                ('threshold', models.DecimalField(decimal_places=2, default=0, help_text='Country threshold for gift VAT', max_digits=15)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, help_text='Output VAT due (if above threshold)', max_digits=15)),
                ('currency_code', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('BELOW_THRESHOLD', 'Below threshold — no VAT'), ('VAT_DUE', 'Above threshold — VAT assessed'), ('DECLARED', 'VAT included in return')], default='BELOW_THRESHOLD', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Gift/Sample Event',
                'db_table': 'gift_sample_vat',
                'ordering': ['-gift_date'],
            },
        ),
        migrations.CreateModel(
            name='InternalConsumptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(help_text='Date of internal consumption event')),
                ('trigger_type', models.CharField(choices=[('INTERNAL_USE', 'Internal consumption'), ('EMPLOYEE_BENEFIT', 'Employee benefit/gift'), ('CROSS_BRANCH', 'Cross-branch (different VAT regime)'), ('EXEMPT_PROJECT', 'Used on VAT-exempt project'), ('MARKETING', 'Marketing/promotional use'), ('OTHER', 'Other')], default='INTERNAL_USE', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, help_text='Quantity consumed', max_digits=15)),
                ('department', models.CharField(blank=True, default='', help_text='Department or cost center consuming the goods', max_length=200)),
                ('cost_value', models.DecimalField(decimal_places=2, default=0, help_text='Cost/book value of goods used', max_digits=15)),
                ('fair_market_value', models.DecimalField(decimal_places=2, default=0, help_text='Fair market value for VAT assessment (if > threshold)', max_digits=15)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=0, help_text='VAT rate applied on self-supply', max_digits=7)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, help_text='Output VAT amount due on self-supply', max_digits=15)),
                ('currency_code', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending assessment'), ('ASSESSED', 'VAT assessed'), ('DECLARED', 'Included in VAT return'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Internal Consumption Event',
                'db_table': 'self_supply_vat_event',
                'ordering': ['-event_date'],
            },
        ),
        migrations.RemoveField(
            model_name='giftsamplevat',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='giftsamplevat',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='giftsamplevat',
            name='recipient_contact',
        ),
        migrations.RemoveField(
            model_name='selfsupplyvatevent',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='selfsupplyvatevent',
            name='organization',
        ),
        migrations.AlterModelOptions(
            name='intrabranchvattransfer',
            options={'ordering': ['-transfer_date'], 'verbose_name': 'Intra-Branch VAT Transfer (DEPRECATED)'},
        ),
        migrations.RenameIndex(
            model_name='accountbalancesnapshot',
            new_name='account_bal_tenant__c281f2_idx',
            old_name='account_bal_organiz_54abac_idx',
        ),
        migrations.RenameIndex(
            model_name='accountbalancesnapshot',
            new_name='account_bal_tenant__a38ba6_idx',
            old_name='account_bal_organiz_1d029d_idx',
        ),
        migrations.RenameIndex(
            model_name='budget',
            new_name='finance_bud_tenant__cc5c16_idx',
            old_name='finance_bud_organiz_3e6611_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='chartofacco_tenant__9dbbcd_idx',
            old_name='chartofacco_organiz_8a6b47_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='chartofacco_tenant__f942bd_idx',
            old_name='chartofacco_organiz_b882b3_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='chartofacco_tenant__425576_idx',
            old_name='chartofacco_organiz_8b07f0_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='chartofacco_tenant__0ff896_idx',
            old_name='chartofacco_organiz_af93d7_idx',
        ),
        migrations.RenameIndex(
            model_name='currencyrevaluation',
            new_name='finance_cur_tenant__f78f72_idx',
            old_name='finance_cur_organiz_ab65da_idx',
        ),
        migrations.RenameIndex(
            model_name='exchangerate',
            new_name='finance_exc_tenant__509586_idx',
            old_name='finance_exc_organiz_2b0a91_idx',
        ),
        migrations.RenameIndex(
            model_name='forensicauditlog',
            new_name='forensicaud_tenant__e91fcc_idx',
            old_name='forensicaud_organiz_15cd02_idx',
        ),
        migrations.RenameIndex(
            model_name='forensicauditlog',
            new_name='forensicaud_tenant__a96361_idx',
            old_name='forensicaud_organiz_f6ab40_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='journalentr_tenant__8a56b4_idx',
            old_name='journalentr_organiz_5c542f_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='journalentr_tenant__2aaed0_idx',
            old_name='journalentr_organiz_339014_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='journalentr_tenant__1f43db_idx',
            old_name='journalentr_organiz_cdf611_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentryline',
            new_name='journalentr_tenant__655ba8_idx',
            old_name='journalentr_organiz_d847f4_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentryline',
            new_name='journalentr_tenant__d96f42_idx',
            old_name='journalentr_organiz_ebb715_idx',
        ),
        migrations.RenameIndex(
            model_name='openingbalance',
            new_name='opening_bal_tenant__e1cf48_idx',
            old_name='opening_bal_organiz_f2c4ba_idx',
        ),
        migrations.RenameIndex(
            model_name='postingrulehistory',
            new_name='finance_pos_tenant__c43dd9_idx',
            old_name='finance_pos_organiz_0710a1_idx',
        ),
        migrations.RenameIndex(
            model_name='postingrulehistory',
            new_name='finance_pos_tenant__1f958a_idx',
            old_name='finance_pos_organiz_6be4cc_idx',
        ),
        migrations.RenameIndex(
            model_name='reconciliationmatch',
            new_name='reconciliat_tenant__d70831_idx',
            old_name='reconciliat_organiz_2f6525_idx',
        ),
        migrations.RenameIndex(
            model_name='reconciliationmatch',
            new_name='reconciliat_tenant__0a19cf_idx',
            old_name='reconciliat_organiz_dee980_idx',
        ),
        migrations.RenameIndex(
            model_name='recurringjournaltemplate',
            new_name='finance_rec_tenant__d7d68e_idx',
            old_name='finance_rec_organiz_c86bac_idx',
        ),
        migrations.RemoveField(
            model_name='withholdingtaxrule',
            name='auto_generate_certificate',
        ),
        migrations.RemoveField(
            model_name='withholdingtaxrule',
            name='certificate_required',
        ),
        migrations.RemoveField(
            model_name='withholdingtaxrule',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='withholdingtaxrule',
            name='effective_until',
        ),
        migrations.RemoveField(
            model_name='withholdingtaxrule',
            name='threshold_amount',
        ),
        migrations.AddField(
            model_name='withholdingtaxrule',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Direct contact link (when no tax profile exists)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withholding_rules', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='withholdingtaxrule',
            name='credit_account_code',
            field=models.CharField(blank=True, default='', help_text='Liability account for WHT payable', max_length=20),
        ),
        migrations.AddField(
            model_name='withholdingtaxrule',
            name='debit_account_code',
            field=models.CharField(blank=True, default='', help_text='Account to debit for withheld amount', max_length=20),
        ),
        migrations.AddField(
            model_name='withholdingtaxrule',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withholdingtaxrule',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum WHT amount per transaction (cap)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='withholdingtaxrule',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum transaction amount before WHT applies', max_digits=15),
        ),
        migrations.AlterField(
            model_name='accountbalancesnapshot',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='advancepaymentvat',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='baddebtvatclaim',
            name='eligible_date',
            field=models.DateField(blank=True, help_text='Date when claim becomes eligible', null=True),
        ),
        migrations.AlterField(
            model_name='baddebtvatclaim',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='barcodesettings',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='coamigrationsession',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='consolidationentity',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='consolidationgroup',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='consolidationline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='consolidationrun',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='contextualpostingrule',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='counterpartytaxprofile',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='countrytaxtemplate',
            name='custom_tax_rule_presets',
            field=models.JSONField(blank=True, default=list, help_text='Default custom tax rules for this country. Each entry: {"name": "...", "rate": "0.0100", "transaction_type": "BOTH", "math_behavior": "ADDED_TO_TTC", ...}'),
        ),
        migrations.AlterField(
            model_name='creditnotevatreversal',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='creditnotevatreversal',
            name='vat_return_period',
            field=models.CharField(blank=True, default='', help_text='VAT return period this reversal will be included in', max_length=20),
        ),
        migrations.AlterField(
            model_name='currency',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='currencyrevaluation',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='currencyrevaluationline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='customtaxrule',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='financialaccountcategory',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='financialevent',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='fiscalperiod',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='forensicauditlog',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='gatewayconfig',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='importdeclaration',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='importdeclaration',
            name='other_charges',
            field=models.JSONField(blank=True, default=list, help_text='Additional charges: [{name, amount, capitalize}]'),
        ),
        migrations.AlterField(
            model_name='intercompanyrule',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='intrabranchvattransfer',
            name='destination_branch',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='intrabranchvattransfer',
            name='destination_vat_registration',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='intrabranchvattransfer',
            name='goods_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='intrabranchvattransfer',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='intrabranchvattransfer',
            name='source_branch',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='intrabranchvattransfer',
            name='source_vat_registration',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='intrabranchvattransfer',
            name='transfer_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='intrabranchvattransfer',
            name='vat_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='intrabranchvattransfer',
            name='vat_rate_destination',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='intrabranchvattransfer',
            name='vat_rate_source',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='loaninstallment',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='marginschemetransaction',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='openingbalance',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='orgtaxpolicy',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='periodictaxaccrual',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='postingrule',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='postingrulehistory',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='profitdistribution',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='reconciliationline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='reconciliationmatch',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='recurringjournalexecution',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='recurringjournalline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='recurringjournaltemplate',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='reportdefinition',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='reportexecution',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='reversechargeselfassessment',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='taxaccountmapping',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='taxjurisdictionrule',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='transactionsequence',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='vatratechangehistory',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='withholdingtaxrule',
            name='counterparty_profile',
            field=models.ForeignKey(blank=True, help_text='Counterparty tax profile this rule belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withholding_rules', to='finance.counterpartytaxprofile'),
        ),
        migrations.AlterField(
            model_name='withholdingtaxrule',
            name='name',
            field=models.CharField(help_text='Rule name, e.g. "Lebanon Services WHT 7.5%"', max_length=200),
        ),
        migrations.AlterField(
            model_name='withholdingtaxrule',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AlterField(
            model_name='withholdingtaxrule',
            name='rate',
            field=models.DecimalField(decimal_places=4, help_text='Withholding rate as decimal (e.g. 0.075 for 7.5%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='zatcaconfig',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='giftsampleevent',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_sample_entries', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='giftsampleevent',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='giftsampleevent',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product gifted (if single product)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_events', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='giftsampleevent',
            name='recipient_contact',
            field=models.ForeignKey(blank=True, help_text='Contact who received the gift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_gifts', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='giftsampleevent',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse from which goods were issued', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_events', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='internalconsumptionevent',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='Journal entry recording the output VAT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_consumption_entries', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='internalconsumptionevent',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddField(
            model_name='internalconsumptionevent',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product consumed internally', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_events', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='internalconsumptionevent',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse from which goods were consumed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_events', to='inventory.warehouse'),
        ),
        migrations.DeleteModel(
            name='GiftSampleVAT',
        ),
        migrations.DeleteModel(
            name='SelfSupplyVATEvent',
        ),
    ]
