# Generated by Django 6.0.3 on 2026-04-08 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0052_fne_api_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrytaxtemplate',
            name='e_invoice_standard',
            field=models.ForeignKey(blank=True, help_text='E-invoicing standard for this country (e.g. FNE for CI, ZATCA for SA)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_templates', to='finance.einvoicestandard'),
        ),
        migrations.AddField(
            model_name='countrytaxtemplate',
            name='einvoice_enforcement',
            field=models.CharField(choices=[('NONE', 'None — No e-invoicing'), ('OPTIONAL', 'Optional — Tenant can choose'), ('RECOMMENDED', 'Recommended — Shown as default'), ('MANDATORY', 'Mandatory — Required by law')], default='OPTIONAL', help_text='How strictly e-invoicing is enforced for this country', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fne_invoice_id',
            field=models.CharField(blank=True, help_text='FNE platform invoice UUID (needed for refund/credit note endpoint)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fne_raw_response',
            field=models.JSONField(blank=True, help_text='Full JSON response from FNE API for audit trail', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fne_reference',
            field=models.CharField(blank=True, help_text='FNE official reference number (e.g. 9606123E25000000019)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fne_token',
            field=models.TextField(blank=True, help_text='FNE verification token URL (for QR code generation)', null=True),
        ),
    ]
