# Generated by Django 6.0.4 on 2026-04-12 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_journalentryline_employee_alter_taxgroup_rate_and_more'),
        ('finance', '0053_einvoice_enforcement_field'),
    ]

    operations = [
    ]
