# Generated by Django 6.0.4 on 2026-04-20 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_remove_approvalrule_organization_and_more'),
        ('finance', '0058_fiscalyear_internal_closing_je'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zatcaconfig',
            options={'verbose_name': 'ZATCA Configuration', 'verbose_name_plural': 'ZATCA Configurations'},
        ),
        migrations.AlterUniqueTogether(
            name='customerbalance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='supplierbalance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='dispute_reason',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='disputed_amount_delta',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='disputed_lines_count',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='fne_balance_sticker',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='locked_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='locked_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_blocked',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='posted_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='posted_journal_entry',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='reversal_of',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='fne_item_id',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='purchase_order_line',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='policy_snapshot',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='required_levels_frozen',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='locked_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='locked_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='posted_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='posted_journal_entry',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reversal_of',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='countrytaxtemplate',
            name='tax_group_presets',
            field=models.JSONField(blank=True, default=list, help_text='Default tax groups to seed for this country. Each entry: {"name": "TVA Standard", "rate": "18.00", "tax_type": "STANDARD", "is_default": true, "description": "..."}'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='is_pos_enabled',
            field=models.BooleanField(default=False, help_text='Whether this account is available for POS transactions'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale'), ('CONSIGNEE', 'Consignee'), ('STANDARD', 'Standard'), ('WHOLESALE', 'Wholesale'), ('CONSIGNEE', 'Consignee')], default='RETAIL', help_text='Sub-classification: Retail/Wholesale/Consignee (sales) or Standard/Wholesale/Consignee (purchase)', max_length=20),
        ),
        migrations.AddField(
            model_name='taxgroup',
            name='tax_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('REDUCED', 'Reduced'), ('ZERO', 'Zero Rate'), ('EXEMPT', 'Exempt'), ('REVERSE_CHARGE', 'Reverse Charge')], default='STANDARD', help_text='Classification: STANDARD, REDUCED, ZERO, EXEMPT, REVERSE_CHARGE', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='type',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash Drawer'), ('BANK', 'Bank Account'), ('MOBILE', 'Mobile Wallet'), ('PETTY_CASH', 'Petty Cash'), ('SAVINGS', 'Savings Account'), ('FOREIGN', 'Foreign Currency Account'), ('ESCROW', 'Escrow Account'), ('INVESTMENT', 'Investment Account')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fne_invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fne_raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fne_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fne_status',
            field=models.CharField(choices=[('NONE', 'Not Certified'), ('PENDING', 'Pending Certification'), ('CERTIFIED', 'Certified'), ('FAILED', 'Certification Failed'), ('REFUNDED', 'Refunded / Reversed')], default='NONE', help_text='Lebanese FNE / Saudi ZATCA certification status', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fne_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.site'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTIAL_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled'), ('WRITTEN_OFF', 'Written Off')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierbalance',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxratecategory',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zatcaconfig',
            name='certificate_pem',
            field=models.TextField(blank=True, help_text='X.509 compliance certificate (PEM format)', null=True),
        ),
        migrations.AlterField(
            model_name='zatcaconfig',
            name='compliance_certificate_pem',
            field=models.TextField(blank=True, help_text='Compliance certificate from ZATCA onboarding', null=True),
        ),
        migrations.AlterField(
            model_name='zatcaconfig',
            name='csr_request_id',
            field=models.CharField(blank=True, help_text='ZATCA onboarding CSR request ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zatcaconfig',
            name='invoice_counter',
            field=models.IntegerField(default=0, help_text='Sequential counter of ZATCA-submitted invoices'),
        ),
        migrations.AlterField(
            model_name='zatcaconfig',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether ZATCA e-invoicing is enabled for this org'),
        ),
        migrations.AlterField(
            model_name='zatcaconfig',
            name='is_sandbox',
            field=models.BooleanField(default=True, help_text='Use ZATCA sandbox API (True) or production (False)'),
        ),
        migrations.AlterField(
            model_name='zatcaconfig',
            name='last_invoice_hash',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', help_text='SHA-256 hash of the last submitted invoice (chain anchor)', max_length=64),
        ),
        migrations.AlterField(
            model_name='zatcaconfig',
            name='private_key_pem',
            field=models.TextField(blank=True, help_text='ECDSA private key (PEM format, encrypted at rest)', null=True),
        ),
        migrations.AlterField(
            model_name='zatcaconfig',
            name='production_certificate_pem',
            field=models.TextField(blank=True, help_text='Production certificate from ZATCA onboarding', null=True),
        ),
        migrations.AlterField(
            model_name='zatcaconfig',
            name='seller_name',
            field=models.CharField(help_text='Legal seller name as registered with ZATCA', max_length=255),
        ),
        migrations.AlterField(
            model_name='zatcaconfig',
            name='vat_registration_number',
            field=models.CharField(help_text='Saudi VAT TRN (Tax Registration Number), 15 digits', max_length=15),
        ),
    ]
