# Generated by Django 6.0.4 on 2026-04-24 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_remove_approvalrule_organization_and_more'),
        ('finance', '0061_coa_clears_at_close'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYearCloseSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('OFFICIAL', 'Official'), ('INTERNAL', 'Internal')], max_length=10)),
                ('total_assets', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_equity', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_income', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('retained_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('trial_balance', models.JSONField(default=list)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'finance_fy_close_snapshot',
            },
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='journalentr_tenant__902e76_idx',
            old_name='finance_je_org_supers_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='journalentr_tenant__b9b068_idx',
            old_name='finance_je_org_role_idx',
        ),
        migrations.AddField(
            model_name='fiscalyearclosesnapshot',
            name='captured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fy_close_snapshots_captured', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalyearclosesnapshot',
            name='closing_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='close_snapshots_closing', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='fiscalyearclosesnapshot',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_snapshots', to='finance.fiscalyear'),
        ),
        migrations.AddField(
            model_name='fiscalyearclosesnapshot',
            name='opening_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='close_snapshots_opening', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='fiscalyearclosesnapshot',
            name='organization',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.AddIndex(
            model_name='fiscalyearclosesnapshot',
            index=models.Index(fields=['organization', 'fiscal_year'], name='finance_fy__tenant__c7dd3c_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalyearclosesnapshot',
            index=models.Index(fields=['fiscal_year', 'scope'], name='finance_fy__fiscal__29a44d_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscalyearclosesnapshot',
            constraint=models.UniqueConstraint(fields=('fiscal_year', 'scope'), name='fy_close_snapshot_uniq_year_scope'),
        ),
    ]
