# Generated by Django 6.0.4 on 2026-04-24 10:12
# + data-migration step to backfill hashes on pre-existing snapshots.

import hashlib
import json
from django.db import migrations, models


def _canonical_payload(s) -> dict:
    tb_sorted = sorted(
        s.trial_balance or [],
        key=lambda x: (str(x.get('code', '')), x.get('account_id', 0)),
    )
    return {
        'organization_id': str(s.organization_id),
        'fiscal_year_id': s.fiscal_year_id,
        'scope': s.scope,
        'closing_journal_entry_id': s.closing_journal_entry_id,
        'opening_journal_entry_id': s.opening_journal_entry_id,
        'total_assets': str(s.total_assets),
        'total_liabilities': str(s.total_liabilities),
        'total_equity': str(s.total_equity),
        'net_income': str(s.net_income),
        'retained_earnings': str(s.retained_earnings),
        'trial_balance': tb_sorted,
        'prev_hash': s.prev_hash,
    }


def _compute(s) -> str:
    payload = json.dumps(
        _canonical_payload(s),
        sort_keys=True, default=str, separators=(',', ':'),
    )
    return hashlib.sha256(payload.encode('utf-8')).hexdigest()


def forwards(apps, schema_editor):
    """Backfill hash chain on any snapshots already captured prior to
    this migration (the FY 2025 dry-run snapshot, in practice). Chains
    per-organization in chronological capture order.
    """
    Snap = apps.get_model('finance', 'FiscalYearCloseSnapshot')
    from collections import defaultdict
    by_org = defaultdict(list)
    for s in Snap.objects.all().order_by('organization_id', 'captured_at', 'id'):
        by_org[s.organization_id].append(s)
    for org_id, chain in by_org.items():
        prev = None
        for s in chain:
            s.prev_hash = prev
            s.content_hash = _compute(s)
            s.save(update_fields=['prev_hash', 'content_hash'])
            prev = s.content_hash


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0063_parent_allow_posting_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyearclosesnapshot',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 of canonical payload — changes if snapshot is tampered with.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='fiscalyearclosesnapshot',
            name='prev_hash',
            field=models.CharField(blank=True, help_text='content_hash of the prior snapshot in chronological order (per org). Null for the first row.', max_length=64, null=True),
        ),
        migrations.RunPython(forwards, backwards),
    ]
