# Generated by Django 6.0.4 on 2026-04-24 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_remove_approvalrule_organization_and_more'),
        ('finance', '0064_fiscalyearclosesnapshot_content_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeferredRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('LICENSE', 'License'), ('MAINTENANCE', 'Maintenance Contract'), ('SUPPORT', 'Support Plan'), ('ADVANCE_PAYMENT', 'Advance Payment'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('recognition_method', models.CharField(choices=[('STRAIGHT_LINE', 'Straight-line over duration'), ('MILESTONE', 'Per-milestone (performance obligations)'), ('USAGE', 'Usage-based (tracked externally)')], default='STRAIGHT_LINE', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField()),
                ('duration_months', models.PositiveIntegerField(default=1)),
                ('monthly_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('months_recognized', models.PositiveIntegerField(default=0)),
                ('source_invoice_id', models.IntegerField(blank=True, help_text='Optional FK to the Invoice that created this deferral', null=True)),
                ('contact_id', models.IntegerField(blank=True, help_text='Counterparty (Customer) for sub-ledger reporting', null=True)),
                ('scope', models.CharField(default='OFFICIAL', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deferred_coa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_revenue_liabilities', to='finance.chartofaccount')),
                ('organization', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization')),
                ('revenue_coa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_revenue_recognitions', to='finance.chartofaccount')),
            ],
            options={
                'db_table': 'deferredrevenue',
            },
        ),
        migrations.CreateModel(
            name='RevenuePerformanceObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('allocation_amount', models.DecimalField(decimal_places=2, help_text='Portion of deferred_revenue.total_amount allocated to this obligation', max_digits=15)),
                ('expected_satisfaction_date', models.DateField(blank=True, null=True)),
                ('is_satisfied', models.BooleanField(default=False)),
                ('satisfied_at', models.DateTimeField(blank=True, null=True)),
                ('satisfaction_evidence', models.TextField(blank=True, help_text='Free text: signed acceptance, shipment tracking, usage report, etc.', null=True)),
                ('deferred_revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='finance.deferredrevenue')),
                ('organization', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization')),
                ('release_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_obligations_released', to='finance.journalentry')),
            ],
            options={
                'db_table': 'revenueperformanceobligation',
            },
        ),
        migrations.AddIndex(
            model_name='deferredrevenue',
            index=models.Index(fields=['organization', 'status'], name='deferredrev_tenant__0cca66_idx'),
        ),
        migrations.AddIndex(
            model_name='deferredrevenue',
            index=models.Index(fields=['organization', 'start_date'], name='deferredrev_tenant__f23628_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueperformanceobligation',
            index=models.Index(fields=['deferred_revenue', 'is_satisfied'], name='revenueperf_deferre_5f6e8e_idx'),
        ),
    ]
