# Generated by Django 6.0.4 on 2026-04-24 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_remove_approvalrule_organization_and_more'),
        ('finance', '0065_deferredrevenue_revenueperformanceobligation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scope', models.CharField(choices=[('FISCAL_PERIOD', 'Per fiscal period (monthly / quarterly close)'), ('FISCAL_YEAR', 'Per fiscal year (year-end close)')], default='FISCAL_YEAR', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Auto-applied when a new close run is initiated')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization')),
            ],
            options={
                'db_table': 'finance_close_checklist_template',
            },
        ),
        migrations.CreateModel(
            name='CloseChecklistRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open — items being completed'), ('READY', 'Ready — all required items done, awaiting close'), ('CLOSED', 'Closed — fiscal close completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='close_checklists_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='close_checklist_runs', to='finance.fiscalperiod')),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='close_checklist_runs', to='finance.fiscalyear')),
                ('organization', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='finance.closechecklisttemplate')),
            ],
            options={
                'db_table': 'finance_close_checklist_run',
            },
        ),
        migrations.CreateModel(
            name='CloseChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('RECONCILIATION', 'Reconciliation (bank, AR, AP, IC)'), ('ACCRUALS', 'Accruals & deferrals posted'), ('INVENTORY', 'Inventory count + valuation'), ('FX', 'FX revaluation run'), ('TAX', 'Tax calculation & filing'), ('DEPRECIATION', 'Depreciation posted'), ('REVIEW', 'Management review / approval'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_required', models.BooleanField(default=True, help_text='If False, item is advisory — close proceeds even if unchecked')),
                ('auto_check_signal', models.CharField(blank=True, default='', help_text='Optional machine signal to auto-mark done', max_length=60)),
                ('organization', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.closechecklisttemplate')),
            ],
            options={
                'db_table': 'finance_close_checklist_item',
                'ordering': ['template', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CloseChecklistItemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('auto_checked', models.BooleanField(default=False)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='close_checklist_items_completed', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='finance.closechecklistitem')),
                ('organization', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_v2_set', to='erp.organization')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_states', to='finance.closechecklistrun')),
            ],
            options={
                'db_table': 'finance_close_checklist_item_state',
                'indexes': [models.Index(fields=['organization', 'run', 'is_complete'], name='finance_clo_tenant__40e957_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'item'), name='close_checklist_state_uniq_run_item')],
            },
        ),
        migrations.AddIndex(
            model_name='closechecklisttemplate',
            index=models.Index(fields=['organization', 'scope', 'is_default'], name='finance_clo_tenant__643c06_idx'),
        ),
        migrations.AddConstraint(
            model_name='closechecklistrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'READY'])), fields=('fiscal_period', 'template'), name='close_checklist_one_active_per_period'),
        ),
        migrations.AddConstraint(
            model_name='closechecklistrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'READY'])), fields=('fiscal_year', 'template'), name='close_checklist_one_active_per_year'),
        ),
        migrations.AddIndex(
            model_name='closechecklistitem',
            index=models.Index(fields=['organization', 'template', 'order'], name='finance_clo_tenant__2bc03b_idx'),
        ),
    ]
