# Generated by Django 6.0.4 on 2026-04-24 21:49
#
# Schema/state mismatch correction: the DB column for
# COATemplate.organization was already `tenant_id` (from the original
# TenantOwnedModel inheritance), but Django's migration history had
# drifted to think it was `organization_id`. Adding the missing
# db_column='tenant_id' to the model makes the ORM-generated SQL match
# reality. Marking this operation as `state_operations` only — Django
# updates its internal state without running any schema DDL, because
# the column is already correctly named in the DB.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_remove_approvalrule_organization_and_more'),
        ('finance', '0066_closechecklisttemplate_closechecklistrun_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # no DDL — DB column already correct
            state_operations=[
                migrations.AlterField(
                    model_name='coatemplate',
                    name='organization',
                    field=models.ForeignKey(
                        blank=True, db_column='tenant_id',
                        help_text='Only set for custom (per-org) templates; NULL for system templates',
                        null=True, on_delete=django.db.models.deletion.CASCADE,
                        related_name='coa_templates', to='erp.organization',
                    ),
                ),
            ],
        ),
    ]
