"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env if it exists
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() in ('true', '1', 'yes')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-fallback'
    else:
        raise ValueError("DJANGO_SECRET_KEY environment variable is required in production!")

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    
    # Local
    'erp',
]

# Auto-discover modules in 'apps' directory
APPS_DIR = BASE_DIR / "apps"
if APPS_DIR.exists():
    for item in APPS_DIR.iterdir():
        if item.is_dir() and (item / "apps.py").exists():
            INSTALLED_APPS.append(f"apps.{item.name}")

MIDDLEWARE = [
    'erp.middleware_maintenance.MaintenanceModeMiddleware',
    'erp.latency_middleware.LatencyTrackingMiddleware',
    'erp.ip_whitelist.SaaSIPWhitelistMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # SaaS Tenant Isolation
    'erp.middleware.TenantMiddleware',
]

# CORS — restrict to known origins
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL', 'False').lower() in ('true', '1')
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'https://tsf.ci,https://pos.tsf.ci,https://saas.tsf.ci').split(',')
CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^https://.*\.tsf\.ci$',  # Any subdomain of tsf.ci
]
CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'erp.auth_token.ExpiringTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Rate Limiting (Throttling)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '120/minute',       # Public endpoints
        'user': '2000/minute',     # Authenticated users (SSR makes many parallel calls)
        'login': '10/minute',       # Login attempts (custom)
        'register': '3/minute',    # Registration attempts
        'tenant_resolve': '60/minute',  # Tenant resolution
    }
}

# Token expiration (hours) — tokens older than this are auto-rejected
TOKEN_TTL_HOURS = int(os.getenv('TOKEN_TTL_HOURS', '24'))


# SaaS Admin IP Whitelisting
# Empty list = allow all IPs (open mode)
# Add IPs to restrict /api/saas/ endpoints via SAAS_IP_WHITELIST env
SAAS_ADMIN_IP_WHITELIST = os.getenv('SAAS_IP_WHITELIST', '').split(',') if os.getenv('SAAS_IP_WHITELIST') else []

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


import os

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'tsf_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'db'),
        'PORT': os.getenv('DB_PORT', '5432'),
        # ── Performance: Persistent DB connections ──────────────────
        # Reuse connections for 10 min instead of opening/closing per request.
        # Saves ~5-15ms per request (TCP handshake + PG auth).
        'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '600')),
        'CONN_HEALTH_CHECKS': True,  # Django 4.1+ — validate before reuse
    }
}

# SaaS Integration Settings
X_TENANT_HEADER = 'HTTP_X_TENANT_ID'

# Logging — capture full tracebacks even with DEBUG=False
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'erp': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Session Security
# Default to 1 hour (3600 seconds) for better security
SESSION_COOKIE_AGE = 3600 
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Production: collectstatic output
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

# Media files (user uploads — local fallback)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ── Cloud Storage (Cloudflare R2 / S3-compatible) ─────────────
STORAGE_DEFAULT_PROVIDER = os.getenv('STORAGE_PROVIDER', 'LOCAL')
STORAGE_R2_ENDPOINT = os.getenv('STORAGE_R2_ENDPOINT', '')
STORAGE_R2_ACCESS_KEY = os.getenv('STORAGE_R2_ACCESS_KEY', '')
STORAGE_R2_SECRET_KEY = os.getenv('STORAGE_R2_SECRET_KEY', '')
STORAGE_R2_BUCKET = os.getenv('STORAGE_R2_BUCKET', 'tsf-files')
STORAGE_MAX_FILE_SIZE_MB = int(os.getenv('STORAGE_MAX_FILE_SIZE_MB', '50'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Celery / Redis Configuration ──────────────────────────────
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://redis:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 300       # 5 min hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 240  # 4 min soft limit

# ── Celery Beat Schedule ──────────────────────────────────────
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'check-overdue-invoices': {
        'task': 'erp.tasks.check_overdue_invoices',
        'schedule': crontab(minute=0),           # Every hour
    },
    'check-low-stock': {
        'task': 'erp.tasks.check_low_stock',
        'schedule': crontab(minute=0, hour='*/6'),  # Every 6 hours
    },
    'warm-analytics-cache': {
        'task': 'erp.tasks.warm_analytics_cache',
        'schedule': crontab(minute=0, hour=2),      # Daily 02:00
    },
    'cleanup-old-audit-logs': {
        'task': 'erp.tasks.cleanup_old_audit_logs',
        'schedule': crontab(minute=0, hour=3, day_of_week='sunday'),  # Weekly
    },
    'generate-daily-backup': {
        'task': 'erp.tasks.generate_daily_backup',
        'schedule': crontab(minute=0, hour=1),      # Daily 01:00
    },
    'send-daily-digest': {
        'task': 'erp.tasks.send_daily_digest',
        'schedule': crontab(minute=0, hour=8),       # Daily 08:00
    },
    # ── Workspace auto-task engine ──────────────────────────────
    'fire-recurring-auto-tasks': {
        'task': 'apps.workspace.tasks.fire_recurring_auto_tasks',
        'schedule': crontab(minute='*/15'),          # Every 15 min
    },
    'check-stale-orders': {
        'task': 'apps.workspace.tasks.check_stale_orders',
        'schedule': crontab(minute=0, hour='*/4'),   # Every 4 hours
    },
    'fire-period-reminders': {
        'task': 'apps.finance.tasks.fire_period_reminders',
        'schedule': crontab(minute=0, hour=6),       # Daily 06:00
    },
}

# ── Email Configuration (for notifications) ──────────────────
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'ERP System <noreply@tsf.ci>')



AUTHENTICATION_BACKENDS = [
    'erp.backends.TenantAuthBackend',
    # NOTE: Do NOT add ModelBackend here — it calls get_by_natural_key(username)
    # without tenant scoping, which crashes with MultipleObjectsReturned when
    # the same username exists in multiple organizations (valid multi-tenant data).
    # TenantAuthBackend already handles admin panel logins.
]

AUTH_USER_MODEL = 'erp.User'

import sys
# Local dev hacks to bypass model clashes and migration history issues
if 'runserver' in sys.argv or 'test' in sys.argv or 'migrate' in sys.argv or os.getenv('APP_ENV') == 'production':
    SILENCED_SYSTEM_CHECKS = ["fields.E304", "auth.W004"]
    # Bypass migrations for speed/simplicity in local dev if needed
    if 'test' in sys.argv:
        class DisableMigrations:
            def __contains__(self, item): return True
            def __getitem__(self, item): return None
        MIGRATION_MODULES = DisableMigrations()
